### ISSUE TITLE
Using @ in Razor Page .cshtml in Visual Code

### ISSUE THREAD

**Issue by abdollahkahne** [OmniSharp/omnisharp-vscode#4784] opened 2021-09-22 21:09 UTC
Issue Type: Feature Request

When I try to use` @{` in Razor Page to switch the context to c#, The IntelliSense feature replace it with `@__o{` which is not Intended. It is the case if you use parenthesis instead of curly brace. It would be great to resolve this.
Thanks in advance

VS Code version: Code 1.60.1
OS version: Linux x64 5.11.0-34-generic
Restricted Mode: No

**Comment by JoeRobich** [comment] 2021-09-22 21:10
@ryanbrandenburg Have you seen this before?

**Comment by JoeRobich** [comment] 2021-09-22 21:12
Closing. This appears to be a duplicate of https://github.com/dotnet/aspnetcore/issues/35601

**Closed by JoeRobich** 2021-09-22 21:12 UTC
Labels: Resolved-Duplicate, Razor
