### ISSUE TITLE
context menu stuck using Ctrl + . command

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#663] opened 2016-08-16 07:11 UTC
Copied from Microsoft/vscode#10479

---

From @mrunixus

- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:
Ctrl + .  command, to import a namespace in C#

1.  make the method async
2.  the context method got stuck
![capture](https://cloud.githubusercontent.com/assets/1231598/17628260/9beb6e1c-6082-11e6-8be5-b60c313793b6.PNG)

---

```
[Extension Host] .NET Core Debugger tools already installed
[Extension Host] rejected promise not handled with 1 second
Cannot read property 'find' of undefined: TypeError: Cannot read property 'find' of undefined
    at C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\out\assets.js:36:52
    at tryCatcher (C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\<user>\.vscode\extensions\ms-vscode.csharp-1.3.0\node_modules\bluebird\js\main\async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by DustinCampbell** [comment] 2016-08-26 20:44
Dupe of #664

**Closed by DustinCampbell** 2016-08-26 20:44 UTC
Labels: Resolved-Duplicate
