### ISSUE TITLE
Build errors are not hyperlinking to the associated .cs files

### ISSUE THREAD

**Issue by bittercoder** [OmniSharp/omnisharp-vscode#1621] opened 2017-07-03 21:00 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

VS Code version: 1.13.1

C# Extension version: 1.11.0

## Steps to reproduce

Build a project or test project which contains compilation errors e.g. missing semicolon

## Expected  behavior

I expect that the build output error messages should be hyperlinked to the file line/character position they are associated with.

## Actual behavior

When building projects or if a test project fails to compile when running a test then the build output is not hyperlinked to the file/line number.

The only thing that is hyperlinked is the path of the .csproj file which isn't useful.

**Comment by DustinCampbell** [comment] 2017-07-04 22:59
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1197.

**Closed** 2017-07-04 22:59 UTC
Labels: Resolved-Duplicate
