### ISSUE TITLE
OmniSharp fails to run with the new 1.19 update

### ISSUE THREAD

**Issue by mat1jaczyyy** [OmniSharp/omnisharp-vscode#2992] opened 2019-04-16 20:57 UTC
## Issue Description ##
OmniSharp fails to run with the new 1.19 update.

Note I am running an older version of Windows 10 that does not support .NET Framework 4.7:
![image](https://user-images.githubusercontent.com/13300194/56243342-ac181400-609a-11e9-977a-404698acf8e9.png)

## Steps to Reproduce ##
1. Open a C# file
2. Check output

## Expected Behavior ##
OmniSharp works and detects problems.

## Actual Behavior ##
OmniSharp crashes on startup.

### OmniSharp log ###
<details>Starting OmniSharp server at 4/16/2019, 10:52:40 PM
    Target: c:\Users\mat1jaczyyy\Desktop\apollo-studio\Apollo.sln

OmniSharp server started.
    Path: C:\Users\mat1jaczyyy\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\OmniSharp.exe
    PID: 764

System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.HostHelpers.Start(Func`1 action)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).</details>

### C# log ###
<details>(empty)</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.22.1|
|csharp|ms-vscode|1.19.0|
|discord-vscode|icrawl|3.4.0|
|python|ms-python|2019.3.6558|
|vetur|octref|0.18.1|
|vscode-xml-complete|rogalmic|0.1.6|
|vsliveshare|ms-vsliveshare|1.0.45|;

</details>

**Comment by rtablada** [comment] 2019-04-16 21:18
I have also been running into issues and have to force the version back to 1.18 every time I start VSCode (because the add-on keeps trying to auto update)

## Environment Information

.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.106/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.503 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

*VSCode Version:* 1.33.1
*C# Extension:* 1.19.0

**Comment by mat1jaczyyy** [comment] 2019-04-16 21:29
@rtablada, as a temporary workaround, before installing specific version 1.18 you can disable autoupdating here: 
![image](https://user-images.githubusercontent.com/13300194/56245316-6a3d9c80-609f-11e9-9e71-b3ffd4911ee3.png)

**Comment by filipw** [comment] 2019-04-16 21:37
Latest OmniSharp requires .NET 4.7.2, see https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#13214---2019-04-08

**Comment by mat1jaczyyy** [comment] 2019-04-16 23:50
@filipw ugh, annoying at the very least. i assume this was done because some feature specific to 4.7.2 was required, rather than just updating for the sake of it. the portion of the userbase that refuses to update because the release build of windows 10 has a friendly way of disabling automatic updates, is dropped once again.

**Comment by thomazmoura** [comment] 2019-04-18 15:38
> Latest OmniSharp requires .NET 4.7.2, see https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#13214---2019-04-08

@filipw Is a specific minor version of .NET 4.7.2 needed? I have .NET 4.7.2 installed (even target it for a few applications) and yet I'm facing this same problem, as reported on #2997

**Comment by filipw** [comment] 2019-04-23 15:43
> i assume this was done because some feature specific to 4.7.2 was required, rather than just updating for the sake of it.

Yes, unfortunately MSBuild 16, which was introduced in this latest build of OmniSharp as part of .NET Core 3.0 support requires .NET 4.7.2 to run.
I will close this as behavior by design.

Note that there is a new build to try out, that will at least prompt you to install .NET 4.7.2 instead of failing silently https://github.com/OmniSharp/omnisharp-vscode/issues/3004#issuecomment-484655065

Sorry for your troubles - at this point there is no way we can support both new .NET Core 3.0 stuff and old OS builds (Windows 10 1507 reach end of life 2 years ago I believe).

**Closed by filipw** 2019-04-23 15:43 UTC

**Comment by mat1jaczyyy** [comment] 2019-04-23 15:59
Very sad situation where Windows 7 is supported but the release version of Windows 10 isn't. 👍 for the update though.

**Comment by bruce31** [comment] 2019-05-17 16:30
Why .Net Framework??
Mac version is working fine with no version of .Net Framework installed.
Can't it use .net core or Mono if present (or can that be an option when installing as a user install?)

**Comment by gregg-miskelly** [comment] 2019-05-17 16:38
@bruce31 OmniSharp does **NOT** run on .NET Framework on macOS/Linux. On macOS/Linux, it will run on Mono. On Windows it will run on the full .NET Framework.

**Comment by bruce31** [comment] 2019-05-25 20:33
It is ironic that in order to support .Net Core 3.0 it forces an upgrade of Full Framework when the selling point of 3.0 is that windows desktop apps can use the latest and greatest, independent of the version of full framework installed on the system.
