### ISSUE TITLE
All debugging broken on MacOS Sierra (10.12.4?)

### ISSUE THREAD

**Issue by sunmorgus** [OmniSharp/omnisharp-vscode#1220] opened 2017-02-10 14:58 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc3-004530
```

VS Code version: `Version 1.9.1 (1.9.1)`
C# Extension version: `1.7.0`

## Steps to reproduce
1. Open dotnet core c# project
1. Launch the debugger
1. Wait for project to build

## Expected  behavior
The debugger launches and allows me to debug the code

## Actual behavior
An error is returned in the output window:

```
--------------------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (clrdbg) with Visual Studio
Code, Visual Studio or Visual Studio for Mac software to help you develop and
test your applications.
--------------------------------------------------------------------------------
ERROR: Unable to start debugging. Unexpected CLRDBG output from command "-exec-run".
The program '/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin/bin/Debug/netcoreapp1.1/BAH.Admin.dll' has exited with code 42 (0x0000002a).
```

I ran the following (suggested from [here](https://github.com/OmniSharp/omnisharp-vscode/issues/750)):

```
/Users/nicklasdemayo/.vscode/extensions/ms-vscode.csharp-1.7.0/.debugger/clrdbg --interpreter=mi
-gdb-exit
```

And got no other unexpected output.

**Comment by gregg-miskelly** [comment] 2017-02-10 22:59
@sunmorgus could you enable [engineLogging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging) (hopefully the quick way will work) and add the relevant sections around '-exec-run' to this bug?

**Comment by sunmorgus** [comment] 2017-02-10 23:28
The quick way appeared to work. I copied everything from the `1011-exec-run` line down, let me know if you need more.

```
1: (686) <-1011-exec-run
1: (11041) ->=telemetry,event-name="VS/Diagnostics/Debugger/clrdbg/LaunchFailed",properties={VS.Diagnostics.Debugger.clrdbg.ErrorCode="0x80070057",VS.Diagnostics.Debugger.clrdbg.Version="15.0.26013.0 built by: PREVIEW.DBG2",VS.Diagnostics.Debugger.clrdbg.OSFamily="Darwin",VS.Diagnostics.Debugger.clrdbg.KernelRelease="16.5.0"}
1: (11042) ->1011^error,msg=""
1: (11042) ->(gdb)
E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/clrdbg/LaunchFailed","data":{"VS.Diagnostics.Debugger.clrdbg.ErrorCode":-2147024809,"VS.Diagnostics.Debugger.clrdbg.Version":"15.0.26013.0 built by: PREVIEW.DBG2","VS.Diagnostics.Debugger.clrdbg.OSFamily":"Darwin","VS.Diagnostics.Debugger.clrdbg.KernelRelease":"16.5.0"},"type":"output"}
1: (11044) 1011: elapsed time 10358
E output: {"category":"stderr","output":"ERROR: Unable to start debugging. Unexpected CLRDBG output from command \"-exec-run\".\n","data":null,"type":"output"}
ERROR: Unable to start debugging. Unexpected CLRDBG output from command "-exec-run".
1: (11055) <--gdb-exit
1: (11056) ->^exit
1: (11061) <-logout
E output: {"category":"console","output":"The program '/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin/bin/Debug/netcoreapp1.1/BAH.Admin.dll' has exited with code 42 (0x0000002a).\r\n\n","data":null,"type":"output"}
The program '/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin/bin/Debug/netcoreapp1.1/BAH.Admin.dll' has exited with code 42 (0x0000002a).
E exited: {"exitCode":42,"type":"exited"}
E terminated: {"type":"terminated"}
E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.31028.1","VS.Diagnostics.Debugger.HostVersion":"1.0.30207.1","VS.Diagnostics.Debugger.AdapterId":"coreclr","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0},"type":"output"}
C disconnect: {"restart":false}
 R: {"success":true,"message":null,"request_seq":6,"command":"disconnect","body":null,"running":false,"refs":null,"seq":0,"type":"response"}```

**Comment by gregg-miskelly** [comment] 2017-02-10 23:53
@sunmorgus got it. So it looks like '-exec-run' is failing with E_INVALIDARG (0x80070057), which we don't provide a description for, and that results in this bad error message. Unfortunately that doesn't tell us much about the root cause for where the E_INVALIDARG might be coming from. If you scroll up a little bit where you should see the program path, working directory, and arguments passed, does anything by chance look 'weird'?

**Comment by sunmorgus** [comment] 2017-02-11 00:07
@gregg-miskelly I do see this error a little further up:

```
1: (501) ->(gdb)
1: (501) <-1006-break-insert main
1: (501) ->1006^error,msg="-break-insert currently only supports file/line breakpoints"
1: (501) ->(gdb)
1: (501) 1006: elapsed time 0
```

However, I took a look at the program path, working directory, and arguments, but nothing sticks out to me as being off...

**Comment by gregg-miskelly** [comment] 2017-02-11 00:11
@sunmorgus that error is actually normal / ignorable. Hmm... I am not quite sure how to troubleshoot this. 

Do you get this problem for all projects?

**Comment by sunmorgus** [comment] 2017-02-11 00:29
@gregg-miskelly I went and created a new project, and the same issue occurred. 

Also, I feel I should mention (and probably should have earlier, sorry)... this issue started occurring after 2 events this morning:

1. Installing Visual Studio for Mac (and the supporting Mono framework stuff). I tried removing all of that (as well as removing and reinstalling OmniSharp in vscode), but that didn't help.
1. I also updated this morning to macOS 10.12.4 Public Beta Version 2, but that would be a difficult one to roll back.

It's hard to say whether or not either of those caused the issue I suppose, but they are about the only things I can think of that changed recently.

**Comment by gregg-miskelly** [comment] 2017-02-11 00:48
@sunmorgus Thanks. I will see if I can reproduce this on that OS.

**Comment by stevepentland** [comment] 2017-02-14 04:53
Hoping a solution may be found soon, I am also experiencing this issue when trying to debug. 

Both on a simple "Hello, World" project, and more advanced code. 

Exact same OS version as @sunmorgus with same environment also.

**Comment by Griesmar** [comment] 2017-02-16 13:53
Same situation here, also with macOS 10.12.4 Beta 2.

**Comment by sunmorgus** [comment] 2017-02-16 14:58
Other things I've tried/noticed:

1. It _almost_ feels like it's having an issue reading the stdin. I had a simple python script I was trying to run recently that was supposed to take input from the stdin, but it wasn't able to for some reason. I didn't dig into it much, but maybe they are related?
1. I verified that it wasn't an issue with my dotnet core install by reinstalling it, making sure to complete the openssl req as well.
1. I'm keeping an eye out for a new update to the public beta, and I'm going to submit feedback to Apple as well.

**Comment by LukeStephen** [comment] 2017-02-16 19:41
I am getting this same error all of a sudden, worked fine yesterday, but last night my MacOS did update to 10.12.4 Public Beta 2.

Builds fine, but can't debug any longer, any ideas?

**Comment by Dima4ka** [comment] 2017-02-17 19:05
Same for me.
Updated to macOS 10.12.4 beta 2.

**Comment by mshulman** [comment] 2017-02-19 19:37
Also able to repro: On 10.12.4 Beta (16E154a)

Terminal window in vscode:
`
bash-3.2$ /Users/mshulman/.vscode/extensions/ms-vscode.csharp-1.7.0/.debugger/clrdbg --interpreter=mi
=message,text="--------------------------------------------------------------------------------\nYou may only use the Mic
rosoft .NET Core Debugger (clrdbg) with Visual Studio\nCode, Visual Studio or Visual Studio for Mac software to help you
develop and\ntest your applications.\n--------------------------------------------------------------------------------\n"
,send-to="output-window"
(gdb)
-gdb-exit
^exit
`

**Comment by mshulman** [comment] 2017-02-20 18:25
I thought I'd be able to work around this by launching my app, then attaching the debugger. Unfortunately, I get the same message.

**Comment by LukeStephen** [comment] 2017-02-20 20:30
I ended up downloaded the latest stable MacOS version from apple's developer site and it installed back to the pre-beta version without effecting anything that was installed on my MacBook. With that this error was gone, no beta for me till this is resolved...

**Comment by stevepentland** [comment] 2017-02-21 13:31
Error still occurs, 10.12.4 beta 3 release of macOS.

**Comment by sunmorgus** [comment] 2017-02-21 13:32
It happens in visual studio for Mac is well.

-- 
Nick DeMayo

**Comment by lt72** [comment] 2017-02-22 23:05
@noahfalk FYI

**Comment by gregg-miskelly** [comment] 2017-02-23 01:52
This issue is caused by an issue with a CoreCLR component. I opened https://github.com/dotnet/coreclr/issues/9730 to track the problem.

**Comment by robvdveer** [comment] 2017-02-23 10:43
I have the same error since upgrading to macOS 10.12.4 beta 2 and 3. Not only Visual Studio for Mac but also VSCode stopped working for me. I'll try reverting to stable 10.12.3 to see if that 'solves' the issue of not being able to debug.

**Comment by sunmorgus** [comment] 2017-03-06 12:26
It seems that 1.8.0-beta2 made progress towards a resolution here... I'm now able to at least start the project inside of vscode, but I get a new error message `Unable to attach to CoreCLR`:

```bash
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Unable to attach to CoreCLR.
Hosting environment: Development
Content root path: [redacted]
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

I can see that the extension is now using **vsdbg** rather than **clrdbg** and that is has options for vscode specifically. I tried running the below to see if I'd get any expected output (grasping at straws here... not entirely certain what I'm even doing is correct):

```bash
./vsdbg --interpreter=vscode --engineLogging=vsdbg.log --attach --name dotnet
```

But got no errors or anything in the log file.

**Comment by gregg-miskelly** [comment] 2017-03-06 15:30
@sunmorgus I debugged the issue and we are fairly certain we know what is going wrong. The underlying issue is a problem with CoreCLR (see above CoreCLR bug). We are leaving this issue open as we will need to update the debugger to a new CoreCLR once there is a fix from the CLR team.

**Comment by robvdveer** [comment] 2017-03-06 16:36
I rolled back the osX beta update and that fixed my issue and i was able to run the debugger.

**Comment by sunmorgus** [comment] 2017-03-06 16:37
@robvdveer How do I roll it back? Do I have to do a clean install to do that?

**Comment by LukeStephen** [comment] 2017-03-06 16:39
I rolled back too, to fix this... go to apple developer portal, download the latest non beta version of Mac OS and install it. It didn't wipe anything for me, I was able to debug in VSCode as soon as it booted back up. MAKE SURE you disable updating back to beta in Mac Settings, otherwise you are back where you started, happened to me once...

**Comment by sunmorgus** [comment] 2017-03-06 16:41
Sigh... I'm on the public beta and don't have access to the developer portal :(

**Comment by robvdveer** [comment] 2017-03-06 16:53
Can't you find the nonbeta download in your app store history.

**Comment by sunmorgus** [comment] 2017-03-06 16:57
I don't see it in the purchase history... I got the laptop on January 20th (ish), with Sierra already loaded.

**Comment by robvdveer** [comment] 2017-03-06 17:50
If your lapto is not even a month old just do a recovery reset after you make a backup.

**Comment by mikem8361** [comment] 2017-03-06 22:38
@gregg-miskelly: Is this the same problem as issue https://github.com/dotnet/coreclr/issues/9730 (launch fails on Sierra because the vmmap output changed)?

**Comment by gregg-miskelly** [comment] 2017-03-07 00:13
@mikem8361: Yes. The two bugs are linked above.

**Comment by poorboss3** [comment] 2017-03-10 03:45
Similar issue on WIN 10 X64

**Comment by xuzhuoyi** [comment] 2017-03-10 04:19
Error still occurs, 10.12.4 beta 4(16E183b) release of macOS.

**Comment by gregg-miskelly** [comment] 2017-03-10 05:39
@poorboss3 your issue is **NOT** similar if it is happening on Windows. If you would like help, please open a new bug.

**Comment by LukeStephen** [comment] 2017-03-27 19:47
Mac OS Sierra  10.12.4 (non-Beta) was released to the public today and this breaks .NET core from working on anyone's Mac running the latest version of Mac OS...

**Comment by gregg-miskelly** [comment] 2017-03-27 20:40
@LukeStephen :( I hope to have a beta release out later this week with the fix. I will see if I can put a work around together today using unofficial bits.

**Comment by LukeStephen** [comment] 2017-03-27 20:49
Thanks!  Even having it work inside visual studio code insiders would be good enough for now...

**Comment by gkhanna79** [comment] 2017-03-27 21:27
CC @mikem8361 @lt72

**Comment by gregg-miskelly** [comment] 2017-03-27 21:34
Here is a work around that worked for me:

1. Download https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.osx.10.10-x64.Microsoft.NETCore.Runtime.CoreCLR/1.1.2-servicing-25123-01
2. Open the resulting file as a zip, and copy out `runtimes/osx.10.10-x64/native/libdbgshim.dylib`
2. Open a terminal
3. `cd ~/.vscode/extensions/ms-vscode.csharp-1.8.0/.debugger`
4. `cp <path-to-extracted-libdbgshim> .`

As I said above, but just to repeat here, I expect to have a real fix out soon. But hopefully this will unblock folks in the mean time.

**Comment by LukeStephen** [comment] 2017-03-27 23:05
I can confirm this workaround worked for me. Although my extensions directory was ms-vscode.csharp-1.7.0

Thanks!!

**Comment by zbseattle** [comment] 2017-03-27 23:48
FYI, I ran into this issue today too, but with Mac OS Sierra 10.12.2, using VS Code, both via "Attach"  with one project, and "Launch (web)" with another project.

The project associated with the Attach attempt was a new one I just started exploring today (the MS-birthed, very cool Humanitarian Toolbox AllReady project), and the project associated with the Launch attempt was an existing one that was debuggable just fine as recently as last week.

And I suspect this might be related to a new C# 1.8.0, which VS Code reported needing updating today - so I did. Since I did this in the context of the new project, I initially assumed the problem might be something related to it.

But I can confirm that the problem is fixed now for both projects after following Gregg's instructions above.

Yippee! Thanx much.

**Comment by TypicalFooBar** [comment] 2017-03-28 04:56
I ran into this issue on Mac OS Sierra 10.12.3, but the workaround provided by @gregg-miskelly worked! Thank you! I'm not sure what I did to run into this, because it was working yesterday for me.

**Comment by alejandrofloresm** [comment] 2017-03-28 17:55
I ran into the same problem today it may be linked to any of the following events:
- Xcode update
- iWork update
- macOS update 

I'll go for the macOS update, anyway @gregg-miskelly worked perfectly.

**Comment by gregg-miskelly** [comment] 2017-03-28 18:37
I have posted a new release of the C# extension that includes the fix. 

To try it -- use the use the [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) instructions to install [v1.9.0-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.9.0-beta2).

**Comment by jorgecotillo** [comment] 2017-03-28 18:58
Thanks, is working now, I was having the same issue today.

**Comment by southplatte** [comment] 2017-03-29 06:33
macOS 10.12.4 and the beta release has enabled debugging to work as expected for myself as well.   Thank you.

**Comment by robvdveer** [comment] 2017-03-30 20:11
I am happy to see this working for VSCode now. However, will this patch work for Visual Studio for Mac Preview as well?

**Comment by jorgecotillo** [comment] 2017-03-30 20:40
That is a really good point, I ran into the same issue when trying to debug with VS for Mac preview.

**Comment by robvdveer** [comment] 2017-03-30 20:53
@jorgecotillo yes thanks that workaround fixed it for me! Back to work!

**Comment by DustinCampbell** [comment] 2017-03-31 13:18
@gregg-miskelly: Should this resolved fixed now?

**Comment by sunmorgus** [comment] 2017-03-31 13:36
@gregg-miskelly Version 1.8.1 fixed the issue for me as well.

**Comment by gregg-miskelly** [comment] 2017-03-31 14:31
@DustinCampbell I was going to resolve this as soon as we pushed to the gallery (since hithub makes it harder to find closed issues and this one is popular).

**Comment by gregg-miskelly** [comment] 2017-03-31 17:12
Version 1.8.1 has now been released to the extension gallery, and contains a fix for this issue. Thanks!

**Closed by gregg-miskelly** 2017-03-31 17:12 UTC
Labels: Debugger
