### ISSUE TITLE
".NETFramework,Version=v4.6" were not found

### ISSUE THREAD

**Issue by hubluesky** [OmniSharp/omnisharp-vscode#2010] opened 2018-02-06 02:36 UTC
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:1.13.1

## Steps to reproduce

1. Use unity 2017.0.0f3 create a project
2. Open unity menu "Edit/Project Settings/Player"
3. Chose Scripting Runtime Version to "Experimental(.NET 4.6 Equivalent)"
4. Restart unity and create any a C# script file.
5. Open the C# file by vscode.
6. OmniSharp Log will output this fail:
`[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.`

`[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'e:\Workspace\CSharpTest\Assembly-CSharp.csproj'.
e:\Workspace\CSharpTest\Assembly-CSharp.csproj`

**Comment by DustinCampbell** [comment] 2018-02-06 22:31
This is a duplicate of #1888. You might trying downloading and installing the .NET Framework 4.6 target pack from https://www.microsoft.com/en-us/download/details.aspx?id=48136.

**Closed by DustinCampbell** 2018-02-06 22:31 UTC
Labels: Resolved-Duplicate, Unity

**Comment by hubluesky** [comment] 2018-02-07 02:51
It's work,thank you.

**Comment by DustinCampbell** [comment] 2018-02-07 17:15
excellent! Thanks for confirming.

**Comment by BrianHubble** [comment] 2018-03-28 17:49
I am seeing this issue on a Mac where I cannot install the framework. It is complaining about ".NETFramework,Version=v3.5"

My mono version is 5.4.1.6

**Comment by BrianHubble** [comment] 2018-03-28 17:58
I made sure to install the mono-sdk and update dotnet-sdk in homebrew and now my other projects are not working either.

**Comment by emanuelceballos** [comment] 2018-06-18 15:51
I have a similar issue but running on Ubuntu 16.04. Is there a solution for VScode Linux based?

**Comment by afk-mcz** [comment] 2018-07-17 17:57
In Mac downloading the .NET famework solved the issue https://www.microsoft.com/net/learn/get-started/macos#macos

**Comment by Doeke** [comment] 2019-02-11 10:28
> I have a similar issue but running on Ubuntu 16.04. Is there a solution for VScode Linux based?

Installing the latest stable version of Mono on Ubuntu 18.04 fixed this error for me (The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found.)

**Comment by ngmgit** [comment] 2019-12-07 10:04
^ Also in addition to that make sure to add the PPA for [mono](https://www.mono-project.com/download/stable/#download-lin) because the default repository doesnt have the latest one.
