### ISSUE TITLE
File not found (file:///Controllers/ValuesController.cs)

### ISSUE THREAD

**Issue by WaterworthD** [OmniSharp/omnisharp-vscode#2194] opened 2018-04-15 03:44 UTC
Hi

When there's a compilation error from a C# file which resides in a folder below the project roor folder, vscode cannot location the file when you click on the error message.

For example if I create an ASP.NET Core project, i.e.

`>dotnet new webapi`

Then modify the \Controllers\ValuesController.cs file so it fails to compile, I get an error message on the Problems tab and if I click on the message I get

Unable to open 'ValuesController.cs': File not found (file:///Controllers/ValuesController.cs).

It seems to believe the Controllers folder resides at the root of the file system and not off the project root (there's an option to create the file and if I do so it creates a blank c:/Controllers/ValuesController.cs file)

Regards
Dave

**Comment by DustinCampbell** [comment] 2018-04-16 16:49
Thanks for filing this issue. It looks to me like this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1197. Do you agree?

**Comment by WaterworthD** [comment] 2018-04-18 18:07
Yes i think it might be, I added /property:GenerateFullPaths=true to my tasks.json build step. I've also noticed that it helps to add the cs files to the csproj file, I use an extension called 'VS Code .csproj' to make it easier.

**Comment by DustinCampbell** [comment] 2018-04-18 19:50
Thanks!

**Closed by DustinCampbell** 2018-04-18 19:50 UTC
Labels: Resolved-Duplicate
