### ISSUE TITLE
Use the vs-code language settings for error text.

### ISSUE THREAD

**Issue by Domvel** [OmniSharp/omnisharp-vscode#2543] opened 2018-09-20 11:19 UTC
## Environment data
`dotnet --info` output: 
.NET Core SDK ("global.json"):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime environment (translated from 'Laufzeitumgebung'):
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3-servicing-26724-03
  Commit:  124038c13e

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.27.2
C# Extension version: 1.16.1

## Steps to reproduce
Produce a warning of a deprecated feature. In latest Unity `DestroyObject` is deprecated.
Im from germany an the Windows OS language is german. VS Code is set to english. 
But the text of C# comes in german `"Object.DestroyObject(Object)" ist veraltet ...`
should be `... is deprecated ...`. Development should always be in english in my opinion.
But anyway, I wondering why is this in german. It should use the editor / ide (VS Code) language setting.

## Expected  behavior
All text of errors and warnings should be in english. (not german)

## Actual behavior
The text is mixed of german and english. e.g.
`'"Object.DestroyObject(Object)" ist veraltet: "use Object.Destroy instead." [Assembly-CSharp-firstpass]`

Maybe this text comes from SDK. But this is very weak if there are separated language versions.
How to fix / change this?

**Comment by akshita31** [comment] 2018-09-20 17:14
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2513

**Closed** 2018-09-20 17:30 UTC
Labels: Backlog, Feature Request, Resolved-Duplicate
