### ISSUE TITLE
Referenced assembly resolution is broken

### ISSUE THREAD

**Issue by elvirb** [OmniSharp/omnisharp-vscode#464] opened 2016-06-25 22:36 UTC
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
VS Code version: 1.2.1
C# Extension version: 1.1.6
## Steps to reproduce

project:

```
{
  "version": "1.0.0-*",
  "dependencies": {
  },
  "frameworks": {
    "monotouch": {
      "dependencies": {
        "someproject": {
          "target": "project",
          "version": "1.0.0-*"
        }
      }
    }
  }
}
```

referenced projects:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": false,
    "allowUnsafe": true
  },
  "frameworks": {
    "monotouch":{
        "bin" : { "assembly": "[someproject dll]" }
    }
  }
}
```
## Expected  behavior

Code in project compiles resolving references from the referenced project.
## Actual behavior

VSCode shows issues with resolving types from referenced project.

dotnet restore + dotnet build works fine and compiles code.

**Comment by remcoros** [comment] 2016-06-28 08:36
duplicate of #424

**Closed** 2016-11-15 23:04 UTC
Labels: Resolved-Duplicate
