### ISSUE TITLE
Incorrect code format

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#383] opened 2016-05-27 13:29 UTC
_From @larini on May 27, 2016 12:14_
- VSCode Version:1.1.1
- OS Version: Windows 10

Steps to Reproduce:

Use this class:

```
using System.Collections.Generic;
namespace SqlExpress.ViewModels.Consulta
{
    public class EditViewModel
    {
        public int? Peso {get;set;}
        public List<Exame> ExamesFisicos
        {
            get
            {
                var exames = new List<Exame>();
                if (Peso != null)
                    exames.Add(new Exame(){Nome="Peso", Valor=Peso.ToString()});                    
                return exames;
            }
        }

    }
}
```

This line got incorrect indentation:

```
exames.Add(new Exame() { Nome = "Peso", Valor=P = so.ToString()}) ;
```

It should be like this:

```
exames.Add(new Exame() { Nome = "Peso", Valor = Peso.ToString()}) ;
```

_Copied from original issue: Microsoft/vscode#6968_

**Comment by DustinCampbell** [comment] 2016-11-24 05:52
@larini: I'm sorry that this issue has grown so stale. Do you see this problem with the latest release of the C# extension?

**Comment by DustinCampbell** [comment] 2017-02-07 19:22
Closing as I can't reproduce this issue. IIRC, there was a VS Code issue with formatting that got fixed a while back which caused some issues in C# formatting.

**Closed by DustinCampbell** 2017-02-07 19:22 UTC
Labels: Resolved-Not Reproducible
