### ISSUE TITLE
Omnisharp server not starting

### ISSUE THREAD

**Issue by taunon** [OmniSharp/omnisharp-vscode#3909] opened 2020-07-12 14:25 UTC
## Steps to Reproduce ##
Open solution directory, any .cs file, Intellisense is not working.
Also, trying a command such as '.NET: Restore Project' resulted in an error (OmniSharp server is not running.)

## Expected Behavior ##
Working Intellisense

## Actual Behavior ##
No Omnisharp features are working. Looks like the Omnisharp server never loads. There is no process with PID: 21916 (from Omnisharp log) in Windows Task Manager. 
Windows Event Logs don't show any errors. When I start omnisharp.exe manually, I can see it in the task manager, but VScode still says the server is not running.

Things I've tried:
- Restarting Omnisharp
- Increasing server load timeout to 1200
- Reinstalling Omnisharp (past 3 versions)
- Reinstalling VScode

### OmniSharp log ###
Starting OmniSharp server at 7/12/2020, 5:13:55 PM
    Target: j:\Dropbox\Projects\Udemy\Reactivities\Reactivities.sln

OmniSharp server started.
    Path: c:\Users\tauno\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.4-beta.40\OmniSharp.exe
    PID: 21916

The screen cannot be set to the number of lines and columns specified.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

### C# log ###
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!

## Environment information ##

**VSCode version**: 1.47.0
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.22.1|;

</details>

**Comment by cartermp** [comment] 2020-07-14 23:25
@taunon it looks like you have a beta version of omnisharp set. If you go to the `omnisharp.path` setting, can you set this to the default and check if this reproduces for your solution?

**Comment by cartermp** [comment] 2020-09-23 03:07
Closing as no more info was given.

**Closed by cartermp** 2020-09-23 03:07 UTC
Labels: Needs More Info, Triaged

**Comment by sj185907** [comment] 2021-12-15 23:04
I'm a noob, and it's saying "Unable to build and debug. Omnisharp server is not running." 
HELPPPPP
