### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by manuel999999** [OmniSharp/omnisharp-vscode#3630] opened 2020-03-06 14:44 UTC
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.1`

• C# is installed but I always get this message since update: The 'C#' extension is recommended for this file type.
• Also this: The extension 'C#' took a very long time to complete its last operation and it has prevented other extensions from running.
• C# failing when I open large projects

**Comment by daxtonb** [comment] 2020-03-06 15:03
See issue [#3623](https://github.com/OmniSharp/omnisharp-vscode/issues/3623).

**Comment by cartermp** [comment] 2020-03-10 21:20
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3620

**Closed by cartermp** 2020-03-10 21:20 UTC
Labels: Resolved-Duplicate, Triaged
