### ISSUE TITLE
"Debug adapter process has terminated unexpectedly" on certain pages.

### ISSUE THREAD

**Issue by guidobouman** [OmniSharp/omnisharp-vscode#1504] opened 2017-05-22 16:38 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version:  `1.12.2`
C# Extension version: `1.9.0`

## Actual behavior
When starting a dotnet core 1.1 debugger, the process spins up like it should. Certain pages from our web project I can visit. But visiting others will make the debugger crash with `Debug adapter process has terminated unexpectedly` 

## Expected  behavior
A working debugger.

## Settings  
launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PROJECTNAME",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceRoot}/src/PROJECTNAME/bin/Debug/netcoreapp1.1/PROJECTNAME.dll",
            "args": ["--server.urls=http://localhost:50000"],
            "cwd": "${workspaceRoot}/src/PROJECTNAME",
            "stopAtEntry": false,
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        }
    ]
}
```   

## Logs
Crash report:
```
...

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000102031c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

...

Thread 16 Crashed:
0   libsystem_malloc.dylib        	0x00007fffac11027e malloc_zone_malloc + 103
1   libvsbaseservices.dylib       	0x00000001041c23f8 HeapAlloc + 40
2   libvsdebugeng.impl.dylib      	0x000000010450f11e MakeStream(unsigned char const*, unsigned int, IStream**) + 46
3   libvsdebugeng.impl.dylib      	0x00000001044e6fc8 SymProvider::CDiaLoader::LoadSymbolsForModuleInstance(Microsoft::VisualStudio::Debugger::DkmModuleInstance*) + 312
4   libvsdebugeng.dylib           	0x00000001046b6cc2 dispatcher::DkmModuleInstance::FireCreateEvent() + 274
5   libvsdebugeng.dylib           	0x00000001046b6acd dispatcher::Clr::DkmClrModuleInstance::Create(_GUID const&, dispatcher::DkmString*, dispatcher::DkmString*, unsigned long, dispatcher::DkmModuleVersion*, dispatcher::Symbols::DkmSymbolFileId*, dispatcher::DkmModuleFlags, dispatcher::DkmModuleMemoryLayout, unsigned long, unsigned int, unsigned int, dispatcher::DkmString*, dispatcher::Clr::DkmClrRuntimeInstance*, _GUID const&, dispatcher::Clr::DkmClrModuleFlags, dispatcher::Clr::DkmClrAppDomain*, unsigned int, bool, dispatcher::Symbols::DkmModule*, dispatcher::DkmModuleInstance::MinidumpInfo const*, dispatcher::DkmDataItem const&, dispatcher::Clr::DkmClrModuleInstance**) + 957
6   libvsdebugeng.dylib           	0x00000001046b7175 ProcAEA58B7861C86E08A55546A1C4D0ACAD + 229
7   libvsdebugeng.impl.dylib      	0x000000010447812c ManagedDM::CDbiCallback::DoLoadModuleImpl(ManagedDM::CClrInstance*, unsigned int, Microsoft::VisualStudio::Debugger::Clr::DkmClrAppDomain*, ICorDebugModule*, Microsoft::VisualStudio::Debugger::DkmModuleFlags, Microsoft::VisualStudio::Debugger::DkmString*, Microsoft::VisualStudio::Debugger::Clr::DkmClrModuleInstance**, ManagedDM::CDMModule**) + 2604
8   libvsdebugeng.impl.dylib      	0x0000000104478d4d ManagedDM::CDbiCallback::DoLoadModule(ICorDebugAppDomain*, ICorDebugModule*, Microsoft::VisualStudio::Debugger::DkmModuleFlags, Microsoft::VisualStudio::Debugger::Clr::DkmClrModuleInstance**) + 253
9   libvsdebugeng.impl.dylib      	0x000000010447cca3 ManagedDM::CDbiCallback::DoDebugEvents(ATL::CAtlList<CComObjectPtr<ManagedDM::CManagedDebugEvent>, ATL::CElementTraits<CComObjectPtr<ManagedDM::CManagedDebugEvent> > >*) + 1603
10  libvsdebugeng.impl.dylib      	0x00000001044b3dc4 ManagedDM::CV2DbiCallback::OnDebugEvent() + 196
11  libvsdebugeng.impl.dylib      	0x0000000104474ddd ManagedDM::CDbiCallback::LoadModule(ICorDebugAppDomain*, ICorDebugModule*) + 541
12  libvsdebugeng.impl.dylib      	0x00000001044b1910 ManagedDM::CV2DbiCallback::LoadModule(ICorDebugAppDomain*, ICorDebugModule*) + 96
13  libmscordbi.dylib             	0x0000000104e48113 ShimProxyCallback::LoadModule(ICorDebugAppDomain*, ICorDebugModule*)::LoadModuleEvent::Dispatch(ManagedEvent::DispatchArgs) + 35
14  libmscordbi.dylib             	0x0000000104e7ea7f CordbProcess::DispatchRCEvent() + 399
15  libmscordbi.dylib             	0x0000000104e880c8 CordbRCEventThread::FlushQueuedEvents(CordbProcess*) + 152
16  libmscordbi.dylib             	0x0000000104e88892 CordbRCEventThread::ThreadProc() + 1074
17  libmscordbi.dylib             	0x0000000104e88a39 CordbRCEventThread::ThreadProc(void*) + 9
18  libmscordaccore.dylib         	0x00000001051f5bf8 CorUnix::CPalThread::ThreadEntry(void*) + 328
19  libsystem_pthread.dylib       	0x00007fffac1a79af _pthread_body + 180
20  libsystem_pthread.dylib       	0x00007fffac1a78fb _pthread_start + 286
21  libsystem_pthread.dylib       	0x00007fffac1a7101 thread_start + 13
```

I'll be happy to provide more debugging info.

**Comment by gregg-miskelly** [comment] 2017-05-22 16:56
@guidobouman There is now a beta release, [v1.10.0-beta4](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.10.0-beta4), which is available with this fix. See [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) for instructions on installing.

**Comment by gregg-miskelly** [comment] 2017-05-22 16:57
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1456

**Closed by gregg-miskelly** 2017-05-22 16:57 UTC

**Comment by guidobouman** [comment] 2017-05-23 08:35
I was sure I tried this update. But I might have run into another issue before downgrading back to the official release. Let me try this again.

**Comment by guidobouman** [comment] 2017-05-23 08:44
@gregg-miskelly Thanks for getting back so quickly, this was indeed the fix for this issue! (I was indeed having another unrelated issue that I solved later on.)
