### ISSUE TITLE
Intellisense broken Visual Studio code with update to 1.23.3

### ISSUE THREAD

**Issue by DaCapoAlCoder** [OmniSharp/omnisharp-vscode#4114] opened 2020-10-14 08:41 UTC
## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## OmniSharp log
Starting OmniSharp server at 14/10/2020, 09:35:55
    Target: /home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.sln

OmniSharp server started.
    Path: /home/dacapoalcoder/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/run
    PID: 981586

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/home/dacapoalcoder/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/dacapoalcoder/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/home/dacapoalcoder/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/dacapoalcoder/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/dacapoalcoder/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/dacapoalcoder/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.Tests/topsecretproject.Tests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject' on host 981065.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.Tests/topsecretproject.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.Tests/topsecretproject.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/dacapoalcoder/projects/topsecretproject/backend/topsecretproject/topsecretproject.Tests/topsecretproject.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: topsecretproject
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: topsecretproject.Test

## Steps to reproduce
Update from version 1.23.2 to 1.23.3

## Expected  behavior
Intellisense works as normal

## Actual behavior
Intellisense options do not show up when using dot operator

**Comment by johnboker** [comment] 2020-10-14 15:03
Looks like a related issue at https://github.com/OmniSharp/omnisharp-vscode/issues/4110

Downgrading from 1.23.3 to 1.23.2 fixes the problem for me for now.

**Comment by TCROC** [comment] 2020-10-14 18:27
I can confirm that I also have this issue and that downgrading has also fixed it for me

**Comment by oskarious** [comment] 2020-10-15 10:32
Running into the same thing, but downgrading to 1.23.2 does not fix it for me

**Comment by DaCapoAlCoder** [comment] 2020-10-15 10:41
@oskarious What version of .net sdk are you running

**Comment by oskarious** [comment] 2020-10-15 10:48
@DaCapoAlCoder 3.1.403. Was on 3.0.101 previously, but updating didn't seem to help unfortunately

**Comment by DaCapoAlCoder** [comment] 2020-10-15 10:51
@oskarious Downgrading to 3.1.402 might get it working for you again. I've ran into an issue before where omnisharp broke after upgrading the sdk

**Comment by filipw** [comment] 2020-10-15 10:59
this is resolved in https://github.com/OmniSharp/omnisharp-roslyn/pull/1984 which will be released with extension 1.23.4

**Comment by oskarious** [comment] 2020-10-15 11:00
@DaCapoAlCoder Same on 3.1.402 unfortunately. Thanks for the help though, appreciated. I'll hold out until 1.23.4 which @filipw just mentioned. 🙏

**Comment by TCROC** [comment] 2020-10-15 14:48
> Running into the same thing, but downgrading to 1.23.2 does not fix it for me
@oskarious You also have to regenerate your CS Project files:

![image](https://user-images.githubusercontent.com/24307049/96146135-fa96b080-0ed3-11eb-9f7c-4a9759a0b2f1.png)

**Comment by JoeRobich** [comment] 2020-10-15 16:22
A pre-release build of 1.23.4 is available at https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.4. Please try it out and let us know if it resolves the issues you are seeing.

**Comment by DaCapoAlCoder** [comment] 2020-10-15 16:26
@JoeRobich After a cursory run through that seems to have fixed it

**Comment by breadnone** [comment] 2020-10-15 16:39
Good god, every update from omnisharp makes my heart beats faster...

**Comment by filipw** [comment] 2020-10-20 11:38
> @JoeRobich After a cursory run through that seems to have fixed it

thanks for confirming

**Closed by filipw** 2020-10-20 11:38 UTC
