### ISSUE TITLE
Type "override" should show a list of virtual function of base class?

### ISSUE THREAD

**Issue by guoboism** [OmniSharp/omnisharp-vscode#1184] opened 2017-02-06 03:10 UTC
If it is not a feature already , I would suggest to add auto-completion for override-able functions after typing "override".

public class LevelButtonEditor : Editor {

    override 

   //will pop a list and we can select one and result in below

    public override void OnInspectorGUI() {
    }

}

**Comment by DustinCampbell** [comment] 2017-02-06 13:54
Hi! This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1044.

**Closed by DustinCampbell** 2017-02-06 13:54 UTC
Labels: Resolved-Duplicate
