### ISSUE TITLE
Changing marketplace publisher from ms-vscode to ms-dotnettools causes extension recommendations to repeat ad nauseum

### ISSUE THREAD

**Issue by rjgotten** [OmniSharp/omnisharp-vscode#3620] opened 2020-03-05 15:47 UTC
## Steps to reproduce

1. Have an old version of the extension installed that uses `ms-vscode.csharp` as the extension ID.
2. Be upgraded to `ms-dotnettools.csharp`.
3. Have a project that uses extension recommendations, set up to install the extension under the new `ms-dotnettools.csharp`

## Expected behavior
Everything keeps working normally.

## Actual behavior
Constantly keep being pestered with the need to install a not-yet-installed recommended extension, even though the extension is already installed.

**Comment by rjgotten** [comment] 2020-03-05 15:54
## NOTE

Issue can be worked around by
1. going into the VSCode extensions folder (`%USERPROFILE/.vscode/extensions/` on Windows)
2. opening the `ms-dotnettools.csharp` extension folder holding the locally installed extension.
3. opening the `package.json` file.
4. editing the `publisher` field to the `ms-dotnettools` value.

Moral of the story;
Probably don't just change the publisher on the marketplace without also correctly updating the package manifest?

**Comment by widgetcollector** [comment] 2020-03-05 17:55
Your workaround does not work for me, @rjgotten, but my situation may be slightly different (perhaps we have different situations or encountered different repo states)

`<h2>Steps To Reproduce</h2>`
1. Open an existing workspace for which the "csharp" extension is "recommended", that was created before the release of the latest extension version 1.21.13 (I have Azure Functions app workspaces that were built prior to March 5, 2020)
2. Let VS Code update the csharp extension to the latest available version (automatic in my case, but could be manual for other users)

`<h2>Expected behavior</h2>`
Everything keeps working normally.

`<h2>Actual behavior</h2>`
VS Code still recommends the extension referencing the old publisher attribute and shows the following warning notification after the latest extension has been upgraded to v1.21.13:

"The below 1 extension(s) in workspace recommendations have issues:
ms-vscode.csharp (not found in marketplace)"

`<strong>NOTE</strong>`: In this case, Investigating %USERPROFILE%/.vscode/extensions/ms-dotnettools.csharp-1.21.13/package.json reveals that it already has the new publisher attribute ("publisher": "ms-dotnettools")

`<h2>Workaround</h2>`
Because the existing workspace references the old publisher attribute value ("ms-vscode.csharp"), the only workaround I know of is to edit every such workspace in the following way: 

1. Edit each workspace's extensions file: \.vs-code\extensions.json 
2. Change the recommendation line from "ms-vscode.csharp" to "ms-dotnettools.csharp"
3. Load/Reload the given workspace(s)
4. Result: No more publisher mismatch for the recommended plugin, so no warning notification.

This really should not happen with such a broadly used and recommended extension :(

Hope this helps some folks

**Comment by JoeRobich** [comment] 2020-03-05 17:55
@rjgotten Sorry about that. There was a gap time between the publisher switch and we when we were able to publish a new build with the updated publisher id. We published a new release this morning so things should be back in a good state. Note you will likely see a suggestion to try the C# extension but that should go away with the next insiders release 3/6 and the next stable release 3/9.

**Comment by widgetcollector** [comment] 2020-03-05 18:07
Totally understand and appreciate the reply, hopefully others can avoid the nagging message using my quick workaround or perhaps somebody has another suggestion for the interim end-user workaround.

From the extension upgrade side of things, is there not a means (formal SOP or similar) to update the publisher attribute at the repo/asset level without such issues resulting?  I'm thinking super simply here, but some manifest attribute that can list historical publisher values.  I'm not sure how the extensions mechanisms work internally, but it would be nice if you could change things like the publisher or extension name while still keeping mappings to the previous states such that VS Code could easily detect and handle these types of changes?  (e.g. VS Code would recognize that a workspace is simply using an old reference and not render such warnings, or have a mechanism that updates recommendations automatically)

**Comment by JoeRobich** [comment] 2020-03-05 18:38
@widgetcollector I believe on the backend, requests for the package under the old publisher will get forwarded correctly. The issue is that the suggestion engine is just doing a string comparison and not aware of the package forwarding.

**Comment by videopilot** [comment] 2020-03-05 19:30
Unfortunately, it also seems to prevent other extensions from loading:

<img width="566" alt="publisher" src="https://user-images.githubusercontent.com/6528746/76018185-d4e10c00-5eed-11ea-946f-d7e40d07c44b.png">
<img width="557" alt="publisher2" src="https://user-images.githubusercontent.com/6528746/76018193-d90d2980-5eed-11ea-9e22-aab6ffafd7a3.png">

**Comment by rjgotten** [comment] 2020-03-05 20:03
> @widgetcollector 
> my situation may be slightly different (perhaps we have different situations or encountered different repo states)

Yes; you seem to have had the dual of my problem; a recommendation setting for the old publisher ID and an installation that according to:

> _NOTE: In this case, Investigating %USERPROFILE%/.vscode/extensions/ms-dotnettools.csharp-1.21.13/package.json reveals that it already has the new publisher attribute ("publisher": "ms-dotnettools")_

--- came with the new publisher ID. I guess that means you must've installed the new version with the fixed publisher ID that @JoeRobich referred to, while I was still served the old one.

Good to hear that everything is syncing back up and the problem will fix itself.

> @videopilot 
> Unfortunately, it also seems to prevent other extensions from loading:

_That_ though... Ouch. That sounds significantly more nasty than a bit of notification-nag. Probably better to roll back to the old version and disable auto-updates until the other extensions can catch up. Or maybe a compatibility package published under the old publisher ID can be issued in the mean time, to serve as a pass-through/proxy or something?

**Comment by petergiuntoli** [comment] 2020-03-05 20:04
@videopilot you could try https://github.com/Unity-Technologies/vscode-unity-debug/pull/152 for a fix for unity and track https://github.com/Unity-Technologies/vscode-unity-debug/issues/153 for a related issue.  I've made the change locally.  I had rolled back to https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.12 for a bit this morning which also worked.

**Comment by zachstronaut** [comment] 2020-03-05 21:11
Rolling back to 1.21.12 via uninstall and command line code --install-extension csharp-1.21.12.vsix worked for me... intellisense back up and running

**Comment by SporeProductions** [comment] 2020-03-05 21:25
I've had to stop work and waste hours searching for a solution and finally happened on this thread. Not good as I'm self-employed. I don't know where to start with "rolling back" things. Surely there was a more graceful way to have handled this change? Was it absolutely necessary to change publisher id?? Millions of devs use VSCode.

**Comment by zachstronaut** [comment] 2020-03-05 21:33
> I've had to stop work and waste hours searching for a solution and finally happened on this thread. Not good as I'm self-employed. I don't know where to start with "rolling back" things. Surely there was a more graceful way to have handled this change? Was it absolutely necessary to change publisher id?? Millions of devs use VSCode.

Same here. Instructions:

1. uninstall c# extension (and disable any other extensions that are throwing errors because of c# not being "found").

2. Download csharp-1.21.12.vsix from here: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.12

3. Restart VS Code

4. Open the Command Palette in VS Code. Search for "shell command install" and run that 

4. Open a command line terminal and go to the folder you downloaded the vsix file to

5. Run: code --install-extension csharp-1.21.12.vsix

6. Restart VS Code

7. Open Preferences -> Settings in VS Code. Search for "update" and uncheck Extensions: Auto Update

**Comment by rjgotten** [comment] 2020-03-06 08:57
> @JoeRobich 
> Note you will likely see a suggestion to try the C# extension but that should go away with the next insiders release 3/6 and the next stable release 3/9

I take it you're refering to the built-in notifications in VS Code to use a pre-determined extension to handle files of a known type?

**Comment by cha0tic75** [comment] 2020-03-07 19:12
Thank you zachstronaut!  Sorry, you lost so much time researching the issue and thank you for saving me time with your solution.  It worked perfectly.

**Comment by warethis-dev** [comment] 2020-03-08 08:57
Thank you @zachstronaut this thing's been driving me crazy. I finally found this and that worked perfectly

**Comment by enriquemorenotent** [comment] 2020-03-08 21:33
Having the same problem with Ubuntu 19.10

**Comment by pantapita** [comment] 2020-03-08 22:52
Same problem /w Ubuntu 18.04

**Comment by zephyo** [comment] 2020-03-08 22:58
Same problem with macOS Mojave

**Comment by rjgotten** [comment] 2020-03-09 08:23
> Rolling back to 1.21.12 via uninstall and command line code --install-extension csharp-1.21.12.vsix worked for me

Eventually did the same as well, because next to these issues the new .13 release has major performance problems too - hanging for minutes on end and clogging up all manner of other functionality in VS Code, all the way to git commit/pull/push/etc actions.

It's just completely broken and imho should be pulled.

**Comment by lm-ffx** [comment] 2020-03-09 08:32
Same problem /w Windows 10. Rolling to csharp-1.21.12 back fixed it.

**Comment by leehans** [comment] 2020-03-09 08:58
> 4. Open the Command Palette in VS Code. Search for "shell command install" and run that

Thanks @zachstronaut , this worked for me as well. I didn't have to do step 4, though (as I couldn't find that specific item in the command palette).

**Comment by nvtuan96** [comment] 2020-03-09 10:26
@zachstronaut  thank bro

**Comment by panzerstadt-dev** [comment] 2020-03-09 15:05
Thanks @zachstronaut , and I also didn't do step 4, instead I downloaded the vsix package, and seached for "Install from VSIX" to run that.

**Comment by JoeRobich** [comment] 2020-03-09 23:22
I've got an update. I've verified that the latest stable and insiders releases, which are available now, no longer suggest installing the C# extension from the old publisher. However, extensions with dependencies on the C# extension still need to be republished specifying the new publisher.

**Comment by enriquemorenotent** [comment] 2020-03-10 08:17
@JoeRobich Confirmed. v1.43.0 fixed the popup

**Comment by cartermp** [comment] 2020-03-10 22:21
Closing as the issue with the popup is resolved. #3620 is tracking the overall rename issue.

**Comment by cartermp** [comment] 2020-03-10 22:22
Haha, whoops, I'm stupid. Re-opening.

**Comment by cartermp** [comment] 2020-03-10 22:33
Update regarding unity: https://github.com/Unity-Technologies/vscode-unity-debug/pull/152

Pull request is merged, so once the unity debugger extension is updated, this shouldn't be an issue for folks using it. A lot of reports here came from that. Many other extensions have had PRs sent to them, but it will take time for them to incorporate those changes and publish updates. Since the name change is final (and changing it again would break things again), I think we'll just have to close this out as by design. Sorry for the horrible inconvenience here. We'll strive to do better and ensure something like this doesn't happen again.

**Closed by cartermp** 2020-03-10 22:33 UTC
Labels: Resolved-By Design, Triaged

**Comment by alecperkey** [comment] 2020-03-13 16:03
> Update regarding unity: [Unity-Technologies/vscode-unity-debug#152](https://github.com/Unity-Technologies/vscode-unity-debug/pull/152)
> 
> Pull request is merged, so once the unity debugger extension is updated, this shouldn't be an issue for folks using it. A lot of reports here came from that. Many other extensions have had PRs sent to them, but it will take time for them to incorporate those changes and publish updates. Since the name change is final (and changing it again would break things again), I think we'll just have to close this out as by design. Sorry for the horrible inconvenience here. We'll strive to do better and ensure something like this doesn't happen again.


https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by alecperkey** [comment] 2020-03-13 16:19
asdf

**Comment by abouroubi** [comment] 2020-09-21 13:58
Still having the issue with v1.23.2 and VS Code Insider 1.50.0-insider

**Comment by JoeRobich** [comment] 2020-09-21 17:30
@abouroubi Sorry you are seeing this issue. What is the message that you are seeing in VS Code?

**Comment by abouroubi** [comment] 2020-09-21 17:53
@JoeRobich VSCode send a notification each time I open a C# project.
`The 1 extension(s) below, in workspace recommendations have issues: ms-vscode.csharp (not found in marketplace)`

**Comment by JoeRobich** [comment] 2020-09-21 20:01
@abouroubi Workspace recommendations are stored locally in your workspace and must be manually updated (https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions). You should be able to change `ms-vscode.csharp` to `ms-dotnettools.csharp` to get rid of this message.

**Comment by abouroubi** [comment] 2020-09-22 12:49
@JoeRobich Thank you, it helped me solve it.
So if someone has the same issue, for me it was a project created with Azure Function Extension, wich had an outdated extension name.
