### ISSUE TITLE
VS Code broken: Omnisharp reqires a complete install of mono

### ISSUE THREAD

**Issue by TCROC** [OmniSharp/omnisharp-vscode#5448] opened 2022-11-09 13:10 UTC
![image](https://user-images.githubusercontent.com/24307049/200838492-ec8699ed-6469-4cd5-875f-b7c5fc22da24.png)

My VS Code started giving me this error yesterday.  My OS is Ubuntu 20.04.  I use mono when developing for unity.  "useModernNet" is false.

When running "mono --version" I get this output:

```
mono --version
Mono JIT compiler version 6.12.0.182 (tarball Tue Jun 14 22:35:00 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```

And msbuild --version

```
msbuild --version
Microsoft (R) Build Engine version 16.10.1 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.10.1.31701
```

**Comment by YW0330** [comment] 2022-11-09 15:41
I meet same problem :cry:

**Comment by YW0330** [comment] 2022-11-09 15:57
https://github.com/OmniSharp/omnisharp-vscode/issues/5443#issuecomment-1308955329 This is useful for me.

**Comment by TCROC** [comment] 2022-11-09 17:57
@YW0330 Thanks!  I found downgrading it to help as well.  I'll keep this issue open tho until its resolved.  Not sure why the other one closed

**Comment by dibarbet** [comment] 2022-11-09 21:30
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5443 .  Should be resolved in the next release (hopefully today).  Until then, the linked issue has workarounds.

**Closed by dibarbet** 2022-11-09 21:30 UTC
Labels: Resolved-Duplicate, Triaged
