### ISSUE TITLE
Intellisense showing the appropriate context menu suggestion last

### ISSUE THREAD

**Issue by radu-matei** [OmniSharp/omnisharp-vscode#265] opened 2016-04-30 09:25 UTC
For example,  when in a console  application I write a `Console.WriteLine` without having a `using System` statement, if I trigger the context menu, the appropriate action (add a `using System` statement)  is the last, which can cause some confusion.

![screen shot 2016-04-30 at 12 18 51 pm](https://cloud.githubusercontent.com/assets/13103165/14935095/80827874-0ece-11e6-8095-5ef6214feabc.png)

**Comment by DustinCampbell** [comment] 2016-05-04 14:43
This is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/86.

Essentially, there's some very strange ordering code over in omnisharp-roslyn that we need to take a look at. There are also several refactorings offered in your screenshot that shouldn't show up here.

**Closed** 2016-08-27 10:57 UTC
Labels: Resolved-Duplicate

**Comment by cwe1ss** [comment] 2016-09-17 10:04
@DustinCampbell Would it be better to keep this issue open and close the other one since this addresses the general ordering issue?

E.g. it's the same with "Implement interface". IMO this should be at the top and the first 4 shouldn't even be there:
 
![omnisharp-quickfix](https://cloud.githubusercontent.com/assets/4581460/18607511/8b2e66e8-7cce-11e6-80c0-6785fae2c24d.PNG)
