### ISSUE TITLE
Remote debugging not working on arm-linux with yocto

### ISSUE THREAD

**Issue by geoffrey-vl** [OmniSharp/omnisharp-vscode#3356] opened 2019-10-17 15:28 UTC
We have 2 devices to test .Net Core upon. Both are ARM i.MX6 systems, the mayor difference is the Yocto distro.

I successfully have setup remote debugging on one system (yocto 2.2) using both VSCode and VS2019 using following tutorials:
https://www.hanselman.com/blog/RemoteDebuggingWithVSCodeOnWindowsToARaspberryPiUsingNETCoreOnARM.aspx
https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio

Repeating that same process on the other device running yocto 2.4 doesn't work.
Both VSCode and VS2019 go into debugging mode, but at that point the debugger halts without nothing happening. It doesn't hit my first breakpoint.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     fsl-imx-x11
 OS Version:  4.9.88-2.0.0
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/root/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/home/root/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/home/root/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/home/root/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.39.2
C# Extension version: 1.21.5

## Steps to reproduce
See tutorials

## Expected  behavior
Hit breakpoint on first line of code

## Actual behavior
Debugger halts

**Comment by geoffrey-vl** [comment] 2019-10-17 15:33
Managed to get it working, the goal was rather to share my findings.
Possible it is related to [#27124](https://github.com/dotnet/coreclr/issues/27124) and [#15693](https://github.com/dotnet/coreclr/issues/15693).

## Fix
The fix is to add the following to the launch.json:
```
"env": {
    "COMPlus_LTTng": "0"
}
```

Its working for both VSCode and VS2019

**Comment by gregg-miskelly** [comment] 2019-10-29 01:22
It sounds like this is really a dupe of https://github.com/dotnet/coreclr/issues/27124, so I will resolve this as external.

**Closed by gregg-miskelly** 2019-10-29 01:22 UTC
