### ISSUE TITLE
VS Code Error Some projects have trouble loading. Please review the output for more details.

### ISSUE THREAD

**Issue by tarekahf** [OmniSharp/omnisharp-vscode#5111] opened 2022-03-17 07:12 UTC
## Issue Description ##
Error when creating and loading dotnet console application for .NET 5.0

## Steps to Reproduce ##
- Start VS Code under Windows 10
- Create a new dotnet project using C#
```
dotnet new console --framework net5.0
```
- Try to use IntelliSense

## Expected Behavior ##
Everything is working fine and C# IntelliSense is working.

## Actual Behavior ##
Error reported from OmniSharp Output Log.
You can build and run the project, but IntelliSense is not working.

It was working before and suddenly stopped working.

### OmniSharp log ###
<details>Post the output from Output-->[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Projects\Jira\LPLCLSINT-389-DocGen\tests\tests.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Projects\Jira\LPLCLSINT-389-DocGen\tests\tests.csproj'.
System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  
See the full output log attached.

[OmniSharp output.log](https://github.com/OmniSharp/omnisharp-vscode/files/8282168/OmniSharp.output.log)
</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.65.2
**C# Extension**: 1.24.1

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.102\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|2.10.9|
|Bookmarks|alefragnani|13.2.4|
|code-spell-checker|streetsidesoftware|2.1.7|
|csharp|ms-dotnettools|1.24.1|
|data-workspace-vscode|ms-mssql|0.1.1|
|dotnet-test-explorer|formulahendry|0.7.7|
|fabric8-analytics|redhat|0.3.5|
|java|redhat|1.4.0|
|mssql|ms-mssql|1.13.0|
|open-lnk|EnkelDigital|0.0.1|
|packsharp|elsnoman|2.3.2|
|powershell|ms-vscode|2021.12.0|
|sql-database-projects-vscode|ms-mssql|0.14.1|
|vscode-commons|redhat|0.0.6|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-fileutils|sleistner|3.5.0|
|vscode-html-css|ecmel|1.11.0|
|vscode-java-debug|vscjava|0.38.0|
|vscode-java-dependency|vscjava|0.19.0|
|vscode-java-pack|vscjava|0.22.0|
|vscode-java-test|vscjava|0.34.2|
|vscode-maven|vscjava|0.35.1|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-yaml|redhat|1.5.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.17|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by filipw** [comment] 2022-03-17 10:17
duplicate of #5113 

see https://github.com/OmniSharp/omnisharp-vscode/issues/5113#issuecomment-1070753945

**Closed by filipw** 2022-03-17 10:17 UTC
