### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。always

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#1702] opened 2017-08-11 09:28 UTC
_From @yalishanyi on August 11, 2017 8:27_

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.扩展主机意外终止。请重新加载窗口以恢复。always
2.

_Copied from original issue: Microsoft/vscode#32294_

**Comment by weinand** [comment] 2017-08-11 09:28
What did you do when this happened?

**Comment by weinand** [comment] 2017-08-11 09:28
_From @yalishanyi on August 11, 2017 9:9_

下载安装之后，安装c#扩展之后弹出这个警告，然后点"重新加载窗口也没用"，删除软件再重装也没用，每次都会弹出来，sorry,my english is poor

警告是：
扩展主机意外终止。请重新加载窗口以恢复。

**Comment by weinand** [comment] 2017-08-11 09:28
@yalishanyi even if your English is poor, it would be great if you could help us by using a translation tool. Since my Chinese is poor as well, I'll have to use the translation tool:
 
Translation:
Download and install, after the installation of c # expansion pop-up after the warning, and then "reload the window is useless", remove the software and then reload is useless, each time will pop up
The warning is:
The extended host terminated unexpectedly. Please reload the window to restore.

**Comment by weinand** [comment] 2017-08-11 09:28
Since this seems to be related to C# I'm moving this issue.

**Comment by yalishanyi** [comment] 2017-08-11 09:39
@weinand It is no use unloading c #. What are the methods I can try solving this problem

**Comment by DustinCampbell** [comment] 2017-08-11 12:35
@yalishanyi: If I understand you correctly, it sounds like you're seeing this with the C# extension installed but you also see it after uninstalling the C# extension. Is that correct?

**Comment by DustinCampbell** [comment] 2017-08-23 14:33
@yalishanyi: I never received an answer to my question above. Were you able to get this working?

**Comment by DustinCampbell** [comment] 2017-08-31 17:23
@yalishanyi: without more information, we're not able to investigate this issue. I'm going to go ahead and close it, but please feel free to reopen the issue if you have further information.

**Closed by DustinCampbell** 2017-08-31 17:23 UTC
Labels: Needs More Info

**Comment by JustinYi922** [comment] 2017-12-25 06:58
I also run this problem.
![image](https://user-images.githubusercontent.com/12181444/34334732-ef6f70c0-e983-11e7-97bb-44f971f9c8d9.png)
Can you tell me how to deal with it?

**Comment by sistersun1newbie** [comment] 2017-12-28 02:24
![qq 20171228101146](https://user-images.githubusercontent.com/18097428/34398183-a2ec9008-ebb7-11e7-9f2b-1ec417330aa3.png)
![qq 20171228101218](https://user-images.githubusercontent.com/18097428/34398184-a33854a2-ebb7-11e7-9642-abd21bfb9333.png)

I've had this problem before and I solved the problem by deleting the git folder.
I have this problem again today.The same approach doesn't work.
I was just trying to install a git plug-in, but that's what happens when I install it.
Then I uninstall the plugin but the problem is not solved.
This problem does not crash the software, but it does affect my use because the error message cannot be turned off.
I can only delete this dom in the console to solve this problem temporarily.
Here are the plug-ins I tried to install before
![qq 20171228102328](https://user-images.githubusercontent.com/18097428/34398350-3120e7d8-ebb9-11e7-8bed-9426917d7c2a.png)
