### ISSUE TITLE
Debugger prints "You may only use the Microsoft .NET Core Debugger (vsdbg)..."

### ISSUE THREAD

**Issue by astepanov83** [OmniSharp/omnisharp-vscode#3699] opened 2020-03-30 10:32 UTC
`dotnet -info`:
```
/home/alex/Downloads$ dotnet --info                                                  
.NET Core SDK (reflecting any global.json):                                          
 Version:   2.2.402                                                                  
 Commit:    c7f2f96116                                                               
                                                                                     
Runtime Environment:                                                                 
 OS Name:     ubuntu                                                                 
 OS Version:  18.04                                                                  
 OS Platform: Linux                                                                  
 RID:         ubuntu.18.04-x64                                                       
 Base Path:   /usr/share/dotnet/sdk/2.2.402/                                         
                                                                                     
Host (useful for support):                                                           
  Version: 2.2.7                                                                     
  Commit:  b1e29ae826                                                                
                                                                                     
.NET Core SDKs installed:                                                            
  2.2.402 [/usr/share/dotnet/sdk]                                                    
                                                                                     
.NET Core runtimes installed:                                                        
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All] 
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App] 
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]       
                                                                                     
To install additional .NET Core runtimes or SDKs:                                    
  https://aka.ms/dotnet-download                                                     
```

VS Code version:
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic
```

C# Extension version:
1.21.15

## Steps to reproduce
Opened a folder with sln file and C# projects in it. Added the following launch configuration:

```
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/trigger_management/bin/Debug/trigger_management.exe",
            "args": [],
            "cwd": "${workspaceFolder}/trigger_management/bin/Debug",
            "console": "internalConsole",
            "stopAtEntry": false,
        }
```
Clicked Run -> Start Debugging. 

## Expected  behavior
The binary is executed

## Actual behavior
Got the following message in debug console:

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

**Comment by WardenGnaw** [comment] 2020-03-30 18:22
That message means the debugger has started up.

Can you enable logging to help us investigate what the debugger is currently doing?

You can do this by adding to your `launch.json`:
```
"logging": {
   "engineLogging": true
}
```

**Comment by ErtanM** [comment] 2020-04-21 19:24
I think I'm having the same issue, these are my logs;

### Dotnet info
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Bjorn\gradebook\GradeBook> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### VS Code output;
```
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"C:\\Users\\Bjorn\\gradebook\\GradeBook/GradeBookConsole/bin/Debug/netcoreapp3.1/GradeBookConsole.dll","args":[],"cwd":"C:\\Users\\Bjorn\\gradebook\\GradeBook/GradeBookConsole","console":"internalConsole","stopAtEntry":false,"justMyCode":false,"logging":{"engineLogging":false},"internalConsoleOptions":"openOnSessionStart","__sessionId":"a8d1d8ee-7542-42af-8e51-77c517bbc716"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":3}
<- (R) {"seq":6,"type":"response","request_seq":3,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":4}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/ProcessCreate","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.5.20117.1 commit:2a72eb2aadc6bc6a29b05ebcc642a2699007df45","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.17763"}}}
<- (E) {"seq":8,"type":"event","event":"process","body":{"name":"C:\\Users\\Bjorn\\gradebook\\GradeBook\\GradeBookConsole\\bin\\Debug\\netcoreapp3.1\\GradeBookConsole.dll","systemProcessId":16344,"isLocalProcess":true,"startMethod":"launch"}}
<- (E) {"seq":9,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Launch","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.5.20117.1 commit:2a72eb2aadc6bc6a29b05ebcc642a2699007df45","VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.17763","VS.Diagnostics.Debugger.vsdbg.Launch.Duration":156,"VS.Diagnostics.Debugger.vsdbg.TargetType":"Live","VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":0}}}
<- (R) {"seq":10,"type":"response","request_seq":4,"success":true,"command":"configurationDone"}
-> (C) {"command":"threads","type":"request","seq":5}
<- (R) {"seq":11,"type":"response","request_seq":5,"success":true,"command":"threads","message":"","body":{"threads":[]}}
<- (E) {"seq":12,"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\3.1.3\\System.Private.CoreLib.dll'. Cannot find or open the PDB file.\n"}}
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Private.CoreLib.dll'. Cannot find or open the PDB file.
<- (E) {"seq":13,"type":"event","event":"module","body":{"reason":"new","module":{"id":1000,"name":"System.Private.CoreLib.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\3.1.3\\System.Private.CoreLib.dll","isOptimized":true,"isUserCode":false,"version":"4.700.20.11803","symbolStatus":"Cannot find or open the PDB file."}}}
<- (E) {"seq":14,"type":"event","event":"thread","body":{"reason":"started","threadId":19028}}
<- (E) {"seq":15,"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Users\\Bjorn\\gradebook\\GradeBook\\GradeBookConsole\\bin\\Debug\\netcoreapp3.1\\GradeBookConsole.dll'. Symbols loaded.\n"}}
Loaded 'C:\Users\Bjorn\gradebook\GradeBook\GradeBookConsole\bin\Debug\netcoreapp3.1\GradeBookConsole.dll'. Symbols loaded.
<- (E) {"seq":16,"type":"event","event":"module","body":{"reason":"new","module":{"id":1001,"name":"GradeBookConsole.dll","path":"C:\\Users\\Bjorn\\gradebook\\GradeBook\\GradeBookConsole\\bin\\Debug\\netcoreapp3.1\\GradeBookConsole.dll","isOptimized":false,"isUserCode":true,"version":"1.00.0.0","symbolStatus":"Symbols loaded.","symbolFilePath":"C:\\Users\\Bjorn\\gradebook\\GradeBook\\GradeBookConsole\\bin\\Debug\\netcoreapp3.1\\GradeBookConsole.pdb"}}}
<- (E) {"seq":17,"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\3.1.3\\System.Runtime.dll'. Cannot find or open the PDB file.\n"}}
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Runtime.dll'. Cannot find or open the PDB file.
<- (E) {"seq":18,"type":"event","event":"module","body":{"reason":"new","module":{"id":1002,"name":"System.Runtime.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\3.1.3\\System.Runtime.dll","isOptimized":true,"isUserCode":false,"version":"4.700.20.12001","symbolStatus":"Cannot find or open the PDB file."}}}
<- (E) {"seq":19,"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\3.1.3\\System.Console.dll'. Cannot find or open the PDB file.\n"}}
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Console.dll'. Cannot find or open the PDB file.
<- (E) {"seq":20,"type":"event","event":"module","body":{"reason":"new","module":{"id":1003,"name":"System.Console.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\3.1.3\\System.Console.dll","isOptimized":true,"isUserCode":false,"version":"4.700.20.12001","symbolStatus":"Cannot find or open the PDB file."}}}
<- (E) {"seq":21,"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\3.1.3\\System.Threading.dll'. Cannot find or open the PDB file.\n"}}
```

### VS Code version info
```
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

### C# extension version: **1.21.17**

**Comment by gregg-miskelly** [comment] 2020-04-21 20:44
@ErtanM are you seeing some sort of problem?

That log indicates that the debugger successfully started and launched the app, and the app is just sitting there. If you are expecting the app to do something, you might want to hit the 'pause' button to break into your app and see where it is stuck.

**Comment by jakubsuchybio** [comment] 2020-04-22 10:56
Same problem here with logs:
```
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"name":"Cake: Task Debug Script (CoreCLR)","type":"coreclr","request":"launch","program":"C:\\dev\\Csharp\\cake-test/tools/Cake.CoreCLR/Cake.dll","args":["c:\\dev\\Csharp\\cake-test\\build.cake","--target=\"Default\"","--debug","--verbosity=normal"],"cwd":"C:\\dev\\Csharp\\cake-test","stopAtEntry":true,"console":"internalConsole","logging":{"exceptions":false,"moduleLoad":false,"programOutput":true,"engineLogging":false,"browserStdOut":false},"internalConsoleOptions":"openOnSessionStart","__sessionId":"7ca8e6a6-0d09-4569-9ad1-623179265ac3"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":3}
<- (R) {"seq":6,"type":"response","request_seq":3,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":4}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/ProcessCreate","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.5.20117.1 commit:2a72eb2aadc6bc6a29b05ebcc642a2699007df45","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.18363"}}}
<- (E) {"seq":8,"type":"event","event":"process","body":{"name":"C:\\dev\\Csharp\\cake-test\\tools\\Cake.CoreCLR\\Cake.dll","systemProcessId":25684,"isLocalProcess":true,"startMethod":"launch"}}
<- (E) {"seq":9,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Launch","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.5.20117.1 commit:2a72eb2aadc6bc6a29b05ebcc642a2699007df45","VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.18363","VS.Diagnostics.Debugger.vsdbg.Launch.Duration":16,"VS.Diagnostics.Debugger.vsdbg.TargetType":"Live","VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":0}}}
<- (R) {"seq":10,"type":"response","request_seq":4,"success":true,"command":"configurationDone"}
-> (C) {"command":"threads","type":"request","seq":5}
<- (R) {"seq":11,"type":"response","request_seq":5,"success":true,"command":"threads","message":"","body":{"threads":[]}}
<- (E) {"seq":12,"type":"event","event":"module","body":{"reason":"new","module":{"id":1000,"name":"System.Private.CoreLib.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Private.CoreLib.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":13,"type":"event","event":"thread","body":{"reason":"started","threadId":21448}}
<- (E) {"seq":14,"type":"event","event":"module","body":{"reason":"new","module":{"id":1001,"name":"Cake.dll","path":"C:\\dev\\Csharp\\cake-test\\tools\\Cake.CoreCLR\\Cake.dll","isOptimized":true,"isUserCode":false,"version":"0.37.0.0","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":15,"type":"event","event":"module","body":{"reason":"new","module":{"id":1002,"name":"System.Runtime.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Runtime.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":16,"type":"event","event":"module","body":{"reason":"new","module":{"id":1003,"name":"Cake.Core.dll","path":"C:\\dev\\Csharp\\cake-test\\tools\\Cake.CoreCLR\\Cake.Core.dll","isOptimized":true,"isUserCode":false,"version":"0.37.0.0","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":17,"type":"event","event":"module","body":{"reason":"new","module":{"id":1004,"name":"Autofac.dll","path":"C:\\dev\\Csharp\\cake-test\\tools\\Cake.CoreCLR\\Autofac.dll","isOptimized":true,"isUserCode":false,"version":"4.09.4.0","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":18,"type":"event","event":"module","body":{"reason":"new","module":{"id":1005,"name":"netstandard.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\netstandard.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":19,"type":"event","event":"module","body":{"reason":"new","module":{"id":1006,"name":"System.Runtime.Extensions.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Runtime.Extensions.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":20,"type":"event","event":"module","body":{"reason":"new","module":{"id":1007,"name":"System.Linq.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Linq.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":21,"type":"event","event":"module","body":{"reason":"new","module":{"id":1008,"name":"Cake.Common.dll","path":"C:\\dev\\Csharp\\cake-test\\tools\\Cake.CoreCLR\\Cake.Common.dll","isOptimized":true,"isUserCode":false,"version":"0.37.0.0","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":22,"type":"event","event":"module","body":{"reason":"new","module":{"id":1009,"name":"Cake.NuGet.dll","path":"C:\\dev\\Csharp\\cake-test\\tools\\Cake.CoreCLR\\Cake.NuGet.dll","isOptimized":true,"isUserCode":false,"version":"0.37.0.0","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":23,"type":"event","event":"module","body":{"reason":"new","module":{"id":1010,"name":"System.Collections.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Collections.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":24,"type":"event","event":"module","body":{"reason":"new","module":{"id":1011,"name":"System.Console.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Console.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":25,"type":"event","event":"module","body":{"reason":"new","module":{"id":1012,"name":"System.Threading.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Threading.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":26,"type":"event","event":"module","body":{"reason":"new","module":{"id":1013,"name":"System.ComponentModel.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.ComponentModel.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":27,"type":"event","event":"module","body":{"reason":"new","module":{"id":1014,"name":"System.Collections.Concurrent.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Collections.Concurrent.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":28,"type":"event","event":"module","body":{"reason":"new","module":{"id":1015,"name":"System.Linq.Expressions.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Linq.Expressions.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
-> (C) {"command":"threads","type":"request","seq":6}
<- (R) {"seq":29,"type":"response","request_seq":6,"success":true,"command":"threads","message":"","body":{"threads":[{"id":21448,"name":"Thread #21448"}]}}
<- (E) {"seq":30,"type":"event","event":"module","body":{"reason":"new","module":{"id":1016,"name":"Anonymously Hosted DynamicMethods Assembly","path":"Anonymously Hosted DynamicMethods Assembly","isOptimized":true,"isUserCode":false,"symbolStatus":"Binary was not built with debug information."}}}
<- (E) {"seq":31,"type":"event","event":"module","body":{"reason":"new","module":{"id":1017,"name":"System.Runtime.InteropServices.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Runtime.InteropServices.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":32,"type":"event","event":"module","body":{"reason":"new","module":{"id":1018,"name":"System.Runtime.InteropServices.RuntimeInformation.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Runtime.InteropServices.RuntimeInformation.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":34,"type":"event","event":"module","body":{"reason":"new","module":{"id":1019,"name":"System.IO.FileSystem.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.IO.FileSystem.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":35,"type":"event","event":"module","body":{"reason":"new","module":{"id":1020,"name":"System.Memory.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Memory.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":36,"type":"event","event":"module","body":{"reason":"new","module":{"id":1021,"name":"System.ObjectModel.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.ObjectModel.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":38,"type":"event","event":"module","body":{"reason":"new","module":{"id":1022,"name":"System.Diagnostics.Tracing.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.17\\System.Diagnostics.Tracing.dll","isOptimized":true,"isUserCode":false,"version":"4.06.28619.1","symbolStatus":"Skipped loading symbols."}}}
<- (E) {"seq":39,"type":"event","event":"output","body":{"category":"console","output":"The program '[25684] Cake.dll' has exited with code 1 (0x1).\n"}}
The program '[25684] Cake.dll' has exited with code 1 (0x1).
<- (E) {"seq":40,"type":"event","event":"exited","body":{"exitCode":1}}
<- (E) {"seq":41,"type":"event","event":"terminated","body":{}}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":7}
<- (E) {"seq":42,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.5.20117.1 commit:2a72eb2aadc6bc6a29b05ebcc642a2699007df45","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.18363","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}
<- (R) {"seq":43,"type":"response","request_seq":7,"success":true,"command":"disconnect"}

```

**Comment by gregg-miskelly** [comment] 2020-04-22 15:28
@jakubsuchybio can you elaborate? What is happening/not happening that you are expecting?

**Comment by jakubsuchybio** [comment] 2020-04-23 05:20
@gregg-miskelly I also created issue ticket in cake-vscode extension repo.
There is also repro steps.
Basically I just have repo with cake-build script. If you open it with vs code, install ```cake``` extension you will get codelens for Tasks in .cake scripts. Those code lenses are ```run task``` and ```debug task```. Also there is also ```.vscode/launch.json``` from which I can F5 debug that script, which works. But running debug through that ```debug task``` code lens crashes with error mentioned in my previous post with log.

**Comment by gregg-miskelly** [comment] 2020-04-23 16:53
Thanks @jakubsuchybio, to make sure I understand, you are talking about the following message? That actually isn't an error - it is just license text.

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

**Comment by gregg-miskelly** [comment] 2020-04-23 17:52
I am going to close this issue for now, because I think it is confusing people. If anyone is experiencing a problem (and not just confused by the license text) please open a new issue.

**Closed by gregg-miskelly** 2020-04-23 17:52 UTC
Labels: Debugger, Needs More Info, Triaged

**Comment by jakubsuchybio** [comment] 2020-04-23 18:03
@gregg-miskelly  Well in the log near the end there is
```
The program '[25684] Cake.dll' has exited with code 1 (0x1).
```
So it crashed because of some other reason. I have concrete repro, so can we investigate somehow further?

**Comment by gregg-miskelly** [comment] 2020-04-23 18:28
@jakubsuchybio sounds good. Let us know if you find this is a debugger problem.

**Comment by Iron-E** [comment] 2020-04-30 01:07
I'm getting this issue too. By issue, I don't mean that the message is printing— I mean that the message is the only thing that happens. I can launch debugging after creating a simple test that only involves simple number addition and subtraction and it does not execute a single thing. No breakpoints, and no end. I cannot pause, and restarting the debug session yields an error:

```
WARNING: Unable to connect to debuggerEventsPipeName '/home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.17/.TestDebugEvents-581800'. Cannot assign requested address /home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.17/.TestDebugEvents-581800
```

I'm having issues with running tests in `OmniSharp.vim` too, I'll file that issue in the proper location though.

I have also enabled logging as per the previously stated instructions, and there does not seem to be any further output other than the legal message and this:

```
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session started.
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session ended.
```

in the output window (the "ended" appearing after manually stopping the debug session after waiting several minutes to see if it would resolve itself).

**Comment by Perustaja** [comment] 2020-06-02 19:38
Same issue here. I know it's an odd problem to describe. I am using Arch Linux. I can run and debug the same projects in Windows just fine, both .NET Core and ASP.NET Core. Using the same project and extensions on Arch, my debugger just hangs after displaying the licensing message regardless of whether it's a simple console app or a webapi with or without tests. Cannot debug tests either if they are present. 

In fact adding the logging statement to launch.json still results in just that message being printed for me. Everything runs properly, just debugging support doesn't.

**Comment by gregg-miskelly** [comment] 2020-06-02 21:19
@Perustaja if you installed VS Code from the Arch package repository: the problem is that you have the OSS version of VS Code, and the C# debugger is not licensed to work in non-Microsoft products. Please install VS Code from Microsoft if you would like to use the debugger from this extension.

If that is not your problem: please open a new issue. Unfortunately this issue is very generic, so, unless you look at a debugger log to see what failure is being reported, it is hard to guess if one person's problem is the same as another. So I will lock it to prevent further comments.
