### ISSUE TITLE
Does it support the "dotnet watch" tool?

### ISSUE THREAD

**Issue by WHATSAF** [OmniSharp/omnisharp-vscode#2661] opened 2018-11-08 06:09 UTC
Just like the ```dotnet watch run```'s behaviour, after i modified some codes(the c-sharp codes) it will watch the file changes and recompile the codes.
Can somebody tell me if this plugin support that, or show me some configurations please.

**Comment by rchande** [comment] 2018-11-08 17:03
@WHATSAF Can you be more specific about what aspect of dotnet watch you're interested in? Omnisharp will detect changes to your source code and adjust language services accordingly...

**Comment by WHATSAF** [comment] 2018-11-09 10:03
@rchande I'm running a project with the ```dotnet watch run```command, when i modified the codes and save, the dotnet's watch tool will discover the file has changed and restart. What i expect is that after i modified the code, the vscode can restart the debugger automatically.

**Comment by rchande** [comment] 2018-11-09 16:16
@WHATSAF Thanks for clarifying. @gregg-miskelly thoughts?

**Comment by gregg-miskelly** [comment] 2018-11-09 17:00
This is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/2043

**Closed by gregg-miskelly** 2018-11-09 17:00 UTC
Labels: Debugger, Feature Request
