### ISSUE TITLE
Omnisharp fails to load certain .csproj files, unable to write lines to temporary file

### ISSUE THREAD

**Issue by starrodkirby86** [OmniSharp/omnisharp-vscode#1916] opened 2017-12-11 00:07 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.18.1
C# Extension version: 1.13.1

## Steps to reproduce
Loading a C# project with a ``.csproj`` file inherently similar to [this scripts template](https://github.com/Damnae/storybrew/blob/master/scripts/scripts.csproj) in VS Code.

## Expected  behavior
Omnisharp should successfully load, giving the project Intellisense luxuries and the rest of Omnisharp's cool features.

## Actual behavior
Omnisharp fails to load the ``.csproj`` file, named ``scripts``.

```
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Could not write lines to file "\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs". The UNC path should be of the form \\server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'd:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj'.
d:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj
```

### Full log
```
Starting OmniSharp server at 2017-12-10 15:57:57
    Target: d:\Alice\osu!\storybrew\projects\be-your-light\storyboard.sln

OmniSharp server started
    Path: C:\Users\Starrodkirby86\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\OmniSharp.exe
    PID: 6876

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2017 15.3.26730.12 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Starrodkirby86\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2017 15.3.26730.12 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Alice\osu!\storybrew\projects\be-your-light'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\Alice\osu!\storybrew\projects\be-your-light
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'd:\Alice\osu!\storybrew\projects\be-your-light\storyboard.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: d:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Could not write lines to file "\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs". The UNC path should be of the form \\server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'd:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj'.
d:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Alice\osu!\storybrew\projects\be-your-light'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Alice\osu!\storybrew\projects\be-your-light' on host 4728.
```

### Other remarks
Loading traditional projects, such as ones created fresh in Visual Studio, *do* work. Omnisharp can load those kinds of projects successfully without any hitches. These particular projects that Omnisharp is failing to load are generated by an editor program, which are based off [this file I linked earlier](https://github.com/Damnae/storybrew/blob/master/scripts/scripts.csproj). Perhaps there is something inherently different about this kind of project file?

This error does not occur when using the v1.12.1 release. It may be possible that this bug occurs due to an introduced feature or change made from v1.13.0 and higher. The error also occurs in Omnisharp v1.13.0, along with the latest release, v1.14.0-beta2.

**Comment by rchande** [comment] 2017-12-12 18:14
@starrodkirby86 OmniSharp was updated to use MSBuild included with Visual Studio 2017 if you have it installed. It looks like you have VS 2017 15.3 installed. Would you mind updating your VS installation to see if a newer MSBuild release solves this for you?

**Comment by Endaris** [comment] 2017-12-13 21:40
I can replicate this behaviour on two machines, most notably on a Windows 7 SP1 machine that has no Visual Studio installed.
Visual Studio Code 1.18.1 
C# Extension version: 1.13.1

### Log
```
Starting OmniSharp server at 2017-12-13 21:48:20
    Target: c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject\storyboard.sln

OmniSharp server started
    Path: C:\Users\Florian\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\OmniSharp.exe
    PID: 1448

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.1.7601.65536 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\Florian\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\Florian\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\Florian\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\Florian\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\Florian\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild
            MSBuildToolsPath = C:\Users\Florian\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject\storyboard.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject\scripts.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Could not write lines to file "\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs". Der UNC-Pfad muss folgendes Format haben: \\server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject\scripts.csproj'.
c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject\scripts.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Florian\Desktop\storybrew.1.58\projects\testproject' on host 212.
```

I also confirmed that it is working fine with v1.12.1

**Comment by starrodkirby86** [comment] 2017-12-13 22:30
Thank you for your response, @rchande .

Upgraded my VS to 15.5. However, I'm still getting the same ``MSBuild`` error:

```
Starting OmniSharp server at 2017-12-13 14:01:46
    Target: d:\Alice\osu!\storybrew\projects\be-your-light\storyboard.sln

OmniSharp server started
    Path: C:\Users\Starrodkirby86\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\OmniSharp.exe
    PID: 14868

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2017 15.5.27130.2003 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Starrodkirby86\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2017 15.5.27130.2003 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Alice\osu!\storybrew\projects\be-your-light'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\Alice\osu!\storybrew\projects\be-your-light
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'd:\Alice\osu!\storybrew\projects\be-your-light\storyboard.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: d:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Could not write lines to file "\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs". The UNC path should be of the form \\server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'd:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj'.
d:\Alice\osu!\storybrew\projects\be-your-light\scripts.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Alice\osu!\storybrew\projects\be-your-light'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Alice\osu!\storybrew\projects\be-your-light' on host 9612.
```

As before, projects created in Visual Studio do not have this build error. Only the projects generated from the scripts.csproj file in the opening post seem to do that so far.

**Comment by Endaris** [comment] 2017-12-15 00:18
After some troubleshooting it occured that starrodkirby86 had linked not _quite_ the correct file.
Although very similar, the scripts template looks or rather looked like [this](https://github.com/Damnae/storybrew/blob/cdae3238cbaab9d60b5b19975f7287bee93685d4/editor/Resources/project/scripts.csproj#L22).
The notable difference being the line
`<IntermediateOutputPath>\</IntermediateOutputPath>`

Originally this line was supposed to stop the creation of an `obj/` directory.
Starting with v.1.13.0 it now seems to be mandatory.

For the time being we opted to set it to a shared cache folder in order to circumvent the problem.
It appears to me as odd that with v1.13.1 `IntermediateOutputPath` can no longer be set to `\` while `OutputPath` still can.

**Comment by DustinCampbell** [comment] 2018-01-03 16:58
With 1.13.0 of C# for VS Code, we use 1.27.2 of OmniSharp. This version of OmniSharp correctly runs a "design-time" build via MSBuild similarly to how Visual Studio does. This causes the "CoreCompile" and "Compile" targets to run all the way up to the point that the C# compiler would be invoked but stops there. This allows any targets which generate files in obj to run, which is necessary to produce all of the files and references needed for a correct design-time experience (e.g. IntelliSense, Find All References, etc.). For example, if you use the `Antlr4.CodeGenerator` and `Antlr4.Runtime` packages, you would expect that the targets those packages introduce into your project would run and the C# files generated by those targets would contribute to IntelliSense.

Setting `<IntermediateOutputPath>\</IntermediateOutputPath>` was never intended to block the production of the `IntermediateOutputPath`. Instead, you're just setting an MSBuild property that will happily be used by any of the targets runs that are trying to generate files to the `IntermediateOutputPath` as part of the design-time build. Those targets try to combine the `IntermediateOutputPath` with the names of the files they're trying to generate, producing paths like `\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs`.

Does that make sense? I would expect you to see similar warnings in the Output window in Visual Studio when trying to do this (though you might have turn up the verbosity of the build output in the VS settings).

**Comment by DustinCampbell** [comment] 2018-01-23 19:32
Is there any action for us on this issue? AFAICT, it looks like you were depending on some MSBuild behavior that wouldn't ever have been guaranteed to work and you've applied another workaround. I don't think there's anything we can do to change the MSBuild behavior.

**Comment by DustinCampbell** [comment] 2018-01-23 19:32
If you have any other input, let me know. For now, I'll go ahead and close this issue.

**Closed by DustinCampbell** 2018-01-23 19:32 UTC

**Comment by inox99** [comment] 2018-03-18 11:18
I got the same problem, (in my case) creating a cordova project, adding a windows platform and loading plug-ins.
So if there is a .sln-file AND you have Visual-Studio installed, maybe you get further help, if you open the sln-file with Visual Studio getting a Migration Report. 
I assume if Visual-Studio can't build, OmniSharp can't also, as it uses the same build engine.
