### ISSUE TITLE
Every single error message is displayed twice.

### ISSUE THREAD

**Issue by vim2meta** [OmniSharp/omnisharp-vscode#1878] opened 2017-11-17 21:05 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version: 1.18.1
C# Extension version: 1.13.1

## Steps to reproduce
Open any C# file.

## Expected  behavior
Only one error message will be shown per error.

## Actual behavior
Every single error message is shown exactly twice: https://i.imgur.com/7WwUdn9.png. This does not only happen for semicolons, but for every C# error all the time.

## Additional information
I have reinstalled both the C# extension and VS Code with no success. I have also noticed that right after opening VS Code, errors are only displayed once at first, but after around 2-3 seconds, every single error message will be shown twice from that point on. Furthermore, this happens **only** with the C# extension. When using linters for other languages, error messages are only displayed once.

**Comment by filipw** [comment] 2017-11-17 21:30
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1830

**Comment by vim2meta** [comment] 2017-11-18 19:46
@filipw Is there an ETA on the fix for this?

**Comment by DustinCampbell** [comment] 2017-11-20 14:32
Since this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1830, I'm going to go ahead and close this issue. Please continue any discussion over there.

**Closed by DustinCampbell** 2017-11-20 14:32 UTC
Labels: Resolved-Duplicate

**Comment by josmithua** [comment] 2021-03-16 20:11
I'm still seeing this issue. Only difference between the two duplicated error lines is on the right of the problems pane:
```
...       (CS1061) [12, 93]
... csharp(CS1061) [12, 93]
```

Is it because I have the C# extension installed?

```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```
