### ISSUE TITLE
C# debugging output does not allow to click and jump into the error (Windows?)

### ISSUE THREAD

**Issue by zeroskyx** [OmniSharp/omnisharp-vscode#1463] opened 2017-05-07 10:03 UTC
Back in the project.json days, the debugging output allowed you to click onto errors/ warnings/ messages in the output dialog since messages contained: C:\Path\To\Project\And\File.cs(100,16)
At least on windows, csproj only displays relative paths that are not picked up by VSCode as links

Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Implementations\SingleInstance\FiveRings\DataService.cs(179,42): error CS7036: There is no argument given that corresponds to the required formal parameter 'TechnologyExcitement' of 'MatrixDepartment.MatrixDepartment(Guid, Guid, Guid, string, string, double, double, double, double)' [c:\Project\Project.csproj]
Implementations\SingleInstance\FiveRings\DataService.cs(190,34): error CS7036: There is no argument given that corresponds to the required formal parameter 'TechnologyExcitementForUser' of 'MatrixPerson.MatrixPerson(Guid, Guid, Guid, string, string, double, double, double, double, ImmutableDictionary<Guid, double>, ImmutableDictionary<Guid, double>, ImmutableDictionary<Guid, double>, ImmutableDictionary<Guid, double>)' [c:\Project\Project.csproj]
Build FAILED.

Implementations\SingleInstance\FiveRings\DataService.cs(179,42): error CS7036: There is no argument given that corresponds to the required formal parameter 'TechnologyExcitement' of 'MatrixDepartment.MatrixDepartment(Guid, Guid, Guid, string, string, double, double, double, double)' [c:\Project\Project.csproj]
Implementations\SingleInstance\FiveRings\DataService.cs(190,34): error CS7036: There is no argument given that corresponds to the required formal parameter 'TechnologyExcitementForUser' of 'MatrixPerson.MatrixPerson(Guid, Guid, Guid, string, string, double, double, double, double, ImmutableDictionary<Guid, double>, ImmutableDictionary<Guid, double>, ImmutableDictionary<Guid, double>, ImmutableDictionary<Guid, double>)' [c:\Project\Project.csproj]
    0 Warning(s)
    2 Error(s)

The project file (c:\Project\Project.csproj) can be clicked which doesn't really help.
Are there plans to change this behavior back to the old pattern by
a) either prefixing the project path, or
b) making VSCode a bit smarter to pick up the paths as links on its own.

Keep up the amazing work!

Thanks in advance and best regards
-Simon

Environment data:
VSCode 1.12.1
.NET Command Line Tools (1.0.1)
Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16188
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by DustinCampbell** [comment] 2017-05-07 13:42
Thanks for the report! This is a duplicate of an issue we're tracking with https://github.com/OmniSharp/omnisharp-vscode/issues/1197.

**Closed by DustinCampbell** 2017-05-07 13:42 UTC
Labels: Resolved-Duplicate
