### ISSUE TITLE
Consider implementing an ignore file/setting

### ISSUE THREAD

**Issue by TomasHubelbauer** [OmniSharp/omnisharp-vscode#2185] opened 2018-04-13 08:29 UTC
I have a repository which has a `data` directory in it. This `data` directoty is Git-ignored and in its tree has several .NET Core projects for various reasons. I would like to prevent the C# extension from prompting me to install dependencies for these nested .NET Core projects each time I open the main project with the `data` directory in it. The extension's contributions have some settings for supressing certain warnings and such, but I would like this to only apply to the `data` directory and have the extension work as usual for the root project. Is this something you're open to including in the extension? My idea is that either a `.netignore` file could exist that would work identically to the `.gitignore` file or there could be a repository-level (the `.vscode` directory) setting where I could ignore it using a glob pattern.

**Comment by DustinCampbell** [comment] 2018-04-13 15:03
Thanks for filing this issue! I believe it's a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1694 and https://github.com/OmniSharp/omnisharp-roslyn/issues/896.

Let me know if you disagree.

**Closed by DustinCampbell** 2018-04-13 15:03 UTC
Labels: Resolved-Duplicate
