### ISSUE TITLE
Creating a comment doc block

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#20] opened 2016-01-26 16:09 UTC
_From @TheColorRed on January 21, 2016 2:21_

Is there anything that will allow for shorthand creation of documentation?

So for example, in C# if I type:

`///` and press <kbd>Enter</kbd>

It would create a doc comment block

    /// <summary>
    ///     Summary of my item
    /// </summary>

It would add things such as:

* Summary
* Parameters
* Return
* Etc.

_Copied from original issue: Microsoft/vscode#2140_

**Comment by jrieken** [comment] 2016-01-26 16:09
_From @Tyriar on January 21, 2016 5:25_

I believe you could do this with an extension

**Comment by jrieken** [comment] 2016-01-26 16:09
_From @weinand on January 21, 2016 9:11_

@TheColorRed Please try snippets: https://code.visualstudio.com/docs/customization/userdefinedsnippets

**Comment by jrieken** [comment] 2016-01-26 16:09
_From @TheColorRed on January 21, 2016 16:9_

I did do snippets as a final, but you can't have a snippet of `///` so I had to use text instead. However, it would be nice if either: 

* The editor picked up that `///` was a saved snippet
* That this doc feature was built into the editor

**Comment by jrieken** [comment] 2016-01-26 16:09
_From @alexandrudima on January 26, 2016 11:15_

@TheColorRed Would you expect that typing `///` prepopulates the contents in the doc comment with the parameters and return type of the current method?

cc @jrieken : would be a nice rich language feature

**Comment by jrieken** [comment] 2016-01-26 16:09
The omnisharp extension should handle that

**Comment by jrieken** [comment] 2016-01-26 16:09
_From @TheColorRed on January 26, 2016 15:32_

@alexandrudima Yeah, that is what I was thinking would happen. It would also be nice if it was supported in other languages as well (at least eventually).

**Comment by DustinCampbell** [comment] 2016-01-27 16:20
This is a duplicate of #8.

**Closed** 2016-01-27 16:20 UTC
Labels: Resolved-Duplicate
