### ISSUE TITLE
VScode can't find using Microsoft.MixedReality

### ISSUE THREAD

**Issue by JuenTingShie** [OmniSharp/omnisharp-vscode#4145] opened 2020-10-24 14:26 UTC
## Issue Description ##
I'm Develop Unity App for HoloLnes 2, recently when I using vscode to edit my code, it keep showing that some of my using is not found, like:

* using Microsoft.MixedReality

or

* GetComponent<TMPro.TMP_Dropdown> ()

My codes still can be build and run,but it confuse me so much since I am a coding noob if without IntelliSense, 

The solution I found is

```
Downgrade C# extension version to **1.23.1**
```

It fix problem that I describe above, but maybe someone is be confuse by this issue, maybe it will be fix another version?

and also I found that this issue not appear to MRTK.Examples... but mine projects

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: ~~1.23.1~~ I edited it, It is latest version before I downgrade

<details><summary>Dotnet Information</summary>
.NET Core SDK (�ϬM���� global.json):
 Version:   3.1.403
 Commit:    9e895200cd

���涥�q����:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  2.1.516 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|arepl|almenon|1.0.24|
|better-cpp-syntax|jeff-hykin|1.15.0|
|clang-format|xaver|1.9.0|
|code-runner|formulahendry|0.11.1|
|code-settings-sync|Shan|3.4.3|
|CppSnippets|hars|0.0.14|
|cpptools|ms-vscode|1.0.1|
|csharp|ms-dotnettools|1.23.1|
|csharp-colors|logerfo|0.1.8|
|csharpfixformat|Leopotam|0.0.84|
|emojisense|bierner|0.8.0|
|html-css-class-completion|Zignd|1.19.0|
|html-preview|SimonSiefke|2.0.6|
|html-preview-vscode|tht13|0.2.5|
|html-snippets|abusaidm|0.2.1|
|java|redhat|0.69.0|
|markdown-checkbox|bierner|0.1.3|
|markdown-emoji|bierner|0.0.9|
|markdown-footnotes|bierner|0.0.7|
|markdown-image-size|bierner|0.0.4|
|markdown-preview-enhanced|shd101wyy|0.5.13|
|mssql|ms-mssql|1.9.0|
|pdf|tomoki1207|1.1.0|
|python|ms-python|2020.9.114305|
|remote-ssh|ms-vscode-remote|0.55.0|
|remote-ssh-edit|ms-vscode-remote|0.55.0|
|remote-wsl|ms-vscode-remote|0.50.1|
|sonarlint-vscode|SonarSource|1.18.0|
|threejs|En10ve|0.0.1|
|unity-debug|Unity|2.7.5|
|vscode-clang|mitaki28|0.2.3|
|vscode-java-debug|vscjava|0.29.0|
|vscode-java-dependency|vscjava|0.14.0|
|vscode-java-pack|vscjava|0.10.0|
|vscode-java-test|vscjava|0.25.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vscode-language-pack-zh-hant|MS-CEINTL|1.50.2|
|vscode-leetcode|LeetCode|0.17.0|
|vscode-markdownlint|DavidAnson|0.37.1|
|vscode-maven|vscjava|0.25.0|
|vscode-mindmap|Souche|0.0.5|
|vscode-sql-formatter|adpyke|1.4.4|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|;

</details>

**Comment by filipw** [comment] 2020-10-26 19:16
This  looks like a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4113#issuecomment-714735140
Follow this discussion for an explanation and a workaround. Thanks.

**Closed by filipw** 2020-10-26 19:16 UTC
