### ISSUE TITLE
Cannot display non-ascii character correctly from Omnisharp.exe

### ISSUE THREAD

**Issue by itn3000** [OmniSharp/omnisharp-vscode#378] opened 2016-05-26 08:14 UTC
when I opened dotnet project including non ascii character path,some text in omnisharp log was corrupted.
here is my screen shot.
![corrupted-text](https://cloud.githubusercontent.com/assets/10163465/15568140/315f8498-2365-11e6-898f-0f7e8a41487d.png)

**Comment by itn3000** [comment] 2016-05-26 14:18
sorry,I forget to write my environment:
* Windows 10 x64
* vscode 1.1.1
* omnisharp-vscode 1.0.11

**Comment by DustinCampbell** [comment] 2016-05-26 18:14
I believe this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/140.

**Closed by DustinCampbell** 2016-05-26 18:14 UTC
Labels: Bug, Resolved-Duplicate
