### ISSUE TITLE
Error: Command failed: cat /etc/*-release cat: /etc/upstream-release: Is a directory

### ISSUE THREAD

**Issue by rocketfingers** [OmniSharp/omnisharp-vscode#401] opened 2016-06-04 23:25 UTC
## Environment data
 1.0.0-rc2-002411
linux Mint 17.3
`dotnet --info` output:
VS Code version:
C# Extension version:
1.0.10
## Actual behavior
Error: Command failed: cat /etc/*-release
cat: /etc/upstream-release: Is a directory

**Comment by chuckries** [comment] 2016-06-05 00:36
This is a dupe of #272.

The latest version of the extension in the marketplace does not have a fix for this, but the latest pre-release version on our [release page](https://github.com/OmniSharp/omnisharp-vscode/releases) does. Download the latest release (1.1.2) and `File -> Open` the .vsix from VS Code to install.

**Closed by chuckries** 2016-06-05 00:36 UTC

**Comment by rocketfingers** [comment] 2016-06-05 22:09
Thx for info!

W dniu niedziela, 5 czerwca 2016 Chuck Ries <notifications@github.com>
napisał(a):
