### ISSUE TITLE
#region..#endregion is not foldable if at same column as enclosed method

### ISSUE THREAD

**Issue by kieferrm** [OmniSharp/omnisharp-vscode#617] opened 2016-07-25 18:42 UTC
Moved from https://github.com/Microsoft/vscode/issues/9661:
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Regions must be in the same tab. It would be great to allow us to fold no matter if they are in the same tab or not.
![wrong](https://cloud.githubusercontent.com/assets/4130008/17082018/93afe09a-5144-11e6-809b-345afabc7cc7.png)
![right](https://cloud.githubusercontent.com/assets/4130008/17082019/95e419ee-5144-11e6-8e7f-1e5c435f0699.png)

Steps to Reproduce:
1. Create a Script (C#)
2. Create a method
3. Create a region encapsulating the method (Must be at the same tabulation)
4. Region cannot be fold
5. Move the method using tab
6. Now you can fold the region

**Comment by DustinCampbell** [comment] 2016-07-29 16:57
Hmmm... I wonder if this is fixed with #631.

**Comment by ivanz** [comment] 2016-08-02 11:01
It doesn't. I did notice that `csharp.json` has this section:

```json
  "foldingStartMarker": "^\\s*#\\s*region|^\\s*/\\*|^(?![^{]*?//|[^{]*?/\\*(?!.*?\\*/.*?\\{)).*?\\{\\s*($|//|/\\*(?!.*?\\*/.*\\S))",
  "foldingStopMarker": "^\\s*#\\s*endregion|^\\s*\\*/|^\\s*\\}",
```

There are two issues:

1. The regex's are malformed - all `/` should be escaped `\/` or in this case because they are in a string block `\\/`
2. Even fixed (locally) it still doesn't have any impact on folding in VSCode, so I am not sure what contributes to how folding works in VSCode

**Comment by DustinCampbell** [comment] 2016-08-02 15:38
I haven't investigated folding in VS Code either, so I was curious if it gathered information from the syntax grammar. Will take a closer look in the near future

**Comment by DustinCampbell** [comment] 2016-08-27 11:05
Similar to #567

**Comment by GuardRex** [comment] 2016-08-27 14:47
Probably same issue, but note that they don't seem to work at column 0 ...
![capture](https://cloud.githubusercontent.com/assets/1622880/18028109/1e344204-6c3b-11e6-97e9-9bf45da3aa8b.PNG)

**Comment by tidyui** [comment] 2016-10-31 18:21
Any updates on this issue? I can confirm that it's still the same, I use version `1.6.1` on Mac OS X

**Comment by DustinCampbell** [comment] 2016-10-31 18:22
Unfortunately, no there isn't any update on this one yet.

**Comment by JimmyDeemo** [comment] 2016-11-07 15:14
I would like to add another quirk to this bug, the folding matches on the next '#' not the end of the region. For example;

```C#
#region FOO
    //Some code
#if BAR
    //Some conditional code
#endif
    //Bit more code
#endregion
```
If you fold the FOO region it collapses to the 'BAR' part of the if.

**Comment by DustinCampbell** [comment] 2017-02-07 19:59
Just updating everyone here. The problem is that we don't actually have a way to add custom folding in VS Code today. There is an issue tracking this: https://github.com/Microsoft/vscode/issues/3422.

**Comment by guoboism** [comment] 2017-02-09 03:58
@DustinCampbell 
OmniSharp wont support folding on #region until VS Code fix stuff at their side? Sad

**Comment by DustinCampbell** [comment] 2017-02-09 03:59
@guoboism: I'm confused by your comment. There's actually no way for us to do it until we have API from VS Code to make it possible.

**Closed** 2018-05-22 15:49 UTC
Labels: Bug, Editor-Code Folding

**Comment by DarkSystemCD** [comment] 2022-05-29 00:06
Enable folding only to **regions**; by disabling all other foldable that are not regions;
