### ISSUE TITLE
Extension fails on ARM

### ISSUE THREAD

**Issue by bradcla** [OmniSharp/omnisharp-vscode#3553] opened 2020-02-05 18:42 UTC
## Issue Description ##
I have tried this with dotnet 3.1, dotnet 3.0 and now dotnet 2.2.  I have a Raspberry Pi 4 running Raspian Stretch configured with key authentication.  I am getting the following error;

[ERROR] Error: spawn /home/pi/.vscode-server/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run ENOENT

The .omnisharp directory does not exist.

I even went back to an older version of OmniSharp to see if that would resolve the issue.

I am doing development from Windows 10 using VS Code.  When I install the extension the above error is reported in the OmniSharp log.

## Steps to Reproduce ##

I reinstall from the same Raspian disk image before attempting any of the above variants.

## Expected Behavior ##

I expect OmniSharp to install properly and simplify my development process.

## Actual Behavior ##

Error is reported when extension is installed on remote server.

Starting OmniSharp server at 2/5/2020, 6:33:48 PM
    Target: /home/pi/src/Test1

[ERROR] Error: spawn /home/pi/.vscode-server/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run ENOENT

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>
Starting OmniSharp server at 2/5/2020, 6:33:48 PM
    Target: /home/pi/src/Test1

[ERROR] Error: spawn /home/pi/.vscode-server/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run ENOENT

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.10

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.110
 Commit:    4797dabd3c

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/pi/dotnet/sdk/2.2.110/

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.2.110 [/home/pi/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/home/pi/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/home/pi/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/home/pi/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.10|;

</details>

**Comment by gregg-miskelly** [comment] 2020-02-05 18:45
This extension will not work on ARM.

**Comment by filipw** [comment] 2020-02-06 07:10
OmniSharp doesn't support ARM at the moment. We discussed this recently and it may be feasible to add it though.

**Comment by gregg-miskelly** [comment] 2020-04-23 20:24
This is a duplicate of #2771

**Closed by gregg-miskelly** 2020-04-23 20:24 UTC
Labels: Feature Request, Triaged
