### ISSUE TITLE
Omnisharp.json does not support formatting for C# 7 tuples

### ISSUE THREAD

**Issue by zeroskyx** [OmniSharp/omnisharp-vscode#1320] opened 2017-03-13 22:30 UTC
With the following omnisharp.json:

    {
    	"FormattingOptions":
    	{
    		"NewLine": "\r\n",
    		"UseTabs": true,
    		"TabSize": 4,
    		"IndentationSize": 4,
    
    		"SpaceWithinMethodDeclarationParenthesis": true,
    		"SpaceWithinMethodCallParentheses": true,
    		"SpaceAfterControlFlowStatementKeyword": false,
    		"SpaceWithinExpressionParentheses": true,
    		"SpaceWithinCastParentheses": true,
    		"SpaceWithinOtherParentheses": true,
    		"SpaceWithinSquareBrackets": true
    	}	
    }

the following code:

    ( int One, int Two ) DoSomething()
    {
    	return ( 16, 5 );
    }

gets formatted to:

    (int One, int Two) DoSomething()
    {
    	return (16, 5);
    }

We do not currently have a property like "SpaceWithinTupleParenthesis".

**Comment by DustinCampbell** [comment] 2017-03-14 00:54
These also do not exist in Visual Studio 2017 or Roslyn. We discussed whether to add these as part of C# 7, and decided to wait and see if anyone actually wanted to use them once coding style for tuples settled down.

@Pilchie: Do you have ask for this in the Roslyn repo already?

**Comment by DustinCampbell** [comment] 2017-03-17 13:35
pinging @Pilchie

**Comment by Pilchie** [comment] 2017-03-17 14:36
https://github.com/dotnet/roslyn/issues/10587

**Comment by DustinCampbell** [comment] 2017-03-17 14:53
Thanks @Pilchie!

@zeroskyx: We're reliant on Roslyn for formatting. If there is enough user feedback to add support for specialized formatting around tuples in Roslyn, we'll expose that via the omnisharp.json as well. For now, this is a dupe of https://github.com/dotnet/roslyn/issues/10587.

**Closed by DustinCampbell** 2017-03-17 14:53 UTC
Labels: Resolved-Duplicate
