### ISSUE TITLE
STOP forcing output panel display!

### ISSUE THREAD

**Issue by brmassa** [OmniSharp/omnisharp-vscode#5068] opened 2022-02-23 03:39 UTC
NEVER EVER force VSCode automatically show an output. In my particular case, EVERY time I open the editor, even for a web non-c# project, a message of installing C# immediately pops up. It's HTML pop up level of annoyance.

**Comment by filipw** [comment] 2022-02-23 09:21
This is a duplicate of #5032 which was fixed in #5041

**Closed by filipw** 2022-02-23 09:21 UTC
