### ISSUE TITLE
Issue with overriding methods in .razor files

### ISSUE THREAD

**Issue by Yutsa** [OmniSharp/omnisharp-vscode#4329] opened 2021-01-04 15:15 UTC
## Issue Description ##

When I'm editing a Blazor file (`.razor`) and I want to override a method, the snippets is wrong. I have a GIF explaining my issue 

![2021-01-04-14-12-10](https://user-images.githubusercontent.com/11539831/103549598-ec8b7700-4ea7-11eb-8dc2-4d1f60733872.gif)

## Steps to Reproduce ##

As you can see in the gif, simply type "override" then your shortcut for completion and choose a method to override.

## Expected Behavior ##

The snippet should insert the right method block with the "override" section in the right place.

## Actual Behavior ##

The "override" section of the method definition is at the end.

### OmniSharp log ###
<details>Starting OmniSharp server at 04/01/2021 à 16:17:47
    Target: /home/edouard/Projects/pf1e-vtt/pf1e-vtt.sln

OmniSharp server started.
    Path: /home/edouard/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/run
    PID: 59357

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on debian 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/home/edouard/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/edouard/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/home/edouard/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/edouard/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/edouard/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/edouard/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/edouard/Projects/pf1e-vtt'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/edouard/Projects/pf1e-vtt/pf1e-vtt.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/edouard/Projects/pf1e-vtt/Server/pf1e-vtt.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/edouard/Projects/pf1e-vtt/Client/pf1e-vtt.Client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/edouard/Projects/pf1e-vtt/Shared/pf1e-vtt.Shared.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/edouard/Projects/pf1e-vtt'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/edouard/Projects/pf1e-vtt/Server/pf1e-vtt.Server.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/edouard/Projects/pf1e-vtt' on host 59231.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: /home/edouard/Projects/pf1e-vtt/Client/Pages/Counter.razor__virtual.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/edouard/Projects/pf1e-vtt/Server/pf1e-vtt.Server.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/edouard/Projects/pf1e-vtt/Server/pf1e-vtt.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/edouard/Projects/pf1e-vtt/Client/pf1e-vtt.Client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/edouard/Projects/pf1e-vtt/Client/pf1e-vtt.Client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/edouard/Projects/pf1e-vtt/Client/pf1e-vtt.Client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/edouard/Projects/pf1e-vtt/Shared/pf1e-vtt.Shared.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/edouard/Projects/pf1e-vtt/Shared/pf1e-vtt.Shared.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/edouard/Projects/pf1e-vtt/Shared/pf1e-vtt.Shared.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: pf1e-vtt.Server
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: pf1e-vtt.Client
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: pf1e-vtt.Shared
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 15,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.\\nParameter name: index\\n  at Microsoft.CodeAnalysis.Text.SourceText+LineInfo.get_Item (System.Int32 index) [0x0000f] in <02f1a35137194cc3b7bab26f0cb540aa>:0 \\n  at OmniSharp.Extensions.TextExtensions.GetPositionFromLineAndOffset (Microsoft.CodeAnalysis.Text.SourceText text, System.Int32 lineNumber, System.Int32 offset) [0x00006] in <52f5f577212a4b0da7fdb8528dac09a0>:0 \\n  at OmniSharp.Extensions.TextExtensions.GetPositionFromPoint (Microsoft.CodeAnalysis.Text.SourceText text, OmniSharp.Models.V2.Point point) [0x0000d] in <52f5f577212a4b0da7fdb8528dac09a0>:0 \\n  at OmniSharp.Extensions.TextExtensions.GetSpanFromRange (Microsoft.CodeAnalysis.Text.SourceText text, OmniSharp.Models.V2.Range range) [0x00007] in <52f5f577212a4b0da7fdb8528dac09a0>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2[TRequest,TResponse].GetTextSpan (OmniSharp.Models.V2.CodeActions.ICodeActionRequest request, Microsoft.CodeAnalysis.Text.SourceText sourceText) [0x00015] in <88f2819c12ee464e94d6700e849310cf>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2[TRequest,TResponse].GetAvailableCodeActions (OmniSharp.Models.V2.CodeActions.ICodeActionRequest request) [0x00128] in <88f2819c12ee464e94d6700e849310cf>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.GetCodeActionsService.Handle (OmniSharp.Models.V2.CodeActions.GetCodeActionsRequest request) [0x0006b] in <88f2819c12ee464e94d6700e849310cf>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].GetFirstNotEmptyResponseFromHandlers (OmniSharp.Endpoint.Exports.ExportHandler`2[TRequest,TResponse][] handlers, TRequest request) [0x00099] in <954ed0cf974c4f038a543c1ed1dfaa98>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].HandleRequestForLanguage (System.String language, TRequest request, OmniSharp.Protocol.RequestPacket packet) [0x00163] in <954ed0cf974c4f038a543c1ed1dfaa98>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].Process (OmniSharp.Protocol.RequestPacket packet, OmniSharp.Endpoint.LanguageModel model, Newtonsoft.Json.Linq.JToken requestObject) [0x0024b] in <954ed0cf974c4f038a543c1ed1dfaa98>:0 \\n  at OmniSharp.Stdio.Host.HandleRequest (System.String json, Microsoft.Extensions.Logging.ILogger logger) [0x000e7] in <60d68949688146858c57cddcbc6c56f5>:0 \"",
  "Body": null,
  "Seq": 59,
  "Type": "response"
}
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 14,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.\\nParameter name: index\\n  at Microsoft.CodeAnalysis.Text.SourceText+LineInfo.get_Item (System.Int32 index) [0x0000f] in <02f1a35137194cc3b7bab26f0cb540aa>:0 \\n  at OmniSharp.Extensions.TextExtensions.GetPositionFromLineAndOffset (Microsoft.CodeAnalysis.Text.SourceText text, System.Int32 lineNumber, System.Int32 offset) [0x00006] in <52f5f577212a4b0da7fdb8528dac09a0>:0 \\n  at OmniSharp.Extensions.TextExtensions.GetPositionFromPoint (Microsoft.CodeAnalysis.Text.SourceText text, OmniSharp.Models.V2.Point point) [0x0000d] in <52f5f577212a4b0da7fdb8528dac09a0>:0 \\n  at OmniSharp.Extensions.TextExtensions.GetSpanFromRange (Microsoft.CodeAnalysis.Text.SourceText text, OmniSharp.Models.V2.Range range) [0x00007] in <52f5f577212a4b0da7fdb8528dac09a0>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2[TRequest,TResponse].GetTextSpan (OmniSharp.Models.V2.CodeActions.ICodeActionRequest request, Microsoft.CodeAnalysis.Text.SourceText sourceText) [0x00015] in <88f2819c12ee464e94d6700e849310cf>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2[TRequest,TResponse].GetAvailableCodeActions (OmniSharp.Models.V2.CodeActions.ICodeActionRequest request) [0x00128] in <88f2819c12ee464e94d6700e849310cf>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.GetCodeActionsService.Handle (OmniSharp.Models.V2.CodeActions.GetCodeActionsRequest request) [0x0006b] in <88f2819c12ee464e94d6700e849310cf>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].GetFirstNotEmptyResponseFromHandlers (OmniSharp.Endpoint.Exports.ExportHandler`2[TRequest,TResponse][] handlers, TRequest request) [0x00099] in <954ed0cf974c4f038a543c1ed1dfaa98>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].HandleRequestForLanguage (System.String language, TRequest request, OmniSharp.Protocol.RequestPacket packet) [0x00163] in <954ed0cf974c4f038a543c1ed1dfaa98>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].Process (OmniSharp.Protocol.RequestPacket packet, OmniSharp.Endpoint.LanguageModel model, Newtonsoft.Json.Linq.JToken requestObject) [0x0024b] in <954ed0cf974c4f038a543c1ed1dfaa98>:0 \\n  at OmniSharp.Stdio.Host.HandleRequest (System.String json, Microsoft.Extensions.Logging.ILogger logger) [0x000e7] in <60d68949688146858c57cddcbc6c56f5>:0 \"",
  "Body": null,
  "Seq": 58,
  "Type": "response"
}
</details>

### C# log ###
<details>Empty</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
SDK .NET (reflétant tous les fichiers global.json) :
 Version:   5.0.101
 Commit:    d05174dc5a

Environnement d'exécution :
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|blazorsnippets|ScottSauber|1.4.0|
|code-settings-sync|Shan|3.4.3|
|csharp|ms-dotnettools|1.23.8|
|vscode-emacs-friendly|lfs|0.9.0|
|vscode-icons|vscode-icons-team|11.1.0|;

</details>

**Comment by NTaylorMullen** [comment] 2021-01-04 19:05
@Yutsa thanks for the report! For now closing as a duplicate of: https://github.com/dotnet/aspnetcore/issues/25509

Right now that issue is backlogged but I encourage you to share your support on that issue so we can more accurately triage it in the future. We make triaging decisions based on feedback / urgency from the community.

**Closed by NTaylorMullen** 2021-01-04 19:05 UTC
Labels: Razor, Resolved-Duplicate
