### ISSUE TITLE
xUnit Tests stopped working

### ISSUE THREAD

**Issue by rich-ware** [OmniSharp/omnisharp-vscode#1758] opened 2017-09-15 12:12 UTC
I am developing on a Mac and I get the error in the pic. I am using xUnit for my unit tests. Is there a fix for this? 

![screen shot 2017-09-11 at 7 45 05 am](https://user-images.githubusercontent.com/2387404/30481636-5d172968-99e5-11e7-86e4-c762922cf5a2.png)

**Comment by DustinCampbell** [comment] 2017-09-15 13:55
Hi @rich-ware -- I've not seen this specific error. Could you provide a little more information to help us investigate?

1. Could you provide the information that was requested in the issue template when you filed this issue? Most important is the environment data:
    * `dotnet --info` output:
    * VS Code version:
    * C# Extension version:
2. Could you open VS Code, reproduce the problem and then provide your OmniSharp log? You can retrieve the log by selecting View->Output in VS Code and then choosing "OmniSharp Log" from the dropdown at the top-right of the Output pane.
3. Is there any chance you could provide a project that reproduces the issue?

Thanks!

**Comment by rich-ware** [comment] 2017-09-18 20:53
dotnet --info output
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code Version: 1.16.1

C# Extension: 1.12.1

So today I ran my tests and I did not have this error. I am not sure how my error went away. I am now able to write tests and run them. I am still interested in finding out the cause and what the fix should be. My fear is I will run into this again and not be able to do TDD for my client work.

Thanks for your help! I appreciate it.

**Comment by DustinCampbell** [comment] 2017-09-18 20:54
If you do see it again, grab the OmniSharp Log before closing VS Code. There's no guarantee that it'll reveal the cause, but it might have something useful.

**Comment by rich-ware** [comment] 2017-09-18 20:56
Yes, I'll definitely grab the OmniSharp Log and share it with you. I was surprised to see my tests run successfully today.

**Comment by DustinCampbell** [comment] 2017-10-30 15:45
@rich-ware : I'm going to go ahead and close this issue. Do let me know if you see the problem again.

**Closed by DustinCampbell** 2017-10-30 15:45 UTC
Labels: Resolved-Not Reproducible, Test
