### ISSUE TITLE
Problems view: Same error appears three times, two result in "File not found"

### ISSUE THREAD

**Issue by andy-hanson** [OmniSharp/omnisharp-vscode#1588] opened 2017-06-25 00:54 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         linuxmint.18.1-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

VS Code version: 1.14.0-Insider
C# Extension version: 1.10.0

## Steps to reproduce

This problem happens for me in any project.

* Go to an empty directory
* `dotnet new console`
* `code-insiders .`
* Remove the semicolon after `Console.WriteLine("Hello World!")` and save.
* It warns: `Required assets to build and debug are missing...`. Hit "Yes".
* Ctrl-Shift-B to build.

## Expected  behavior

Exactly one problem shows up, and I can navigate to it without "File not found".

## Actual behavior

* Output:

```
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(9,46): error CS1002: ; expected [/home/andy/git/dotnet-problems/dotnet-problems.csproj]

Build FAILED.

Program.cs(9,46): error CS1002: ; expected [/home/andy/git/dotnet-problems/dotnet-problems.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.47
```

* Problems view looks like:

	- Program.cs (1)
	  X ; expected [dotnet-problems] (9, 46)

	- Program.cs / (2)
	  X ; expected [/home/andy/git/dotnet-problems/dotnet-problems.csproj] (9, 46)
	  X ; expected [/home/andy/git/dotnet-problems/dotnet-problems.csproj] (9, 46)

* Clicking on the top one works.
* Clicking on either of the bottom ones gets me an error `Unable to open 'Program.cs': File not found (/Program.cs).`

**Comment by DustinCampbell** [comment] 2017-06-26 16:05
Hi @andy-hanson! Thanks for reporting this issue. It looks to my like a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1197 and https://github.com/OmniSharp/omnisharp-vscode/issues/1198.

**Closed by DustinCampbell** 2017-06-26 16:05 UTC
Labels: Resolved-Duplicate
