### ISSUE TITLE
predefined type [xxx].[yyy] warnings & highlights

### ISSUE THREAD

**Issue by bored-user** [OmniSharp/omnisharp-vscode#3969] opened 2020-08-11 22:56 UTC
## Description ##
The extension keeps generating warnings like "Predefined type '[xxx].[yyy]' is not defined or imported" (and "The type or namespace name 'System' could not be found" on `using System;`)

## Steps to reproduce ##
Open a folder where a `dotnet new` was ran

## Expected Behavior ##
Don't show those warnings

## Actual Behavior ##
Showing warnings about predefined types even though the code compiles and runs normally. Already tried to remove `bin`, `obj` and `.vscode` folders and run `dotnet restore` and `dotnet build` (as suggested on stackoverflow - for visual studio). The warnings are still there.

### OmniSharp log ###
Starting OmniSharp server at 8/11/2020, 7:33:14 PM
    Target: /home/user/Desktop/my_app

OmniSharp server started with Mono 6.10.0.
    Path: /home/user/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/OmniSharp.exe
    PID: 4405

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on linuxmint 20.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.4 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.4 - "/home/user/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.4 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/user/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/user/Desktop/my_app'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/user/Desktop/my_app'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/user/Desktop/my_app/my_app.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/user/Desktop/my_app'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/user/Desktop/my_app/my_app.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/user/Desktop/my_app' on host 4163.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/user/Desktop/my_app/my_app.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/user/Desktop/my_app/my_app.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: my_app

### C# log ###
[empty]

## Environment information ##

**VSCode version**: 1.47.3
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.10.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  20
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|code-runner|formulahendry|0.11.0|
|code-settings-sync|Shan|3.4.3|
|coffeelinter|lkytal|1.4.0|
|color-highlight|naumovs|2.3.0|
|cpptools|ms-vscode|0.30.0-insiders|
|csharp|ms-dotnettools|1.22.1|
|csharpextensions|jchannon|1.3.1|
|dart-code|Dart-Code|3.13.2|
|debugger-for-chrome|msjsdiag|4.12.9|
|dotenv|mikestead|1.0.1|
|EditorConfig|EditorConfig|0.15.1|
|endwise|kaiwood|1.4.2|
|gc-excelviewer|GrapeCity|3.0.39|
|gitlens|eamodio|10.2.2|
|go|golang|0.16.1|
|Handlebars|andrejunges|0.4.1|
|haskelly|UCL|0.5.5|
|indent-rainbow|oderwat|7.4.0|
|java|redhat|0.65.0|
|language-haskell|justusadam|3.3.0|
|language-julia|julialang|1.0.3|
|LiveServer|ritwickdey|5.6.1|
|material-theme|zhuangtongfa|3.8.5|
|mustache|dawhite|1.1.1|
|path-intellisense|christian-kohler|2.2.1|
|php-cs-fixer|junstyle|0.1.155|
|php-debug|felixfbecker|1.13.0|
|php-intellisense|felixfbecker|2.3.14|
|python|ms-python|2020.7.96456|
|remote-ssh|ms-vscode-remote|0.51.0|
|remote-ssh-edit|ms-vscode-remote|0.51.0|
|rest-client|humao|0.24.1|
|ruby|rebornix|0.27.0|
|ruby-rubocop|misogi|0.8.3|
|rust|rust-lang|0.7.8|
|slim|sianglim|0.1.2|
|solargraph|castwide|0.21.1|
|subtitles-editor|pepri|1.0.4|
|svelte-vscode|svelte|101.9.0|
|vetur|octref|0.26.1|
|vscode-docker|ms-azuretools|1.4.1|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-firefox-debug|firefox-devtools|2.9.0|
|vscode-gemfile|bung87|0.4.0|
|vscode-html-css|ecmel|0.2.3|
|vscode-icons|vscode-icons-team|10.2.0|
|vscode-import-cost|wix|2.12.0|
|vscode-instant-markdown|dbankier|1.4.4|
|vscode-java-debug|vscjava|0.27.1|
|vscode-java-dependency|vscjava|0.10.2|
|vscode-java-pack|vscjava|0.9.1|
|vscode-java-test|vscjava|0.24.0|
|vscode-maven|vscjava|0.24.0|
|vscode-npm-script|eg2|0.3.13|
|vscode-react-native|msjsdiag|0.17.0|
|vscode-ruby|wingrunr21|0.27.0|
|vscode-svgviewer|cssho|2.0.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-yaml|redhat|0.9.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.9|
|vsliveshare|ms-vsliveshare|1.0.2619|;

</details>

**Comment by JoeRobich** [comment] 2020-08-11 23:21
@bored-user Thanks for logging this issue. We've identified it as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3951. See this comment for a workaround https://github.com/OmniSharp/omnisharp-vscode/issues/3951#issuecomment-668710888

**Closed by JoeRobich** 2020-08-11 23:21 UTC
