### ISSUE TITLE
OmniSharp does not work when there are spaces in the path.

### ISSUE THREAD

**Issue by frg2089** [OmniSharp/omnisharp-vscode#5156] opened 2022-04-06 03:16 UTC
## Issue Description ##
OmniSharp does not work when there are spaces in the path.

## Steps to Reproduce ##
0. Open VSCode.
1. Open a folder and this folder is a C# project.

## Expected Behavior ##
OmniSharp Language Server should be running.

## Actual Behavior ##
OmniSharp Language Server are not running.

## Logs ##
<details>
<summary><h3>OmniSharp log</h3></summary>

```plain
Starting OmniSharp server at 2022/4/6上午10:40:43
    Target: 

OmniSharp server started with .NET 7.0.100-preview.2.22153.17
.
    Path: D:/Program Files/omnisharp/OmniSharp.exe
    PID: 25368

'D:/Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```
<details>
<summary>Native program output are not always utf-8. This is the result of incorrectly reading gb2312 encoding as utf8 encoding</summary>

This is the result of the command prompt on a different code page.
```cmd
活动代码页: 936

C:\>D:/Program Files/omnisharp/OmniSharp.exe
'D:/Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


Active code page: 65001

C:\>D:/Program Files/omnisharp/OmniSharp.exe
'D:/Program' is not recognized as an internal or external command,
operable program or batch file.
```

</details>
</details>

### C# log ###
empty

## Environment information ##

**VSCode version**: 1.65.1
**C# Extension**: 1.24.3

<details><summary>Dotnet Information</summary>
.NET SDK (反映任何 global.json):
 Version:   7.0.100-preview.2.22153.17
 Commit:    9c52c56c13

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22581
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.2.22153.17\

Host (useful for support):
  Version: 7.0.0-preview.2.22152.2
  Commit:  e24f66dff0

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22154.4 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.2.22153.17 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.2.22153.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.2.22152.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.2.22153.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|android-dev-ext|adelphes|1.3.2|
|background|shalldie|1.1.30|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|chat|karigari|0.35.0|
|code-beautifier|michelemelluso|2.3.3|
|comment-translate|intellsmi|2.0.1|
|copilot|GitHub|1.11.5453|
|csharp|ms-dotnettools|1.24.3|
|docs-markdown|docsmsft|0.2.110|
|dotnet|formulahendry|0.0.4|
|EditorConfig|EditorConfig|0.16.4|
|eslint-rules-zh-plugin|maggie|0.1.0|
|fluent-icons|miguelsolorio|0.0.17|
|fluent-ui-vscode|leandro-rodrigues|2.0.3|
|git-graph|mhutchie|1.30.0|
|gitlens|eamodio|12.0.5|
|gradle-language|naco-siren|0.2.3|
|hexeditor|ms-vscode|1.9.5|
|ini-for-vscode|DavidWang|0.0.4|
|live-server|ms-vscode|0.2.12|
|markdown-pdf|yzane|1.4.4|
|material-product-icons|PKief|1.2.0|
|output-colorizer|IBM|0.1.2|
|postcss|csstools|1.0.9|
|powershell|ms-vscode|2021.12.0|
|preview-mp4|analytic-signal|0.0.1|
|rainbow-csv|mechatroner|2.2.0|
|remote-containers|ms-vscode-remote|0.231.3|
|remote-ssh|ms-vscode-remote|0.76.1|
|remote-wsl|ms-vscode-remote|0.64.2|
|rest-client|humao|0.24.6|
|solutionextension|Tobias-Sekan|1.9.2|
|sqlite-viewer|qwtel|0.1.5|
|svg|jock|1.4.17|
|todo-tree|Gruntfuggly|0.0.215|
|unotes|ryanmcalister|1.4.1|
|volar|johnsoncodehk|0.33.10|
|vs-keybindings|ms-vscode|0.2.1|
|vscode-caniuse|akamud|0.5.4|
|vscode-docker|ms-azuretools|1.21.0|
|vscode-dotnet-runtime|ms-dotnettools|1.5.0|
|vscode-edit-csv|janisdd|0.6.8|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-firefox-debug|firefox-devtools|2.9.6|
|vscode-fix-checksums|lehni|1.1.0|
|vscode-google-translate|funkyremi|1.4.13|
|vscode-gradle|vscjava|3.11.0|
|vscode-gradle-extension-pack|richardwillis|0.0.4|
|vscode-icons|vscode-icons-team|11.10.0|
|vscode-language-pack-zh-hans|MS-CEINTL|1.65.3|
|vscode-open|sandcastle|0.1.0|
|vscode-pull-request-github|GitHub|0.38.1|
|vscode-resx-editor|DominicVonk|0.0.5|
|vscode-sort-json|richie5um2|1.20.0|
|vscode-tailwindcss|bradlc|0.7.7|
|vscode-thunder-client|rangav|1.14.4|
|vscode-typescript-next|ms-vscode|4.7.20220403|
|vscode-vibrancy|eyhn|1.0.16|
|vscode-wasm|dtsvet|1.3.1|
|vscode-xml|redhat|0.20.0|
|vscode-yaml|redhat|1.6.0|
|vscode-zipfs|arcanis|2.3.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.18|
|vsliveshare|ms-vsliveshare|1.0.5449|
|vsliveshare-audio|ms-vsliveshare|0.1.91|
|vsliveshare-pack|ms-vsliveshare|0.4.0|
|websocket-client|mohamed-nouri|0.2.0|
|yangformat|tongfengyang|0.0.5|;

</details>

**Comment by filipw** [comment] 2022-04-06 06:05
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5150 which was fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/5154

A prerelease build is out with a fix for this issue. https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.4-beta1

**Closed by filipw** 2022-04-06 06:05 UTC
