### ISSUE TITLE
Not working on Raspberry Pi 4

### ISSUE THREAD

**Issue by Khhs167** [OmniSharp/omnisharp-vscode#4395] opened 2021-02-14 15:00 UTC
Well, I am not suprised it does not work, but it would really help if a Raspberry PI build was made. Or at least an alternative. I am using a raspberry pi and want to develop C# apps on it, but the extension(C#) is not supported, any ideas.

This text is awful, excuse me.

**Comment by lokinfey** [comment] 2021-02-18 03:15
I think this is the same problem in arm device (including Surface Pro X , Apple Silicon , Raspberry ............)

**Comment by Khhs167** [comment] 2021-02-18 11:05
> I think this is the same problem in arm device (including Surface Pro X , Apple Silicon , Raspberry ............)

Raspberry PI has an ARM processor

**Comment by gregg-miskelly** [comment] 2021-02-18 19:42
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2771

**Closed** 2021-02-18 19:42 UTC
Labels: Resolved-Duplicate
