### ISSUE TITLE
OmniShart code completion crashes

### ISSUE THREAD

**Issue by nkev** [OmniSharp/omnisharp-vscode#3194] opened 2019-07-28 08:39 UTC
## Issue Description ##
OmniShart code completion crashes at `OmniSharp.Extensions.JsonRpc.Server.JsonRpcException`
## Steps to Reproduce ##
On a Mac with VS Code with dotnet Core 2.2:
 - Follow the Orchard Core example [here](https://www.youtube.com/watch?v=4o9zG17cfa0&feature=youtu.be&t=1391): 
 - press the "dot" at the end of "Orchard." right where the video above starts.

It doesn't always happen immediately, but definitely occurs within 2 minutes, every time.

## Expected Behavior ##
Code completion works without failure

## Actual Behavior ##
Code completion crashesthe website within 2 minutes

### C# log ###
<details>
Unhandled Exception: OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Error - 6:15:24 PM] Connection to server got closed. Server will not be restarted.
</details>

## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.21.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.0.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|cordova-tools|msjsdiag|1.8.5|
|csharp|ms-vscode|1.21.0|
|debugger-for-chrome|msjsdiag|4.11.6|
|Go|ms-vscode|0.11.4|
|hg|mrcrowl|1.3.0|
|jet|diogogmt|0.0.1|
|jquerysnippets|donjayamanne|0.0.1|
|jshint|dbaeumer|0.10.20|
|json-tools|eriklynd|1.0.2|
|node-debug2|ms-vscode|1.33.0|
|npm-intellisense|christian-kohler|1.3.0|
|quicktype|quicktype|12.0.46|
|sass-indented|robinbentley|1.5.1|
|vetur|octref|0.21.1|
|vsc-docker|Zim|0.34.0|
|vscode-eslint|dbaeumer|1.9.0|
|vscode-generate-getter-setter|DSKWRK|0.5.0|
|vscode-great-icons|emmanuelbeziat|2.1.47|
|vscode-markdownlint|DavidAnson|0.29.0|
|vscode-npm-script|eg2|0.3.8|
|vscode-proto3|zxh404|0.3.0|
|vscode-wasm|dtsvet|1.2.1|;

</details>

**Comment by rchande** [comment] 2019-07-29 17:07
cc @NTaylorMullen  -- sounds like something in the Razor LS is crashing?

**Comment by rchande** [comment] 2019-07-29 17:08
Potentially a dupe of https://github.com/aspnet/Razor.VSCode/issues/372 ?

**Comment by NTaylorMullen** [comment] 2019-07-29 17:10
> Potentially a dupe of [aspnet/Razor.VSCode#372](https://github.com/aspnet/Razor.VSCode/issues/372) ?

Yup, definitely a dupe

**Closed by NTaylorMullen** 2019-07-29 17:10 UTC
Labels: Resolved-Duplicate
