### ISSUE TITLE
Intellesense not working

### ISSUE THREAD

**Issue by SluttySlug77** [OmniSharp/omnisharp-vscode#4026] opened 2020-08-29 16:06 UTC
## OmniSharp log
```
Starting OmniSharp server at 29/08/2020, 17:03:11
    Target: c:\Users\mishk\arena\arena.sln

OmniSharp server started.
    Path: c:\Users\mishk\.vscode\extensions\ms-dotnettools.csharp-1.23.1\.omnisharp\1.37.0\OmniSharp.exe
    PID: 22924

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.7.30406.217 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\mishk\.vscode\extensions\ms-dotnettools.csharp-1.23.1\.omnisharp\1.37.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.7.30406.217 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\mishk\arena'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\mishk\arena\arena.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\UnityEngine.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\Unity.TextMeshPro.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\Unity.Timeline.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\Unity.TextMeshPro.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\Unity.Timeline.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\UnityEditor.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\Unity.Rider.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\Unity.CollabProxy.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\arena\Unity.VSCode.Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\mishk\arena'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\UnityEngine.TestRunner.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\mishk\arena' on host 14560.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\mishk\arena\Assets\scripts\health.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\UnityEngine.TestRunner.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\UnityEngine.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\UnityEngine.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\UnityEngine.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\Unity.TextMeshPro.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\Unity.TextMeshPro.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\Unity.TextMeshPro.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\Unity.Timeline.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\Unity.Timeline.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\Unity.Timeline.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\Unity.TextMeshPro.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\Unity.TextMeshPro.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\Unity.TextMeshPro.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\Unity.Timeline.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\Unity.Timeline.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\Unity.Timeline.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\UnityEditor.TestRunner.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\UnityEditor.TestRunner.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\UnityEditor.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\UnityEditor.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\UnityEditor.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\Unity.Rider.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\Unity.Rider.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\Unity.Rider.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\Unity.CollabProxy.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\Unity.CollabProxy.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\Unity.CollabProxy.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\arena\Unity.VSCode.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\arena\Unity.VSCode.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\arena\Unity.VSCode.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEngine.TestRunner
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEngine.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.TextMeshPro
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.Timeline
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.TextMeshPro.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.Timeline.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEditor.TestRunner
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEditor.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.Rider.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.CollabProxy.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.VSCode.Editor
```

## Steps to reproduce
Open a script in unity.

## Expected  behavior
For intellesense to work

## Actual behavior
Intellesense not working.

**Comment by miko-t** [comment] 2020-08-31 10:59
Same problem 
Intellesense not working while working with unity,
nothing no suggestion no variables its just dead

**Comment by filipw** [comment] 2020-08-31 11:54
@miko-t if you are on Linux/macOS see https://github.com/OmniSharp/omnisharp-vscode/issues/4007#issuecomment-677405332

**Comment by jmarolf** [comment] 2020-09-01 23:22
closing as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4007

**Closed by jmarolf** 2020-09-01 23:22 UTC
