### ISSUE TITLE
Cannot debug step-by-step dotnet vstest run

### ISSUE THREAD

**Issue by evil-shrike** [OmniSharp/omnisharp-vscode#2015] opened 2018-02-07 17:48 UTC
I'm trying to debug a mstest project running inside Linux Docker container from VSCode running on Windows.

VS Code: 1.20.0-insider

Host and Docker image both have latest .net sdk.

I built and published my mstest project: `dotnet publish -f netcoreapp2.0`

Then I built an image with `docker build -t  xfw_tests_mstest:debug . -f Dockerfile.debug`
where `Dockerfile.debug` is:
```
FROM microsoft/dotnet:2.0-sdk
WORKDIR /app
COPY ./bin/Debug/netcoreapp2.0/publish/ .
WORKDIR /vsdbg
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg 
WORKDIR /app
ENTRYPOINT ["tail", "-f", "/dev/null"]
```
and run it:
```
docker run --rm -it --name xfw_tests_mstest_debug xfw_tests_mstest:debug
```

I can enter inside the container (`docker exec -it xfw_tests_mstest /bin/bash`) and check that /app folder contains all dlls **and** pdbs.

Then I created a launch.json in VSCode. VSCode I open inside my mstest project folder (not solution).

Here's my launch.json (it was a hard work to create it I should say):

```
        {
            "name": "Debug Docker",
            "type": "coreclr",
            "request": "launch",
            "cwd": "/app",
            "program": "dotnet",
            "args":[
                "vstest", "MyUnitTests.dll", "--Tests:MyTestMethod"
            ],
            "sourceFileMap": {
                "/app": "${workspaceRoot}"
            },
            "pipeTransport": {
                "debuggerPath": "/vsdbg/vsdbg",
                "pipeProgram": "docker",
                "pipeCwd": "${workspaceRoot}",
                "pipeArgs": [
                    "exec", "-i", "xfw_tests_mstest_debug"
                ],
                "quoteArgs": false
            },
            "requireExactSource": false,
            "symbolPath": [
                "${workspaceRoot}/bin/Debug/netcoreapp2.0"
            ],
            "justMyCode": false,
            "stopAtEntry": true
        }
```

As you can see I try to run `dotnet vstest MyUnitTests.dll --Tests:MyTestMethod` inside my container.

Run the configuration and I can see that my test is executed. VSCode seems to be attached. But I can't stop at a breakpoint. Even while `stopAtEntry` is true.

I set symbolPath. I check pdb inside container, set sourceFileMap. 

What can be wrong?

## Expected  behavior
Stop at a breakpoint and debug step by step.

## Actual behavior
dotnet vstest just executes and exits.

**Comment by evil-shrike** [comment] 2018-02-07 19:02
I've tried with a simplest app created with `dotnet new console` inside /test (on the container).
VSCode debugs fine (after I copied Program.cs on host)
```
            "program": "/test/",
            "program": "/test/bin/Debug/netcoreapp2.0/test.dll",
            "sourceFileMap": {
                "/test": "${workspaceRoot}"
            },
```

So the problem probably is with vstest?

**Comment by gregg-miskelly** [comment] 2018-02-07 19:23
@evil-shrike as far as I know, there is no good way to do what you are trying to do. The problem is that what you are debugging when you run `program='dotnet'` + `args='vstest...'` is a root controller process for vstest, but your user code doesn't run in that process. It runs in some worker process that this root process creates. The only way that I know of to debug such a thing would be to add some sort of `while (!Debugger.IsAttached) Thread.Sleep(100);` loop into your test code. Though maybe I am wrong, and `dotnet vstest` has some special mode to run everything in one process.

@DustinCampbell do you remember the contact for `dotnet vstest`?

**Comment by evil-shrike** [comment] 2018-02-07 22:59
thanks for the response, it makes it clearer for me..

> ..It runs in some worker process that this root process creates

Interesting, and it explains why I can't attach VSCode.
But it makes remote debugging not possible at all...

> The only way that I know of to debug such a thing would be to add some sort of while (!Debugger.IsAttached) Thread.Sleep(100); loop into your test code.

and then attach debugger to that process? but how to know what process to attach?

> dotnet vstest has some special mode to run everything in one process.

I haven't found anything similar in the [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest). 
Interesting that in previous version of [VSTest.Console.exe](https://msdn.microsoft.com/en-us/library/jj155796.aspx?f=255&MSPPError=-2147217396) there was `/InIsolation` option. So it was in-process by default.

**Comment by gregg-miskelly** [comment] 2018-02-07 23:02
RE: How to know what process to attach to - you might be able to figure it out by looking at the command line of the 'dotnet' process. We will need to find someone who knows more about how the test runner works :).

**Comment by evil-shrike** [comment] 2018-02-07 23:04
ok, I'll try to create an issue in dotnet/cli

**Comment by evil-shrike** [comment] 2018-02-12 12:33
Found some workaround via setting VSTEST_HOST_DEBUG=1 envvar and then attaching debugger.
Full story: https://techblog.dorogin.com/running-and-debugging-net-core-unit-tests-inside-docker-containers-48476eda2d2a

**Comment by gregg-miskelly** [comment] 2018-02-12 17:25
Cool! I will close this issue then.

**Closed by gregg-miskelly** 2018-02-12 17:25 UTC
Labels: Test
