### ISSUE TITLE
Unable to use go to definition

### ISSUE THREAD

**Issue by ashishmansukhani** [OmniSharp/omnisharp-vscode#1273] opened 2017-03-01 00:32 UTC
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
1.7.0
## Steps to reproduce
install extention. 
try to use go to or peek definition

**Comment by DustinCampbell** [comment] 2017-03-01 00:58
Could you provide more detailed repro steps? Do you have a C# project we could use to reproduce the issue?

**Comment by DustinCampbell** [comment] 2017-03-08 16:08
I'm going to go ahead and close this since there's not enough information provided to investigate. If you have more information that could help us reproduce the issue, let me know.

**Closed by DustinCampbell** 2017-03-08 16:08 UTC
Labels: Needs More Info
