### ISSUE TITLE
Does not support unsafe blocks

### ISSUE THREAD

**Issue by hez2010** [OmniSharp/omnisharp-vscode#3349] opened 2019-10-15 09:37 UTC
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.39.1
C# Extension version: 1.21.4

## Steps to reproduce
```
dotnet new console
add <AllowUnsafeBlocks>true</AllowUnsafeBlocks> to .csproj
open the project directory and write unsafe blocks
```

## Expected  behavior
nothing happen

## Actual behavior
intellisense throws error about the `unsafe` blocks.

**Comment by filipw** [comment] 2019-10-15 10:07
This has been supported for a long time - so it should be working.
Could you please post your omnisharp log?

**Comment by cartermp** [comment] 2020-04-16 20:39
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3525

**Closed by cartermp** 2020-04-16 20:39 UTC
Labels: Needs More Info
