### ISSUE TITLE
Debugger: watch, tooltip etc. reports a zero valued decimal field as non-zero on OSX.

### ISSUE THREAD

**Issue by maxild** [OmniSharp/omnisharp-vscode#673] opened 2016-08-17 15:39 UTC
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.4.0
C# Extension version: 1.3.0

## Steps to reproduce

```
public class MysteriousBugs
    {
        class Person
        {
            public decimal Earnings { get; set; }
        }

        [Fact]
        public void ZeroDecimalFieldOfObjectDoesNotShowUpCorrectlyInVsCodeDebugger()
        {
            var person = new Person { Earnings = 0m};
            person.Earnings.ShouldBe(0m); // <---- BREAKPOINT HERE
        }
}
```

## Expected  behavior

Put a breakpoint on the person.Earnings... debugger tooltip, watch etc should report the value as '0'.

## Actual behavior

debugger tooltip, watch etc. reports the zero value as something like '4458488992' (not zero...value not important).

**Comment by maxild** [comment] 2016-08-17 15:53
It works on windows 7 where I have identical versions of vscode and the extenion running. 

My dotnet CLI on windows is

```
.NET Command Line Tools (1.0.0-preview2-003121)       
                                                      
Product Information:                                  
 Version:            1.0.0-preview2-003121            
 Commit SHA-1 hash:  1e9d529bc5                       
                                                      
Runtime Environment:                                  
 OS Name:     Windows                                 
 OS Version:  6.1.7601                                
 OS Platform: Windows                                 
 RID:         win7-x64                                
```

I am not on linux so can't tell if the c# debugger extension work as expected here.

**Comment by gregg-miskelly** [comment] 2016-08-17 16:25
@maxild Thanks for the report. This looks like a dupe of #632.

**Closed by gregg-miskelly** 2016-08-17 16:25 UTC
Labels: Debugger, Resolved-Duplicate
