### ISSUE TITLE
Analyzers are not working well on Fedora 35.

### ISSUE THREAD

**Issue by tmds** [OmniSharp/omnisharp-vscode#5006] opened 2022-01-13 14:55 UTC
I have .NET 6 installed on Fedora 35. This is the source-built version from the Fedora package repository.

I'm using VS Code 1.62.3 with omnisharp 1.23.17.

When I create a simple library project, analyzers don't work well.

Class1.cs:
```cs
namespace lib;
public class Class1
{

}
```
lib.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.3.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <AdditionalFiles Include="PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
  </ItemGroup>

</Project>
```
omnisharp.json:
```json
{
    "RoslynExtensionsOptions": {
        "enableAnalyzersSupport": true
    },
    "FormattingOptions": {
        "enableEditorConfigSupport": true
    }
}
```
PublicAPI.Shipped.txt, PublicAPI.Unshipped.txt: empty files.

In the problem view, the issues reported by the analyzer show up:
![image](https://user-images.githubusercontent.com/1025424/149351814-bdcebe9a-af8a-4801-90cf-290f07418cce.png)

Code actions from the analyzer are available:
![image](https://user-images.githubusercontent.com/1025424/149351937-39fe9a60-ef67-45cf-91be-310fb4776d12.png)

Applying the code action doesn't seem to do anything.

OmniSharp log: [omnisharp_log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/7863683/omnisharp_log.txt)

**Comment by filipw** [comment] 2022-01-13 20:04
This is a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1592
analyzers and code action that rely on additional files, like public api analyzer are currently not supported

**Closed by filipw** 2022-01-13 20:04 UTC

**Comment by tmds** [comment] 2022-01-13 21:02
@filipw I may be hitting the same issue as OmniSharp/omnisharp-roslyn#1592.

From the log, I think there may be additional issues:

```
...
[fail]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Creating instance of code fix provider 'Microsoft.NetFramework.CSharp.Analyzers.CSharpAvoidDuplicateAcceleratorsFixer' failed, error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Composition.AttributedModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Composition.AttributedModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)
  at System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) [0x00013] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x00037] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at System.RuntimeType.GetCustomAttributes (System.Type attributeType, System.Boolean inherit) [0x00038] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at System.Attribute.GetCustomAttributes (System.Reflection.MemberInfo element, System.Type type, System.Boolean inherit) [0x00088] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at System.Attribute.GetCustomAttribute (System.Reflection.MemberInfo element, System.Type attributeType, System.Boolean inherit) [0x00000] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at System.Attribute.GetCustomAttribute (System.Reflection.MemberInfo element, System.Type attributeType) [0x00000] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at System.Reflection.CustomAttributeExtensions.GetCustomAttribute (System.Reflection.MemberInfo element, System.Type attributeType) [0x00000] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T] (System.Reflection.MemberInfo element) [0x00000] in <9f0df102fe6e4cfea29d2e46f585d8a5>:0 
  at OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects+<>c__DisplayClass6_0.<LoadFrom>b__2 (System.Reflection.TypeInfo x) [0x00000] in <dbd4c42c78874a71919856b53db6870e>:0 
Can't find custom attr constructor image: /tmp/CodeAnalysis/AnalyzerShadowCopies/6b001b8e11394c83b357712cf7fc1d56/1/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll mtoken: 0x0a000014 due to: Could not load file or assembly 'System.Composition.AttributedModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
....
```

**Comment by filipw** [comment] 2022-01-14 12:39
That one is resolved in the .NET 6.0 build of OmniSharp.

**Comment by tmds** [comment] 2022-01-14 12:48
> That one is resolved in the .NET 6.0 build of OmniSharp.

Will the next version of omnisharp-vscode use that build?

**Comment by tmds** [comment] 2022-01-18 07:51
@filipw what do I need to do (or wait for) to get that build?

**Comment by filipw** [comment] 2022-01-18 08:23
there is a pre-release here https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.0
You will need to configure `omnisharp.useModernNet` to `true` in the VS Code settings in order to use the .NET 6 build.

**Comment by tmds** [comment] 2022-01-18 09:13
Thanks!

> You will need to configure omnisharp.useModernNet to true in the VS Code settings in order to use the .NET 6 build.

Is the plan to make this the default for 1.24 final (or a future version)?

**Comment by tmds** [comment] 2022-01-25 12:55
> Is the plan to make this the default for 1.24 final (or a future version)?

@filipw ?

**Comment by filipw** [comment] 2022-01-25 19:50
1.24.0 shipped already and it is not the default option. We plan to make it default and retire the embedded Mono variant with standalone MSBuild which is the current default, but there is no timeframe yet.

**Comment by JoeRobich** [comment] 2022-02-09 18:31
@tmds Are you running with `omnisharp.path` set to 'latest'? It looks like maybe the updated Roslyn in recent builds requires a newer .NET SDK. Try installing 6.0.102 from https://dotnet.microsoft.com/en-us/download/dotnet/6 or removing the `omnisharp.path` setting for now.
