### ISSUE TITLE
Debugger: Breakpoint should be hidden while function snippet fold

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#511] opened 2016-06-30 10:29 UTC
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 Set a breakpoint at  any function in HomeController.cs
2 Fold this function

## Expected  behavior
The breakpoint should be hidden 

## Actual behavior
This breakpoint  was still displayed on the editor

**Comment by chuckries** [comment] 2016-06-30 20:51
I believe this is by design. It is a visual indicator that one or more breakpoints are set within the folded region. Screenshots for clarity:

Before Folding:
![image](https://cloud.githubusercontent.com/assets/6598594/16503797/99622242-3ec9-11e6-836a-27d8c11a5b00.png)

After Folding:
![image](https://cloud.githubusercontent.com/assets/6598594/16503811/a683a11c-3ec9-11e6-962c-52ac15e0b0f6.png)

I am going to close this as by design.

**Closed** 2016-06-30 20:53 UTC
Labels: Debugger
