### ISSUE TITLE
MSTest UnitTest file has "error" marks on testclass and method

### ISSUE THREAD

**Issue by tsalinger** [OmniSharp/omnisharp-vscode#2083] opened 2018-03-02 08:13 UTC
from @jrbobc 
Copied from original issue: [Microsoft/vscode#44883](https://github.com/Microsoft/vscode/issues/44883)

### Issue Type
Bug

### Description

From the command line create a unit test project with "dotnet new mstest".
Open the project folder, go to the UnitTest1.cs file that is auto generated.
See the red squiggles.

https://github.com/jrbobc/mstest-src

The cs file, and csproj file.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:31:21.019Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2820  @ 2.13GHz (2 x 2132)|
|Load (avg)|1, 1, 1|
|Memory (System)|3.68GB (0.15GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.28
mssql|ms-|1.3.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.1.0

</details>
Reproduces only with extensions

![image](https://user-images.githubusercontent.com/22580656/36880371-ec81caa0-1d8d-11e8-8566-563c025f0c1b.png)

Note that if you run "dotnet test" it will succeed, and run the test. It is just that VS code is improperly marking Microsoft.**VisualStudio**.TestTools.UnitTesting, **TestClass** and **TestMethod**.

**Comment by rchande** [comment] 2018-03-02 22:26
@tsalinger I'm having trouble reproducing this and would appreciate some more information from you
* If you hover on one of those squiggles, what is the error?
* What version of the .NET CLI are you on, and do you still see the problem if you upgrade to the latest release?

**Comment by jrbobc** [comment] 2018-03-03 03:17
/home/mediacenter/Desktop/Screenshot at 2018-03-02 21-12-24.png
/home/mediacenter/Desktop/Screenshot at 2018-03-02 21-07-02.png
/home/mediacenter/Desktop/Screenshot at 2018-03-02 21-06-33.png
/home/mediacenter/Desktop/Screenshot at 2018-03-02 21-06-05.png
/home/mediacenter/Desktop/Screenshot at 2018-03-02 21-05-30.png

There are the scrren shots. I'm using the "latest" version of the cli (2.0.2) that is available for my install, the latest version of vscode (1.20.1) and c# extension 1.14.0

**Comment by jrbobc** [comment] 2018-03-03 04:03
There is one other thing, that I had not considered when I filed the bug.

If you do the following commands
![image](https://user-images.githubusercontent.com/22580656/36930377-072cc670-1e65-11e8-80ad-29167710c6ff.png)

The MSTest will be a sub project within the main solution. That will generate the squiggles. However, if you do not open the "main" project in vs code, but open vs code within the test folder it will properly display the Test tools without "false" failures.

Ex: `
> mkdir mstest
 > cd mstest
 > dotnet new mstest 
 > code . 
`

**Comment by DustinCampbell** [comment] 2018-03-09 22:20
@jrbobc: Could you provide your OmniSharp Log when this issue occurs? You can retrieve this by selecting View->Output in VS Code and choosing "OmniSharp Log" from the dropdown at the top-right corner of the Output pane.

**Comment by jrbobc** [comment] 2018-03-10 02:19
Here is the OmniSharp Log:
```
Starting OmniSharp server at 3/9/2018, 8:15:15 PM
    Target: /home/mediacenter/progs/testmstest

OmniSharp server started wth Mono
    Path: /home/mediacenter/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/run
    PID: 2652

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 17.10 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/mediacenter/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/mediacenter/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/mediacenter/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /home/mediacenter/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild
            CscToolPath = /home/mediacenter/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/mediacenter/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/mediacenter/progs/testmstest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /home/mediacenter/progs/testmstest
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/mediacenter/progs/testmstest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/mediacenter/progs/testmstest/testmstest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/mediacenter/progs/testmstest/unittest/unittest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/mediacenter/progs/testmstest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/mediacenter/progs/testmstest/testmstest.csproj
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/mediacenter/progs/testmstest' on host 2561.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/mediacenter/progs/testmstest/testmstest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/mediacenter/progs/testmstest/unittest/unittest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/mediacenter/progs/testmstest/unittest/unittest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: testmstest
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: unittest

```

**Comment by jrbobc** [comment] 2018-03-10 02:30
And here is the "Problems" Tab.
![image](https://user-images.githubusercontent.com/22580656/37237334-6f909364-23d7-11e8-9bc4-d630c09f97bc.png)


And it does see the Asserts in the Intellisense. Even though they have the red squiggles that make it look like it shouldn't.
![image](https://user-images.githubusercontent.com/22580656/37237364-d7f0f692-23d7-11e8-96ac-f33b924b4df7.png)


I was doing some more testing with it too last weekend, but haven't had a chance to reply back until now.  If you create a parent folder, then have your app folder and test folder under that same folder there are no squiggles.

So the folder would look like: 
> MyProgram
>> My App
>> My Test

And no solution file in the folder. 

To reproduce with dotnet on the command line it would be 
```
mkdir mainfolder
cd mainfolder
mkdir app
mkdir mstest
cd app
dotnet new console app
cd ..
cd mstest
dotnet new mstest
cd ..
code .
```
And that will work fine. So this issue maybe able to be closed as I might have done something that is "unsupported". That being said I wouldn't think it would matter what folder you put a unit test in so long as the test has access to the dlls to be tested.

Thanks.

**Comment by rchande** [comment] 2018-03-12 16:17
@jrbobc I think your analysis is correct: projects created using `dotnet new` need to be in distinct subdirectories. The "globbing" support of the project file means that in the directory structure:
```
A/
a.csproj
a.cs
A/B/
b.csproj
b.cs
```
OmniSharp will count b.cs as a member of a.csproj if you open the A directory. That would lead to the error squiggle you saw, since a.csproj might not have the same references as b.csproj. Note that if you really want that directory structure, you can disable globbing and explicitly include items in the projects.

Thanks for taking the time to analyze this! I'm going to go ahead and close this bug. Feel free to add additional comments if you think there's more to do here.

**Closed by rchande** 2018-03-12 16:17 UTC
Labels: Needs More Info
