### ISSUE TITLE
Duplicate warnings and using suggestions - mac only

### ISSUE THREAD

**Issue by CoderJason123** [OmniSharp/omnisharp-vscode#2045] opened 2018-02-16 01:04 UTC
## Environment data
vs code 1.20 mac os high sierra
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
open any c# project, throw in some classes, generate some warnings.  it's not a pattern as to which ones will double, but it has been this way since day one one the mac.  I use it on a pc and mac, but i prefer the mac :).  I just thought it was some quirk that would eventually go away but it never has.

## Expected  behavior
work the same as a pc

## Actual behavior
see the link below where i pasted some screenshots.  I love the extension, just need to clean up some stuff if possible.
[https://github.com/Microsoft/vscode/issues/43663](url)

**Comment by rchande** [comment] 2018-02-16 16:08
@CoderJason123 We believe this was fixed in the recent 1.14 release of the C# extension for VS Code. Can you confirm what version of the extension you have?

**Comment by CoderJason123** [comment] 2018-02-16 21:27
Hi.  I am on 1.14.0 :(

**Comment by rchande** [comment] 2018-02-20 22:01
@CoderJason123 Can you try deleting ~/.omnisharp ?

**Comment by akshita31** [comment] 2018-02-20 22:11
To reinstall omnisharp you will also need to delete the install.Lock file in the extension folder.

**Comment by CoderJason123** [comment] 2018-02-21 04:03
I did all of these suggestions.  And for about 2 seconds, it appeared to work, but then the duplicates reappeared.  I will note this..there is one set of warnings showing a path, and another showing a path with a trailing slash. Like "startup.cs" and "startup.cs/"  Screen shot attached.

And another thing, i am only seeing this now for duplicate "usings", not all messages.  Now that i've updated, I can not tell you what the behavior was before.

<img width="588" alt="screen shot 2018-02-20 at 10 00 17 pm" src="https://user-images.githubusercontent.com/33351931/36462524-9d61ffcc-1689-11e8-9afc-2a3eadc52ea5.png">

**Comment by rchande** [comment] 2018-02-21 17:15
@CoderJason123 Are you using the build command to build your project? It looks like you're seeing https://github.com/OmniSharp/omnisharp-vscode/issues/1197 .

If you close and reopen VS Code to your folder, do you see any duplicate errors with the "/" character before you do a build?

**Comment by CoderJason123** [comment] 2018-02-21 21:53
no, no duplicates before I build.  interesting.

**Comment by rchande** [comment] 2018-02-22 18:19
@CoderJason123 Thanks for following up, I'm going to close this as a duplicate of #1197

**Closed by rchande** 2018-02-22 18:19 UTC

**Comment by rchande** [comment] 2018-02-22 18:33
@CoderJason123 I was able to reproduce this on a Windows machine (build -> duplicate warnings). I don't believe it's Mac specific.

**Comment by CoderJason123** [comment] 2018-02-22 19:32
Ok, good to know!  I had not seen it there or just forgot.  Thank you!
