### ISSUE TITLE
Ambigous name detected (seen by OmniSharp and not by the compiler)

### ISSUE THREAD

**Issue by gsscoder** [OmniSharp/omnisharp-vscode#3552] opened 2020-02-05 17:04 UTC
[This project](https://github.com/gsscoder/pickall) contains part of a [library](https://github.com/gsscoder/csharpx) as source in the main **csproj** and references the same library with **NuGet/Paket** in the test **csproj**.

As you can see from this screenshot:
![OmniSharp-ambigous-name-detected](https://user-images.githubusercontent.com/1194228/73863948-20e25780-4841-11ea-86ff-2bb48966a4a0.png)
the code compiles (and tests succeed).

This doesn't compromise ability to work with the project in any way. But I thought it deserves to file an issue (hope not to be wrong!).

My `dotnet --info` on **macOS Catalina**:
```sh
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

My OmniSharp log:
```
Starting OmniSharp server at 2/5/2020, 5:13:05 PM
    Target: /Users/coder/OneDrive/Projects/pickall/src/PickAll.sln

OmniSharp server started with Mono 6.8.0.
    Path: /Users/coder/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/OmniSharp.exe
    PID: 5686

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.3 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.3 - "/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.3 - "/Users/coder/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.3 - "/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /Users/coder/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/coder/OneDrive/Projects/pickall/src'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/coder/OneDrive/Projects/pickall/src/PickAll.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/coder/OneDrive/Projects/pickall/src'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/coder/OneDrive/Projects/pickall/src' on host 5591.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.OmniSharpWorkspace
        Removing analyzer reference: /Users/coder/.nuget/packages/xunit.analyzers/0.10.0/analyzers/dotnet/cs/xunit.analyzers.dll
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /Users/coder/.nuget/packages/xunit.analyzers/0.10.0/analyzers/dotnet/cs/xunit.analyzers.dll
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.OmniSharpWorkspace
        Removing analyzer reference: /Users/coder/.nuget/packages/xunit.analyzers/0.10.0/analyzers/dotnet/cs/xunit.analyzers.dll
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /Users/coder/.nuget/packages/xunit.analyzers/0.10.0/analyzers/dotnet/cs/xunit.analyzers.dll
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Sample/PickAll.Sample.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll.Specs/PickAll.Specs.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/coder/OneDrive/Projects/pickall/src/PickAll/PickAll.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Sample
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll.Specs
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PickAll
```

Best regards,
Giacomo S. S.

**Comment by filipw** [comment] 2020-02-06 07:11
thanks, are you able to share the project that reproduces the issue?

**Comment by gsscoder** [comment] 2020-02-07 06:31
@filipw, no problem! As always I'm happy to help the **OmniSharp** project.

If you need **anything else**, please don't hesitate to contact me.

**Comment by cartermp** [comment] 2020-03-19 20:43
Hey @gsscoder have you seen this happen recently? I just tried it today and can't reproduce it

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/6309070/77113237-aa13af00-69e7-11ea-808a-781570ba3e81.png">

**Comment by cartermp** [comment] 2020-09-22 23:47
Closing out as no additional info was added.

**Closed by cartermp** 2020-09-22 23:47 UTC
Labels: Needs More Info, Triaged
