### ISSUE TITLE
Omni sharp requires .NetFramework 4.7.2

### ISSUE THREAD

**Issue by BigGodMike** [OmniSharp/omnisharp-vscode#3203] opened 2019-07-31 06:39 UTC
## Issue Description ##
the enviroment information show as blow, When VScode get started, the omni Sharp report this error: Omni sharp.exe - the application can not be started ... requires .NetFramework 4.7.2 .And I am very sure I have install the right version of the framework , and I even try the lastest version of .NetFramework 4.8.0 
But the error still there. And since the Omni Sharp didn't work , the whole function of the code snippet and code assist were disable.
Hope can get your reply, thanks.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.21.0

<details><summary>Dotnet Information</summary>
.NET Core SDK����ӳ�κ� global.json��:
 Version:   2.1.403
 Commit:    04e15494b6

����ʱ����:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.0|
|csharpextensions|jchannon|1.3.0|
|csharpextensions|kreativ-software|1.3.0|
|csharpfixformat|Leopotam|0.0.82|
|ctagsx|jtanx|1.1.1|
|fresh-material|2ndshift|2.3.8|
|java|redhat|0.47.0|
|material-palenight-theme|whizkydee|1.9.5|
|mssql|ms-mssql|1.6.0|
|shaderlabvscodefree|amlovey|1.1.3|
|Theme-MaterialKit|ms-vscode|0.1.4|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-snippets|YclepticStudios|0.1.2|
|vsc-material-theme|Equinusocio|29.2.0|
|vscode-csharp-snippets|jorgeserrano|0.3.1|
|vscode-icon-theme|jtlowe|1.6.5|
|vscode-java-debug|vscjava|0.20.0|
|vscode-java-dependency|vscjava|0.5.1|
|vscode-java-pack|vscjava|0.7.1|
|vscode-java-test|vscjava|0.18.2|
|vscode-language-pack-zh-hans|MS-CEINTL|1.37.0|
|vscode-markdownlint|DavidAnson|0.29.0|
|vscode-maven|vscjava|0.18.1|
|vscode-simpler-icons|davidbabel|1.6.5|
|vscode-theme-onelight|akamud|2.1.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.8|;

</details>

**Comment by akshita31** [comment] 2019-08-02 19:34
@filipw Do you have any ideas here ?

**Comment by filipw** [comment] 2019-08-02 19:40
no idea it definitely should work

can you post a screenshot of the error? also, can you go to Control Panel > Programs and show which versions of .NET you have available?

**Comment by mota57** [comment] 2019-11-05 15:48
![image](https://user-images.githubusercontent.com/7569989/68222908-2fab3b00-ffc2-11e9-9707-5e6127068ecd.png)

@filipw

**Comment by filipw** [comment] 2019-11-05 17:56
yes please install 4.7.2 - it is required now

**Comment by binbsr** [comment] 2019-11-06 11:34
@filipw Can you please elaborate a bit on this, why the projects targeting .NET Core requires Full .NET?
I am also facing the same issue here, mine is a console app on top of .NET Core 3.0 and suddenly omnisharp window pops up for .NET 4.7.2 and ignoring that VSCode becomes notepad for C# development: No Intellisense at all :).

**Comment by filipw** [comment] 2019-11-06 13:17
OmniSharp itself (the language server) is a .NET 4.7.2 application which requires either .NET 4.7.2 on Windows or Mono on *nix. 
It's not thyoure project that requires it but in order to use OmniSharp the full framework must be available.

Note that it is a separate thing to *run* a .NET project and to *provide language services*. Due to the nature of msbuild and the wide array of project types (desktop .NET, .NET Core, Unity etc) that we need to support, the best support is possible when OmniSharp is targeting full framework.
This has been the case for a long time now (2+ years); the change from .NET 4.6.1 to .NET 4.7.2 happened in April.

This issue should be closed as "by design". cc @akshita31

**Closed** 2019-11-06 21:23 UTC
Labels: Resolved-By Design
