### ISSUE TITLE
"'Microsoft.NET.Sdk' could not be found" when running VS Code from Git Bash

### ISSUE THREAD

**Issue by inosik** [OmniSharp/omnisharp-vscode#1754] opened 2017-09-14 13:21 UTC
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Users\nosikil\scoop\apps\dotnet-sdk\current\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.15.0
C# Extension version: 1.12.1

## Steps to reproduce

In Git Bash:

```
dotnet new console
code.cmd .
```

Note that Git, the .NET SDK and VS Code are installed with [Scoop](http://scoop.sh) on my machine.

## Expected  behavior

This is what I get when running VS Code from the console or PowerShell:

```
Starting OmniSharp server at 14.9.2017, 15:09:52
    Target: d:\temp

OmniSharp server started
    Path: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\OmniSharp.exe
    PID: 5580

OmniSharp: -s d:\temp --hostPID 4480 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'd:\temp' on host 4480.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\temp
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Omnisharp will use local MSBuild.
    MSBUILD_EXE_PATH: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe
    MSBuildExtensionsPath: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'd:\temp'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: d:\temp\temp.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: temp
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\temp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.
```

## Actual behavior

This is what I get with Git Bash:

```
Starting OmniSharp server at 14.9.2017, 15:06:24
    Target: d:\temp

OmniSharp server started
    Path: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\OmniSharp.exe
    PID: 12952

OmniSharp: -s d:\temp --hostPID 7308 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'd:\temp' on host 7308.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\temp
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Omnisharp will use local MSBuild.
    MSBUILD_EXE_PATH: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe
    MSBuildExtensionsPath: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'd:\temp'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: d:\temp\temp.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'd:\temp\temp.csproj'.
d:\temp\temp.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  d:\temp\temp.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.LoadProject(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics, ImmutableArray`1& targetFrameworks)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\temp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.
```

**Comment by DustinCampbell** [comment] 2017-09-14 16:27
After launching VS Code from Git Bash, could you try running `dotnet --info` from within VS Code's Integrated Terminal and pasting the output here?

**Comment by inosik** [comment] 2017-09-15 06:02
It's the same as above:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Users\nosikil\scoop\apps\dotnet-sdk\current\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by DustinCampbell** [comment] 2017-09-15 13:23
Thanks! I'll get WSL set up on my machine and take a look.

**Comment by inosik** [comment] 2017-09-15 17:06
This has nothing to do with WSL, just plain Windows + Bash which comes with Git.

Can I make the output more verbose, to see what parameters MSBuild gets?

**Comment by DustinCampbell** [comment] 2017-09-15 17:10
Thanks! I was thinking this would be related to another issue I was talking to somebody about with WSL. Glad I'm wrong. :smile:

Try setting the `"omnisharp.loggingLevel": "debug"` option in VS Code's preferences. That might provide a few clues in the log.

**Comment by inosik** [comment] 2017-09-15 17:49
Thanks, I'll try that on Monday.

**Comment by inosik** [comment] 2017-09-18 06:21
The MSBuild parameters are the same for both cases:

```
[dbug]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild environment:
Mode: Standalone
RunningTests: False
RunningInVisualStudio: False
MSBuildToolsDirectory32: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild
MSBuildToolsDirectory64: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild
MSBuildSDKsPath: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\Sdks
CurrentMSBuildConfigurationFile: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe.config
CurrentMSBuildExePath: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe
CurrentMSBuildToolsDirectory: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild
VisualStudioInstallRootDirectory:
MSBuildExtensionsPath: C:\Users\nosikil\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild
```

The only difference I see before I get the warning message with the exception is this:

```
[dbug]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Using MSBuildSDKsPath: C:\Users\nosikil\scoop\apps\dotnet-sdk\current\sdk\2.0.0\Sdks
```

This message **is not** logged when I run VS Code from Bash.

To me this looks like MSBuild searches for the SDKs in some default directory, probably somewhere in `.vscode\ms-vscode.csharp-1.12.1\.omnisharp\`, when I run VS Code from Bash. I guess I need a debug build of OmniSharp.

**Comment by inosik** [comment] 2017-09-18 06:27
The message should be logged when [this call](https://github.com/OmniSharp/omnisharp-roslyn/blob/4f248b193047925613c9c877c5ce15fe5882dcfd/src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs#L281-L285) adds something to the `globalProperties` dictionary.

**Comment by inosik** [comment] 2017-09-18 09:51
I think I tracked it down. This is very similar to dotnet/cli#3995 and dotnet/corefx#13146.

When I'm in Bash, I have the `home` and `HOME` environment variables. I think this breaks the [interaction between OmniSharp and `dotnet --info`](https://github.com/OmniSharp/omnisharp-roslyn/blob/4f248b193047925613c9c877c5ce15fe5882dcfd/src/OmniSharp.Abstractions/Services/DotNetCliService.cs#L136), which then probably [returns some default infos](https://github.com/OmniSharp/omnisharp-roslyn/blob/4f248b193047925613c9c877c5ce15fe5882dcfd/src/OmniSharp.Abstractions/Services/DotNetCliService.cs#L140). When I do `unset home` before running VS Code, everything works as expected. You can reproduce it when you do `foo=1 FOO=1 code .` in Bash.

**Comment by DustinCampbell** [comment] 2017-09-18 16:26
Thanks for the lead! At the very least, I'll add some logging around this to see if we can make it clearer when this fails. It's a little tricky because it's not exactly an error case when the .NET Core SDK doesn't work. After all, we support .NET Framework, Unity and Xamarin projects. However, it should be easier to trace the issue.

**Comment by bandrei** [comment] 2018-07-10 08:01
Ok, it looks like I managed to solve it by running `dotnet restore` on the project whcih fixed the omnisharp server which is now starting. After this I deleted a .env file and re-started VSCode to update it, after which things started working.

**Comment by lucastheisen** [comment] 2018-10-13 18:04
Another data point...  I just upgraded dotnet using chocolatey (was 2.1.101 _or something_, now 2.1.403).  Then created a new project:
```
dotnet new console --name New.Project
dotnet new sln --name New.Project
dotnet sln add .\New.Project\New.Project.csproj
dotnet build
code .
```
Which results in this _OUTPUT_:
```
Starting OmniSharp server at 10/13/2018, 1:52:37 PM
    Target: c:\Users\lucas\git\new-project\New.Project.sln

OmniSharp server started.
    Path: C:\Users\lucas\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\OmniSharp.exe
    PID: 9056

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\lucas\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\lucas\git\new-project'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\lucas\git\new-project\New.Project.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\lucas\git\new-project\New.Project\New.Project.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\lucas\git\new-project'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\lucas\git\new-project' on host 16340.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\lucas\git\new-project\New.Project\New.Project.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\lucas\git\new-project\New.Project\New.Project.csproj'.
c:\Users\lucas\git\new-project\New.Project\New.Project.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  c:\Users\lucas\git\new-project\New.Project\New.Project.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath)
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader)

[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\Users\lucas\git\new-project\New.Project\New.Project.csproj
```

My `dotnet --info` output is:
```
PS C:\Users\lucas\git\new-project> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

My guess is that it has something to do with this:
```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\lucas\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin"
```
Which I would imagine might have `dotnet` mentioned (as in `dotnet msbuild`).  My `dotnet` install is at:
```
PS C:\Users\lucas\git\new-project> get-command dotnet

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     dotnet.exe                                         2.1.269... C:\Program Files\dotnet\dotnet.exe
```

**Comment by guftall** [comment] 2019-04-16 05:12
i installed .NET Core SDKs: 2.2.104 AND 3.0.100-preview-010184. (ubuntu 18)
and had same problem.
but after creating `global.json` in my project folder and defining `2.2.104` as my `sdk`, this problem solved.

**Comment by cartermp** [comment] 2020-03-26 21:31
Closing as a duplicate of #3541 which will track these issues

**Closed by cartermp** 2020-03-26 21:31 UTC
