### ISSUE TITLE
Omnisharp not working on .Net SDK 2.1.403 (Windows 7)

### ISSUE THREAD

**Issue by ikinetik** [OmniSharp/omnisharp-vscode#2995] opened 2019-04-17 03:12 UTC
Hello,

Omnisharp stopped working today whenever I create a new project. 

.Net Core SDK installed: 2.1.403
Host Version: 2.1.5
Windows OS Version: 6.1.7601
VS Code version: 1.33.1

Output Log:

Starting OmniSharp server at 4/16/2019, 7:33:36 PM
    Target: c:\Users\Admin\Documents\Coding Dojo\C# stack\Entity\WeddingPlanner

OmniSharp server started.
    Path: C:\Users\Admin\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.17\OmniSharp.exe
    PID: 7376

System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.HostHelpers.Start(Func`1 action)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

Thank you to all who can help!

**Comment by filipw** [comment] 2019-04-17 05:08
You need to install .NET 4.7.2.
Latest OmniSharp requires .NET 4.7.2, see https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#13214---2019-04-08

**Comment by filipw** [comment] 2019-04-30 17:57
I will close this because it is by design. We also already merged a change that will actually prompt you to install 4.7.2 instead of failing silently https://github.com/OmniSharp/omnisharp-roslyn/pull/1469

**Closed by filipw** 2019-04-30 17:57 UTC

**Comment by ikinetik** [comment] 2019-04-30 19:34
Thank you Filip for your help! I greatly appreciate it! 

⁣Get BlueMail for Android ​
