### ISSUE TITLE
How to view Source Generated files?

### ISSUE THREAD

**Issue by YairHalberstadt** [OmniSharp/omnisharp-vscode#4550] opened 2021-05-15 18:37 UTC
Sorry if this is the wrong place to ask.

Is it possible to view files generated by Roslyn Source Generators in VS code?

Also currently navigating to a source generated member doesn't work. It would be super cool if that could be made to work!

Thanks for your help!

**Comment by 333fred** [comment] 2022-08-12 05:55
Closing as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4215.

**Closed by 333fred** 2022-08-12 05:55 UTC
