### ISSUE TITLE
C# support not working after C# extension installed

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#114] opened 2016-03-21 08:25 UTC
_From @leocrespo on March 20, 2016 2:15_

- VSCode Version: 0.10.11
- OS Version: 10.11.3

Steps to Reproduce:

1. Download this file and open it with VS Code http://d.pr/f/1jczl
2. Check if there's intellisense.

If it doesn't have intellisense, it's not an editor. Might as well use textedit.

![Image of No Intellisense]
(http://d.pr/i/1he2V.gif)

_Copied from original issue: Microsoft/vscode#4467_

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @Tyriar on March 20, 2016 2:18_

Did you install the C# extension? https://code.visualstudio.com/Docs/languages/csharp#_installing-c35-support

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @leocrespo on March 20, 2016 2:23_

Yes it's installed

![Image of VSCode]
(http://d.pr/i/15tLS.png)

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @Tyriar on March 20, 2016 2:28_

@leocrespo and was vscode restarted after it was installed?

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @leocrespo on March 20, 2016 2:30_

Yes of course. Have you tried downloading the file and opening it, I'm sure there won't be any intellisense.

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @Tyriar on March 20, 2016 2:40_

Works fine for me. I'm on Windows 10 and had VS2015 installed before VSCode.

![image](https://cloud.githubusercontent.com/assets/2193314/13902545/8c9a1062-ee09-11e5-83a0-e56936a1c6f7.png)

I haven't actually used the C# support before, one of the other devs might be able to help you out beyond this point.

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @leocrespo on March 20, 2016 2:48_

I can do that too, that's not intellisense. 
![Image of candothattoo]
(http://d.pr/i/1k46V.png)

This is intellisense
![Image of thisisintellisense]
(http://d.pr/i/XTlX.gif)

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @Tyriar on March 20, 2016 3:6_

@leocrespo this might resolve your issue http://stackoverflow.com/a/29979730/1156119

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @leocrespo on March 20, 2016 3:14_

1. There isn't any option for me to create a project.json or a solution. (amazing)
2. There is no "Open folder" command 

![Image of selection]
(http://d.pr/i/aeyZ.gif)

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @leocrespo on March 20, 2016 3:24_

All I want is to have basic intellisense on the file I posted, just as I do when I open it with VS. So I created a solution in VS2015. 

![Image of aa]
(http://d.pr/i/14zVQ.png)

then opened everything with VSCode and still no intellisense. 
![Image of bb]
(http://d.pr/i/QX0t.gif)

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @Tyriar on March 20, 2016 7:33_

Visual Studio can generate sln files as you mention, VSCode cannot. VSCode typically relies on external tools or extensions for that kind of project scaffolding.

As for the `project.json`, it looks like this is created using the relatively new .NET Core and [`dotnet` CLI](http://dotnet.github.io/getting-started/) which uses a more folder-based approach to C# development which is more inline with what VSCode was designed to work with (as opposed to project/solution-based).

So once the .NET Core is installed, you should be able to run this to generate a project.json:

```
dotnet new
```

And then this to run your application:

```
dotnet restore # install deps
dotnet run
```

When coming back to VSCode I ran into this OmniSharp issue related to VSCode not being able to find the globally installed dnx runtime https://github.com/Microsoft/vscode/issues/126#issuecomment-160131771

---

Not sure why open folder is not there, it always has been for me (I don't use OSX though).

![image](https://cloud.githubusercontent.com/assets/2193314/13903312/6a670562-ee32-11e5-9244-e22b8301c335.png)

You can always run the command from the command palette:

1. Press <kbd>F1</kbd>
2. Type `open folder`
3. Press <kbd>enter</kbd>

![image](https://cloud.githubusercontent.com/assets/2193314/13903317/8e364188-ee32-11e5-8c6a-e4d929e5df56.png)

**Comment by jrieken** [comment] 2016-03-21 08:25
_From @pflannery on March 20, 2016 17:29_

@leocrespo just want to point out that the example you show here would never work as your trying to write the script in the c# class root scope.
In this scenario Visual studio also fails to show intellisense too

![animation](https://cloud.githubusercontent.com/assets/1727302/13905713/94439ea8-eebf-11e5-8228-9d51b603061d.gif)


Try this example project in vscode https://github.com/dotnet/core/tree/master/samples/helloworld

run `dotnet restore` in the root and you should get this:

![image](https://cloud.githubusercontent.com/assets/1727302/13905764/e5085166-eec0-11e5-87b0-8fa97477751b.png)

i'm running vscode 0.10.11

**Comment by jrieken** [comment] 2016-03-21 08:25
@leocrespo There is a Omnisharp log file (Cmd+L,L) Please paste its contents here.

**Comment by jrieken** [comment] 2016-03-21 10:48
invalid C# code as outlined here: https://github.com/OmniSharp/omnisharp-vscode/issues/114#issuecomment-199169555

**Comment by leocrespo** [comment] 2016-03-21 11:23
It's 2 steps to reproduce there error: 
Download this file and open it with VS Code http://d.pr/f/1jczl
Check if there's intellisense.

If you guys don't get it, never mind, I'm not with patience to explain. Good luck with your "editor".

**Comment by leocrespo** [comment] 2016-03-21 11:29
VSCode, no intellisense
![Image of aaa](http://d.pr/i/FgnW.gif)

VS 2015, same file, here's the intellisense. 
![Image of aaa](http://d.pr/i/1emfN.gif)

**Comment by jrieken** [comment] 2016-03-21 11:52
@leocrespo https://github.com/OmniSharp/omnisharp-vscode/issues/114#issuecomment-199169557

**Comment by Tyriar** [comment] 2016-03-22 08:08
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/47

**Comment by colinramsay** [comment] 2016-03-22 13:10
I have this issue on OSX. My log file shows:

```
[INFO] Starting OmniSharp at '/private/tmp/ConsoleApplication'...
[INFO] Started OmniSharp from '/Users/colinramsay/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 33980...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/private/tmp/ConsoleApplication' on host 33971.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/colinramsay/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update1'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/private/tmp/ConsoleApplication' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/private/tmp/ConsoleApplication/project.json'.
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Using '/Users/colinramsay/.dnx/runtimes/dnx-mono.1.0.0-rc1-update1' for design time host.
[ERROR:OmniSharp.Startup] The project system 'DnxProjectSystem' threw an exception.
System.InvalidOperationException: File name has not been set
   at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) in <filename unknown>:line 0
   at System.Diagnostics.Process.Start () in <filename unknown>:line 0
   at (wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
   at OmniSharp.Dnx.DesignTimeHostManager.Start (System.String hostId, System.Action`1 onConnected) in <filename unknown>:line 0
   at OmniSharp.Dnx.DnxProjectSystem.Initalize (IConfiguration configuration) in <filename unknown>:line 0
   at OmniSharp.Startup.Configure (IApplicationBuilder app, IServiceProvider serviceProvider, ILibraryManager manager, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOptions`1 optionsAccessor) in <filename unknown>:line 0
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/private/tmp/ConsoleApplication'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/private/tmp/ConsoleApplication'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
```

After finding [this issue](https://github.com/OmniSharp/omnisharp-roslyn/issues/345), the problem was solved this by installing the mono runtime with `dnvm`: 

`dnvm upgrade -r mono`

**Comment by DustinCampbell** [comment] 2016-04-05 19:50
This is a duplicate of #47, which was filed by the same customer.

**Closed by DustinCampbell** 2016-04-05 19:50 UTC
Labels: Resolved-Duplicate
