### ISSUE TITLE
The CLI tools preview4 with csproj results in Type-Mismatch Warnings

### ISSUE THREAD

**Issue by stefc** [OmniSharp/omnisharp-vscode#979] opened 2016-11-22 13:58 UTC
## Environment data
Product Information:
 Version:            1.0.0-preview4-004110
 Commit SHA-1 hash:  740a7fe3fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004110

VS Code version: 1.7.1

C# Extension version: 1.5.4

## Steps to reproduce
create a new project with 'dotnet new' with new project format (aka csproj)

The Console.WriteLine() statement would be marked with a warning.

The hint contains the following : 
`Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Console' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [sample]
`
## Expected  behavior

No warning on this type mismatch 4.0.0.0 vs 4.1.0.0 

## Actual behavior

The warning

**Comment by DustinCampbell** [comment] 2016-11-22 14:55
Thanks for reporting this! It's a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/967.

**Closed** 2016-11-22 14:55 UTC
Labels: Resolved-Duplicate
