### ISSUE TITLE
Blazor WebAssembly warning no longer needed

### ISSUE THREAD

**Issue by ar0311** [OmniSharp/omnisharp-vscode#3932] opened 2020-07-27 01:10 UTC
When opening a Blazor WebAssembly project in VS Code, the warning for additional setup still appears even though the nightly JavaScript debugger extension no longer needs to be installed as of latest VS Code version (1.47.2)

Tested with C# extension v1.22.2

https://github.com/aspnet/Announcements/issues/430

**Comment by gregg-miskelly** [comment] 2020-07-27 17:07
CC @captainsafia

**Comment by captainsafia** [comment] 2020-07-29 15:40
We might be able to pull two weeds with one yank here and resolve this when we close https://github.com/dotnet/aspnetcore/issues/23832.

I'll close this issue in favor of that one since we track the other issue as part of our sprint planning.

Thanks for opening this issue, @ar0311!

**Comment by captainsafia** [comment] 2020-07-29 15:41
Welp -- I'm not in to the dotnet org so someone else will have to close this.

@JoeRobich Can you help out with this?

**Comment by JoeRobich** [comment] 2020-07-29 16:31
This issue is a duplicate of https://github.com/dotnet/aspnetcore/issues/23832. Progress can be tracked on that issue.

**Closed by JoeRobich** 2020-07-29 16:31 UTC
Labels: Razor, Resolved-External
