### ISSUE TITLE
[C#] "this" will autocomplete as "ThreadStaticAttribute" when writing ternary expressions before ending semi-colon has been added

### ISSUE THREAD

**Issue by divillysausages** [OmniSharp/omnisharp-vscode#3096] opened 2019-06-04 20:58 UTC
## Issue Description ##

Issue Type: <b>Bug</b>

It happens mostly when writing ternary expressions (e.g. `(condition) ? doThis() : orThat()`) or when using `()` brackets in an assignment, _but before the ending semi-colon has been added._

When it happens, auto-complete doesn't seem to recognise that `this` exists, but will only show something like `ThreadStaticAttribute` (if there's a `using System;` directive at the top of the file) or `ThreadPriority`;

This is a default Unity project using VSCode, but it might be possible to reproduce in a pure C# environment.

## Steps to Reproduce ##

- Create a MonoBehaviour such as:

```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MyBehaviour : MonoBehaviour {
	// Use this for initialization
	void Start () {
	}
}
```

- Inside the `Start()` method, start to write a ternary expression using `this` in the condition:

```
int foo = (this) // proposes "ThreadStaticAttribute"
```

- Instead of auto-completing the `this`, VSCode will only propose `ThreadStaticAttribute`. It will also automatically replace `this` with `ThreadStaticAttribute` if you hit Space or Tab, so you need to explicitly hit Esc before moving on
- Writing the ternary with the `;` already added (not the default behaviour) will properly offer `this` as an option:

```
int foo = (this); // autocompletes
```

- Writing without the brackets will also properly offer `this` as an option:

```
int foo = this // autocompletes
```

## Expected Behavior ##

`this` should autocomplete as normal

## Actual Behavior ##

`this` isn't present in the auto-complete dialog meaning that when you press Tab, [dot], etc, it replaces it with another word

## Environment information ##

**VSCode version**: 1.34.0
**C# Extension**: 1.19.1

<details><summary>Dotnet Information</summary>
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.4|
|csharp|ms-vscode|1.19.1|
|java|redhat|0.45.0|
|LiveServer|ritwickdey|5.6.1|
|RelativePath|jakob101|1.4.0|
|searchdocsets-vscode|silverlakesoftware|1.0.1|
|unity-debug|Unity|2.7.2|
|vscode-cosmosdb|ms-azuretools|0.10.2|
|vscode-css-formatter|aeschli|1.0.1|
|vscode-java-debug|vscjava|0.19.0|
|vscode-java-dependency|vscjava|0.4.0|
|vscode-java-pack|vscjava|0.7.1|
|vscode-java-test|vscjava|0.17.0|
|vscode-maven|vscjava|0.17.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.6|;

</details>

**Comment by rchande** [comment] 2019-06-05 16:51
@divillysausages I'm having trouble reproducing this. Can you share the exact text where this happens for you?
![image](https://user-images.githubusercontent.com/3751401/58974512-695be980-8777-11e9-8982-596e8ce46e55.png)

**Comment by divillysausages** [comment] 2019-06-05 22:39
Hi @rchande,

Thanks for taking the time to look at this. On my end, in trying to get a screenshot of the issue, it doesn't seem to happen with every class and I haven't yet been able to nail down the reason why.

This is what it looks like when it happens:

![image](https://i.imgur.com/9IWZdqh.png)

(https://imgur.com/a/4oUXw81 if it doesn't link). This is inside a Unity project; I'm not sure if that makes a difference.

Is there something that I can send you (project?), or something that I can run that would give you the necessary logs or whatever to help track it down?

**Comment by rchande** [comment] 2019-06-05 23:05
@divillysausages That screenshot is perfect, looks like this happens if there's a variable declaration after the one you're creating, eg:
```csharp
            int z = (t)
            object o = new object();
```

I can reproduce this in VS 2019, so this is actually a bug in Roslyn, the project that implements C# intellisense for Visual Studio and that provides the library omnisharp uses in order to do completion. I've gone ahead and filed https://github.com/dotnet/roslyn/issues/36194 for you and I'm going to close this issue.

**Closed by rchande** 2019-06-05 23:05 UTC

**Comment by divillysausages** [comment] 2019-06-06 07:43
Excellent, thank you! I was worried that I was going to have to move the bug again; it was originally posted in the VSC GitHub :D
