### ISSUE TITLE
typing a period in a triple-slash comment brings up the auto-complete UI

### ISSUE THREAD

**Issue by chronicgamedev** [OmniSharp/omnisharp-vscode#2200] opened 2018-04-17 20:30 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

VS Code version:
Version 1.23.0-insider
Commit dfeffb55b62cc2c1dde5cc1e25e98632eeb7744b
Date 2018-04-16T05:17:45.591Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

C# Extension version:
1.14.0

## Steps to reproduce
1.  open a C# file
2.  enter a single line comment beginning with three slashes ///
3.  end the comment with a period

## Expected  behavior
typing a period and a space in a comment adds a period and a space

## Actual behavior
typing the period opens the auto-complete UI, and pressing space will insert the first suggestion

![vs-code-xml-comment-auto-complete-bug](https://user-images.githubusercontent.com/22398672/38894893-678d7436-4243-11e8-9986-48f77cbefdf5.png)

**Comment by DustinCampbell** [comment] 2018-04-17 21:16
This for the report! This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1424.

**Closed by DustinCampbell** 2018-04-17 21:16 UTC
Labels: Resolved-Duplicate
