### ISSUE TITLE
Quick Fix (Ctrl + . ) Issue - Doesn't show required namespaces

### ISSUE THREAD

**Issue by sushantjadhav** [OmniSharp/omnisharp-vscode#1764] opened 2017-09-21 12:12 UTC
## Environment data
```
.NET Command Line Tools (2.0.0)

Product Information:
Version:            2.0.0
Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

Base Path:   C:\Program Files\dotnet\sdk\2.0.0\
Microsoft .NET Core Shared Framework Host
Version  : 2.0.0
Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.9.1
C# Extension version: 1.7.0

## Steps to reproduce
Install NET Core SDK 2.0
Create angular project using dotnet core cli ( dotnet new angular )
Open project in Visual Studio Code 1.9.1
Install C# and C# extensions
Start Omni sharp if not already started

C# Intelligence works in Visual Studio Code.
Quck Fix (Ctrl + .) doesn't work, It doesn't show required namespaces after hitting (Ctrl + .) 

## Expected  behavior
Quck Fix (Ctrl + .) should show required/missing namespaces after hitting (Ctrl + .) 
For ex.

```C#
public ICollection<Project> Projects { get; set; }
```

When cursor is on ICollection keyword, if you will press Ctrl + .  
Quick Fix should show "using System.Collections"

## Actual behavior
   After hitting (Ctrl + .),  Quck Fix doesn't show required namespace suggestion.
   Build is successful. 
   OmniSharp is also running fine. 
   C# Intelligence is working fine. 
   No error in problem pane

## Note
I am behind the proxy.

## OmniSharp Output
```
Starting OmniSharp server at 9/21/2017, 1:32:56 PM
    Target: d:\Development_Avecto\OneR\OneR.sln

OmniSharp server started
    Path: C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\OmniSharp.exe
    PID: 7428

OmniSharp: -s d:\Development_Avecto\OneR\OneR.sln --hostPID 7228 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'd:\Development_Avecto\OneR' on host 7228.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\Development_Avecto\OneR
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild\MSBuild.exe
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild\Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'd:\Development_Avecto\OneR\OneR.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'd:\Development_Avecto\OneR\OneR.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: d:\Development_Avecto\OneR\OneR.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: OneR
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Development_Avecto\OneR'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.
```

**Comment by sushantjadhav** [comment] 2017-09-21 12:55
---------------------------------------------------------------------------------------- 
dotnet --info  output
----------------------------------------------------------------------------------------
.NET Command Line Tools (2.0.0)

Product Information:
Version:            2.0.0
Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
Base Path:   C:\Program Files\dotnet\sdk\2.0.0\
Microsoft .NET Core Shared Framework Host
Version  : 2.0.0
Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version: 1.9.1
C# Extension version: 1.7.0

----------------------------------------------------------------------------------------
Issue: Quick Fix (Ctr + . ) Not Working, doesn't show Required Namespaces
----------------------------------------------------------------------------------------
I have created .Net Core 2.0 Project using dotnet cli
Omni sharp is working fine ( can see Fire Log and Running at taskbar right hand side)
                   Spaces: 4        UTF-8       LF      C#           (OmniSharp Logo) Running 
Intelligence is also working fine.

But Quick Fix (Ctr + .) is not working.
For ex.
         public ICollection<Project> Projects { get; set; }
         When cursor is on ICollection keyword, if you press Ctr + . , 
         Quick Fix doesn't show required namespace  

Build is passed, it doesn't show any problem in Problems section
Please help.

----------------------------------------------------------------------------------------
Omnisharp Log
----------------------------------------------------------------------------------------
Starting OmniSharp server at 9/21/2017, 1:32:56 PM
    Target: d:\Development_Avecto\OneR\OneR.sln

OmniSharp server started
    Path: C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\OmniSharp.exe
    PID: 7428

OmniSharp: -s d:\Development_Avecto\OneR\OneR.sln --hostPID 7228 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'd:\Development_Avecto\OneR' on host 7228.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\Development_Avecto\OneR
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild\MSBuild.exe
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to C:\Users\379212\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild\Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'd:\Development_Avecto\OneR\OneR.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'd:\Development_Avecto\OneR\OneR.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: d:\Development_Avecto\OneR\OneR.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: OneR
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Development_Avecto\OneR'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by DustinCampbell** [comment] 2017-09-21 15:54
@sushantjadhav: Have you tried updating C# for VS Code to 1.12.1? 1.7.0 is very old.

**Comment by sushantjadhav** [comment] 2017-09-22 06:39
Upgraded VS Code From 1.9.1 To 1.16.1
 public ICollection<Project> Projects { get; set; }     	

Now Quick Fix (Ctrl + . ) shows suggestions when cursor is on "ICollection"
But In subjection 
 it shows "System.Collections.Generic.ICollection"
 But still "using System.Collections.Generic" is missing

Could you please tell me how Quick Fix (Ctrl + .) will show me messing namespaces
So that I can add it?

**Comment by bernardbr** [comment] 2017-09-22 15:25
Hello @sushantjadhav. I've missed something...

For example, you have this class:
```csharp
namespace MyNamespace
{
    public class MyClass
    {
        public ICollection<int> Get()
        {
        }
    }
}
```

And when you press ```(Ctrl + .)```. Does the VsCode do this?

```csharp
using System.Collections.Generic;

namespace MyNamespace
{
    public class MyClass
    {
        public ICollection<int> Get()
        {
        }
    }
}
```

If it's happening, it's the correct form.

See what appears in my case:

![My case](https://user-images.githubusercontent.com/4705034/30751789-ba23e500-9f90-11e7-9f1d-ec7354f8d423.png)

What options are shown to you?

**Comment by sushantjadhav** [comment] 2017-09-26 12:35
Still using statement is missing

![image](https://user-images.githubusercontent.com/20818488/30860541-1417485c-a2e5-11e7-8f28-2c777cc091fa.png)

Build is successfull, but it show red lines. Why VS shows these red lines and how shall I remove these red lines (Application is .NET Core 2.0 Angular)
![image](https://user-images.githubusercontent.com/20818488/30860597-4c393826-a2e5-11e7-9e65-47384da0671c.png)

**Comment by sushantjadhav** [comment] 2017-09-27 04:46
As I am behind corporate security, its not possible to share the screen. 
But I can give you whatever information required to trouble shoot the issue. 
##Please let me know if you need anything specif.

##Below software's are install on my system
1. Visual Studio code 1.16.1 
2. Visual Studio 2017
3. .NET Core 2.0 SDK
4. Node v8.5.0, NPM 4.0.0

##Below Extensions are install in VS 1.16.1
1. C#: 1.7.0
2. C# Extensions: 1.3.0

##I have created project using below command
dotnet new angular

##Environment data
.NET Command Line Tools (2.0.0)

Product Information:
Version:            2.0.0
Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

Base Path:   C:\Program Files\dotnet\sdk\2.0.0\
Microsoft .NET Core Shared Framework Host
Version  : 2.0.0
Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by rchande** [comment] 2017-10-05 17:51
@sushantjadhav I tried the steps you mentioned above (`dotnet new angular`). "Add using" works and I don't see any errors in the editor. Can you share more info about your project and how you added the files you see errors in?

**Comment by piotrpMSFT** [comment] 2017-10-13 04:52
@sushantjadhav I noticed you updated VS Code itself, but the C# extension is still at version 1.7.0, per your last response. Can you open VS Code, have it check for extension updates, then update the C# extension to the latest version?

**Comment by DustinCampbell** [comment] 2017-10-30 15:55
FWIW, the fact that there is an error stating that "Predefined type 'System.Void' is not defined or imported" leads me to believe that something about your project is not loading properly, which is why the "Add Using" code fix is not available. A couple of questions:

* Are you able to reproduce this with a new project?
* Could you try the [latest beta release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.13.0-beta4) of C# for VS Code? You can follow the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install a beta release.

**Comment by luecano** [comment] 2017-12-29 21:00
Same problem here.

![image](https://user-images.githubusercontent.com/5108807/34447369-31e50b2e-ecb1-11e7-9987-5d33d6eb99ba.png)

![image](https://user-images.githubusercontent.com/5108807/34447358-044ceeb6-ecb1-11e7-8ce1-2c2e9e577ae9.png)

![image](https://user-images.githubusercontent.com/5108807/34447041-38052cd0-ecae-11e7-964c-3718c4830d0c.png)

ms-vscode.csharp 1.13.1
Net Core SDK 2.1.3
VSCode-win32-x64-1.19.1

**Comment by MaximumViciousDeer** [comment] 2019-01-16 14:37
I'm having a similar problem as OP.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.503/

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  2.1.503 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
VS Code version: 
```
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.14.74-1.pvops.qubes.x86_64
```
C# Extension version:
Tested 1.17.1 and 1.18.0-beta4

## Steps to reproduce

- Install NET Core SDK 2.1
- Create new console project: dotnet new console
- Open folder and program.cs file in VS Code
- Make sure extensions are installed and omni sharp is running
- C# IntelliSense works properly for methods on objects
- Add new line `IEnumerable test = null;`
- Problem is shown: "The type or namespace name 'IEnumerable' could not be found (are you missing a using directive or an assembly reference?)"
- Press Ctrl + . beside IEnumerable (with the red line) shows: `No suggestions.`

## Expected  behavior

I was expecting to be shown a list of ways to solve the missing reference (adding namespace, create new interface etc.).

## Actual behavior

I have to manually add `using System.Collections;` to fix the problem.

**Comment by MaximumViciousDeer** [comment] 2019-01-18 08:50
Update:
I have now also tested this on Fedora 28 with .Net Core SDK 2.2.103.
Same problem persists, i.e. no suggestions for adding namespaces for missing types.

**Comment by cartermp** [comment] 2020-03-11 00:00
This is resolved for me with @MaximumViciousDeer's repro:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/6309070/76369308-5a026180-62f0-11ea-9b98-4b718be100c0.png">

As with @sushantjadhav 's repro:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/6309070/76369370-8ae29680-62f0-11ea-8d5b-48b2b296345c.png">

Since a lot of time has passed, and there have been numerous fixes to this extension, .NET, and Roslyn and the issue isn't reproducible, I'll close this out. Happy to open it back up if it reproduces for folks with updated tooling and environment.

**Closed by cartermp** 2020-03-11 00:00 UTC
Labels: Editor-Code Actions, Resolved-Not Reproducible

**Comment by TanvirArjel** [comment] 2022-11-07 16:32
@cartermp The issue is still persisting in VSCode 1.73.0!

**Comment by mohaaron** [comment] 2023-04-03 00:03
Yeah, same here using VSCode 1.77
