### ISSUE TITLE
Error namespace could not be found when using namespace of referenced project

### ISSUE THREAD

**Issue by hong-duc** [OmniSharp/omnisharp-vscode#1423] opened 2017-04-24 08:32 UTC
## Environment data
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /opt/dotnet/sdk/1.0.1
VS Code version: 1.11.2
C# Extension version: 1.9.0

## Steps to reproduce
Just refence another project and add using namespace of that project

## Expected  behavior
Not show error

## Actual behavior
show error namespace could not be found

**Comment by DustinCampbell** [comment] 2017-04-24 12:16
Hi! Could you provide a bit more detail?

1. What steps are you going through to reference another project? E.g. Are you typing in the csproj file, or did you use the 'dotnet add project' command from the CLI?

**Comment by DustinCampbell** [comment] 2017-04-24 12:18
2. Could you provide your OmniSharp log after adding a project? To get this, select View->Output from the VS Code menu and choose "OmniSharp Log" from the combo box at the top-right of the Output pane.

**Comment by sunmorgus** [comment] 2017-04-24 15:37
I'm having the same issue. To answer some of your questions...

1. Added the reference using the `dotnet add project` command.
1. This worked just fine in 1.8.1, the project was added as a reference while using that version.
1. Log shows "unable to resolve project reference"

Things I tried/notes:

1. I tried removing the references and adding them back, didn't help
1. Tried switching from relative paths to full paths, didn't help

Relevant csproj section:

```
  <ItemGroup>
    <ProjectReference Include="..\BAH.Admin\BAH.Admin.csproj"/>
    <ProjectReference Include="..\BAH.Admin.Client\BAH.Admin.Client.csproj"/>
  </ItemGroup>
```

OmniSharp output:

```
Starting OmniSharp server at 4/24/2017, 10:21:53 AM
    Target: /Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Test

OmniSharp server started wth Mono
    Path: /Users/nicklasdemayo/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/run
    PID: 98655

OmniSharp: -s /Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Test --hostPID 98612 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Test' on host 98612."},"Seq":1,"Type":"event"}
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Test
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to /Users/nicklasdemayo/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/omnisharp/msbuild/MSBuild.dll
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to /Users/nicklasdemayo/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/omnisharp/msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to /Users/nicklasdemayo/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/omnisharp/msbuild/Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild will use local OmniSharp installation.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in '/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Test'
Discovered Mono file path: /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono
Resolved symbolic link for Mono file path: /Library/Frameworks/Mono.framework/Versions/4.8.0/bin/mono-sgen32
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: /Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Test/BAH.Admin.Test.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: BAH.Admin.Test
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve project reference '/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Client/BAH.Admin.Client.csproj' for 'BAH.Admin.Test'.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve project reference '/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin/BAH.Admin.csproj' for 'BAH.Admin.Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/nicklasdemayo/aaa/projects-git/<project folder>/BAH.Admin.Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.
```

**Comment by DustinCampbell** [comment] 2017-04-24 15:41
Obvious question: Do the paths exist? :smile:

**Comment by sunmorgus** [comment] 2017-04-24 15:42
@DustinCampbell lol, they do, yes 😄

**Comment by DustinCampbell** [comment] 2017-04-24 15:49
I figured. Trying to repro now.

**Comment by sunmorgus** [comment] 2017-04-24 15:53
FYI, switching OmniSharp's log level to debug didn't appear to provide any more information.

**Comment by DustinCampbell** [comment] 2017-04-24 15:54
Yeah, I can repro.

**Comment by DustinCampbell** [comment] 2017-04-24 16:48
Actually, I *can't* repro. I had typed the file path incorrectly.

**Comment by DustinCampbell** [comment] 2017-04-24 16:49
I see what's happening for you.

**Comment by DustinCampbell** [comment] 2017-04-24 16:51
I wouldn't have expected this to have worked before. You've open VS Code on `/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin/BAH.Admin.Test` and you're trying to add references to projects outside of the folder opened in VS Code. Looking at the code in OmniSharp, this shouldn't have ever worked. Try opening on `/Users/nicklasdemayo/aaa/projects-git/Service-BAHAdmin`

**Comment by DustinCampbell** [comment] 2017-04-24 17:06
If you verify that this works, I think this is probably a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/963.

**Comment by sunmorgus** [comment] 2017-04-24 17:07
Yes, that resolved the issue. Thanks!

**Comment by DustinCampbell** [comment] 2017-04-24 17:09
Great! I'm going to resolve this as a duplicate, but I'm moved #963 into the 1.10 milestone. It's been too long for this not to work. :smile:

**Closed by DustinCampbell** 2017-04-24 17:09 UTC
Labels: Bug, Resolved-Duplicate
