### ISSUE TITLE
Is official support for arch comming anytime soon?

### ISSUE THREAD

**Issue by spluf** [OmniSharp/omnisharp-vscode#1391] opened 2017-04-14 08:47 UTC
At this point I can run .net core projects in VSCode but I can not debug them due to this exception:

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /opt/dotnet/sdk/1.0.1
```

VS Code version:
`1.11.2-1`
C# Extension version:
`1.8.1`
## Steps to reproduce
Open / create a .Net Core web api (or any other .Net Core project), create launch.json and task.json and start debugging.

## Expected  behavior
Start the project in debug mode.

## Actual behavior
`Failed to initialize CoreCLR, HRESULT: 0x80131500`

**Comment by gregg-miskelly** [comment] 2017-04-14 14:51
@spluf This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1323.

To answer your question about 'official' support - for .NET Core 2.0, the CoreCLR team is releasing a version of CoreCLR that they expect to be compatible with most distributions. So once that has a 'go live' preview we hope to switch to that.

**Closed by gregg-miskelly** 2017-04-14 14:51 UTC
