### ISSUE TITLE
Error "Process is terminating due to StackOverflowException." occurs every time when a C# program ends. 

### ISSUE THREAD

**Issue by TobiichiAmane** [OmniSharp/omnisharp-vscode#2587] opened 2018-10-06 16:08 UTC
## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.5 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.27.2

C# Extension version: 1.17.0-beta5

## Steps to reproduce
Create a new C# console application using `dotnet new console`;
Try to debug the default HelloWorld program;

## Expected  behavior
Program exits with no error. 

## Actual behavior
Error "Process is terminating due to StackOverflowException." occurs.
![image](https://user-images.githubusercontent.com/14824064/46573242-05550b80-c9c5-11e8-87d4-bb4793b0efd7.png)

**Comment by gregg-miskelly** [comment] 2018-10-06 21:47
@TobiichiAmane If you run the program without debugging, do you get the same problem?

This sounds like an incompatibility between arch and .NET Core.

**Comment by TobiichiAmane** [comment] 2018-10-07 02:47
@gregg-miskelly No. I won't get the same problem when running it directly. 
![image](https://user-images.githubusercontent.com/14824064/46577663-6826c100-ca1e-11e8-954d-9b9b59a9642f.png)

**Comment by TobiichiAmane** [comment] 2018-10-07 03:03
This problem occurs no matter if I try to debug it in the integrated terminal or an external terminal. The same problem occurs when using Gnome-terminal instead of Konsole. The same problem occurs when using Gtk based DE (I tried Gnome and Cinnamon) instead of KDE.

**Comment by coinnail** [comment] 2018-10-22 21:32
Seem to be a duplicate of #2439

**Comment by gregg-miskelly** [comment] 2018-10-23 00:40
I hope to put out a new beta tomorrow that has a fix for 2439. So we should hopefully know if this is indeed a duplicate or not soon...

**Comment by gregg-miskelly** [comment] 2018-10-23 18:40
[1.17.0-beta6](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta6) is now on the release page. Please follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install.

**Comment by TobiichiAmane** [comment] 2018-10-24 04:45
1.17.0-beta6 solved this issue. Nice work! 
And it confirmed that this issue is a duplicate of #2439 .

**Closed** 2018-10-24 04:45 UTC
Labels: Debugger

**Comment by Aides359** [comment] 2018-10-24 07:34
@gregg-miskelly i wanted to try the new version but vscode just repeatedly wanted me to reload which is why I updated vscode.
Now when installing the 1.17.0-beta6 it says that the extension is not compatible with code 1.27.2.

Which version do I need to correctly install the beta?

**Comment by TobiichiAmane** [comment] 2018-10-24 07:36
@Aides359 My code version is 1.28.2, and OmniSharp 1.17.0-beta6 works perfectly.

**Comment by gregg-miskelly** [comment] 2018-10-24 14:46
The extension currently requires 1.28 (see [this line](https://github.com/OmniSharp/omnisharp-vscode/blob/9acb7494ed847b3cbd244b265a6923e0eb7b8ba5/package.json#L325)). I believe that is the version of VS Code that came out in early October on the stable channel.
