### ISSUE TITLE
'Go to Definition' Reports 'No Definition Found' for External Assemblies

### ISSUE THREAD

**Issue by DrakeLambert** [OmniSharp/omnisharp-vscode#3326] opened 2019-10-08 01:15 UTC
## Issue Description ##
'Go to Definition' Reports 'No Definition Found' for External Assemblies
## Steps to Reproduce ##
1. Declare `string` typed variable in any code block.
  > Note, `string` type can be replaced with any type defined in an external assembly.
2. Right click on type declaration.
3. Select 'Go to Definition'

## Expected Behavior ##

New tab of assembly metadata is opened.

## Actual Behavior ##

The following message appears: 'No definition found for ...'

## Notes ##

I have tested this on the previous version of the C# extension, 1.21.3, and it does not have this issue.

I have also replicated the results on projects targeting `netcoreapp2.2` and `netcoreapp3.0`.

### OmniSharp log ###
```
Starting OmniSharp server at 10/7/2019, 8:08:20 PM
    Target: c:\Working\Tests\OmniSharpDefinitionTest

OmniSharp server started.
    Path: C:\Users\dlambert\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\OmniSharp.exe
    PID: 18364

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.3.29318.209 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            2: StandAlone 16.0 - "C:\Users\dlambert\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.3.29318.209 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Working\Tests\OmniSharpDefinitionTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Working\Tests\OmniSharpDefinitionTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Working\Tests\OmniSharpDefinitionTest\OmniSharpDefinitionTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Working\Tests\OmniSharpDefinitionTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Working\Tests\OmniSharpDefinitionTest\OmniSharpDefinitionTest.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Working\Tests\OmniSharpDefinitionTest' on host 17172.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Working\Tests\OmniSharpDefinitionTest\OmniSharpDefinitionTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Working\Tests\OmniSharpDefinitionTest\OmniSharpDefinitionTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: OmniSharpDefinitionTest
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 3.
```

### C# log ###

No C# log output

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.4

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.4|
|Bookmarks|alefragnani|10.5.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.7.18|
|csharp|ms-vscode|1.21.4|
|docomment|k--kato|0.1.8|
|gitlens|eamodio|10.1.0|
|markdown-pdf|yzane|1.3.1|
|material-icon-theme|PKief|3.9.1|
|Material-theme|zhuangtongfa|2.28.2|
|mssql|ms-mssql|1.6.0|
|plantuml|jebbs|2.12.1|
|powershell|ms-vscode|2019.9.0|
|uridecode|sryze|0.3.5|
|vscode-azurefunctions|ms-azuretools|0.18.1|
|vscode-html-css|ecmel|0.2.3|
|vscode-markdownlint|DavidAnson|0.30.2|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by DrakeLambert** [comment] 2019-10-08 01:45
After more digging, I think this issue comes from the update to omnisharp-roslyn 1.34.4 and specifically the pull request: https://github.com/OmniSharp/omnisharp-roslyn/pull/1582

**Comment by filipw** [comment] 2019-10-08 04:54
Thanks. this is a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1624

It is already fixed here https://github.com/OmniSharp/omnisharp-roslyn/pull/1625

there is a pre-release OmniSharp that can be used as workaround.

"omnisharp.path": "1.34.5-beta.28"

**Closed by filipw** 2019-10-08 04:54 UTC
