### ISSUE TITLE
OmniSharp won't start after upgrading to VS Code 1.66

### ISSUE THREAD

**Issue by jettoblack** [OmniSharp/omnisharp-vscode#5145] opened 2022-04-02 16:52 UTC
## Issue Description ##
OmniSharp won't start after upgrading to VS Code 1.66

## Steps to Reproduce ##
Open the project folder ( c:\Users\Jason Livingston\Dropbox\FixMyCrypto ) in VS Code 1.66
OmniSharp: Select Project -> select FixMyCrypto.csproj

Tried opening other C# directories or project files, same results.

Tried uninstalling & reinstalling OmniSharp to no effect.

Attempting to use OmniSharp: Select Project, or OmniSharp: Restart OmniSharp, gives the log:

[ERROR] Attempt to restart OmniSharp server failed because another server instance is starting.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

### OmniSharp log ###
Starting OmniSharp server at 4/2/2022, 12:40:57 PM
    Target: c:\Users\Jason Livingston\Dropbox\FixMyCrypto

OmniSharp server started with .NET 6.0.101
.
    Path: c:\Users\Jason Livingston\.vscode\extensions\ms-dotnettools.csharp-1.24.3-win32-x64\.omnisharp\1.38.2-net6.0\OmniSharp.dll
    PID: 16512

System.ArgumentException: OmniSharp only supports being launched with a directory path or a path to a solution (.sln, .slnf) file. (Parameter 'path')
   at OmniSharp.Services.OmniSharpEnvironment..ctor(String path, Int32 hostPid, LogLevel logLevel, String[] additionalArguments) in D:\a\1\s\src\OmniSharp.Host\Services\OmniSharpEnvironment.cs:line 38
   at OmniSharp.CommandLineApplicationExtensions.CreateEnvironment(CommandLineApplication application) in D:\a\1\s\src\OmniSharp.Host\CommandLineApplicationExtensions.cs:line 12
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 49
   at OmniSharp.CommandLineApplication.<>c__DisplayClass12_0.<OnExecute>b__0() in D:\a\1\s\src\OmniSharp.Host\CommandLineApplication.cs:line 92
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OmniSharp.CommandLineApplication.Execute(String[] args) in D:\a\1\s\src\OmniSharp.Host\CommandLineApplication.cs:line 65
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_0.<Main>b__0() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 84
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 30

### C# log ###
(blank)

## Environment information ##

**VSCode version**: 1.66.0
**C# Extension**: 1.24.3

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|back-n-forth|nick-rudenko|3.1.1|
|csharp|ms-dotnettools|1.24.3|
|githistory|donjayamanne|0.6.19|
|gitlens|eamodio|12.0.5|
|vscode-graphviz|joaompinto|0.0.6|
|vscode-opencl|galarius|0.7.3|;

</details>

**Comment by filipw** [comment] 2022-04-04 07:39
I will close this as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5150.
The problem is a space in your path, as a workaround, you can move your code to a folder without spaces.

**Closed by filipw** 2022-04-04 07:39 UTC
