### ISSUE TITLE
ms-vscode.csharp (not found in marketplace)

### ISSUE THREAD

**Issue by Version2beta** [OmniSharp/omnisharp-vscode#3631] opened 2020-03-06 16:39 UTC
## Issue Description ##

"The below 1 extension(s) in workspace recommendations have issues: ms-vscode.csharp (not found in marketplace)"

The extension isn't available, as I understand it, because it's now called `ms-dotnettools.csharp`.

## Steps to Reproduce ##

Open a `.csproj` file

## Expected Behavior ##

The system shouldn't complain about an installed and updated extension.

## Actual Behavior ##

The system complains.
### OmniSharp log ###

Starting OmniSharp server at 3/6/2020, 9:35:18 AM
    Target: /Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc/FanfoldTrimCalc.sln

OmniSharp server started with Mono 6.6.0.
    Path: /Users/rob.martin/.vscode/extensions/ms-dotnettools.csharp-1.21.13/.omnisharp/1.34.13/omnisharp/OmniSharp.exe
    PID: 28171

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.3 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.4 - "/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.4 - "/Users/rob.martin/.vscode/extensions/ms-dotnettools.csharp-1.21.13/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.4 - "/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /Users/rob.martin/.vscode/extensions/ms-dotnettools.csharp-1.21.13/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc/FanfoldTrimCalc.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc/FanfoldTrimCalc.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc/FanfoldTrimCalc.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc' on host 27987.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc/FanfoldTrimCalc.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimCalc/FanfoldTrimCalc/FanfoldTrimCalc.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/rob.martin/Projects/businessintelligence/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/rob.martin/Projects/businessintelligence/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator/FanfoldTrimReportGenerator.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FanfoldTrimCalc
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FanfoldTrimReportGenerator

### C# log ###

*no output*

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.13

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.6.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.8|
|azure-pipelines|ms-azure-devops|1.165.1|
|azurecli|ms-vscode|0.5.0|
|azurerm-vscode-tools|msazurermtools|0.8.4|
|chat|karigari|0.31.0|
|codestream|CodeStream|6.2.0|
|csharp|ms-dotnettools|1.21.13|
|elixir-formatter|saratravi|1.3.0|
|elixir-ls|JakeBecker|0.2.25|
|elixirlinter|iampeterbanjo|0.4.1|
|erlang|pgourlain|0.5.2|
|gitlens|eamodio|10.2.1|
|mssql|ms-mssql|1.8.0|
|sqltools|mtxr|0.21.6|
|swdc-vscode|softwaredotcom|2.1.16|
|tslint|eg2|1.0.44|
|typescript-hero|rbbit|3.0.0|
|typescript-javascript-grammar|ms-vscode|0.0.53|
|vscode-azureappservice|ms-azuretools|0.16.2|
|vscode-azurefunctions|ms-azuretools|0.21.0|
|vscode-azurestorage|ms-azuretools|0.8.0|
|vscode-cosmosdb|ms-azuretools|0.12.1|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-elixir|mjmcloug|1.1.0|
|vscode-node-azure-pack|ms-vscode|0.0.10|
|vscode-peacock|johnpapa|3.5.0|
|vsliveshare|ms-vsliveshare|1.0.1711|
|vsliveshare-audio|ms-vsliveshare|0.1.80|
|vsliveshare-pack|ms-vsliveshare|0.3.4|
|vsls-pomodoro|lostintangent|0.1.0|
|vsls-whiteboard|lostintangent|0.0.9|;

</details>

**Comment by kodx** [comment] 2020-03-07 15:16
I have similar problem with Unreal Engine 4 generated project. 

Here is an easy fix.  
Find `<Project name>.code-workspace` if your project folder and replace
```
"extensions": {
		"recommendations": [
			"ms-vscode.csharp"
		]
	}
```

with this

```
"extensions": {
		"recommendations": [
			"ms-dotnettools.csharp"
		]
	}
```
and this warning will disappear.

This warning is came from malconfigured worksapce file, not the extension itself. I suggest you to close this issue.

**Comment by filipw** [comment] 2020-03-07 20:13
this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3620

see https://github.com/OmniSharp/omnisharp-vscode/issues/3620#issuecomment-595362743 for explanation and sorry for the trouble

**Closed by filipw** 2020-03-07 20:13 UTC
