### ISSUE TITLE
Format ignoring indent preference

### ISSUE THREAD

**Issue by mohd-akram** [OmniSharp/omnisharp-vscode#1632] opened 2017-07-12 13:00 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```
VS Code version: 1.14.0
C# Extension version: 1.11.0

## Steps to reproduce

Run "Format Document" command on .cs file.

## Expected  behavior

File will be formatted according to indentation preference (eg. Spaces: 4) in Status Bar.

## Actual behavior

File is formatted with global `editor.tabSize` indentation setting.

**Comment by DustinCampbell** [comment] 2017-07-13 15:30
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1574

**Closed by DustinCampbell** 2017-07-13 15:30 UTC
Labels: Editor-Formatting, Resolved-Duplicate
