### ISSUE TITLE
Omnisharp 1.12.0 on MacOS does not start. Complains of missing file: mcs.exe

### ISSUE THREAD

**Issue by peratproductmadness** [OmniSharp/omnisharp-vscode#1705] opened 2017-08-11 14:12 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

VS Code version: 1.15.0
C# Extension version: 1.12.0

## Steps to reproduce
Open a .cs file

## Expected  behavior
Omnisharp starts working

## Actual behavior
Omnisharp keeps showing "Running" in the bottom right corner and does not work.

The output of OmniSharp Log is:
```
Starting OmniSharp server at 8/11/2017, 3:05:53 PM
    Target: /Users/perbnielsen/Documents/state-machine-unity/Unity/Unity.sln

OmniSharp server started wth Mono
    Path: /Users/perbnielsen/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/run
    PID: 29831

OmniSharp: -s /Users/perbnielsen/Documents/state-machine-unity/Unity/Unity.sln --hostPID 29793 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/perbnielsen/Documents/state-machine-unity/Unity' on host 29793."},"Seq":1,"Type":"event"}
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/perbnielsen/Documents/state-machine-unity/Unity
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        OmniSharp initialized with Mono MSBuild.
    MSBUILD_EXE_PATH: /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/MSBuild.dll
    MSBuildExtensionsPath: /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild
    TargetFrameworkRootPath: /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild-frameworks
    RoslynTargetsPath: /Users/perbnielsen/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/omnisharp/msbuild/Roslyn
    CscToolPath: /Users/perbnielsen/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/omnisharp/msbuild/Roslyn

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/Users/perbnielsen/Documents/state-machine-unity/Unity/Unity.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: /Users/perbnielsen/Documents/state-machine-unity/Unity/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The specified task executable location "/Users/perbnielsen/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/omnisharp/msbuild/Roslyn/mcs.exe" is invalid.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file '/Users/perbnielsen/Documents/state-machine-unity/Unity/Assembly-CSharp.csproj'.
/Users/perbnielsen/Documents/state-machine-unity/Unity/Assembly-CSharp.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: /Users/perbnielsen/Documents/state-machine-unity/Unity/Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The specified task executable location "/Users/perbnielsen/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/omnisharp/msbuild/Roslyn/mcs.exe" is invalid.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file '/Users/perbnielsen/Documents/state-machine-unity/Unity/Assembly-CSharp-Editor.csproj'.
/Users/perbnielsen/Documents/state-machine-unity/Unity/Assembly-CSharp-Editor.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/perbnielsen/Documents/state-machine-unity/Unity'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.
```

**Comment by DustinCampbell** [comment] 2017-08-11 14:31
This looks like a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1704. The solution is to update to the latest stable Mono version (5.0.1).

**Comment by DustinCampbell** [comment] 2017-08-11 14:33
Also reported here: https://github.com/OmniSharp/omnisharp-vscode/issues/1699.

**Comment by DustinCampbell** [comment] 2017-08-11 15:00
Do let me know if this doesn't fix the issue for you.

**Comment by peratproductmadness** [comment] 2017-08-11 15:06
That did indeed fix it. Thank you.

**Comment by DustinCampbell** [comment] 2017-08-11 15:06
Glad to hear it. Thanks!

**Closed** 2017-08-11 15:06 UTC
Labels: Resolved-Duplicate
