### ISSUE TITLE
Intellisense should suggest a class name when instantiating

### ISSUE THREAD

**Issue by CarlosTorrecillas** [OmniSharp/omnisharp-vscode#815] opened 2016-10-12 22:19 UTC
## Environment data
`dotnet --info` output: 
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
VS Code version: 1.6.0
C# Extension version: 1.4.1

## Steps to reproduce

- Create a public class (let's say `public class TestClass{}`)
- Create a variable of that class: `TestClass myTestClass;`
- Instantiate `myTestClass` by doing `myTestClass = new TestClass();`

## Expected  behavior

I should have expected that intellisense would suggest `TestClass` after I typed `new`

## Actual behavior

Nothing happens and you need to type the class name by yourself.

**Comment by DustinCampbell** [comment] 2016-10-13 14:27
Thanks for the request! This is a duplicate of #146.

**Closed by DustinCampbell** 2016-10-13 14:27 UTC
Labels: Resolved-Duplicate
