### ISSUE TITLE
Missed AxImp.exe when loading the project in VSC on Mac

### ISSUE THREAD

**Issue by martyrzsd** [OmniSharp/omnisharp-vscode#2748] opened 2018-12-15 11:31 UTC
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:1.30.0
C# Extension version:1.17.1

## Steps to reproduce
Load the project, then fail. Already tried reinstall extension, haven't tried to reinstall mono because I actually don't know how😂😂😂. I'm a student and still fresh to all these.
But this worked several days ago. I can't recall when, but this worked well. I didn't make any improper changes on the software environment, maybe I did update the VSC or **VS for Mac**(I guess that's the why) for once?

## Expected  behavior
Outline autocomplete and reference should be showed

## Actual behavior
No outline nor reference nor autocomplete display.

##LOG
Starting OmniSharp server at 12/15/2018, 7:03:49 PM
    Target: /Users/shawnezhang/Desktop/gobang/gobang.sln

OmniSharp server started with Mono 5.16.0.
    Path: /Users/shawnezhang/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/OmniSharp.exe
    PID: 9351

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.2 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/shawnezhang/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/shawnezhang/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/shawnezhang/Desktop/gobang'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/shawnezhang/Desktop/gobang/gobang.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/shawnezhang/Desktop/gobang/gobang/gobang.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/shawnezhang/Desktop/gobang'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/shawnezhang/Desktop/gobang' on host 9319.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/shawnezhang/Desktop/gobang/gobang/gobang.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        Task attempted to find "AxImp.exe" in two locations. 1) Under the "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/4.5/" processor specific directory which is generated based on SdkToolsPath 2) The x86 specific directory under "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/4.5/" which is specified by the SDKToolsPath property. You may be able to solve the problem by doing one of the following:  1) Set the "SDKToolsPath" property to the location of the Microsoft Windows SDK.
[fail]: OmniSharp.MSBuild.ProjectLoader
        Task could not find "AxImp.exe" using the SdkToolsPath "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/4.5/" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/shawnezhang/Desktop/gobang/gobang/gobang.csproj'.
/Users/shawnezhang/Desktop/gobang/gobang/gobang.csproj
/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2749,5): Error: Task attempted to find "AxImp.exe" in two locations. 1) Under the "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/4.5/" processor specific directory which is generated based on SdkToolsPath 2) The x86 specific directory under "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/4.5/" which is specified by the SDKToolsPath property. You may be able to solve the problem by doing one of the following:  1) Set the "SDKToolsPath" property to the location of the Microsoft Windows SDK.
/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2749,5): Error: Task could not find "AxImp.exe" using the SdkToolsPath "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/4.5/" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed

[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: /Users/shawnezhang/Desktop/gobang/gobang/gobang.csproj

**Comment by martyrzsd** [comment] 2018-12-15 11:50
Other projects on my computer have no such issues, as well as a new created single .cs files.

**Comment by rchande** [comment] 2018-12-17 17:49
@martyrzsd It sounds like your mono installation may be missing some files? See https://github.com/OmniSharp/omnisharp-vscode/issues/1722 for a similar issue

**Comment by tedstromBrierley** [comment] 2020-06-03 03:36
@martyrzsd  did you end up finding a solution?  I don't remember installing Mono before, may have been a long time back as far as I can remember, but I'm getting the same on Mono6.8.  Tried installing the latest from the mono-project which mentions it's needed to be able to support VS on mac, although I only use Code these days.  It's definitely looking for it in the wrong place though since ```/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.5/``` doesn't exist.  I'm not sure where it installed itself but I haven't found where that SdkToolsPath is getting set yet or why it's looking in the wrong place to begin with.

**Comment by cartermp** [comment] 2020-09-15 23:31
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1722

**Closed by cartermp** 2020-09-15 23:31 UTC
