### ISSUE TITLE
remove unused usings

### ISSUE THREAD

**Issue by kindohm** [OmniSharp/omnisharp-vscode#1245] opened 2017-02-16 15:35 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.9.1
C# Extension version: 1.7.0

## Steps to reproduce
Search in Command Palette for "Remove Unused Usings" or "Remove Unnecessary Usings" command.

## Expected  behavior
Option to "Remove Unused Usings" or "Remove Unncessary Usings" is available in Command Palette. Executing the command will remove all unnecessary usings from the active .cs file.

## Actual behavior
No feature exists.

Expecting a feature like this (from VS 2015):

![remove-unused-usings](https://cloud.githubusercontent.com/assets/9797/23027734/de05d468-f42a-11e6-89a1-e43cade07447.png)

This issue seems very similar to #788 but I think _removing_ unused usings is a much different feature from sorting. Removing usings prevents code warnings, shortens code, etc.

**Comment by DustinCampbell** [comment] 2017-02-16 15:55
This is really a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1179.

**Comment by msivers** [comment] 2018-11-04 01:14
Bump!... This reasonably basic capability is a big miss on Visual Studio Code. I'm so used to having this from VS2017 and before and when you have loads of .cs files and many have a lot of using statements there is no way to cull the list without a majorly time-consuming effort.

Please can we have the capability to remove unused using statements - either through keyboard shortcut or through document formatting.

**Comment by CrossBound** [comment] 2019-08-17 15:26
Any update on this? I would really love to have this available... It is so nice in VS to be able to run a keystroke and it remove & sort my usings.

**Comment by memark** [comment] 2019-09-14 15:32
Any update on this?

**Comment by DmitriyBobrovskiy** [comment] 2019-11-04 12:41
Any updates, guys? We really would like to see this feature in VSCode.

**Comment by marcusturewicz** [comment] 2019-11-30 23:18
How would one go about implementing this? Happy to have a crack, given some direction.

**Comment by DmitriyBobrovskiy** [comment] 2019-12-01 16:19
> How would one go about implementing this? Happy to have a crack, given some direction.

Well, there is already implemented some kind of this functionality in vscode. When you go to usings and press Ctrl+. at the line with unused using, you would see suggestion to remove unnecessary usings.
Furthermore there is feature of determining usings which are not used (they are not so bright as those which are used).
So, probably there is some way of combining these two features to make it work.
If I know it a bit deeper, I'd implement it by myself.
![image](https://user-images.githubusercontent.com/33372992/69916679-9a874f00-1466-11ea-9016-9a043dfb4250.png)

**Comment by savpek** [comment] 2019-12-01 17:33
I think this can be handled by https://github.com/OmniSharp/omnisharp-roslyn/pull/1581 once it's ready, it might be good idea to add shortcut key support for "Fix all auto fixable issues at current document" (?)

**Comment by richarddavenport** [comment] 2020-02-13 16:39
@savpek That's a fantastic idea. Do you know if/when OmniSharp/omnisharp-roslyn#1581 is going to be shipped?

**Comment by filipw** [comment] 2020-02-13 16:49
should not be long

**Comment by FloatingSunfish** [comment] 2020-09-13 09:59
@filipw Any updates on this issue?
Having an option to remove unused `using`s upon Save would be a very useful thing to have.

**Comment by johmarjac** [comment] 2020-09-18 20:42
is there any news on this? jesus i dont see how this is still not implemented?

**Comment by Esildor** [comment] 2021-01-19 20:56
lololol at this still not being implemented yet. I'm over here living in 2021 bro

**Comment by filipw** [comment] 2021-01-19 21:30
it is already implemented.

press `ctrl+p` (`cmd+P` on a Mac), select the option `OmniSharp: Fix all occurrences of a code issue within a project` (there are additional options for document/solution level too). All fixable issues from the given scope should show up - so select `CS8019: Unnecessary using directive`.

![Bildschirmaufnahme 2021-01-19 um 22 25 44](https://user-images.githubusercontent.com/1710369/105095392-e0a5d480-5aa5-11eb-8c3f-c0a93be24a3c.gif)

**Comment by JoeRobich** [comment] 2021-01-19 22:48
Closing as this has been implemented.

**Closed by JoeRobich** 2021-01-19 22:48 UTC
Labels: Editor-Unnecessary usings, Feature Request, Triaged

**Comment by richarddavenport** [comment] 2021-01-20 15:12
@filipw Thanks for the update. One clarifying question, do you know if this is possible when formatting? Thanks!

**Comment by filipw** [comment] 2021-01-20 15:45
unfortunately not at the moment. there is only an option to sort the usings on formatting (https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#13410---2020-01-27)

**Comment by thistlehouse** [comment] 2023-08-16 15:32
Visual Studio has ctrl + R, ctrl + G for that, could Visual Code has something similar (different shortcut though)?
