### ISSUE TITLE
With SDK 3.1.401, loading .NET Core projects with some problems in VSCode.

### ISSUE THREAD

**Issue by dandanmu** [OmniSharp/omnisharp-vscode#3951] opened 2020-08-04 08:50 UTC
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:1.47.3
C# Extension version:1.22(v1.22.2)

## Steps to reproduce
1.Install VSCode.
2.Launch VSCode and install the C# extension.
3.Install Mono 6.12.0.90 and “omnisharp.useGlobalMono” is set to “auto” .
4.Create a new .NET Core project.
5.Open the project in VSCode.

## Expected  behavior
The project succeeds to load, build and run succeeded without any problems.

## Actual behavior
The project succeeds to load, build and run succeeded with some problems.
![Screen Shot 2020-08-04 at 3 47 10 PM](https://user-images.githubusercontent.com/65638819/89269082-006a4d00-d66c-11ea-8042-0f74015fd026.png)

Note:
For .NET Standard projects, it loads as expected without any problems.

**Comment by filipw** [comment] 2020-08-04 09:12
thanks, you already opened this issue before - https://github.com/OmniSharp/omnisharp-vscode/issues/3935#issuecomment-668281627

**Comment by JoeRobich** [comment] 2020-08-04 16:56
@dandanmu Testing locally I see that it is resolving runtime references from NuGet instead of the dotnet SDK. If you enable the LegacySdkResolver, it will locate the references appropriately.

Creating omnisharp.json as described below, in ~/.omnisharp/ or project directory.

```json
{
   "msbuild": {
       "UseLegacySdkResolver": true
   }
}
```

**Comment by georgikoemdzhiev** [comment] 2020-08-10 11:00
> @dandanmu Testing locally I see that it is resolving runtime references from NuGet instead of the dotnet SDK. If you enable the LegacySdkResolver, it will locate the references appropriately.
> 
> Creating omnisharp.json as described below, in ~/.omnisharp/ or project directory.
> 
> ```json
> {
>    "msbuild": {
>        "UseLegacySdkResolver": true
>    }
> }
> ```

Thank you! That resolved the same issue for me. I use version 3.1.302

**Comment by cartermp** [comment] 2020-08-11 23:43
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3935

Unfortunately this one is a horrible experience and not easy to deal with :(

**Closed by cartermp** 2020-08-11 23:43 UTC
