### ISSUE TITLE
Debugger: Log Message isn't export in output window

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#2212] opened 2018-04-24 07:33 UTC
## Environment data
`dotnet --info` output:
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64
Base Path: /usr/share/dotnet/sdk/2.1.105/
VS Code version: 1.22.2
C# Extension version: 1.15.0-beta5

## Steps to reproduce
1. Open attachment in VSCode
[console.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1941310/console.zip)
2. Add a bp and set Log Message as "aaaaa"
![log](https://user-images.githubusercontent.com/20922638/39171536-acf7abc2-478e-11e8-9d20-5ef45ad0f79a.PNG)
3. Click F5

## Expected  behavior
OUTPUT windows should export log message "aaaaa"

## Actual behavior
It hasn't export message and has error message in Log(Windows)(You can refer to attchment)
![aaaaaaa](https://user-images.githubusercontent.com/20922638/39172595-bbcf4076-4791-11e8-823f-45075377f3d9.PNG)
[LOG (2).txt](https://github.com/OmniSharp/omnisharp-vscode/files/1941317/LOG.2.txt)

**Comment by chuckries** [comment] 2018-04-24 16:45
This also repros against 1.14.0, meaning it is not a regression due to .NET Core 2.1 work. This is simply a new feature that we have not added support for yet. Additionally, the log message will appear in the Debug Console window, not in the output window. Here is an example of a log point from the node debugger:
![image](https://user-images.githubusercontent.com/6598594/39201573-44bca4e8-47a4-11e8-9c42-c9cdec5f1bbe.png)

**Comment by qian6** [comment] 2018-04-25 05:35
Got it, We will test it when tracepoint support.

**Comment by gregg-miskelly** [comment] 2018-08-23 22:37
I am going to look into fixing conditional breakpoints. If this is easy to fix at the same time I will look at this too.

**Comment by gregg-miskelly** [comment] 2022-01-04 21:49
There is now a customer reported issue requesting this feature. So I am going to close this old bug in favor of it. https://github.com/OmniSharp/omnisharp-vscode/issues/4966

**Comment by gregg-miskelly** [comment] 2022-01-04 21:50
Wait, we already had a customer reported bug for this: https://github.com/OmniSharp/omnisharp-vscode/issues/1797

**Closed by gregg-miskelly** 2022-01-04 21:49 UTC
Labels: Debugger, Debugger-Poachable, Improvement
