### ISSUE TITLE
.NET core debugger crashes

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#1383] opened 2017-04-13 07:05 UTC
_From @joonatoona on April 12, 2017 23:8_

Error `Debug adapter process has terminated unexpectedly`

- VSCode Version: 1.11.1
- OS Version: 4.10.8-1-ARCH

Steps to Reproduce:

1. Install visual-studio-code from the aur
2. Open a .NET core project
3. Press F5

_Copied from original issue: Microsoft/vscode#24641_

**Comment by gregg-miskelly** [comment] 2017-04-13 16:01
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1323

**Closed by gregg-miskelly** 2017-04-13 16:01 UTC
