### ISSUE TITLE
Omnisharp CPU performance issues

### ISSUE THREAD

**Issue by KristianBalaj** [OmniSharp/omnisharp-vscode#3079] opened 2019-05-21 15:05 UTC
## Environment data
**Runtime Environment:**
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\
**VS Code version:** 1.34.0
**C# Extension version:** 1.19.1

## Steps to reproduce
1. Open Unity project in Visual Studio Code
2. Start typing in any C# file inside the project
3. Check your CPU blow up
_The project has approximately 2200 c# files._

## Expected  behavior
No crazy CPU load while coding and normal intellisense response times.

## Actual behavior
The intellisense response takes approximately 3 seconds when typing code. The CPU load of omnisharp component in VS code comes while typing.
When I'm not typing anything in any C# file, there's no crazy load on CPU and it all looks fine.
![CPU load right after typing code.](https://user-images.githubusercontent.com/20045353/58106938-3c410000-7be9-11e9-9382-a67e48f2ccee.png)

**Comment by martielo** [comment] 2019-05-21 15:42
I'm getting the same problem whenever I implement **IDisposable**.

![git_omnisharp](https://user-images.githubusercontent.com/33702767/58110376-c9725d80-7bc5-11e9-9e6d-71623276d071.png)

**Comment by mic-hnk** [comment] 2019-07-15 11:15
OS: Ubuntu 16.04
VS Code version: 1.35.1
C# Extension version: 1.20.0

I had the issue in unit test project. Is is gone after I removed all **IDisposable** implementations.

**Comment by rchande** [comment] 2019-07-15 19:31
@KristianBalaj @mic-hnk Can you see if this goes away if you set the option ```"csharp.referencesCodeLens.enabled": false``` ? I think what's happening is that the references code lens provider is consuming a lot of cpu searching for IDisposable implementors.

**Comment by mic-hnk** [comment] 2019-07-16 07:48
@rchande I think it helped. After changing the recommended setting and opening a project with **IDisposable** implementations I cannot observe high cpu usage anymore. I am not sure though if this is a perfect solution to disable the given code lens ;)

**Comment by KristianBalaj** [comment] 2019-07-16 11:06
@rchande yeah disabling code lens helps. I've tested both enabled/disabled states, compared it and the disabled state is exactly how it should work.
On the other hand, I don't think it's a problem just with *IDisposable* implementations. I've tested this issue on a smaller project (approximately 200 code files divided into smaller assemblies) where I have *IDisposable* implemented and there is no such problem with the CPU load (either code lens enabled or disabled). So I think the main factor could be the project size.
Otherwise, like @mic-hnk said that's not the best solution to disable code lens. ;)

**Comment by mic-hnk** [comment] 2019-07-16 11:10
I think project size is not a problem. I faced this issue in xunit test project with 10 files. I even removed all but one code files and cpu usage remained high.

**Comment by KristianBalaj** [comment] 2019-07-16 11:12
Maybe you forgot about xunit assemblies included in the solution. There are many types, too.

**Comment by majames** [comment] 2019-07-18 21:06
As another data point, we just added some unit tests that implement the `IDisposable` in the large code base I work in and omnisharp started to consume crazy amounts of CPU.

My dev environment is on linux so looks like the issue is cross-platform too 😬

**Comment by mvalero** [comment] 2019-07-19 15:36
Several people on my team experience a similar behavior. Specially in some xunit test classes the CPU consumption just goes up to 80-100% through all 8 cores whenever you start editing them and trigger intellisense.

We were since long time trying to isolate one use case where the problem always happens and the hint with `IDisposable` is a very good one 😃, the classes where we mostly get the problem are actually implementing it.

I just did the test of changing one of these classes to not implement `IDisposable` and the problem seems to have disappeared. Whenever I introduce it again, the CPU goes back to 100%.

**Comment by Marchyello** [comment] 2019-08-02 11:42
Can confirm that implementing `IDisposable` was the trigger of (very frustrating) performance issues for me as well. Thank you for pointing this out!

**Comment by icefire1** [comment] 2019-08-28 09:14
Seeing the same thing here... Quite a hassle, but I did not want to disable code lens. Instead I made my own abstract class which implements IDisposable. My classes that should actually implement IDisposable should instead implement IMyDisposable. Quite a bad hack, but it reduces the CPU usage.
```
public abstract class IMyDisposable : IDisposable
{
    public abstract void Dispose();
}
```

And inside my class that needs to be disposable
```
public class TlcManagerTests : IMyDisposable
{
    public override void Dispose()
    {
        ...
    }
}
```

**Comment by martielo** [comment] 2019-09-11 13:45
Well, after some months I'm still facing this problem. I think we all agree that disabling **code lens** is not a good solution.
In order to work with a class that implements **IDisposable**, I need to comment it for a while and then, when I finish coding, I uncomment it.

![image](https://user-images.githubusercontent.com/33702767/64702401-d53da480-d480-11e9-9466-bcf7545f74cb.png)

**Comment by turowicz** [comment] 2019-10-10 12:50
I may have duplicated this issue in #3336

**Comment by nbarbettini** [comment] 2019-10-18 01:25
I've been experiencing random high CPU load from the mono process, but I hadn't pinned down any cause. Disabling CodeLens fixed it, and after I looked deeper, I had an xunit test that implemented `IDisposable`.

**Comment by LiamMorrow** [comment] 2020-02-07 00:30
I had the same issue.  I was editing a new stream implementation and every character typed sent it to 100%.  On arch linux.  Can confirm disabling references codelens fixed the issue for me

**Comment by SirIntruder** [comment] 2020-02-09 12:00
I've tried profiling this problem in the past, but I just found out the issue is in the roslyn rather than in omnisharp. The only thing o# can do at this moment is to specifically turn off code lens for Dispose() methods, same way as ToString() works currently.

o# issue tracking this: https://github.com/OmniSharp/omnisharp-roslyn/issues/367

**Comment by ghandmann** [comment] 2020-03-06 09:33
I recognized the same behavior. Everything is fluent and happy until the moment i add the `IDisposable` interface to a class. Suddenly the fans start spinning and CPU usage goes through the roof.

```
Version: 1.43.0-insider
Commit: 9c341b3d8f2f41277be6dd59e7f4e847e6b594ac
Date: 2020-02-20T05:39:45.923Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-88-generic
```

```
Starting OmniSharp server at 6.3.2020
```

**Comment by ianmann56** [comment] 2020-03-09 23:14
I'm having the same issue. I'm running the following:
```
Linux Mint: 19.1
C# Extension: 1.21.13
dotnet sdk: 2.2.402
```

And my VSCode versions:
```
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:32:17.711Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-54-generic
```

**Comment by Fosol** [comment] 2020-03-30 22:12
I can't even use the extension now.. It's just horrible.  Just keeps saying 'Saving... Getting code actions from "C#', 'C# Extensions'".

**Comment by stann1** [comment] 2020-05-01 08:46
I am having the same issue. Seems like it take a lot of time to resolve...

**Comment by JoeRobich** [comment] 2020-05-14 17:16
Should be fixed with https://github.com/OmniSharp/omnisharp-vscode/pull/3780. We will no longer add a references codelens to the Dispose method. This is related to https://github.com/dotnet/roslyn/issues/38223

**Closed by JoeRobich** 2020-05-14 17:16 UTC
Labels: Bug, Triaged

**Comment by puddies** [comment] 2021-09-02 02:31
Same here in 2021.  I'm using MBP with fresh installed VSCode and c# extension of omnisharp, empty project, then cpu spike over 500%.  Everything go back to normal when i disabled or uninstall this extension.

**Comment by Fosol** [comment] 2021-09-02 17:53
This continues to be an issue for me.  Sometimes I can restart VSCode and it'll start working okay for a bit.  But most days it gets so bad I just have to disable the extension.  I have the latest version of VSCode.

**Comment by DumboJetEngine** [comment] 2021-12-11 19:39
I get the same issue (OmniSharp taking huge amounts of CPU) on Debian Linux, using almost the latest version of VS Code and updated extensions:

Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:51:30.084Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.0-9-amd64
