### ISSUE TITLE
Confusing experience when stopping on exceptions throw from framework code

### ISSUE THREAD

**Issue by saurabhnachankar** [OmniSharp/omnisharp-vscode#1385] opened 2017-04-13 07:16 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

VS Code version:1.11.1
C# Extension version: 1.3.0

## Steps to reproduce
In earlier VS Code, Ominsharp use to show to green color highlighted line on error line which is now not seen on current update.

## Expected  behavior
Show green color highlighted line on error line

## Actual behavior
Not seen green color highlighted line on error line

**Comment by DustinCampbell** [comment] 2017-04-13 13:45
I'm not sure I understand your report. Could you provide more detail or a screenshot that shows what you're expecting to see?

Also, is it accurate that you have C# 1.3.0 installed? The latest version of C# for Visual Studio Code is 1.8.1.

**Comment by DustinCampbell** [comment] 2017-04-19 16:26
Hi! If you have some time, please provide the information requested above and I'll do my best to help.

**Comment by saurabhnachankar** [comment] 2017-04-20 05:37
SDK -1.0.1
RunTime : 1.1.1
VS Code : 1.11.2
Ominsharp : 1.8.1

In Previous version of omnisharp, if there is error or if it crashes while
debugging 'Green color high-lightning' use to show up on the error line. As
it was useful feature for debugging.

But after updating the green color highligtning has stopped so i am unable
to detect on which line it stopped.

Thanks & Regards,

*Saurabh Nachankar*

*Software Engineer*
*Crystal information technology, Thane*
*Mobile No : +91 9503498876  |  Email : saurabhnachankar@gmail.com
<saurabhnachankar@gmail.com>*

* "I am programmer who converts theories into realities.."*
P Print only when necessary |*7* Switch off as you go |*q*Recycle always

**Comment by DustinCampbell** [comment] 2017-04-20 13:29
@gregg-miskelly: Do you know anything about this?

**Comment by gregg-miskelly** [comment] 2017-04-20 23:36
@saurabhnachankar I can repro your problem. It could be that the debugger could be doing something better here, but I think mostly this is a VS Code bug. I will open one there.

**Comment by gregg-miskelly** [comment] 2017-04-21 00:00
VS Code issue: https://github.com/Microsoft/vscode/issues/25104

**Comment by gregg-miskelly** [comment] 2017-04-21 16:07
I tried to work around this on our side, but looks like there is nothing we can do.

So I am resolving this is as External since the issue is now tracked in VS Code.

**Closed by gregg-miskelly** 2017-04-21 16:07 UTC
Labels: Debugger

**Comment by saurabhnachankar** [comment] 2017-04-22 07:09
thanks for help

Thanks & Regards,

*Saurabh Nachankar*

*Software Engineer*
*Crystal information technology, Thane*
*Mobile No : +91 9503498876  |  Email : saurabhnachankar@gmail.com
<saurabhnachankar@gmail.com>*

* "I am programmer who converts theories into realities.."*
P Print only when necessary |*7* Switch off as you go |*q*Recycle always
