### ISSUE TITLE
[Request] Navigate to source code

### ISSUE THREAD

**Issue by seanmars** [OmniSharp/omnisharp-vscode#2298] opened 2018-05-15 07:27 UTC
## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
C# Extension version:

## Steps to reproduce
ctrl + left-click

## Expected  behavior
Navigate to source code of framework or package

## Actual behavior
only metadata

**Comment by DustinCampbell** [comment] 2018-05-15 14:38
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2207.

**Closed by DustinCampbell** 2018-05-15 14:38 UTC
Labels: Resolved-Duplicate
