### ISSUE TITLE
Is it normal that we need to restart omnisharp when we change formattingOptions?

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-vscode#1080] opened 2016-12-23 04:30 UTC
Today I just start using omnisharp.json in vscode. And it not always format when I change that file. It seem like it need to restart omnisharp every times I change option to make it work

Is this is expected behaviour? Should it always inject formattingoption everytime it changed?

**Comment by DustinCampbell** [comment] 2016-12-23 05:50
As far as I can tell, OmniSharp loads the options once at start up. However, you're right that this isn't a great experience. Changing this file should update the options on the fly.

+ @filipw, @david-driscoll for the OmniSharp request.

**Comment by filipw** [comment] 2016-12-23 07:08
I agree - it should be modifiable in real time.
There is actually already an issue to track this - https://github.com/OmniSharp/omnisharp-roslyn/issues/366

It should be fairly easy to implement.

**Comment by DustinCampbell** [comment] 2016-12-23 12:12
FWIW, I wouldn't support that by sending the options with every request as mentioned as a suggested solution in https://github.com/OmniSharp/omnisharp-roslyn/issues/366. Instead, OmniSharp should be watching the omnisharp.json and update the options its using when that file changes.

Anyway, we can track that issue. Closing this as a dupe of https://github.com/OmniSharp/omnisharp-roslyn/issues/366.

**Closed by DustinCampbell** 2016-12-23 12:12 UTC
Labels: OmniSharp, Resolved-Duplicate

**Comment by filipw** [comment] 2016-12-23 12:27
yes I wouldn't do it per request too.
 
However it might be useful to have a route which you can use to modify the options omnisharp started with.

Not sure if VS Code exposes relevant events for that at the moment, but this way i.e. if the user changes the value of `editor.tabSize`, the extension could use the options route to modify the corresponding value in the running OmniSharp process.

**Comment by Thaina** [comment] 2016-12-23 12:30
I'm not sure that issue keep track about the modification of formatting file after omnisharp was started

I has been talk about inherit the setting from config.json. But what happen if config.json was changed after that?

And vscode has expose some event related to file changed. So I think it still in scope of extension (this repo) too pass the notification from vscode to omnisharp for updating the options

**Comment by DustinCampbell** [comment] 2016-12-23 12:32
@filipw: Totally agreed.

@Thaina: The bulk of the work will be in the OmniSharp server with a small amount of work to handle the specific scenario @filipw mentioned. So, I'd rather track it over in omnisharp-roslyn -- especially since the C# extension in VS Code knows nothing about omnisharp.json. I'll update https://github.com/OmniSharp/omnisharp-roslyn/issues/366 to better track this issue.

**Comment by Thaina** [comment] 2016-12-23 12:39
Talk about omnisharp.json, if it is the base config file of omnisharp. I wish that we should add it into validator contribution point for omnisharp-vscode

Actually I was trying to make PR just today. But I can't find its schema

**Comment by DustinCampbell** [comment] 2016-12-23 12:43
The "schema" is generated dynamically by the options that OmniSharp expects to be there. I agree that having something on schemastore.org that we regularly update would be good.

**Comment by Thaina** [comment] 2016-12-23 12:52
If it could generate dynamically then I think it should always generate automatically into omnisharp repo and let other extension reference to it

**Comment by DustinCampbell** [comment] 2016-12-23 12:53
Yup. I agree. We're taking contributions btw :smile:
