### ISSUE TITLE
OmniSharp generating error messages as I type "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by ARAtlas** [OmniSharp/omnisharp-vscode#1046] opened 2016-12-15 21:19 UTC
As I type stuff into the code editor the following error is added to the OmniSharp output window over and over again. I don't see any symptoms beyond the errors appearing in the output window. I'm using VS Code 1.8.0, Unity 5.5, and the dotBunny utility to connect the two.

**[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 4ms**

**Comment by DustinCampbell** [comment] 2016-12-15 21:28
Thanks for taking the time to report this issue. https://github.com/OmniSharp/omnisharp-vscode/issues/980 is a duplicate of this issue, which should already be fixed in the latest beta release.

**Closed by DustinCampbell** 2016-12-15 21:28 UTC
Labels: Resolved-Duplicate
