### ISSUE TITLE
TypeError: Cannot read property 'ActiveSignature' of null 

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#149] opened 2016-04-06 07:40 UTC
Erro reported by error telemetry:

TypeError: Cannot read property 'ActiveSignature' of null 
 at /Users/a123/.vscode-insiders/extensions/ms-vscode.csharp-0.3.7/out/features/signatureHelpProvider.js:24:38 
 at process._tickCallback (node.js:369:9)

**Comment by DustinCampbell** [comment] 2016-04-06 14:50
Duplicate of #64. This is already fixed by #107.

**Closed by DustinCampbell** 2016-04-06 14:50 UTC
Labels: Resolved-Duplicate
