### ISSUE TITLE
Omnisharp does not resolve Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by eneskoroglu** [OmniSharp/omnisharp-vscode#3412] opened 2019-11-19 11:54 UTC
## Issue Description ##
I am using VSCode while writing a webapi in dotnet core 3.0.100. When i try to build below code (ServiceTool.ServiceProvider is IServiceProvider)

`ServiceTool.ServiceProvider.GetService<Stopwatch>();`

I got following error:
`error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments`

After below using definition problem is solved:
`using Microsoft.Extensions.DependencyInjection;`

Why vscode (omnisharp) does not suggest this using?

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here
Starting OmniSharp server at 19.11.2019 14:47:04
    Target: c:\Source\Course\NorthwindBackend.sln

OmniSharp server started.
    Path: C:\Users\myuser\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.7\OmniSharp.exe
    PID: 137124

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.53 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 16.3 - "C:\Users\myuser\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.7\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\myuser\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.7\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.3 - "C:\Users\myuser\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.7\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\myuser\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.7\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\myuser\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.7\.msbuild
            MSBuildToolsPath = C:\Users\myuser\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.7\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Source\Course'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Source\Course\NorthwindBackend.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Source\Course\NorthwindBackend.Entities\NorthwindBackend.Entities.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Source\Course\NorthwindBackend.DataAcces\NorthwindBackend.DataAcces.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Source\Course\NorthwindBackend.Business\NorthwindBackend.Business.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Source\Course\Core\Core.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Source\Course\NorthwindBackend.WebApi\NorthwindBackend.WebApi.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Source\Course'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Source\Course\NorthwindBackend.Entities\NorthwindBackend.Entities.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Source\Course' on host 113904.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Source\Course\NorthwindBackend.Entities\NorthwindBackend.Entities.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Source\Course\NorthwindBackend.Entities\NorthwindBackend.Entities.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Source\Course\NorthwindBackend.DataAcces\NorthwindBackend.DataAcces.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Source\Course\NorthwindBackend.DataAcces\NorthwindBackend.DataAcces.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Source\Course\NorthwindBackend.DataAcces\NorthwindBackend.DataAcces.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Source\Course\NorthwindBackend.Business\NorthwindBackend.Business.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Source\Course\NorthwindBackend.Business\NorthwindBackend.Business.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Source\Course\NorthwindBackend.Business\NorthwindBackend.Business.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Source\Course\Core\Core.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Source\Course\Core\Core.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Source\Course\Core\Core.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Source\Course\NorthwindBackend.WebApi\NorthwindBackend.WebApi.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Source\Course\NorthwindBackend.WebApi\NorthwindBackend.WebApi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Source\Course\NorthwindBackend.WebApi\NorthwindBackend.WebApi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: NorthwindBackend.Entities
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: NorthwindBackend.DataAcces
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: NorthwindBackend.Business
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Core
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: NorthwindBackend.WebApi
</details>

### C# log ###
<details>Post the output from Output-->C# here
error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments
</details>

## Environment information ##

**VSCode version**: 1.40.1
**C# Extension**: 1.21.7

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|angular-console|nrwl|9.0.1|
|Angular2|johnpapa|8.1.1|
|auto-rename-tag|formulahendry|0.1.1|
|autoimport|steoates|1.5.3|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-runner|formulahendry|0.9.14|
|code-settings-sync|Shan|3.4.3|
|csharp|ms-vscode|1.21.7|
|Csharp-ASPNETCore|rahulsahay|1.11.0|
|csharpextensions|jchannon|1.3.1|
|gitlens|eamodio|10.2.0|
|indent-rainbow|oderwat|7.4.0|
|JavaScriptSnippets|xabikos|1.7.2|
|material-icon-theme|PKief|3.9.1|
|prettier-vscode|esbenp|3.6.0|
|regionfolder|maptz|1.0.5|
|remote-wsl|ms-vscode-remote|0.40.3|
|rest-client|humao|0.22.2|
|supersharp|craigthomas|0.1.4|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-html-css|ecmel|0.2.3|
|vscode-npm-script|eg2|0.3.9|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-peacock|johnpapa|3.2.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|;

</details>

**Comment by cartermp** [comment] 2020-04-09 20:35
@eneskoroglu I believe there were some issues with adding a using statement that have been resolved. I cannot reproduce this error with a new ASP.NET Core application where I delete the using, type what you suggest, then hit `ctrl+.` to trigger a code fix. So I'll close this one out, but if you have a reproduction where this still doesn't trigger we can re-open it.

**Closed by cartermp** 2020-04-09 20:35 UTC
Labels: Resolved-Not Reproducible, Triaged
