### ISSUE TITLE
Microsoft.Build.Exceptions.InvalidProjectFileException

### ISSUE THREAD

**Issue by PrakashKumar-27** [OmniSharp/omnisharp-vscode#2022] opened 2018-02-08 03:49 UTC
## Environment data
OmniSharp Log output:
```
Starting OmniSharp server at 2/16/2018, 9:05:18 AM
    Target: e:\VsCode Projects\Console

OmniSharp server started
    Path: C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\OmniSharp.exe
    PID: 4120

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild
            MSBuildToolsPath = C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\VsCode Projects\Console'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in e:\VsCode Projects\Console
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'e:\VsCode Projects\Console'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: e:\VsCode Projects\Console\myApp\myApp.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        **Failed to load project file 'e:\VsCode Projects\Console\myApp\myApp.csproj'.
e:\VsCode Projects\Console\myApp\myApp.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: An unexpected token "s" was found at character position 83 in condition "'$(ImportByWildcardBeforeMicrosoftCommonProps)' == 'true' and exists('C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore')".  C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Microsoft.Common.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)**
   at Microsoft.Build.Evaluation.Parser.Factor(String expression)
   at Microsoft.Build.Evaluation.Parser.RelationalExpr(String expression)
   at Microsoft.Build.Evaluation.Parser.BooleanTermPrime(String expression, GenericExpressionNode lhs)
   at Microsoft.Build.Evaluation.Parser.BooleanTerm(String expression)
   at Microsoft.Build.Evaluation.Parser.Expr(String expression)
   at Microsoft.Build.Evaluation.Parser.Parse(String expression, ParserOptions optionSettings, ElementLocation elementLocation)
   at Microsoft.Build.Evaluation.ConditionEvaluator.EvaluateConditionCollectingConditionedProperties[P,I](String condition, ParserOptions options, Expander`2 expander, ExpanderOptions expanderOptions, Dictionary`2 conditionedPropertiesTable, String evaluationDirectory, ElementLocation elementLocation, ILoggingService loggingServices, BuildEventContext buildEventContext, ProjectRootElementCache projectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateConditionCollectingConditionedProperties(ProjectElement element, String condition, ExpanderOptions expanderOptions, ParserOptions parserOptions, ProjectRootElementCache projectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportGroupElement(String directoryOfImportingFile, ProjectImportGroupElement importGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.LoadProject(String filePath, String solutionDirectory, ILogger logger, MSBuildInstance msbuildInstance, SdksPathResolver sdksPathResolver, MSBuildOptions options, ICollection`1 diagnostics, ImmutableArray`1& targetFrameworks)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, ILogger logger, MSBuildInstance msbuildInstance, SdksPathResolver sdksPathResolver, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\VsCode Projects\Console'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\VsCode Projects\Console' on host 3816.
```

OS- Windows 8 64 bit
VS Code version: 1.20.0
C# Extension version: 1.13.1

**Comment by rchande** [comment] 2018-02-08 16:51
@PrakashKumar-27 Does your project file have a syntax error? Also, is your project really in a directory whose name contains an apostrophe?

**Comment by PrakashKumar-27** [comment] 2018-02-15 02:29
Thanks for your response, rchande.

I am not sure my project have any syntax error. in my directory there is no "apostrophe"

**Comment by rchande** [comment] 2018-02-15 16:08
@PrakashKumar-27 In the omnisharp log that you posted, msbuild is failing to load your project because it contains a syntax error. Please take a look:

```
Microsoft.Build.Exceptions.InvalidProjectFileException: An unexpected token "s" was found at character position 83 in condition "'$(ImportByWildcardBeforeMicrosoftCommonProps)' == 'true' and exists('C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore')".  C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Microsoft.Common.props
```

**Comment by DustinCampbell** [comment] 2018-02-15 18:12
From the error above, it doesn't look like the error is in your project. Instead, it looks like the problem is because your Windows user profile contains an apostrophe character, which is breaking MSBuild's parsing. You can clearly see this above in this condition:

```
exists('C:\Users\It's me\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore')
```

**Comment by mikeobr** [comment] 2019-10-10 14:22
I found this while googling the error. I haven't seen anything about fixes, but a workaround (If you can't rename your userprofile) is to run vscode in portable mode from a different directory. See https://code.visualstudio.com/docs/editor/portable

**Comment by cartermp** [comment] 2020-09-22 23:36
Will close this out as by design, as it's ultimately an MSBuild issue.

**Closed by cartermp** 2020-09-22 23:36 UTC
Labels: Needs More Info, Resolved-By Design
