### ISSUE TITLE
XML in C# Intellisense comments

### ISSUE THREAD

**Issue by welkie** [OmniSharp/omnisharp-vscode#2060] opened 2018-02-21 19:49 UTC
Originally reported [here](https://github.com/Microsoft/vscode/issues/44078).

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version: 1.20.1
C# Extension version: 1.14.0

## Steps to reproduce

1. Begin typing the name of a method to call, press tab to complete it and view comments for method in Intellisense
2. Observe the comment

## Expected  behavior

Intellisense comments appear without XML markup, only showing formatted comments.

## Actual behavior

Intellisense comments appear with XML markup, unformatted.

## Example

![image](https://user-images.githubusercontent.com/7719209/36501921-73fffa2a-1716-11e8-8a41-fa7568faa2a3.png)

**Comment by akshita31** [comment] 2018-02-21 20:31
@welkie This is a bug with the signature help. We are already working on it in this PR : https://github.com/OmniSharp/omnisharp-vscode/pull/1958.

Also this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1940, hence closing it.

**Closed by akshita31** 2018-02-21 20:31 UTC
