### ISSUE TITLE
Please add support for Arm64 architecture.

### ISSUE THREAD

**Issue by aschick82** [OmniSharp/omnisharp-vscode#4720] opened 2021-08-24 15:12 UTC
I am unable to use the extension on a Raspberry Pi 4 with a Arm64 processor.

Is this going to be added soon?

**Comment by JoeRobich** [comment] 2021-08-31 16:25
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2771

**Closed by JoeRobich** 2021-08-31 16:25 UTC
Labels: Resolved-Duplicate, Triaged
