### ISSUE TITLE
Visual Studio Code c# extensions are not working on my Surface Pro X

### ISSUE THREAD

**Issue by AndiBitt** [OmniSharp/omnisharp-vscode#4339] opened 2021-01-09 14:22 UTC
## Visual Studio Code c# extensions are not working ##
##start debugging ##

### OmniSharp log ###
<details>
Starting OmniSharp server at 9.1.2021, 14:06:56
    Target: c:\Temp\TEST

OmniSharp server started.
    Path: c:\Users\andre\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\OmniSharp.exe
    PID: 5344

Das System kann den angegebenen Pfad nicht finden.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

### C# log ###
<details>
Cannot create .NET debug configurations. The OmniSharp server is still initializing or has exited unexpectedly.
</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Dotnet Information</summary>
.NET SDK (gem�� "global.json"):
 Version:   5.0.101
 Commit:    d05174dc5a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.1.3|
|csharp|ms-dotnettools|1.23.8|
|csharpextensions|jchannon|1.3.1|
|csharpextensions|kreativ-software|1.3.6|;

</details>

**Comment by gregg-miskelly** [comment] 2021-01-11 18:39
This is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/3006

**Closed by gregg-miskelly** 2021-01-11 18:39 UTC
