### ISSUE TITLE
Errors in output window do not get source links

### ISSUE THREAD

**Issue by nguerrera** [OmniSharp/omnisharp-vscode#1197] opened 2017-02-07 16:40 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004769)

Product Information:
 Version:            1.0.0-rc4-004769
 Commit SHA-1 hash:  9cf4e9d1d0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004769
```

VS Code version: 1.9.0
C# Extension version: 1.6.2

## Steps to reproduce

* dotnet new console
* dotnet restore
* Edit program.cs and make a deliberate error
* code .
* Ctrl+Shift+B
* Configure build task -> .NET Core
* Ctrl+Shift+B again
* Look at output window

## Expected  behavior

I can click on each of the errors in the output window and go to the relevant source.

## Actual behavior

I can't click on the errors because they have project-relative paths.

## Workaround
Set `<GenerateFullPaths>true</GenerateFullPaths>` in csproj. 

## Notes
Visual Studio arranges to have full paths in its output window, but VS code does not.

Related: dotnet/sdk#823

**Comment by DustinCampbell** [comment] 2017-02-07 16:43
Is there a step missing here? There needs to be a tasks.json file present for Ctrl+Shift+B to work.

**Comment by nguerrera** [comment] 2017-02-07 16:48
Sorry, that was from memory. It prompted me to add necessary files and I said yes.

**Comment by DustinCampbell** [comment] 2017-02-07 16:49
Cool. Just wanted to check and make sure it didn't happen some other way. This is pretty easily solved.

**Comment by nguerrera** [comment] 2017-02-07 16:53
I've updated the steps.

**Comment by rchande** [comment] 2018-02-21 15:43
Thanks for finding the duplicate @akshita31 , I'll look for a fix (unless you want to :) )

**Comment by CoderJason123** [comment] 2018-02-22 18:21
so...on a mac, is this expected behavior, and the line for full paths only on a mac fixes the problem?  The issue i logged 2045 has been closed, i'm not real clear on the resolution or just that it's an on going issue.  please advise and thank you.

**Comment by DustinCampbell** [comment] 2018-02-28 14:06
@rchande: The right fix is to update the tasks.json generation to include `/p:GenerateFullPaths=true`.

**Comment by Xarkam** [comment] 2018-03-02 11:32
I my case, my build is done by a .bat file
Because we can not chain tasks in the launch.json file.
Using a build file, the error persists.

And yes I have the argument on the build line in my .bat file
dotnet build /property:GenerateFullPaths=true

I have to do this because I have to copy dll's for the application to work.

The day the launch.json file will execute tasks successively, then the workaround will work in my case.

**Comment by nguerrera** [comment] 2018-03-09 23:35
So it turns out that VS output window has the same problem (but you can use error list there) for .NET Core projects, but not classic projects. I could swear I checked that when I filed this bug, but @Pilchie doesn't think it's a regression. I am thinking maybe we should just change the default behavior for sdk-based projects to GenerateFullPaths=true.

**Comment by WhatFreshHellIsThis** [comment] 2018-06-05 15:08
I'm seeing this issue in the Problems window after a build.  Is that the same as this case?

**Comment by rchande** [comment] 2018-06-05 15:37
@WhatFreshHellIsThis Likely the same issue. Can you try setting the property as described in the first post of this issue?

**Comment by WhatFreshHellIsThis** [comment] 2018-06-05 15:50
@rchande Yes!  That fixed it, thank you.  For any future readers flailing around the setting referred to in the first post needs to go into a <PropertyGroup>

**Comment by jheffez** [comment] 2018-12-18 08:22
Having similar issue. Running python and step tracing with F11/F10. Running (F5) without the step trace works fine.
What is the fix? Where is the fix?

![image](https://user-images.githubusercontent.com/26058035/50140780-832f7000-02ae-11e9-9780-c81712a57174.png)

**Comment by rchande** [comment] 2018-12-18 16:03
@jheffez Since you're working with Python, I recommend filing an issue against [Python for VS Code](https://github.com/Microsoft/vscode-python). This is the repo for the C# extension.

**Comment by jheffez** [comment] 2019-01-07 11:07
The problem relates to using MS python language support. Since I disabled it I get much less of the errors above. Even better, the horrible VSCode memory leak is gone. 

MS python language server support needs a lot of work....

**Comment by DanJ210** [comment] 2019-06-19 15:31
I'm getting this very often as well. I can try the workaround, is there any downside to it?

Also, is this something I'll have to memorize and start adding to all projects from here on out? Or is this temporary because a solution is being worked on?

**Comment by morden2k** [comment] 2019-06-21 11:51
Any news about this issue? It is very uncomfortable go to file:line by manual file open with navigate to line instead double click to message (using vs code Explorer files opens without problems and it really exist).

How I see this issue exist on internet more than 2 years already (((

Error is the same: `Unable to open 'XXX.cs': File not found ("file://XXX.cs").`
Where `XXX`- is file name without extension.

If I click to Create then it will be created in root folder (`/XXX.cs`) instead file path defined in project (e.g. `/home/qqq/some_path/XXX.cs`).

```
VS Code version: 1.31.1
OS: Ubuntu 14.04, Ubuntu 18.04.2
```

**Comment by nguerrera** [comment] 2019-06-21 14:07
> How I see this issue exist on internet more than 2 years already

There's a trivial workaround in my original bug report. Did you try it?

**Comment by DanJ210** [comment] 2019-06-21 14:46
@nguerrera I guess I'm surprised that there's a workaround for this and not an actual fix yet. Which is what the user above meant by two years and no fix yet. Just a workaround.

**Comment by roa-nyx** [comment] 2019-06-21 14:51
> Set `<GenerateFullPaths>true</GenerateFullPaths>` in csproj.

For those of us who are not proficient with `.csproj` files, this means adding `<GenerateFullPaths>true</GenerateFullPaths>` in the the top-most `<PropertyGroup>` element.

**Comment by nguerrera** [comment] 2019-06-21 14:55
I'm not speaking for the maintainers, but sometimes things which are trivial to achieve with a tweak to a project are naturally lower priority. As the original reporter here, I understand that.

**Comment by WhatFreshHellIsThis** [comment] 2019-06-21 16:38
@nguerrera That's understandable from one very limited point of view certainly however keep in mind that from every single end users point of view who are trying the software for the first time they will all commonly see a major broken aspect of a very important and commonly used part of the UI and either stop using it, live with obviously broken functionality or be forced to go hunting for a resolution.    though the workaround is "trivial" that's ignoring the end user and not respecting their time.  This kind of bug should have a pretty high priority attached to it in the normal course of software development, maybe a priority only one level down from actually losing data so it's understandably inexplicable to anyone not involved in the decision making to see something this serious languish for so long.

**Comment by nguerrera** [comment] 2019-06-21 16:52
I filed this bug as an end user. It frustrated me too and took me a while to figure out. I do think it should be fixed. I too am disappointed it isn't, but also empathize with some things getting delayed by everything else going on.

I'm not a maintainer of this project and I don't speak for them, but "how can this not be fixed for [time period]" really bothers me in general. Developers on a project have many competing responsibilities, and I don't think it's fair to point at one issue that's not yet fixed and say that is disrespectful. Nobody is actively avoiding fixing things. It's just other things filling available time so far.

**Comment by nguerrera** [comment] 2019-06-21 16:56
Correction: I see that this was originally reported to me by a customer. I remembered wrong. Sorry for misrepresenting that.

**Comment by nguerrera** [comment] 2019-06-21 17:04
I think I'll make a change in the 3.0 sdk to make full paths the default. Historically, this was something VS handled but in a world of multiple IDEs, it seems reasonable to me now to pick the most qualified output by default.

**Comment by rchande** [comment] 2019-06-24 15:12
Thanks @nguerrera and all for the thoughtful discussion. We'll do our best to prioritize this.

**Comment by DanJ210** [comment] 2019-06-24 16:32
Gotta imagine too the amount of users who don't take the time to report feedback. They just use something else.

**Comment by rchande** [comment] 2019-06-24 17:05
@DanJ210 I'd also like to point out that this is open source software--you're more than welcome to create pull requests to address issues you feel aren't getting enough traction :).

**Comment by DanJ210** [comment] 2019-06-24 20:25
@rchande I hear you, I'm a huge Microsoft fan and VS Code fan. I support and I understand work is work. I'm not giving any flak for issues especially when I'm a dev myself. If I could help I would but I'm afraid I'm probably not advanced enough yet. Perhaps one day I will be able to. The VS Code team is also pushing out highly advanced features within updates quite often so an issue like this that could drive users away would be something I would think would be top of the backlog after a few months let alone a year.

But I mean no disrespect when I say any of the above. I love the product, I love using it, and I dealt with the issue all this time. I'm only reporting it now in hopes to get it some attention in case not many people are taking the time to report it. I would love for it to keep gaining the user base and love that it's been getting.

**Comment by akshita31** [comment] 2019-06-28 00:30
Another solution is to change the problemMatcher in the tasks.json to "$tsc". I noticed that if you generate the tasks.json using the "Required Assets to debug..." prompt when you first open the project, ths issue doesnt come up as the problem matcher is "$tsc" there.

**Comment by akshita31** [comment] 2019-06-28 01:10
The template that is being used here is shipped as part of vscode: https://github.com/microsoft/vscode/blob/35523f6c51bdc1edae1696a586dadd021fe47096/src/vs/workbench/contrib/tasks/common/taskTemplates.ts#L30. So probably the right change is to either:

1. Append /p:GenerateFullPaths=true in the "dotnet build" line in the template
2. Use the problem matcher as "$tsc"

Thoughts @rchande ?

**Comment by akshita31** [comment] 2019-06-28 22:29
Further analysis, the tsc problem matcher assumes that the file paths are relative and the mscompile problem matcher assumes that the paths are absolute. However mscompile is the correct "out-of-the-box" compiler for C#. Hence we should append the /p:GenerateFullPaths=true in the "dotnet build" line in the template and keep using the mscompile problem matcher. It is already done in the msbuild task so I will do it in the dotnet task also.

https://code.visualstudio.com/docs/editor/tasks#_processing-task-output-with-problem-matchers

**Comment by akshita31** [comment] 2019-06-28 22:46
https://github.com/microsoft/vscode/pull/76318. This is the PR in vscode with the change to the build templates.

**Comment by akshita31** [comment] 2019-06-28 22:50
However this makes me wonder if we should have the dotnet build templates only with the C# extension, however I dont know if that is completely possible.

**Comment by DanJ210** [comment] 2019-07-01 13:20
Cool, so does this mean that future projects generated with VS Code will have the `GenerateFullPaths=true` setting in them?

**Comment by akshita31** [comment] 2019-07-01 20:58
@DanJ210 A part of the problem is fixed. Now when the extension prompts you to add the assets for debugging, the tasks.json added will do the right thing. However the part where we use Ctrl+Shift+B and have some build tasks prompted, comes from vscode and I have created a PR to change that, however the earliest that can be available will be the July vscode release.

**Comment by akshita31** [comment] 2019-07-01 20:58
The extension release should be out in a few days though

**Comment by DanJ210** [comment] 2019-07-05 13:15
Thank you @akshita31 very informative. I appreciate the awesome product no doubt and July is no time at all.

**Comment by akshita31** [comment] 2019-08-02 19:43
This is fixed and merged in the extension and in vscode and should be available in the next releases.

**Closed by akshita31** 2019-08-02 19:43 UTC
Labels: Bug
