### ISSUE TITLE
Mac OS X :: Intellisense not working for method overrides

### ISSUE THREAD

**Issue by pcgeek86** [OmniSharp/omnisharp-vscode#1315] opened 2017-03-11 20:53 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

VS Code version: 1.10.2
C# Extension version: 1.7.0

## Steps to reproduce

Create a class, inherit a base class with virtual methods defined on it, and attempt to define the virtual method overrides from the base class.

## Expected  behavior

Visual Studio Code should automatically prompt the developer to insert virtual method overrides for base classes.

## Actual behavior

Nothing happens.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by DustinCampbell** [comment] 2017-03-13 14:42
Hi Trevor -- this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1044

**Closed by DustinCampbell** 2017-03-13 14:42 UTC
Labels: Resolved-Duplicate
