### ISSUE TITLE
Too much verbosity

### ISSUE THREAD

**Issue by pkese** [OmniSharp/omnisharp-vscode#5050] opened 2022-02-09 17:07 UTC
Each time I start VSCode, the output pane opens and reports

![image](https://user-images.githubusercontent.com/278492/153251957-ffc1a1e7-4354-44e5-8557-3bb6b24f0f70.png)

I'm not interested in any of that - it has zero information to me, I'm not even programming in C#.  
It makes me cursing C# each time while I'm closing the output pane window.

Make it go away, please.

**Comment by JoeRobich** [comment] 2022-02-09 18:33
@pkese Thanks for logging an issue. Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5032. Fixed in #5041

**Closed by JoeRobich** 2022-02-09 18:33 UTC
Labels: Resolved-Duplicate

**Comment by pkese** [comment] 2022-02-09 19:47
🙏
