### ISSUE TITLE
Syntax highlighting breaks when splitting null-conditional operator ?.

### ISSUE THREAD

**Issue by brunnerh** [OmniSharp/omnisharp-vscode#4504] opened 2021-04-19 09:23 UTC
## Issue Description ##

When putting whitespace between the `?` and `.` of the `?.` operator subsequent syntax highlighting is messed up.

## Steps to Reproduce ##

Add a space or line break between `?.`

## Expected Behavior ##

Syntax highlighting works as expected.

## Actual Behavior ##

Syntax highlighting is off.

![image](https://user-images.githubusercontent.com/834235/115213189-91515d80-a101-11eb-8e51-8fd704563706.png)

### OmniSharp log ###
<details>
Starting OmniSharp server at 4/19/2021, 11:04:20 AM
    Target: d:\brunnerh\temp\csharp-highlight-issue

OmniSharp server started.
    Path: c:\Users\hbrunner\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\OmniSharp.exe
    PID: 16376

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Enterprise 2019 16.2.29215.179 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
            2: StandAlone 16.9.0 - "c:\Users\hbrunner\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin"
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Visual Studio lower than VS 2019 16.3 installed.
 Try updating Visual Studio to the most recent release to enable better MSBuild support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\hbrunner\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.9.0 - "c:\Users\hbrunner\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\hbrunner\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\hbrunner\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild
            MSBuildToolsPath = c:\Users\hbrunner\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\brunnerh\temp\csharp-highlight-issue'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\brunnerh\temp\csharp-highlight-issue'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\brunnerh\temp\csharp-highlight-issue'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\brunnerh\temp\csharp-highlight-issue' on host 25104.
</details>

### C# log ###
[Empty]

## Environment information ##

**VSCode version**: 1.55.2
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.801
 Commit:    c404ee777a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.801\

Host (useful for support):
  Version: 2.1.27
  Commit:  37d16c2b4d

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.11|;

</details>

**Comment by JoeRobich** [comment] 2021-04-19 20:54
@brunnerh This is an issue in the C# textmate grammar (https://github.com/dotnet/csharp-tmLanguage). You can set `csharp.semanticHighlighting.enabled` to `true` in your settings to work around these issues.

**Comment by brunnerh** [comment] 2021-04-19 21:00
@JoeRobich Then it's a duplicate of this: https://github.com/dotnet/csharp-tmLanguage/issues/183

Should this be closed then?

**Comment by JoeRobich** [comment] 2021-04-19 21:19
Thanks for reporting. Closing this issue as a duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/183

**Closed** 2021-04-19 21:20 UTC
Labels: Editor-Syntax Highlighting, Resolved-Duplicate, Resolved-External
