### ISSUE TITLE
Auto generate comment block

### ISSUE THREAD

**Issue by leitwolf** [OmniSharp/omnisharp-vscode#1819] opened 2017-10-30 04:03 UTC
How to get this?
![aa](https://user-images.githubusercontent.com/1720546/32154224-324dd79c-bd6a-11e7-8d48-5255ce583b0e.gif)

**Comment by DustinCampbell** [comment] 2017-10-30 15:14
Hi, this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/8. Some are using the https://marketplace.visualstudio.com/items?itemName=k--kato.docomment extension to generate XML documentation comments.

**Closed by DustinCampbell** 2017-10-30 15:14 UTC
Labels: Resolved-Duplicate
