### ISSUE TITLE
Debugger: Function breakpoint cannot be hit

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#481] opened 2016-06-28 10:55 UTC
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 In breakpoints window of VSCode, click button to add a new function breakpoint
2 Input "HomeController" in that text pane
3 Press F5 to start debugging

## Expected  behavior
HomeController constructor should be hit

## Actual behavior
That function breakpoint cannot be hit

**Comment by gregg-miskelly** [comment] 2016-06-28 20:40
Duplicate of #295

**Closed by gregg-miskelly** 2016-06-28 20:40 UTC
