### ISSUE TITLE
ASP.NET Core auto import does not work

### ISSUE THREAD

**Issue by olfek** [OmniSharp/omnisharp-vscode#3304] opened 2019-09-29 11:33 UTC
With this code

```
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactManager.Pages
{
    [AllowAnonymous]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}
```

I typed `[AllowAnonymous]` but it did not auto import `Microsoft.AspNetCore.Authorization`.

Is this intentional or should this work?

**Comment by larryw3i** [comment] 2019-10-03 06:06
use "Ctrl+." to  trigger "import",  it doesn't work if your input method not in English(en)

**Comment by Gameghostify** [comment] 2019-10-09 17:19
Auto imports would be a great thing to have. Cycling through auto suggestions feels great (waiting and pressing `ctrl + .` in this case is not)

**Comment by Gameghostify** [comment] 2019-10-27 12:56
Any movement on this? What has to be done to make this work?

**Comment by cartermp** [comment] 2020-04-23 20:37
Closing as a duplicate of #3730

**Closed by cartermp** 2020-04-23 20:37 UTC
Labels: Bug
