### ISSUE TITLE
There are two similar data tips in VSCode

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#2006] opened 2018-02-05 06:53 UTC
## Environment data
`dotnet --info` output:
![dotnet--info](https://user-images.githubusercontent.com/20184778/35791520-6d85ff0e-0a83-11e8-8348-9e24330cae53.PNG)

VS Code version: v1.19.3
C# Extension version: v1.14.0-beta3

## Steps to reproduce

1. Create a dotnet core app
2. Open this app with VSCode
3. Insert an expression “int a=10;” in Program.cs
4. Move the mouse on variable a to show data tip

## Expected  behavior
Only one data tip should be displayed.
![except_datatip](https://user-images.githubusercontent.com/20184778/35791405-b5842822-0a82-11e8-8f07-93fb6d895bda.PNG)

## Actual behavior
The data tip is repeated as follow:
![datatip](https://user-images.githubusercontent.com/20184778/35791156-3cae4744-0a81-11e8-8410-60e50582a442.PNG)

**Comment by DustinCampbell** [comment] 2018-02-05 17:20
I don't believe these are debugger datatips at all. They are design-time error and warnings. I suspect this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1830.

**Comment by gregg-miskelly** [comment] 2018-02-05 21:07
@DustinCampbell should we dupe this? Or it is worth keeping around to verify they are the same issue?

**Comment by DustinCampbell** [comment] 2018-02-05 22:10
We can dupe it. The second screenshot is pretty clearly the same issue.

**Closed** 2018-02-05 22:23 UTC
Labels: Bug, Editor-Diagnostics, Resolved-Duplicate
