### ISSUE TITLE
IntelliSense - Display names of properties assignable by an object initializer in auto-completion list without needing editor.wordBasedSuggestions.

### ISSUE THREAD

**Issue by seraku24** [OmniSharp/omnisharp-vscode#656] opened 2016-08-12 07:49 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version: 1.4.0
C# Extension version: 1.3.0

## Steps to reproduce
1. Disable `editor.wordBasedSuggestions`.
2. Type the open curly brace that begins an object initializer.  (See the following code snippet.)
```csharp
class Person {
    public string FirstName;
    public string LastName;
}

static class Program {
    private static void Main() {
        var chemist = new Person { FirstName = "Walter", LastName = "White", };
    }
}
```
This issue occurs after typing `new Person {`.

## Expected behavior
The names of any assignable properties are shown in the auto-completion list.

## Actual behavior
No property names are included in the auto-completion list.

Like issue #652, the editor option `editor.wordBasedSuggestions` might show the property names only as a side effect.  The expectation is that IntelliSense recognizes an object initializer and displays the writable properties of the object, which matches the behavior seen in Visual Studio.

**Comment by ivanz** [comment] 2016-08-23 17:38
This is dupe of #260

**Closed** 2016-08-27 10:39 UTC
Labels: Feature Request, IntelliSense, Resolved-Duplicate
