### ISSUE TITLE
Debugger: Error processing lanuch options at filed: processId

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1279] opened 2017-03-03 08:06 UTC
## Environment data
`dotnet --info` output:
VS Code version: 1.10.1
C# Extension version: [\\scratch2\scratch\janraj\vsdbg3\csharp-1.8.0-beta1.vsix ](\\scratch2\scratch\janraj\vsdbg3\csharp-1.8.0-beta1.vsix )
.NET Core SDK: 1.0.0-preview2-1-003177
OS: Windows 10

## Steps to reproduce
1. Open attached folder.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/816117/hwapp.zip)
2. Select '.NET Core Attach'.
3. Set a breakpoint at line of 17 in Program.cs.
4. Use command to "dotnet run" process.
5. Press F5 to select process and start debugging.

## Expected  behavior
It can normal debug and hit  in 17 line.

## Actual behavior
![capture](https://cloud.githubusercontent.com/assets/20922638/23542881/79d75456-002a-11e7-94eb-c0693c625b0b.PNG)

## Investigation
1.This issue repro on all platforms.

**Comment by rajkumar42** [comment] 2017-03-03 17:42
Fix is to change the attach templates from 
"processId": "${command.pickProcess}" 
to
"processId": "${command:pickProcess}" 

Note, the change from dot to colon. Same goes for remote attach.

**Comment by gregg-miskelly** [comment] 2017-03-03 19:34
In that case this is related to https://github.com/OmniSharp/omnisharp-vscode/issues/1275.

I guess we could make an improved error message if we wanted.

**Comment by gregg-miskelly** [comment] 2017-03-03 19:39
We discussed it and we think that the squiggles you get from VS Code should be good enough for folks who have pre-existing launch.json files to understand the problem. So we are resolving this as 'By Design' for now.

**Closed** 2017-03-03 19:40 UTC
Labels: Debugger, Debugger-Poachable, Resolved-By Design
