### ISSUE TITLE
Error underlining red squiggles disappear

### ISSUE THREAD

**Issue by HawkenKing** [OmniSharp/omnisharp-vscode#941] opened 2016-11-15 17:00 UTC
## Environment data
`dotnet --info` output: 1.0.0-preview2-003121
VS Code version: Version 1.7.1 (1.7.1)
C# Extension version: 1.5.0

## Steps to reproduce

open any c# file and type

## Expected  behavior

red squiggles and error hint appear and stay

## Actual behavior

red squiggles and error hint appear and then disappear when moving cursor

![nored](https://cloud.githubusercontent.com/assets/5999766/20315230/76acfa1c-aba0-11e6-9b72-4c87a507c865.gif)

**Comment by DustinCampbell** [comment] 2016-11-15 18:37
Could you post your OmniSharp log for me? I'm wondering if the OmniSharp server is dying and restarting, which causes the errors to disappear.

1. Open Visual Studio Code and reproduce the problem.
2. Select View->Output to display the Output pane
3. At the top-right corner of the Output pane, select "OmniSharp Log" from the dropdown.
4. Copy and paste the content into this issue.

**Comment by HawkenKing** [comment] 2016-11-16 08:35
Hi @DustinCampbell hope this helps!

```
Starting OmniSharp server at 11/16/2016, 5:30:56 PM
    Target: /confidential/project.sln

OmniSharp server started wth Mono
    Path: /confidential/.vscode/extensions/ms-vscode.csharp-1.4.1/out/.omnisharp-mono/OmniSharp.exe
    PID: 73041

OmniSharp: -s /confidential/project.sln --hostPID 73011 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/confidential/project' on host 73011."},"Seq":1,"Type":"event"}
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /confidential/project
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/confidential/project.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/confidential/project.csproj'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/confidential/project/Assembly-CSharp-Editor.csproj'.
[WARNING:OmniSharp#ProjectFileInfo] The private field `Cloud.sre' is assigned but its value is never used
[WARNING:OmniSharp#ProjectFileInfo] The private field `Cloud.sre' is assigned but its value is never used
/confidential/project/Assembly-CSharp-Editor.csproj

[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/confidential/project'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Configuration finished.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 120ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 120ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 22ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 23ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 21ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 17ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 1039ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 11ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 32ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 200 2103ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 1016ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 21ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 2ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 4ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /signatureHelp: 200 10ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 183ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 4ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 407ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 200 83ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 6ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 8ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 30ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 26ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 6ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 48ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 7ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 137ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 27ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 7ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 15ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 1364ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
```

**Comment by DustinCampbell** [comment] 2016-11-16 17:22
Your log shows that you are using 1.4.1 of the C# extension, not 1.5.0 as mentioned at the top of this bug. Did you actually install the new release (now 1.5.2)? You should be able to do so from the Extensions pane in Visual Studio Code (select View->Extensions to display this pane).

**Comment by DustinCampbell** [comment] 2016-11-16 19:56
@HawkenKing: I've dug into this issue and found that it's likely due to a bug in VS Code. Details of my investigation are in #883. I've filed https://github.com/Microsoft/vscode/issues/15585 to track this issue on VS Code.

**Comment by DustinCampbell** [comment] 2016-11-17 16:04
A solid fix for this issue has been checked into VS Code. We should start seeing it working in VS Code Insiders builds soon.

**Closed by DustinCampbell** 2016-11-17 16:04 UTC
Labels: Bug, Resolved-External

**Comment by HawkenKing** [comment] 2016-11-21 11:19
@DustinCampbell just FYI I uninstalled everything related to VScode and started again from scratch. Probably a good idea since I've just been piling on updates since last year. Everything works fine now; intelisense, error underlining etc.

**Comment by DustinCampbell** [comment] 2016-11-21 15:54
Excellent!

**Comment by grandmasteri** [comment] 2020-01-23 01:23
I'm still getting this issue (for C++)...
It started after I downloaded the newest C++ extension.

**Comment by JoeRobich** [comment] 2020-01-23 01:27
Hi @grandmasteri, This repo is for the .NET C# VS Code extension. You can log issues with the C++ extension at https://github.com/Microsoft/vscode-cpptools
