### ISSUE TITLE
Fold All Regions feature doesn't work

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#2621] opened 2018-10-24 07:14 UTC
_From @suadev on October 18, 2018 8:42_

- VSCode Version: 1.28.2
- OS Version: Windows

"Fold All Regions" feature doesn't work neither by ctrl+k, ctrl+8 nor by F1 menu.

_Copied from original issue: Microsoft/vscode#61220_

**Comment by aeschli** [comment] 2018-10-24 07:14
_From @vscodebot[bot] on October 18, 2018 8:42_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [\[folding\] show folding actions at the end of folding range as well (#60670)](https://www.github.com/Microsoft/vscode/issues/60670) 
- [\[folding\] navigateToLastEditLocation doesn't expand folded regions (#59383)](https://www.github.com/Microsoft/vscode/issues/59383)

**Comment by aeschli** [comment] 2018-10-24 07:14
Please add a code sample. I tried with the folloing sample and it worked
foo.ts
```ts
//#region
Test
//#endregion
//#region
Test2
//#endregion
```
- ctrl + k / ctrl + 8: folds all regions
- ctrl + k / ctrl + 9: unfolds all regions

**Comment by aeschli** [comment] 2018-10-24 07:14
_From @suadev on October 23, 2018 10:43_

@aeschli sorry, i should have specified the language.

It looks,  it's ok for .ts file. 

But for .cs file, it doesn't work.

```
public class foo
{
    #region newregion
    int i = 0;
    #endregion
}

**Comment by aeschli** [comment] 2018-10-24 07:14
Do you use an extension for c# ?

Out of the box you get indentation based folding with region markers sand your example works the same way as my example.
But maybe an extension adds language specific folding and doesn't mark the regions correctly.

**Comment by aeschli** [comment] 2018-10-24 07:14
_From @suadev on October 23, 2018 14:14_

Yes, i use c# extension that powered by omnisharp.  My whole extension list; 

![image](https://user-images.githubusercontent.com/5918811/47366723-f372a880-d6e6-11e8-8f90-2ada70fe5605.png)

**Comment by aeschli** [comment] 2018-10-24 07:16
The problem is with the C# extension's foldingRangeProvider: Ranges originating from #region/#endregion need be marked with Kind: FoldingRangeKind.Region.

**Comment by akshita31** [comment] 2018-10-31 05:48
@suadev What are the keys you are using to fold the region. I tried the combination specified here https://code.visualstudio.com/docs/editor/codebasics#_folding and it seems to work fine for me. Note that in using ` Fold Level X (Ctrl+K Ctrl+2 for level 2) folds all regions of level X, except the region at the current cursor position` the region at the current cursor position will not be folded.

**Comment by suadev** [comment] 2018-10-31 05:54
@akshita31  as i said in my first post;

"Fold All Regions" feature doesn't work neither by ctrl+k, ctrl+8 nor by F1 menu.

**Comment by akshita31** [comment] 2018-10-31 06:06
@suadev As per the vscode documentation here : https://code.visualstudio.com/docs/editor/codebasics#_folding, "Fold All" is Ctrl K+ Ctrl 0 and that seems to work fine for me. Can you try that once ?

**Comment by akshita31** [comment] 2018-10-31 06:08
However I do agree that Fold All regions through F1 doesnt work here.

**Comment by akshita31** [comment] 2018-10-31 07:42
@suadev Apologies I got a bit confused here. I am totally able to reproduce the problem.

**Comment by akshita31** [comment] 2018-10-31 07:51
On further investigation, I realised that we are using the "BlockStructureService" from roslyn to provide the spans for CodeFolding. The "BlockType" defined in roslyn doesn't have an explicit type for a "Region" - http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Structure/BlockTypes.cs,863b31bd5e041d18. For regions it returns the base type called "NonStructural". 

In omnisharp-roslyn, we are comparing the type and checking if the type == "Region" which is not returned by roslyn as of now, hence we return the null type to the extension and the given region is not marked as a "Region"

**Comment by zeroskyx** [comment] 2018-11-05 18:28
Same issue here -- folding works flawlessly for languages such as JS but fails for CS.

Keep up the great work =)

**Comment by zeroskyx** [comment] 2018-12-08 08:56
Any news on the issue?

**Comment by zeroskyx** [comment] 2019-04-08 11:10
@akshita31: anything we can do to help with the issue?

**Comment by zeroskyx** [comment] 2019-05-21 17:09
@rchande: anything I can do to help you with the issue? Would be really great to have this working again :) Thanks in advance!

**Comment by rchande** [comment] 2019-05-22 22:09
@zeroskyx The issue is that OmniSharp isn't properly marking "region" folding units as having the "region" kind. Thus, when you issue the command in VS Code, the C# extension doesn't think it has any regions to fold.

**Comment by zeroskyx** [comment] 2019-06-12 18:30
@rchande: thank you for the clarification -- what would be the steps to fix the issue? It would be really great to have it working again with .NET Core 3 coming up :)

Keep up the great work!

**Comment by zeroskyx** [comment] 2020-03-25 16:33
Have you given up on this issue? With region support in almost every language now (even Bash) it's sad to see that this feature only does not work in C# 😕

**Closed** 2020-03-27 18:49 UTC
Labels: Bug

**Comment by JoeRobich** [comment] 2020-04-13 23:55
This issue is fixed in 1.21.17

**Comment by suadev** [comment] 2020-04-14 05:52
@JoeRobich  it doesn't work. Between, when i start vscode, i see this exception;

System.InvalidCastException: Specified cast is not valid.
   at Roslyn.Utilities.EventMap.GetRegistries_NoLock[TEventHandler](String eventName)
   at Roslyn.Utilities.EventMap.AddEventHandler[TEventHandler](String eventName, TEventHandler eventHandler)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExports(Type exportType, String contractName)
   at System.Composition.CompositionContext.GetExports[TExport](String contractName)
   at OmniSharp.Stdio.Host.Initialize() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 57
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 51
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 66
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 29

**Comment by suadev** [comment] 2020-04-14 05:57
It seems, OmniSharp doesn't start properly on my machine.  The exception is added on above. Any idea? @aeschli  @filipw

**Comment by filipw** [comment] 2020-04-14 06:25
do you have a repro project?
also, can you post full Omnisharp log?

**Comment by suadev** [comment] 2020-04-14 06:34
@filipw i am working on a dotnet  core 3.1 web api project. Tried on aother project and got same exception. The whole log:

Starting OmniSharp server at 4/14/2020, 9:31:30 AM
    Target: c:\source\Pms.Backend\PMS.sln

OmniSharp server started.
    Path: C:\Users\skose\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.34.5-beta.28\OmniSharp.exe
    PID: 15168

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Enterprise 2019 16.4.29806.167 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
            2: StandAlone 16.0 - "C:\Users\skose\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.34.5-beta.28\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.4.29806.167 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
System.InvalidCastException: Specified cast is not valid.
   at Roslyn.Utilities.EventMap.GetRegistries_NoLock[TEventHandler](String eventName)
   at Roslyn.Utilities.EventMap.AddEventHandler[TEventHandler](String eventName, TEventHandler eventHandler)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExports(Type exportType, String contractName)
   at System.Composition.CompositionContext.GetExports[TExport](String contractName)
   at OmniSharp.Stdio.Host.Initialize() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 57
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 51
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 66
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 29

**Comment by filipw** [comment] 2020-04-14 06:42
according to your log, you are on the old version of omnisharp
`Path: C:\Users\skose.vscode\extensions\ms-dotnettools.csharp-1.21.17.omnisharp\1.34.5-beta.28\OmniSharp.exe`

it should be 1.35.0.

check if you have any `omnisharp.path` setting in VS Code config and if you do, remove it. 
Then try removing the extension and installing it again.

**Comment by suadev** [comment] 2020-04-14 07:01
@filipw  done :)  Thank you !
