### ISSUE TITLE
Cannot find sdk

### ISSUE THREAD

**Issue by cushmatt** [OmniSharp/omnisharp-vscode#3226] opened 2019-08-14 05:51 UTC
## Issue Description ##
I feel like I'm making progress here.  I know I'm not on a supported version of Linux (Manjaro - Arch Linux) but I was originally getting the error saying that it couldn't load the project at all.  Now it is loading the project successfully and I'm getting red squigglies everywhere!  Never been so happy to see those.  However it seems like it can't find my sdk.  
I have checked and my SDKs are located at:
`/opt/dotnet/sdk/`

This is from a default template build using command:
`dotnet new mvc -o test`

Is there anyway that I can point Omnisharp in the right direction here or am I royally screwed?
I **truly** appreciate any help and will give my best to be helpful in debugging this.

Thank you!
## Steps to Reproduce ##
I originally installed from AUR:
`visual-studio-code-bin` (I believe so at least, I do not think I installed from official repo)
`msbuild-stable`

From official repo:
`dotnet-sdk`
`dotnet-runtime`

This was not working so I tried reinstalling mono by itself from official repo:
`mono`

This did not work, I then installed the preview from aur as this was what I wanted anyways:
`dotnet-sdk-preview`

No improvement, so I then went and found a more recent version of msbuild on aur called just:
`msbuild`

This is when the project file was able to finally be loaded successfully and now I'm stuck with 107 errors from Omnisharp as it cannot find the sdk

## Expected Behavior ##
Omnisharp to find sdk

## Actual Behavior ##
Omnisharp cannot locate sdk

### OmniSharp log ###
<details>
Starting OmniSharp server at 8/13/2019, 11:29:11 PM
    Target: /home/cush/Repo/dotnet_core/test

OmniSharp server started with Mono 5.20.1.
    Path: /home/cush/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/OmniSharp.exe
    PID: 10265

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on manjaro 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.0 - "/home/cush/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/cush/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/cush/Repo/dotnet_core/test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/cush/Repo/dotnet_core/test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cush/Repo/dotnet_core/test/test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/cush/Repo/dotnet_core/test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/cush/Repo/dotnet_core/test' on host 10057.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cush/Repo/dotnet_core/test/test.csproj
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cush/Repo/dotnet_core/test/test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cush/Repo/dotnet_core/test/test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: test
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        test: Did not find 'Microsoft.NETCore.App' in lock file.
</details>

### C# log ###
<details>Post the output from Output-->No logs from C#</details>

## Environment information ##

**VSCode version**: 1.37.0
**C# Extension**: 1.21.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.20.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/3.0.100-preview7-012821/

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.2.108 [/opt/dotnet/sdk]
  3.0.100-preview7-012821 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|agila-theme|whtsky|2.0.2|
|aspnet-helper|schneiderpat|0.6.4|
|auto-rename-tag|formulahendry|0.1.0|
|ayu|teabyii|0.18.0|
|BecauseTogetherNiketa|selfrefactor|0.4.4|
|better-comments|aaron-bond|2.0.5|
|Bookmarks|alefragnani|10.5.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|c-cpp-compile-run|danielpinto8zz6|0.5.0|
|clang-format|xaver|1.9.0|
|code-runner|formulahendry|0.9.12|
|code-settings-sync|Shan|3.4.1|
|code-spell-checker|streetsidesoftware|1.7.17|
|color-highlight|naumovs|2.3.0|
|cpptools|ms-vscode|0.24.1|
|csharp|ms-vscode|1.21.0|
|csharpextensions|jchannon|1.3.0|
|csharpfixformat|Leopotam|0.0.83|
|debugger-for-chrome|msjsdiag|4.11.7|
|docomment|k--kato|0.1.8|
|es7-react-js-snippets|dsznajder|2.4.0|
|extended-cursormove|BillStewart|0.0.2|
|feather|dericcain|0.5.0|
|gitignore|codezombiech|0.6.0|
|gitkraken-glo|axosoft|1.1.0|
|gitlens|eamodio|9.9.3|
|js-quick-console|AhadCove|0.0.3|
|LiveServer|ritwickdey|5.6.1|
|lorem-ipsum|Tyriar|1.2.0|
|material-icon-theme|PKief|3.8.1|
|material-palenight-theme|whizkydee|1.9.5|
|msbuild-project-tools|tintoy|0.2.55|
|mssql|ms-mssql|1.6.0|
|netcore-snippets|doggy8088|0.2.4|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|pip-packages|etmoffat|0.4.3|
|polacode|pnp|0.3.2|
|popping-and-locking-vscode|hedinne|2.0.4|
|prettier-vscode|esbenp|1.9.0|
|python|ms-python|2019.8.30787|
|quick-open|leizongmin|1.1.0|
|razor-plus|austincummings|0.1.4|
|reg|ionutvmi|1.0.1|
|shell-launcher|Tyriar|0.3.0|
|simple-react-snippets|burkeholland|1.2.2|
|solarized-dark-operator-theme|Chad|1.0.1|
|spaces-inside-braces|AiryShift|0.4.0|
|supersharp|craigthomas|0.1.4|
|TabOut|albert|0.1.6|
|theme-cobalt2|wesbos|2.1.6|
|vim|vscodevim|1.9.0|
|vsc-material-theme|Equinusocio|30.0.0|
|vscode-autohotkey-plus|cweijan|2.0.1|
|vscode-csharp-snippets|jorgeserrano|0.3.1|
|vscode-custom-css|be5invis|3.0.4|
|vscode-eslint|dbaeumer|1.9.0|
|vscode-icons|vscode-icons-team|9.2.0|
|vscode-language-babel|mgmcdermott|0.0.23|
|vscode-npm-script|eg2|0.3.8|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscode-versionlens|pflannery|0.24.0|
|vsliveshare|ms-vsliveshare|1.0.694|
|vsliveshare-audio|ms-vsliveshare|0.1.64|;

</details>

**Comment by YamiYukiSenpai** [comment] 2019-08-20 19:21
Also experiencing the same on Ubuntu.  I installed `dotnet-sdk` from the Snap store.

**Comment by balazs4** [comment] 2019-08-23 14:37
This workaround might to resolve this issue as well...https://github.com/OmniSharp/omnisharp-vscode/issues/2970#issuecomment-524292461

**Comment by cartermp** [comment] 2020-06-02 23:55
Unfortunately there isn't the best handling of finding SDKs in the plugin. I'll close this out as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3541 which is being used to aggregate all the issues

**Closed by cartermp** 2020-06-02 23:55 UTC
