### ISSUE TITLE
Debugger:[Remote]It takes long time to break all after launching a program with infinite loop.

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#1308] opened 2017-03-10 09:43 UTC
## Environment data
`dotnet --info` output:
Server Machine:
OS: linuxmint17
VS Code version: 1.10.2
C# Extension version: 1.0.1
VSDBG: https://aka.ms/getvsdbgsh
Machine Name: [VSDIAGPHONE02](http://maddog/goto/MDGoto.Application?md://OrcasTS/Machine/1665154)
Ip Address: 10.194.115.67

Client Machine:
OS: win10 x64
VS: vsucorediag (26309.00)

## Steps to reproduce
1. Open Program.cs in VS2017.

2. Configuration lanuch.xml file as following.
<?xml version="1.0" encoding="utf-8" ?>
	<PipeLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
	  PipePath="D:\putty\plink.exe" PipeArguments="-i D:\putty\putty_key.ppk claire@10.194.114.12 -batch -t /home/claire/latest/vsdbg --interpreter=mi"
	  TargetArchitecture="x64" MIMode="vsdbg" ExePath="dotnet" WorkingDirectory="/home/claire/Documents/hwapp" ExeArguments="/home/claire/Documents/hwapp/bin/Debug/netcoreapp1.1/hwapp.dll">
	</PipeLaunchOptions>
3. Open Command Window(View->OtherWindows->Command Window).
4. Launch Process:
 Debug.MIDebugLaunch /Executable:dotnet /OptionsFile:D:\launch.xml
5. 'Break All'

## Expected  behavior
Cursor hit the loop as soon as possible.

## Actual behavior
Cursor hit the loop need about 10-15 seconds.

## Investigation
1. I tried to do the 'Break All' operation on attach, this issue didn't reproduce.
2. After step #4, set a bp at the line of 12 in Program.cs, also take more time to hit the bp.

**Comment by rajkumar42** [comment] 2017-03-10 18:50
Please stop using tight loops. Resolving this by design.

**Closed by rajkumar42** 2017-03-10 18:50 UTC
