### ISSUE TITLE
Unable to breakpoint and debug cshtml

### ISSUE THREAD

**Issue by jimmy3912msncom** [OmniSharp/omnisharp-vscode#1828] opened 2017-10-31 17:39 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
VS Code version: 1.17.2
C# Extension version: 1.12.1

## Steps to reproduce
1. Create a vanilla mvc project using "dotnet new mvc --auth None"
2. Start debugging the application from Visual Studio Code
3. Attempt to breakpoint in cshtml but fails to set with "No symbols have been loaded for this document." cs file debugging works though

## Expected  behavior
Debugging should work from cshtml

## Actual behavior
The set breakpoint is greyed out and hovering over it gives: "No symbols have been loaded for this document." When it hits the code path, the breakpoint doesn't get hit in the cshtml file.

**Comment by gregg-miskelly** [comment] 2017-10-31 17:48
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1816

**Closed by gregg-miskelly** 2017-10-31 17:48 UTC
Labels: Resolved-Duplicate
