### ISSUE TITLE
Improve Razor template intellisense

### ISSUE THREAD

**Issue by idarous** [OmniSharp/omnisharp-vscode#1443] opened 2017-04-30 20:09 UTC
Hello,

I use both vscode and visual studio 2015/2017 for creating asp.net code project.

With visual studio 2015+ the razor template intellisense is great.
You have
- autocompletion for c# code and html tag helper
- error detections
- autocompletion for variable when a viewmodel is used.

Is it possible to have their features on visual studio code ?

**Comment by DustinCampbell** [comment] 2017-05-01 17:19
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/168.

**Closed by DustinCampbell** 2017-05-01 17:19 UTC
Labels: Resolved-Duplicate
