### ISSUE TITLE
Quick fix: Rename file with {classname}.cs duplicates original file, if not save changes

### ISSUE THREAD

**Issue by seongwon-kang** [OmniSharp/omnisharp-vscode#3595] opened 2020-02-21 01:25 UTC
## Issue Description ##
![20-16-21 10 16 09](https://user-images.githubusercontent.com/56567660/74995141-5b7bff00-5493-11ea-8f12-8a0f8b1825f5.gif)

See original UnitTest1.cs is deleted first(114-115 frame), and recreates.
if this is intented to not apply original file's change immediately, original file must not deleted first.
if save original file and try, this will not be occured.
## Steps to Reproduce ##
1. create new csproj `dotnet new nunit`
2. create an arbitrary folder
3. copy `UnitTest1.cs` (auto-created) to folder
4. rename copied class 
5. open `Quick Fix`, and select `Rename file with {classname}` (I don't know it's original name)

### OmniSharp log ###
(no log available)

### C# log ###
(no log available)
## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.11

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autodocstring|njpwerner|0.4.0|
|cloudcode|googlecloudtools|1.1.2|
|csharp|ms-vscode|1.21.11|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.8|
|dotnet-test-explorer|formulahendry|0.7.1|
|ftp-simple|humy2833|0.7.5|
|increment-selection|albymor|0.2.0|
|java|redhat|0.57.0|
|jenkinsfile-support|ivory-lab|0.4.4|
|python|ms-python|2020.2.63990|
|remote-wsl|ms-vscode-remote|0.42.3|
|testfile-generator-for-junit|marcoLee|0.0.7|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-snippets|YclepticStudios|0.1.2|
|vsc-mybatis|niko|1.2.0|
|vsc-travis-ci-status|felixrieseberg|1.1.0|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-java-debug|vscjava|0.25.0|
|vscode-java-dependency|vscjava|0.9.0|
|vscode-java-pack|vscjava|0.8.1|
|vscode-java-test|vscjava|0.22.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.9|
|vscode-lombok|GabrielBB|1.0.1|
|vscode-maven|vscjava|0.21.0|
|vscode-openapi|42Crunch|2.1.0|
|vscode-position|jtr|1.0.1|
|vscode-postman|eridem|1.0.2|
|vscode-yaml|redhat|0.7.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.5|
|white|arthurwhite|1.3.6|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by ryzngard** [comment] 2020-02-21 01:40
This looks like a race condition between file rename on the omnisharp server and VS Code save logic. Good find!

**Comment by cartermp** [comment] 2020-03-12 20:49
closing as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3616

**Closed by cartermp** 2020-03-12 20:49 UTC
Labels: Resolved-Duplicate, Triaged
