### ISSUE TITLE
Autocomplete often incorrectly replaces typed text

### ISSUE THREAD

**Issue by rayrSC** [OmniSharp/omnisharp-vscode#2472] opened 2018-08-23 15:17 UTC
Original issue reported here: https://github.com/Microsoft/vscode/issues/57037
I was asked to refer this issue to the C# extension project instead.

Often, while typing in the editor, when I press space after a word, the editor will replace the perfectly valid code with something invalid.  I am currently working in C#, and have this happen frequently with several keywords.  Today, I tried the Insiders build as well, but still run into the issue.  I have also attached a video of the problem happening.

Some examples:
- `new` becomes `nameof`
- `private` becomes `partial`
- `return` becomes `ref`

[bad-autocomplete.zip](https://github.com/Microsoft/vscode/files/2311514/bad-autocomplete.zip)

## Environment data
<details>
<summary>`dotnet --info` output:</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
</details>

VS Code version: 1.26.1 and 1.27.0-insiders
C# Extension version: 1.15.2

## Steps to reproduce
Type an entire name/keyword, verbatim, in the editor and press the spacebar.  It does not always happen, but happens enough to be extremely frustrating and to severely impact my productivity.

## Expected  behavior
Typed name or keyword matches the top entry in the suggestion list and should not be changed.

## Actual behavior
Typed name or keyword changes to an unrelated, and often semantically invalid, name or keyword.

**Comment by DustinCampbell** [comment] 2018-08-23 18:42
That is definitely strange behavior! Is the correct word selected in the completion list when you press SPACE? cc @rchande / @akshita31

**Comment by rayrSC** [comment] 2018-08-23 19:50
Yes.  At the very beginning of type (in the example video, after typing `p`), it suggests `partial`, but as soon as I press `r` and for every character afterwards, the top, highlighted suggestion is `private` in the completion list.  It acts almost as though the visual list has been updated but the one it uses after pressing the completion key has not.

**Comment by rchande** [comment] 2018-08-27 22:54
@rayrSC That's extremely strange! I haven't been able to reproduce this on a relatively recent insider's build. Would you mind updating and see if you still see the issue?
``` 
Version: 1.27.0-insider
Commit: 07618102efdd63f09949ce54c161e7fd2a954ee8
Date: 2018-08-23T05:20:35.051Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by dansoper** [comment] 2018-08-29 15:56
Same here, with 
VS Code version: 1.26.1
C# Extension version: 1.15.2

Very quickly installed Insiders and doesn't seem to be happening there, but will keep trying and report back if it does happen.

**Comment by DustinCampbell** [comment] 2018-08-30 08:14
Is it possible that another extension installed into 1.26.1 is interfering and causing the issue?

**Comment by DustinCampbell** [comment] 2018-08-30 15:31
It might be worth installing them 1 at a time into Insiders to see if one of them is the culprit. Additionally, you might try uninstalling and reinstalling C# in 1.26.1 and see if the problem persists. It's definitely not normal behavior.

**Comment by rayrSC** [comment] 2018-08-30 15:57
I had to work on something else for a few days, so I didn't have a chance to do any further testing on this until now.  I have yet to experience the problem with the latest Insiders build, but that's not really direct evidence of anything.  The issue seemed to happen more frequently when I was focused and typing quickly, which is unfortunately since it would often disrupt that focus.

As far as extensions go, I have the following on both 1.26.1 and 1.27.0-insiders:
- C# 1.15.2
- Debugger for Unity 1.3.0

**Comment by SirIntruder** [comment] 2018-08-30 16:55
It happens to me frequently, but never when I try to replicate it... I also noticed it always happen when I am typing really fast. I will try to work with insiders and report if I find it there

**Comment by thesmallbang** [comment] 2018-10-03 08:15
This happens to me multiple times a day and is a real flow interruption. Normally for me it occurs with new and nameof. 

Visual studio appears to fix this issue is by checking if the current text that would apply to intellisense no longer matches the intellisense ui default selected item it just adds a space normally (unless you actually manually select an item).

**Comment by geniikw** [comment] 2018-10-19 03:52
this bug makes me annoying. 
![bug](https://user-images.githubusercontent.com/7575458/47196806-71f4e080-d39d-11e8-9b6a-a6c1684e275b.gif)

**Comment by rchande** [comment] 2018-10-23 16:28
@jrieken Is this a behavior change in VS Code? We haven't made any changes to how we provide completion and I don't believe the API even gives us this level of control...

**Comment by jrieken** [comment] 2018-10-24 07:28
Hm... Looks like a filtering/timing issue... Do you guys use commit characters? Would space be one here? It might be that we work on the `n` prefix and haven't "seen" the `ne` yet. Your provider implements the `resolveCompletionItem` function, right? What version is this? We recently fixed for 1.29-insider in that area...

**Comment by rchande** [comment] 2018-10-24 16:08
We had an internal report of this on 1.29. I'm not sure what version @geniikw is on. We do use space as a commit character (https://github.com/OmniSharp/omnisharp-vscode/blob/9acb7494ed847b3cbd244b265a6923e0eb7b8ba5/src/features/completionItemProvider.ts#L17) but we don't implement `ResolveCompletionItem`.

**Comment by geniikw** [comment] 2018-10-25 00:41
above is on 1.28.
and on 1.29 insider 
Despite turned on [acceptSuggestionOnCommitCharacter] option, Space do not work as commit character. So I can't check above situation at 1.29.

**Comment by jrieken** [comment] 2018-10-25 09:29
@geniikw can you check when value this setting has for you: `editor.suggestSelection`?

**Comment by geniikw** [comment] 2018-10-25 10:28
@jrieken  both were recentlyUsed(1.28, 1.29)

**Comment by jrieken** [comment] 2018-10-25 11:40
@geniikw and what is the exact sequence of events in 
https://github.com/OmniSharp/omnisharp-vscode/issues/2472#issuecomment-431236867. 

* type `n`
* type `e`
* type what❓ did you press space? or tab, enter?

**Comment by geniikw** [comment] 2018-10-25 12:01
@jrieken 
that was "new "
I tried to reproduce the same thing at home, but I can not reproduce it at 1.28.2. (It works fine.)

It seems that I misunderstood the version due to something wrong. When I tried it in the company, it was obviously changed to "nameof " if I wrote "new " quickly.
Anyway, it's okay now. Sorry for miss report.

**Comment by jrieken** [comment] 2018-10-25 13:45
This might be a dupe of https://github.com/Microsoft/vscode/issues/60753. Please try with latest insider for which we have fixed this: https://code.visualstudio.com/insiders/

**Comment by dansoper** [comment] 2018-11-01 09:45
This problem hasn't happened for me now for a while, so I think it has been resolved.  I'm on VS Code 1.28.2.

**Comment by nickstenning** [comment] 2018-11-02 19:55
For what it's worth, this is happening for me (`new`/`nameof` is the one that catches me most frequently) on 1.28.2.

I can reliably make it happen by typing fast and typing either `[n, e, <space>]` or `[n, e, w, <space>]`. Typing fast is crucial. It never happens if I am typing slowly.

<details>
<summary>Full version info</summary>
```
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
</details>

**Comment by nickstenning** [comment] 2018-11-02 20:05
And I'm afraid I can also reproduce with the latest Insiders build (1.29.0), with only the C# extension installed (at version 1.17.0).

<details>
<summary>Full version info</summary>
<pre><code>Version: 1.29.0-insider (user setup)
Commit: 9b2a7f4a83ca6a2d495463276a21157f398b41e7
Date: 2018-11-02T13:42:21.142Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64</code></pre>
</details>

**Comment by jrieken** [comment] 2018-11-05 08:54
Thanks @nickstenning. I will keep digging...

**Comment by HardcodedNumber** [comment] 2019-03-16 00:53
I am on v1.32.2 with Unity 2018.3.x and C#. For int32, I get iPhoneSettings. It's really annoying.

**Comment by rchande** [comment] 2019-03-18 18:12
@jrieken Did you make any progress here?

**Comment by jrieken** [comment] 2019-03-19 10:35
no, we weren't able to reproduce...

**Comment by HardcodedNumber** [comment] 2019-03-24 21:34
You can close this, I think its with VS itself.

**Comment by kettle11** [comment] 2019-05-09 03:10
I wanted to chime in this has been occuring for me for a long time (not sure on the exact time frame) with Unity / VS Code. It occurs when I type "int" followed by spacebar and it completes to "iPhoneSettings". I'm using Visual Studio Code on OSX. It is a major productivity drain for me.

Also, the Visual Studio Code issue @HardcodedNumber referenced is closed with the reason given that it's an extension issue, not a VS Code issue.

**Comment by naknode** [comment] 2019-07-03 00:52
This seems to be occurring for me too.

![image](https://user-images.githubusercontent.com/616320/60555505-d9bc4300-9d02-11e9-8ad2-638196e6fc4b.png)

**Comment by christianscheuer** [comment] 2019-07-07 22:44
This also happens to me many times daily. 50% of the time I type for example `return new ` the `new` gets converted to `nameof`.
From the comment here https://github.com/microsoft/vscode/issues/60753#issuecomment-430190566 it seems like the issue could be a missed "cancel" call on the async suggest handler?
It appears what happens is:
- I start typing "n"
- The suggest system reacts to the "n" event but is slow to respond
- A cancel on that request gets sent since I typed another char "e", but it gets overlooked
- I type "w" and that also gets overlooked
- Now the suggest system responds with "nameof" since it sees that as the item to use:
![image](https://user-images.githubusercontent.com/4005316/60774746-40819800-a119-11e9-83dd-6ba623ec4545.png)
- I type " " (space) and now the "nameof" gets selected/committed, since the suggest system newer reacted to the cancel events.

Note this is just my analysis of what goes on, I have no real idea of how the code is structured.

Wrt repro, it appears this primarily happens with large repros. I think the way to test it would be to simulate slow responses by adding some `Thread.Sleep(...)`.

**Closed** 2019-07-12 21:05 UTC
Labels: Editor-IntelliSense, Needs More Info

**Comment by silicakes** [comment] 2019-07-17 14:03
Started happening to me following the recent update:

OS: macOS Mojave (10.14.5)
VSCode version: 1.36.1
language within editor: Javascript

![flaky_autocomplete](https://user-images.githubusercontent.com/1759539/61381498-8826c300-a881-11e9-9db1-c62833ce2e6e.gif)

It seems like the autocompletion is selected by default and pressing the semicolon key triggers it.

**Comment by jordangrant** [comment] 2019-08-15 02:24
[React.js & React Native] `this.props.item` becomes `this.tsPropertySignature.isTemplateElement;` LOL.
Restarting VSCode also solves it for me. VSCode Version: 1.37.0

**Comment by rchande** [comment] 2019-08-15 21:09
@silicakes This is the repository for the C# extension--we can't help with Javascript issues. For JS, I recommend filing an issue directly against VS Code because JS support is built into VS Code.

**Comment by rodrigoea** [comment] 2023-08-23 17:19
This was happening to me, I disabled the `auto-import` extension and it worked. 

<img width="413" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/1905961/3c0b1a2b-61af-470d-8605-8913da9bb251">

https://github.com/dotnet/vscode-csharp/assets/1905961/7b2529d1-2f99-4e34-8036-664275036090

**Comment by uberubert** [comment] 2025-03-29 11:06
I'm experiencing `new` becoming `nameof`. Since it doesn't happen every time, and mostly when I don't expect it, I'm not sure how to debug or reproduce it.

Should this issue still be "closed as completed"?

**Comment by dibarbet** [comment] 2025-03-31 17:17
> I'm experiencing new becoming nameof. Since it doesn't happen every time, and mostly when I don't expect it, I'm not sure how to debug or reproduce it.

If you can manage to capture a gif or video of it, please file a new issue.
