### ISSUE TITLE
C# Extension is entirely unresponsive

### ISSUE THREAD

**Issue by MartinHaeusler** [OmniSharp/omnisharp-vscode#3673] opened 2020-03-16 19:11 UTC
## Issue Description ##
The C# extension suddenly stopped working for me. Syntax highlighting is okay, but everything else loads indefinitely:
 - Code Completion
 - Formatting
 - Outline
 - ...

All the while, it is consuming 100% CPU resources on one of my cores. I even tried a full fresh install of everything, that didn't help.

## Logs ##
[exthost-c2991c.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4339926/exthost-c2991c.cpuprofile.txt)

[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4339933/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

### OmniSharp log ###

<details><summary>OmniSharp Log</summary>

Starting OmniSharp server at 16.3.2020, 20:07:45
    Target: d:\git\HoBC\Unity\HoBC\HoBC.sln

OmniSharp server started.
    Path: C:\Users\Martin\.vscode\extensions\ms-dotnettools.csharp-1.21.14\.omnisharp\1.34.14\OmniSharp.exe
    PID: 4360

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.5.29911.84 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "c:\Users\Martin\.vscode\extensions\ms-dotnettools.csharp-1.21.14\.omnisharp\1.34.14\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.5.29911.84 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\git\HoBC\Unity\HoBC'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\git\HoBC\Unity\HoBC\HoBC.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\git\HoBC\Unity\HoBC'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\git\HoBC\Unity\HoBC\Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\git\HoBC\Unity\HoBC' on host 14832.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-firstpass.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\git\HoBC\Unity\HoBC\Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor-firstpass.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\git\HoBC\Unity\HoBC\Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-firstpass
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'd:\git\HoBC\Unity\HoBC\Temp\bin\Debug\Assembly-CSharp-firstpass.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'd:\git\HoBC\Unity\HoBC\Temp\bin\Debug\Assembly-CSharp-Editor-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'd:\git\HoBC\Unity\HoBC\Temp\bin\Debug\Assembly-CSharp-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'd:\git\HoBC\Unity\HoBC\Temp\bin\Debug\Assembly-CSharp.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor-firstpass
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'd:\git\HoBC\Unity\HoBC\Temp\bin\Debug\Assembly-CSharp-firstpass.dll'
</details>

### C# log ###
Nothing to paste here; the log is empty.

## Environment information ##

**VSCode version**: 1.43.0
**C# Extension**: 1.21.14

<details><summary>Dotnet Information</summary>
.NET Core SDK (gem�� "global.json"):
 Version:   3.1.200
 Commit:    c5123d973b

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.14|
|unity-debug|Unity|2.7.4|
|vscode-eclipse-keybindings|alphabotsec|0.10.0|
|vscode-icons|vscode-icons-team|10.0.0|;

</details>

**Comment by JoeRobich** [comment] 2020-03-16 20:39
@MartinHaeusler Would it be possible for you to give us access to your project? We've had lots of similar reports but have had trouble getting this issue to reproduce.

**Comment by MartinHaeusler** [comment] 2020-03-16 21:12
@JoeRobich It's a Unity project which is several gigabytes in size - the upload alone would take days with my connection. I can try to extract the code files and strip all art assets, this would bring it down to a more reasonable size, but it should still compile. Would that help?

**Comment by JoeRobich** [comment] 2020-03-16 21:22
@MartinHaeusler Please, just the projects and code would be very helpful.

**Comment by MartinHaeusler** [comment] 2020-03-17 10:31
@JoeRobich here's the project, stripped of all art assets. It's still 33MB because it contains the assemblies and DLLs that come with Unity, so I can't upload it directly as a github attachment. Here's a link to my dropbox instead:

https://www.dropbox.com/s/jym9vkxb80ii2zo/HeirOfBlackwoodCastle.zip?dl=0

Reproduction steps of the issue:
 - have an up-to-date installation of VSCode
 - install the plug-ins listed in the opening post
 - downlaod the archive from the dropbox
 - extract the archive
 - open the top-level folder as VSCode project
 - open any C# file and try to edit it, try to see if you can get code completion and try to save it.

**Comment by TsubasaK111** [comment] 2020-03-17 11:58
Experiencing same issue here.

**Comment by FFBarney** [comment] 2020-03-17 14:36
I have the same issue. And it is also reproduced in the unity project. I think it may be related to unity

**Comment by MartinHaeusler** [comment] 2020-03-17 16:03
**I can say with very high confidence that Unity is not to blame.** The project was working fine for me for several months now, and I didn't upgrade Unity itself lately, so the *.sln and *.csproj files are still the same (also according to my git history).

However, the OmniSharp binary updates itself in the VSCode extension. That in and on itself is very nice, however since one of the more recent updates, things stopped working and cause the issue we are all experiencing.

What might be an issue now with the newer versions of OmniSharp is this crazy forest of *.csproj modules that Unity creates. However, it has always done that. So maybe it's just the new OmniSharp version that runs into an infinite loop somewhere when it tries to load/resolve the project dependencies. That's just my intuition, and it's a long shot.

Possible culprits from my perspective are:
 - VScode update (somewhat unlikely, but not impossible)
 - C# plugin update (has there been any update lately?)
 - OmniSharp update

**Comment by rjgotten** [comment] 2020-03-18 08:12
> I think it may be related to unity

It's not unity.
I have the same symptoms in an ASP.NET Core project.

**Comment by MartinHaeusler** [comment] 2020-03-18 13:44
@TsubasaK111 did you roll back this plugin or the OmniSharp language server itself? How did you manage to keep it from auto-updating again after rolling it back?

@JoeRobich is it possible that OmniSharp is the real culprit here?

**Comment by filipw** [comment] 2020-03-18 13:55
> @JoeRobich is it possible that OmniSharp is the real culprit here?

we didn't update OmniSharp when moving from v1.21.12 to v1.21.13 so it doesn't seem like that's the case

**Comment by JoeRobich** [comment] 2020-03-18 18:44
A change was made where we search through sub-directories of the project directory looking for a launchsettings.json file. Recent investigations point to this being problematic for projects with many nested directories such as those containing a node_modules folder. see https://github.com/OmniSharp/omnisharp-vscode/issues/3664#issuecomment-600795999

**Comment by JoeRobich** [comment] 2020-03-18 18:47
Or a Unity PackageCache as I am discovering.

**Comment by MartinHaeusler** [comment] 2020-03-18 19:25
@JoeRobich mind you, I've deleted a lot of folders from my unity packagecache before uploading. There are entire documentation and example folders in there, the file structure is comparable in size (both breadth and depth) to that of a node_modules folder.

**Comment by filipw** [comment] 2020-03-18 19:43
thanks @JoeRobich this really looks like the culprit 👍

**Comment by Yazir** [comment] 2020-03-18 20:25
I also have the issue with a fairly big Unity project, starting at 1.21.13.
Reverting to 1.21.12 using .vsix and disabling automatic updates is the solution right now.

**Comment by JoeRobich** [comment] 2020-03-19 01:31
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by Centny** [comment] 2020-03-19 03:18
@JoeRobich using v1.21.15, the unity project issue is fixed.

**Comment by Yazir** [comment] 2020-03-19 11:50
Seems to be working just fine. Thank you @JoeRobich !

**Comment by TsubasaK111** [comment] 2020-03-19 15:01
> @TsubasaK111 did you roll back this plugin or the OmniSharp language server itself? How did you manage to keep it from auto-updating again after rolling it back?
> 
> @JoeRobich is it possible that OmniSharp is the real culprit here?

@MartinHaeusler I presume that the above prerelease resolves this, but for future reference, I did exactly as per [kristoff3r's comment](https://github.com/OmniSharp/omnisharp-vscode/issues/3660#issuecomment-598668731):
1. uninstall CSharp extension in VS Code (cmd + shift + P => show installed extensions => Csharp => uninstall
2. Go to this repo's releases page and download their previous version [v1.21.12](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.12)
3. Open a console and execute command `code --install-extension ~/Downloads/csharp-1.21.12.vsix` where `~/Downloads/` is the directory wherever you downloaded the file in step 2.

**Comment by TsubasaK111** [comment] 2020-03-19 15:08
`v1.21.15` confirmed as functional, thank you for the hard work @JoeRobich ! ❤️

**Comment by laminhtruong** [comment] 2020-03-19 15:22
v1.21.15 is work but Unity Debug still got problem, the breakpoint can't hit :(

**Comment by caseypugh** [comment] 2020-03-19 16:21
Just adding another confirm that both `1.21.15` and `1.21.12` work for my Unity project, while `1.21.14` and `1.21.13` do not.

**Comment by lesreaper** [comment] 2020-03-20 04:31
Running into the same problem, but it does not work on 1.21.15. Using Linux.

**Comment by dorian-bian** [comment] 2020-03-20 11:52
I had the same problem on mac. Tried a lot methods, didn't work.  Today I deleted .vscode/, .dotnet/,  removed vscode, then downloaded a new one, did a fresh install. The CPU problem is gone. I don't know why. I think it's worth a try.

**Comment by filipw** [comment] 2020-03-20 12:14
1.21.15 was released to the marketplace so it worked for you on reinstall

**Comment by ROBYER1** [comment] 2020-03-20 16:25
Unity Debugger just completely freezes on breakpoints now :(

**Comment by JoeRobich** [comment] 2020-03-20 17:05
@laminhtruong @ROBYER1 I see a few open issues about breakpoints on Unity Debugger's GitHub. Maybe you can find one that matches what you are seeing and provide your details. https://github.com/Unity-Technologies/vscode-unity-debug/issues

**Comment by JoeRobich** [comment] 2020-03-20 17:06
@MartinHaeusler Thanks for the report. Closing this now that 1.21.15 has been published.

**Closed by JoeRobich** 2020-03-20 17:06 UTC
Labels: Performance, Resolved-Fixed, Triaged

**Comment by ROBYER1** [comment] 2020-03-20 17:39
> @laminhtruong @ROBYER1 I see a few open issues about breakpoints on Unity Debugger's GitHub. Maybe you can find one that matches what you are seeing and provide your details. https://github.com/Unity-Technologies/vscode-unity-debug/issues

Thankyou for addressing this, the issue is very much project and Unity version agnostic, I have experienced it with Unity 2019.3 and 2020.1 beta on over 5 projects on each as well as a blank project with a very basic test script to debug.

I hope the issue can be addressed as it is simple to reproduce in a fresh Unity project.

**Comment by MartinHaeusler** [comment] 2020-03-20 18:44
@JoeRobich thank you for your efforts. Your help is highly appreciated!

**Comment by mauriciogracia** [comment] 2021-08-02 16:53
August 2021 - installing version 1.21.15 help me see the outline of the code of an asp.net project in VS Code
