### ISSUE TITLE
ERROR: Run 'Debug: Download .NET Core Debugger' or open a .NET project...

### ISSUE THREAD

**Issue by EdDore** [OmniSharp/omnisharp-vscode#369] opened 2016-05-23 21:56 UTC
Installed .NET Core 1.0 RC2. Able to create and run simple console app.
Installed Visual Studio Code (1.1.1), and installed the C# code extension.
Opened console project folder in VSCode, and was prompted to add the missing .vscode files (launch.json/tasks.json).

Set a breakpoint in Main(), and then attempted to launch under debugger (.NET Core Launch (console). Was promptly met with the following error:

Error   Run 'Debug: Download .NET Core Debugger' in the Command Palette or open a .NET projects...  "Open launch.json" "Close".

I suspect it's specific to OS X, as I was able to do the same steps on Linux 14.04 successfully.

**Comment by chuckries** [comment] 2016-05-23 22:05
What happens if you run "Debug: Download .NET Core Debugger" from the command palette? Open the command palette with command + F1 and type debug and it should appear. 
![image](https://cloud.githubusercontent.com/assets/6598594/15486066/cf3a8c14-20f7-11e6-8789-5368eb419fcc.png)

**Comment by EdDore** [comment] 2016-05-25 15:54
It doesn't appear to do anything.

**Comment by chuckries** [comment] 2016-05-25 16:09
@EdDore Is there an install.log file in ~/.vscode/extensions/ms-vscode.csharp-<version>/coreclr-debug?

**Comment by EdDore** [comment] 2016-05-25 16:23
What would be the full path to that folder on a OS x installation?

**Comment by chuckries** [comment] 2016-05-25 16:38
Here is the full path on my osx machine:
`/Users/chuckr/.vscode/extensions/ms-vscode.csharp-1.0.11/coreclr-debug/install.log`

**Comment by langsweirdt** [comment] 2016-05-29 19:30
I'm seeing the exact same problem. No install.log file below the coreclr-debug folder. I tried versions 1.0.11 and 1.0.10 of the extension, same behavior. If I can do something to help reproducing/resolving this, please let me know.

**Comment by ruuda** [comment] 2016-05-30 18:37
I am having the same issue. When I tried this a few weeks ago I gave up. I tried again just yet, with the same results. Attached is my [install.log](https://github.com/OmniSharp/omnisharp-vscode/files/289958/install.log.txt). When I visit one of the timed-out urls with my browser I do get a response.

If I try to download again in the same session, nothing happens. When I tried in a new session it went on to download some more and eventually it succeeded, but it took a very long time (about 30 minutes total), on a 8 MB/s connection. The coreclr-debug directory is ~60 MB after downloading, so it shouldn’t really have taken that long.

OS: Windows 7 x64
VS Code version: 1.1.1
C# Extension version: 1.0.11
ISP Location: The Netherlands

**Comment by jaksmid** [comment] 2016-05-31 13:21
Same problem here, no install log whatsoever. CSharp extension version 1.0.11, Net CORE version RC2

**Comment by chuckries** [comment] 2016-05-31 18:24
@langsweirdt Please try deleting the entire csahrp extension directory at `~/.vscode/extensions/ms-vscode.csharp-<version>` and then reinstall the extension. To view the status of the debugger installation you can view the Ouput Panel (View -> Toggle Output) and select the coreclr-debug option:

![image](https://cloud.githubusercontent.com/assets/6598594/15685791/33d5efc6-2722-11e6-8a6a-801e3c791812.png)

**Comment by chuckries** [comment] 2016-05-31 18:25
@jaksmid Are you able to see an install.log at `~/.vscode/extensions/ms-vscode.csharp-<version>/coreclr-debug`

**Comment by jaksmid** [comment] 2016-06-01 08:59
I have reinstalled the extension by deleting ~/.vscode/extensions/ms-vscode.csharp my version directory.
Hit the Download Debug.
Toggled output, but there is no option for coreclr debug.
Only files in core-crl debug are nuget.config and dummy.cs.

I am also behind the corporate proxy, not sure whether it is relevant but vs code had issues to downlaod extension behind proxy in earlier version.

**Comment by chuckries** [comment] 2016-06-01 17:25
@jaksmid Let's test a basic `dotnet restore` of the debugger, which is one step of the extension installation.

1. Copy this to a file called `project.json` in an empty directory on your system

    ```json
    {
      "name": "dummy",
      "compilationOptions": {
        "emitEntryPoint": true
      },
      "dependencies": {
        "Microsoft.VisualStudio.clrdbg": "14.0.25229-preview-2963841",
        "Microsoft.VisualStudio.clrdbg.MIEngine": "14.0.30401-preview-1",
        "Microsoft.VisualStudio.OpenDebugAD7": "1.0.20405-preview-1",
        "NETStandard.Library": "1.5.0-rc2-24027",
        "Newtonsoft.Json": "7.0.1",
        "Microsoft.VisualStudio.Debugger.Interop.Portable": "1.0.1",
        "System.Collections.Specialized": "4.0.1-rc2-24027",
        "System.Collections.Immutable": "1.2.0-rc2-24027",
        "System.Diagnostics.Process": "4.1.0-rc2-24027",
        "System.Diagnostics.StackTrace": "4.0.1-rc2-24027",
        "System.Dynamic.Runtime": "4.0.11-rc2-24027",
        "Microsoft.CSharp": "4.0.1-rc2-24027",
        "System.Threading.Tasks.Dataflow": "4.6.0-rc2-24027",
        "System.Threading.Thread": "4.0.0-rc2-24027",
        "System.Xml.XDocument": "4.0.11-rc2-24027",
        "System.Xml.XmlDocument": "4.0.1-rc2-24027",
        "System.Xml.XmlSerializer": "4.0.11-rc2-24027",
        "System.ComponentModel": "4.0.1-rc2-24027",
        "System.ComponentModel.Annotations": "4.1.0-rc2-24027",
        "System.ComponentModel.EventBasedAsync": "4.0.11-rc2-24027",
        "System.Runtime.Serialization.Primitives": "4.1.1-rc2-24027",
        "System.Net.Http": "4.0.1-rc2-24027"
      },
      "frameworks": {
        "netstandardapp1.5": {
          "imports": [
            "dnxcore50",
            "portable-net45+win8"
          ]
        }
      },
      "runtimes": {
        "osx.10.11-x64": {}
      }
    }
    ```

2. From a shell, `cd` to the directory with `project.json`
3. Run `dotnet restore && dotnet publish -o clrdbg`

Please try these steps and let me know if they succeed or fail, and any error messages that you see.

**Comment by chuckries** [comment] 2016-06-01 17:25
@jaksmid Additionally, what version of OSX are you on?

**Comment by Kizmar** [comment] 2016-06-01 23:31
I'm having this same issue. I tried the steps above and it all worked fine. Still can't run anything in the debugger without getting the "Error: Run 'Debug: Download .NET Core Debugger' in the Command Palette or open a .NET project directory to download the .NET Core Debugger."

When I try to manually download it like it says, it doesn't appear to do anything.

**Comment by chuckries** [comment] 2016-06-01 23:40
@Kizmar do you have an install.log? Can you try performing the manual `dotnet restore` that I suggested to jaksmid? It won't immediately fix the debugger but it will help us diagnose the issue you are seeing.

**Comment by Kizmar** [comment] 2016-06-01 23:55
@chuckries I should also mention that I'm using Code - Insider, but I also tried this on Code and it's doing the same thing. :) 

Did a "dotnet restore" at the solution level...

Code (non-Insiders version): I deleted all of the extensions that were in my "users/<user_name>/.vscode/extensions" folder. Re-installed the c# extension, and I see no "install.log" anywhere in "users/<user_name>/.vscode/extensions/ms-vscode.csharp-1.0.11/*".

Code - Insiders: Where are the Insiders extensions saved to? I used the command pallet to remove the c# extension and reinstall it, but that didn't seen to make a difference. I don't know where the folder is to see if there's an install.log there.

**Comment by chuckries** [comment] 2016-06-02 00:07
@Kizmar Code - Insiders extensions should be in `~/.vscode-insiders/*`

First, please provide the following:
`dotnet --info` output:
VS Code version:
C# Extension version:

Next, to diagnose this please copy the following into a file named `project.json` in an empty directory somewhere on your system. 
```json
{
  "name": "dummy",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.VisualStudio.clrdbg": "14.0.25229-preview-2963841",
    "Microsoft.VisualStudio.clrdbg.MIEngine": "14.0.30401-preview-1",
    "Microsoft.VisualStudio.OpenDebugAD7": "1.0.20405-preview-1",
    "NETStandard.Library": "1.5.0-rc2-24027",
    "Newtonsoft.Json": "7.0.1",
    "Microsoft.VisualStudio.Debugger.Interop.Portable": "1.0.1",
    "System.Collections.Specialized": "4.0.1-rc2-24027",
    "System.Collections.Immutable": "1.2.0-rc2-24027",
    "System.Diagnostics.Process": "4.1.0-rc2-24027",
    "System.Diagnostics.StackTrace": "4.0.1-rc2-24027",
    "System.Dynamic.Runtime": "4.0.11-rc2-24027",
    "Microsoft.CSharp": "4.0.1-rc2-24027",
    "System.Threading.Tasks.Dataflow": "4.6.0-rc2-24027",
    "System.Threading.Thread": "4.0.0-rc2-24027",
    "System.Xml.XDocument": "4.0.11-rc2-24027",
    "System.Xml.XmlDocument": "4.0.1-rc2-24027",
    "System.Xml.XmlSerializer": "4.0.11-rc2-24027",
    "System.ComponentModel": "4.0.1-rc2-24027",
    "System.ComponentModel.Annotations": "4.1.0-rc2-24027",
    "System.ComponentModel.EventBasedAsync": "4.0.11-rc2-24027",
    "System.Runtime.Serialization.Primitives": "4.1.1-rc2-24027",
    "System.Net.Http": "4.0.1-rc2-24027"
  },
  "frameworks": {
    "netstandardapp1.5": {
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
  "runtimes": {
    "osx.10.11-x64": {}
  }
}
```
Do something like
```sh
cd ~
mkdir testProjectJson
cd testProjectJson
<create project.json here>
```

Then do a dotnet restore and publish from this directory:
```sh
cd ~/testProjectJson
dotnet restore && dotnet publish -o ./clrdbg
```

Let me know what the output of this is and we can go from there.

**Comment by Kizmar** [comment] 2016-06-02 00:18
**dotnet --info output:**
.NET Command Line Tools (1.0.0-preview1-002702)
Product Information:
 Version:     1.0.0-preview1-002702
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**VS Code - Insiders version:** 1.2.0, **C# Ext. version:** 1.0.11
**VS Code version:** 1.1.1, **C# Ext. version:** 1.0.11

**New project restore & publish output:**
log  : Restoring packages for /Users/NAME/Documents/Projects/testing/project.json...
info : Committing restore...
log  : Writing lock file to disk. Path: /Users/NAME/Documents/Projects/testing/project.lock.json
log  : /Users/NAME/Documents/Projects/testing/project.json
log  : Restore completed in 1492ms.

NuGet Config files used:
    /Users/NAME/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
Publishing dummy for .NETStandardApp,Version=v1.5/osx.10.11-x64
publish: warning: host executable not available in dependencies, using host for current platform
publish: Published to ./clrdbg
Published 1/1 projects successfully

**Comment by chuckries** [comment] 2016-06-02 00:23
@Kizmar Thanks! It looks like you are able to restore and publishes our packages fine. Can you give me the directory listings for the following directories?

```sh
ls -a /Users/Name/Documents/Projects/testing/clrdbg
ls -a /Users/Name/.vscode/extesnsions/ms-vscode.csharp-1.0.11/coreclr-debug
```

**Comment by Kizmar** [comment] 2016-06-02 00:28
**ls -a /Users/Name/Documents/Projects/testing/clrdbg**
.
..
1033
Microsoft.CSharp.dll
Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll
Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.vsdconfig
Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.dll
Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.vsdconfig
Microsoft.CodeAnalysis.CSharp.dll
Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.dll
Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.dll
Microsoft.CodeAnalysis.dll
Microsoft.DebugEngineHost.dll
Microsoft.DiaSymReader.Interop.dll
Microsoft.DiaSymReader.PortablePdb.dll
Microsoft.DiaSymReader.dll
Microsoft.MICore.dll
Microsoft.MIDebugEngine.dll
Microsoft.VisualStudio.Debugger.Engine.dll
Microsoft.VisualStudio.Debugger.Interop.10.0.dll
Microsoft.VisualStudio.Debugger.Interop.11.0.dll
Microsoft.VisualStudio.Debugger.Interop.12.0.dll
Microsoft.VisualStudio.Debugger.InteropA.dll
Microsoft.VisualStudio.Debugger.Metadata.dll
Microsoft.VisualStudio.OLE.Interop.dll
Microsoft.VisualStudio.VIL.Host.dll
Microsoft.VisualStudio.VIL.dll
Microsoft.Win32.Primitives.dll
Microsoft.Win32.Registry.dll
Newtonsoft.Json.dll
OpenDebugAD7.dll
System.AppContext.dll
System.Buffers.dll
System.Collections.Concurrent.dll
System.Collections.Immutable.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.Collections.dll
System.ComponentModel.Annotations.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.dll
System.Console.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.DiagnosticSource.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.Tools.dll
System.Diagnostics.Tracing.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.Extensions.dll
System.Globalization.Native.dylib
System.Globalization.dll
System.IO.Compression.Native.dylib
System.IO.Compression.ZipFile.dll
System.IO.Compression.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.FileSystem.dll
System.IO.dll
System.Linq.Expressions.dll
System.Linq.dll
System.Native.a
System.Native.dylib
System.Net.Http.Native.dylib
System.Net.Http.dll
System.Net.NameResolution.dll
System.Net.Primitives.dll
System.Net.Sockets.dll
System.ObjectModel.dll
System.Private.CompilerServices.ICastable.dll
System.Private.CoreLib.InteropServices.dll
System.Private.Interop.dll
System.Private.Uri.dll
System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight.dll
System.Reflection.Emit.dll
System.Reflection.Extensions.dll
System.Reflection.Metadata.dll
System.Reflection.Primitives.dll
System.Reflection.TypeExtensions.dll
System.Reflection.dll
System.Resources.ResourceManager.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.PInvoke.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.InteropServices.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Cng.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Native.dylib
System.Security.Cryptography.OpenSsl.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Principal.Windows.dll
System.Security.Principal.dll
System.Text.Encoding.Extensions.dll
System.Text.Encoding.dll
System.Text.RegularExpressions.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Tasks.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.Threading.dll
System.Xml.ReaderWriter.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
clrdbg
coreclr.ad7Engine.json
dummy
dummy.deps.json
dummy.runtimeconfig.json
libclrdbg.dylib
libclrdbg.vsdconfig
libcoreclr.dylib
libdbgshim.dylib
libhostfxr.dylib
libhostpolicy.dylib
libmscordaccore.dylib
libmscordbi.dylib
libsos.dylib
libvsbaseservices.dylib
libvsdebugeng.dylib
libvsdebugeng.impl.dylib
mscorlib.dll
mscorlib.ni.dll
sosdocsunix.txt
version.txt
vsdebugeng.impl.vsdconfig
vsdebugeng.manimpl.dll
vsdebugeng.manimpl.vsdconfig

**ls -a /Users/Name/.vscode/extensions/ms-vscode.csharp-1.0.11/coreclr-debug** _- This is the same for "Insiders" too._
dummy.cs
NuGet.config

**Comment by chuckries** [comment] 2016-06-02 00:43
@Kizmar Thanks. It looks like your machine is capable of restoring the debugger packages from nuget using `dotnet restore`, but the extension is not even getting that far. It would be very helpful if you could try the following:

1. In all open VS Code instances, `File -> Close Folder` and then quit VS Code.This ensures we will have an empty workspace when you restart VS Code.
2. `rm -rf ~/.vscode/extensions/ms-vscode.csharp-1.0.11`
3. Open VS Code and `Help -> Toggle Developer Tools` to bring up the developer tools pane. Switch to the Console tab. 
![image](https://cloud.githubusercontent.com/assets/6598594/15730266/fd22bbfe-281f-11e6-95f5-3b88a0be38b7.png)

4. From the Command Palette, `ext install C#` to install a new copy of the C# extension. Restart VS Code when prompted.

After the restart, run `Debug: Download .NET Core Debugger` from the command palette. Hopefully we will see some kind of error appear in the javascript console. Please send back any log, description, or screenshot of what you see. Thanks for your help!

**Comment by Kizmar** [comment] 2016-06-02 01:07
Ok so, did all that. Once VS Code opened back up I instantly got a bunch of stuff in the console:

> [Extension Host] Activating extension `ms-vscode.csharp` failed: ENOTDIR. threadService.ts:207

> [Extension Host] Here is the error stack:  Error: ENOTDIR
    at Error (native)
    at Function.CoreClrDebugUtil.existsSync (/Users/NAME/.vscode-insiders/extensions/ms-vscode.csharp-1.0.11/out/coreclr-debug/util.js:77:23)
    at isOnPath (/Users/NAME/.vscode-insiders/extensions/ms-vscode.csharp-1.0.11/out/coreclr-debug/main.js:187:28)
    at Object.activate (/Users/NAME/.vscode-insiders/extensions/ms-vscode.csharp-1.0.11/out/coreclr-debug/main.js:21:10)
    at activate (/Users/NAME/.vscode-insiders/extensions/ms-vscode.csharp-1.0.11/out/omnisharpMain.js:82:18)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:24266)
    at Function.t._callActivate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:24051)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:23923
    at Object.h [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13179)
    at Object.__dirname.undefined.M.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:16341)
    at __dirname.undefined.t.Class.define._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:18167)
    at __dirname.undefined.t.Class.define._completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:17608)
    at d (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:21265)
    at z.then.a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:21489)
    at Object.h [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13179)
    at Object.__dirname.undefined.M.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:16341)

>  Activating extension `ms-vscode.csharp` failed: ENOTDIR. nativeExtensionService.ts:98

..and then this at the bottom:

> [Extension Host] [OmniSharp]: Installing to /Users/nwestbrook/.vscode-insiders/extensions/ms-vscode.csharp-1.0.11/.omnisharp
threadService.ts:207 [Extension Host] [OmniSharp] Attempting to download omnisharp-osx-x64-netcoreapp1.0.tar.gz...
threadService.ts:207 [Extension Host] [OmniSharp] Downloading to /var/folders/wg/2xc_3p190_qc3bl070xl_8w00000gn/T/tmp-71774CvRjoiSL3SE4.tmp...
threadService.ts:207 [Extension Host] [OmniSharp] Download complete!
threadService.ts:207 [Extension Host] [OmniSharp] Untaring...
threadService.ts:207 [Extension Host] [OmniSharp] Done! 249 files unpacked.

I tried to run Debug: Download .NET Core Debugger and got this:
> Conflict detected, command `workbench.action.debug.run` cannot be triggered by cmd+f5 due to cordova.run keybindingResolver.ts:188

Out of curiosity I also took the following steps:
1. Removed the Cordova extension, 
2. Restarted Code (still couldn't install the debugger)
3. Removed the C# Extension
4. Restarted code.
5. Reinstalled the C# Extension (watched the console and waited for it to finish)
6. Tried to reinstall the debugger, nothing in the console at all. :(

At this point, when I try to run/debug I'm seeing the following in the console:
> messageService.ts:119 Run 'Debug: Download .NET Core Debugger' in the Command Palette or open a .NET project directory to download the .NET Core Debugger: Error: Run 'Debug: Download .NET Core Debugger' in the Command Palette or open a .NET project directory to download the .NET Core Debugger
    at Object.E [as create] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:17647)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:104:23498
    at Object.p [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:16345)
    at Object.__dirname.undefined.F.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:19673)
    at __dirname.undefined.t.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:20994)
    at __dirname.undefined.t.Class.define._chainedError (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:20353)
    at n (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:18181)
    at Object.p [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:16345)
    at Object.__dirname.undefined.F.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:19673)
    at __dirname.undefined.t.Class.define._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:20994)

**Comment by chuckries** [comment] 2016-06-02 02:02
@Kizmar Thank you! This is perfect. I am out of the office for the rest of today but I will continue to look at this tomorrow.

**Comment by jaksmid** [comment] 2016-06-02 08:09
@chuckries 
Dot net restore completed without any Error messages, OS X version is LeCaptain.
I see that you got ahed with Kizmar, let me know if I can be of any help.

**Comment by chuckries** [comment] 2016-06-02 17:40
@Kizmar The primary issue here is that we are failing to determine if `dotnet` is on your current PATH, and that failure is catastrophic. I need to fix us to fail in a more graceful way, and possibly fix our logic around here altogether. If you don't mind, could you give me your current `$PATH` variable?
```sh
echo $PATH | pbcopy
```

**Comment by Kizmar** [comment] 2016-06-02 17:58
**echo $PATH | pbcopy output:**

> /Users/USER_NAME/.dnx/runtimes/dnx-mono.1.0.0-rc1-update2/bin:/Users/USER_NAME/.dnx/bin:/Users/USER_NAME/.npm-packages/bin:/opt/subversion/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin/node:/usr/local/bin/npm:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet

**Comment by chuckries** [comment] 2016-06-02 18:34
@Kizmar The root cause of this issue in your specific case is that you have the absolute path to a binary in your `$PATH`: `/usr/local/bin/npm`. The next version of the extension will fix this issue, but I believe you can make the current version work if you remove `/usr/loca/bin/npm` from your `$PATH`. I found [this page](http://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/) that has instructions to change the system $PATH on OSX.

**Comment by Kizmar** [comment] 2016-06-02 23:29
I removed the "/usr/local/bin/npm:" portion from my .bash_profile, and I'm still getting the error.

**echo $PATH | pbcopy output:**
> /Users/nwestbrook/.dnx/bin:/Users/nwestbrook/.npm-packages/bin:/opt/subversion/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin/node:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet

**Comment by chuckries** [comment] 2016-06-02 23:34
it looks like `/usr/local/bin/node` is also a full path to an executable, not a directory. That needs to be removed as well.

**Comment by Kizmar** [comment] 2016-06-02 23:49
Heeeyyyyy, it worked! 😄 

Soooo... I'll be able to add that stuff back in to $PATH after it's fixed?

**Comment by chuckries** [comment] 2016-06-02 23:51
Woo!! 

Yes, you should be able to add that back once we release a new version. Keep your eye on our [releases page](https://github.com/OmniSharp/omnisharp-vscode/releases) as we will probably have a new extension there before it hits the marketplace. As of this writing the most recent github release is 1.1.2, which does not have this fix. 1.1.3 or greater should have it.

**Comment by chuckries** [comment] 2016-06-02 23:55
Additionally, I don't know that it makes sense to have full paths to specific binaries in your `$PATH` variable. In a quick search I couldn't find any documentation on the subject, but I believe that `$PATH` need only contain directories. Did you have `/usr/local/bin/node` and `/usr/local/bin/npm` on your path for any particular reason?

**Comment by chuckries** [comment] 2016-06-02 23:57
@EdDore Could you check your `$PATH` on OSX and see if this is the same issue you are running into?

**Comment by Kizmar** [comment] 2016-06-02 23:57
@chuckries I... honestly have no clue. I'm guessing it was added there by some... package install or something? /shrug  I'm not super familiar with $PATH stuff. 😉

**Comment by jaksmid** [comment] 2016-06-03 08:14
@chuckries It turned out I had this on my path: PATH="/usr/local/share/dotnet/dotnet:${PATH}"
I think it was one of the suggestion to try when the workaround to zsh was not yet known.
Thanks a lot for the help!

**Comment by chuckries** [comment] 2016-06-14 23:19
I am closing this issue as it looks like it is fixed for most people. @EdDore if you run into this again and it is not a path issue please reopen.

**Closed by chuckries** 2016-06-14 23:19 UTC
Labels: Debugger, Debugger-Install
