### ISSUE TITLE
No definition found for referenced assemblies

### ISSUE THREAD

**Issue by chickenSandwich** [OmniSharp/omnisharp-vscode#3318] opened 2019-10-04 11:00 UTC
## Issue Description ##
After updating to 1.21.4, Go to Definition for referenced assembly types does not work

## Steps to reproduce
Update to 1.21.4
List<int> test = new List<int>();
Press F12 (Or choose Go to Definition from context menu)

## Expected  behavior
Open the [metadata] csharp file and go to the definition

## Actual behavior
No definition found for 'List'## Logs ##

## Work-around (Verification that 1.21.4 is the culprit)
Go to the Extensions pane
Choose Install Another Version from the C# extension
Choose 1.21.3
Restart VSCode
Repeat the ## Steps to reproduce

## Note:
Upon restarting VSCode after updating to C# 1.21.4 the Output window is blank
Upon restarting VSCode after Install Another Version to C# 1.21.3
The Output window reports:

Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' (43722 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'

Downloading package '.NET Core Debugger (linux / x64)' (64045 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (linux / x64)'

Downloading package 'Razor Language Server (Linux / x64)' (57828 KB).................... Done!
Installing package 'Razor Language Server (Linux / x64)'

Finished

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.4

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.4|
|csharpextensions|jchannon|1.3.0|
|gitignore|codezombiech|0.6.0|
|indent-rainbow|oderwat|7.4.0|
|json-tools|eriklynd|1.0.2|
|rainbow-brackets|2gua|0.0.6|
|shader|slevesque|1.1.4|
|vscode-glsllint|CADENAS|0.0.5|
|vscode-nuget-package-manager|jmrog|1.1.6|
|whitespace|sandcastle|0.0.5|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by filipw** [comment] 2019-10-04 11:37
This is a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1624
There is already a PR with a fix here https://github.com/OmniSharp/omnisharp-roslyn/pull/1625 
As soon as the PR is merged, there will be a pre-release OmniSharp that can be used as workaround.

**Closed by filipw** 2019-10-04 11:37 UTC
