### ISSUE TITLE
No Symbols Loaded: Breakpoints not being hit from 'debug test' CodeLens command

### ISSUE THREAD

**Issue by lmynsberge** [OmniSharp/omnisharp-vscode#2726] opened 2018-12-01 14:13 UTC
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin

VS Code version: 1.17.2
C# Extension version: 1.13.1

## Steps to reproduce
Create a simple project with NUnit unit tests. 
Add a breakpoint to the unit test (first line).
Use CodeLens "debug test" option to debug test.

Optionally clone this sample repo: https://github.com/lmynsberge/vscode-csharp-test.git

## Expected  behavior
VSCode stops at first breakpoint.

## Actual behavior
VSCode completes the entire unit test without stopping.

## Things I've tried
I've tried adding the <DebugType>portable</DebugType> directive to my csproj file. I've also confirmed that both a DLL and a PDB are present in the bin/Debug folder which is where it looks like this test is coming from based on the output:
NUnit Adapter 3.10.0.21: Test discovery starting
NUnit Adapter 3.10.0.21: Test discovery complete
Started debugging process #10478.
NUnit Adapter 3.10.0.21: Test execution started
Debugging selected tests in /Users/lmynsberge/git-projects/dotnet-first/unit-test-nunit/PrimeService.UnitTests/bin/Debug/netcoreapp2.0/PrimeService.UnitTests.dll
NUnit3TestExecutor converted 3 of 3 NUnit test cases
NUnit Adapter 3.10.0.21: Test execution complete
Debugging complete.

While in debug mode, I can hover over the symbol and see that "No symbols have been loaded for this document." I even globally set "justMyCode" to false to be sure this wasn't blocking it. I've had this issue in VS before, but it's just a setting to load symbols by default and a quick switch. I can't find anything similar in VSCode or the extension.

Any help would be greatly appreciated.

**Comment by gregg-miskelly** [comment] 2018-12-18 17:01
I will try and take a look soon and try and figure out what is going wrong.

**Comment by gregg-miskelly** [comment] 2018-12-20 01:15
@lmynsberge I am not able to reproduce this. A few questions:

1. To make sure I understand, you are setting a breakpoint in 'ReturnFalseGivenValuesLessThan2'. Correct? (ex: I set my breakpoint on line 26 in PrimeService.UnitTests/PrimeService_IsPrimeShould.cs)
2. If you copy the output of the debug console to a text, file, and find the information on 'PrimeService.UnitTests.dll', are symbols loading? If not, what reason is given? Here is my line for example: `Loaded '/Users/greggm/scratch/vscode-csharp-test/PrimeService.UnitTests/bin/Debug/netcoreapp2.0/PrimeService.UnitTests.dll'. Symbols loaded.`
3. If you add the following code to your unit test, what happens:
```
            Assert.IsTrue(System.Diagnostics.Debugger.IsAttached);
            System.Diagnostics.Debugger.Break();
```

**Comment by gregg-miskelly** [comment] 2019-01-05 02:15
I am closing this for now. Feel free to ping back if you have more time in the future.

**Comment by lmynsberge** [comment] 2019-01-05 06:39
Hi Gregg - thank you for your hep so far. I looked at it and here are my answers:
1) Correct
2) It does say that the symbols weren't loaded, so that's it. It says it wasn't built with symbols, but I can see the PDB files for both my unit test assembly and the assembly under test:
Loaded '/Users/lmynsberge/git-projects/dotnet-first/unit-test-nunit/PrimeService.UnitTests/bin/Debug/netcoreapp2.0/PrimeService.dll'. Module was built without symbols.
3. That seems to have caused a breakpoint (brought up the breakpoint tools in vscode)

Any idea how to get the symbols to load? At this point, it looks like I'm just doing something wrong, but any help would be appreciated.

**Comment by lmynsberge** [comment] 2019-01-06 00:00
I see the 'PrimeService.pdb' in the same directory with the same timestamp as 'PrimeService.dll.' I don't see it in the build output, however:

  PrimeService -> /Users/lmynsberge/git-projects/dotnet-first/unit-test-nunit/PrimeService/bin/Debug/netstandard2.0/PrimeService.dll
  PrimeService.UnitTests -> /Users/lmynsberge/git-projects/dotnet-first/unit-test-nunit/PrimeService.UnitTests/bin/Debug/netcoreapp2.0/PrimeService.UnitTests.dll

I haven't been able to get this working with any projects, so it is probably system-level.
I installed a newer SDK, but it still won't work. I don't think it's an Omnisharp issue, though, so this can probably be closed.

**Closed** 2019-01-08 21:07 UTC
Labels: Debugger, Test

**Comment by dfdumaresq** [comment] 2020-02-22 00:07
I'm having the same trouble.

**Comment by tomasalles** [comment] 2020-05-05 11:59
Same here

**Comment by dfdumaresq** [comment] 2020-05-06 16:12
@tomasalles - this might help
https://medium.com/front-end-weekly/solve-breakpoint-ignored-with-visual-studio-code-vscode-1-19-chrome-debugger-6d484c88b829

I fixed my problem by focusing on webpack.config.js. In my case, I had to disable source-maps, which seemed counter intuitive. (Long story), anyway good luck!
