### ISSUE TITLE
Intellisense doesn't work on Fedora 34 dotnet-sdk 5.0.203

### ISSUE THREAD

**Issue by AbnerFerrari** [OmniSharp/omnisharp-vscode#4610] opened 2021-06-14 00:20 UTC
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    b5f47e6c6a

## Environment data
`dotnet --info` output:

```
Runtime Environment:
 OS Name:     fedora
 OS Version:  34
 OS Platform: Linux
 RID:         fedora.34-x64
 Base Path:   /usr/lib64/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.203 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.6 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: 1.57.0
C# Extension version:v1.23.12

## OmniSharp log

```
Starting OmniSharp server at 6/13/2021, 9:19:10 PM
    Target: /home/abnerferrari/Projects/my-app

OmniSharp server started.
    Path: /home/abnerferrari/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/run
    PID: 15530

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 34.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.11.0 - "/home/abnerferrari/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/abnerferrari/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.11.0 - "/home/abnerferrari/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/abnerferrari/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/abnerferrari/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/abnerferrari/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/abnerferrari/Projects/my-app'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/abnerferrari/Projects/my-app'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/abnerferrari/Projects/my-app/my-app.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/abnerferrari/Projects/my-app'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/abnerferrari/Projects/my-app' on host 15431.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/abnerferrari/Projects/my-app/my-app.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "Microsoft.AspNetCore.Razor.Tasks.DiscoverDefaultScopedCssItems" task could not be loaded from the assembly /usr/lib64/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/../../tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll. Invalid Image Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/abnerferrari/Projects/my-app/my-app.csproj'.
/home/abnerferrari/Projects/my-app/my-app.csproj
/usr/lib64/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.ScopedCss.targets(118,3): Error: The "Microsoft.AspNetCore.Razor.Tasks.DiscoverDefaultScopedCssItems" task could not be loaded from the assembly /usr/lib64/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/../../tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll. Invalid Image Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/abnerferrari/Projects/my-app/my-app.csproj

```

## Steps to reproduce

```
mkdir my-app
cd my-app
dotnet new webapi
code .
```

## Expected  behavior

Intellisense should work

## Actual behavior

Intellisense doesn't work at all

with other project template like `dotnet new classlib` everything works well

**Comment by JoeRobich** [comment] 2021-06-19 01:10
The issue here is that the source build version of the SDK is installed. There is a known issue that they do not include the Full Framework assemblies in the source build release of the SDK (see https://github.com/dotnet/source-build/issues/2006).

There are different packages you can install. For Arch users there is the `dotnet-sdk-bin` package. For Fedora or CentOS users, you can try this suggestion https://github.com/OmniSharp/omnisharp-vscode/issues/4360#issuecomment-779086868

**Comment by JoeRobich** [comment] 2021-06-19 01:11
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4360

**Closed by JoeRobich** 2021-06-19 01:11 UTC
Labels: Resolved-Duplicate
