### ISSUE TITLE
assuming assembly reference sys.runtime matches identity

### ISSUE THREAD

**Issue by mikehaas763** [OmniSharp/omnisharp-vscode#992] opened 2016-11-24 18:32 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version: 1.7.2
C# Extension version: 1.5.3

## Steps to reproduce
Create a new web project using cli tools preview 3
Open project with latest regular release version of vscode with c# extension

![image](https://cloud.githubusercontent.com/assets/2096573/20607884/1c3b2530-b24a-11e6-9ee0-4f483e5ce257.png)

I then see errors like this in Program.cs and Startup.cs

![image](https://cloud.githubusercontent.com/assets/2096573/20607901/4d7c388c-b24a-11e6-9422-fdcf2b1bc3e6.png)

Is this an issue with the extension or does the scaffold have some issues with dependency versioning?

**Comment by DustinCampbell** [comment] 2016-11-24 19:56
This should work with v1.6-beta2 of the extension available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta2). See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)

**Comment by DustinCampbell** [comment] 2016-11-24 19:57
Dupe of #967

**Closed by DustinCampbell** 2016-11-24 19:57 UTC
Labels: Resolved-Duplicate
