### ISSUE TITLE
Wildcards in PackageReference version cause OmniSharp to hang

### ISSUE THREAD

**Issue by stablecube** [OmniSharp/omnisharp-vscode#2993] opened 2019-04-16 21:04 UTC
## Issue Description ##
If I have a PackageReference with a wildcard version such as 
`<PackageReference Include="My.Package" Version="1.0.*" />`
Omnisharp will hang at "Adding project"

Once I fully type the version number then Omnisharp will then correctly start.

I think this just recently started happening with a new update.

### OmniSharp log ###
<details>
Starting OmniSharp server at 4/16/2019, 1:48:23 PM
    Target: /home/zboyet/project_data/Deadbolt/Media

OmniSharp server started.
    Path: /home/zboyet/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/run
    PID: 25929

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/zboyet/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/zboyet/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/zboyet/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /home/zboyet/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/zboyet/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/zboyet/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/zboyet/project_data/Deadbolt/Media'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/zboyet/project_data/Deadbolt/Media'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api/Image.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api.Model/Image.Api.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.EntityFramework/Image.EntityFramework.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Video.Api/Video.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Video.Api.Model/Video.Api.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Video.EntityFramework/Video.EntityFramework.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Video.EntityFramework.Managers/Video.EntityFramework.Managers.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/MessageQueue/Media.MessageQueue.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/FileSystem/Api/FileSystem.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/FileSystem/Api.DotNetClient/Server.Api.DotNetClient.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/FileSystem/Api.Model/FileSystem.Api.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/FileSystem/EntityFramework/FileSystem.EntityFramework.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/FileSystem/Workspace/FileSystem.Workspace.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/Api/Image.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/Api.DotNetClient/Image.Api.DotNetClient.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/Api.Model/Mutation.Image.Api.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/Gifsicle/Gifsicle.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/ImageMagick/ImageMagick.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/JpegOptim/JpegOptim.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/OptiPng/OptiPng.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Image/PngQuant/PngQuant.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Video/Api/Video.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Video/Api.DotNetClient/Mutation.Video.Api.DotNetClient.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Video/Api.Model/Mutation.Video.Api.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Mutation/Video/FFMpeg/FFMpeg.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Workspace.Api/Workspace.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Workspace.Api.EntityFramework/Workspace.Api.EntityFramework.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/zboyet/project_data/Deadbolt/Media/Workspace.Api.Model/Workspace.Api.Model.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/zboyet/project_data/Deadbolt/Media'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api/Image.Api.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/zboyet/project_data/Deadbolt/Media' on host 25727.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api/Image.Api.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api/Image.Api.csproj'
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CodeFixes.ApplyDiagnosticAnalyzerAttributeFix' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Xunit.Analyzers.FixProviders.MemberFixBase' because it's language doesn't match 'C#'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api.Model/Image.Api.Model.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api.Model/Image.Api.Model.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.Api.Model/Image.Api.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.EntityFramework/Image.EntityFramework.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.EntityFramework/Image.EntityFramework.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/zboyet/project_data/Deadbolt/Media/Ingestion/Image.EntityFramework/Image.EntityFramework.csproj'
</details>

### C# log ###
<details>none</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/35/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [/snap/dotnet-sdk/35/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/snap/dotnet-sdk/35/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/snap/dotnet-sdk/35/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/snap/dotnet-sdk/35/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.6.10|
|csharp|ms-vscode|1.19.0|
|docomment|k--kato|0.1.6|
|dotenv|mikestead|1.0.1|
|githistory|donjayamanne|0.4.6|
|JavaScriptSnippets|xabikos|1.7.2|
|path-intellisense|christian-kohler|1.4.2|
|php-docblocker|neilbrayfield|1.8.0|
|php-intellisense|felixfbecker|2.3.10|
|prettier-vscode|esbenp|1.8.1|
|twig|whatwedo|1.0.2|
|vetur|octref|0.18.1|
|vscode-docker|PeterJausovec|0.6.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|0.1.18|
|vscode-yaml|redhat|0.4.0|;

</details>

**Comment by filipw** [comment] 2019-04-19 05:31
Thanks a lot - I will close this as duplicate of #3009.
Please see https://github.com/OmniSharp/omnisharp-vscode/issues/3009#issuecomment-484772057 for a solution.

**Closed by filipw** 2019-04-19 05:31 UTC
