### ISSUE TITLE
[feature request] Codelens for TestFixture

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-vscode#2064] opened 2018-02-23 08:49 UTC
Please add ability to run test and debug test on TestFixture with nunit

**Comment by akshita31** [comment] 2018-04-11 21:31
@Thaina  We already have a codelens showing up for a Nunit project. Also, with the change in #1961 , we added the capability to run and debug all the tests. 
![nunit](https://user-images.githubusercontent.com/12554141/38644143-67430e5e-3d94-11e8-8eca-66ff3b3687c1.png)

This change is available in the [latest beta release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.15.0-beta4), if you're interested in giving it a spin. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install a beta release of C# for VS Code.

**Comment by DustinCampbell** [comment] 2018-04-11 21:34
This is a dupe of #420, which as @akshita31 mentioned, is already fixed for the next release. Feel free to take a beta release for a spin if you're interested.

**Closed** 2018-04-16 18:00 UTC
Labels: Resolved-Duplicate, Test
