### ISSUE TITLE
C# Extension Performance issue

### ISSUE THREAD

**Issue by Ashokkumar-RV** [OmniSharp/omnisharp-vscode#3629] opened 2020-03-06 14:15 UTC
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.42.1`

new update asked to choose new Formatter, (previously it was "ms-vscode.csharp"):
    "[csharp]": {
        "editor.defaultFormatter": "ms-dotnettools.csharp",
    },

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 202,
		"activateCallTime": 12,
		"activateResolvedTime": 52,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "workspaceContains:*.csproj,*.sln,*.csx,*.cake,**/*.csproj,**/*.sln,**/*.csx,**/*.cake"
		}
	},
	"runtimeErrors": []
}
```
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4298698/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

**Comment by cartermp** [comment] 2020-03-10 21:24
Thanks for the report. This is a result of the changed publisher name, so this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3620

**Closed by cartermp** 2020-03-10 21:24 UTC
Labels: Resolved-Duplicate, Triaged
