### ISSUE TITLE
Restore option is getting displayed for both project.json file and csproj file.

### ISSUE THREAD

**Issue by anuraj** [OmniSharp/omnisharp-vscode#1233] opened 2017-02-13 09:06 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

VS Code version:Version 1.9.1
C# Extension version:1.7.0

## Steps to reproduce

1. Migrated my existing dotnet core project using dotnet migrate command, which created backup folder and moved project.json file inside it.
2. Then open the project folder in VSCode.
3. Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/276411/22877038/8d98930e-f1f9-11e6-8908-5fe40f9d1d59.png)

## Expected  behavior

Only one restore prompt should come, from the selected project file.

## Actual behavior

Two prompts are coming to restore

**Comment by DustinCampbell** [comment] 2017-02-13 14:46
We still support project.json in VS Code and it's entirely possible that you might use VS Code with partially-converted code base. So, it's actually pretty tricky to determine whether project.json files should be restored or not (and not break something else). This isn't a great experience, but it's sort of working as designed.

**Comment by steelwil** [comment] 2017-04-05 11:02
Is there a configuration setting that can set somewhere? I am using VS Code but I still need to support VS2015.

**Comment by DustinCampbell** [comment] 2017-04-05 12:56
If you want to disable processing of project.json projects, you can add an `omnisharp.json` file to your root folder with the following content:

```JSON
{
    "dotnet": {
        "enabled": false
    }
}
```

**Comment by rchande** [comment] 2018-06-13 18:17
Looks like there's a workaround for this problem. Closing the issue--feel free to open a new one if you're still having problems.

**Closed by rchande** 2018-06-13 18:17 UTC
