### ISSUE TITLE
Debugger skips breakpoints in C# projects

### ISSUE THREAD

**Issue by krasimirkrustev** [OmniSharp/omnisharp-vscode#3812] opened 2020-05-28 14:31 UTC
## Environment data
`dotnet --info` output:
------------------------
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
------------------
1.45.1 x64

C# Extension version:
1.21.18

## OmniSharp log

Starting OmniSharp server at 5/28/2020, 5:16:46 PM
    Target: ***\HelloWorld

OmniSharp server started.
    Path: ***\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.1\OmniSharp.exe
    PID: 3772

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "***\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.1\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '***\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.1\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "***\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.1\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = ***\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.1\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = ***\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.1\.msbuild
            MSBuildToolsPath = ***\.vscode\extensions\ms-dotnettools.csharp-1.21.18\.omnisharp\1.35.1\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '***\HelloWorld'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '***\HelloWorld'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '***\HelloWorld\HelloWorld.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '***\HelloWorld'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\programming\HelloWorld\HelloWorld.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '***\HelloWorld' on host 8256.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '***\HelloWorld\HelloWorld.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '***\HelloWorld\HelloWorld.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: HelloWorld

## Steps to reproduce
Open cmd
mkdir HelloWorld
cd HelloWorld
dotnet new console
code .
put breakpoint on line 10
hit F5

## Expected  behavior
VSCode should stop at the line

## Actual behavior
DEBUG CONSOLE tab shows

"You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications."

**Comment by gregg-miskelly** [comment] 2020-05-28 15:41
Unfortunately, VS Code has a bug where it doesn't display error messages. It will be fixed in their next release. You can turn on [debugger logging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging) to see what error is being returned.

I believe the problem is that you have the x86 .NET Core SDK installed on your machine and earlier in the path than the x64 .NET Core SDK (assuming you have both). This extension only supports debugging x64 processes on Windows.

**Comment by krasimirkrustev** [comment] 2020-05-28 17:20
Here is the debugger's log:
`-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"***\\HelloWorld/bin/Debug/netcoreapp3.1/HelloWorld.dll","args":[],"cwd":"***\\HelloWorld","console":"internalConsole","stopAtEntry":false,"logging":{"engineLogging":false},"internalConsoleOptions":"openOnSessionStart","__sessionId":"5e32a8c9-097b-4d28-bdfc-77a9a380d448"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"Program.cs","path":"***\\HelloWorld\\Program.cs","checksums":[{"algorithm":"SHA1","checksum":"3fb673958d99b05299acc895a52b30de6fde8dbe"},{"algorithm":"SHA256","checksum":"5344d406136a1fff8ddae8b327736d9beac318a4f9b67cbdeb48cba43465efde"},{"algorithm":"SHA1","checksum":"b438947097df5c09d068f6368eecdd41e4d0940b"},{"algorithm":"SHA256","checksum":"cda8030706f1ab035ae682fd437995b93c15160925e598cba88aaa915f726514"}]},"lines":[10],"breakpoints":[{"line":10}],"sourceModified":false},"type":"request","seq":3}
<- (R) {"seq":6,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":10}]}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":4}
<- (R) {"seq":7,"type":"response","request_seq":4,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":5}
<- (E) {"seq":8,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/LaunchFailed","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.18363","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-2147220965}}}
<- (R) {"seq":9,"type":"response","request_seq":5,"success":false,"command":"configurationDone","message":"Only 64-bit processes can be debugged."}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":6}
-> (C) {"command":"threads","type":"request","seq":7}
<- (E) {"seq":10,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.18363","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}
<- (R) {"seq":11,"type":"response","request_seq":6,"success":true,"command":"disconnect"}
`

Thank you for the help. Much appreciated. The problem was the x86 SDK.

Two questions:
1. Why there is not information that only x64 processes can be debugged?
2. Is there a plan for support of x86 processes?

**Comment by gregg-miskelly** [comment] 2020-05-28 21:50
1: This is the VS Code bug that I alluded to. You should have seen this message:
`<- (R) {"seq":9,"type":"response","request_seq":5,"success":false,"command":"configurationDone","message":"Only 64-bit processes can be debugged."}`
2: There are no current plans.

**Closed by gregg-miskelly** 2020-05-28 21:50 UTC
Labels: Debugger
