### ISSUE TITLE
C# doens't propose me using namespace or framework installed related to add them automatically to the class

### ISSUE THREAD

**Issue by TheBanker1710** [OmniSharp/omnisharp-vscode#3739] opened 2020-04-22 17:22 UTC
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by TheBanker1710** [comment] 2020-04-22 17:22
n fact, I'm following a tuto on Udemy about .NET CORE and Angular, and the C# extension or Visual Code doesn't show me the quick fix when there is an error. It doesn't underline the error, it seems it doesn't recognize the new classes added and the new framework added too.

![Capture](https://user-images.githubusercontent.com/15126798/80013093-9f5ca600-84ce-11ea-8ca8-e2b4fa8f5b11.JPG)

**Comment by TheBanker1710** [comment] 2020-04-22 17:22
It doesn't recognize new classes or new package added :/ I don't know what to do :/

**Comment by cartermp** [comment] 2020-04-23 20:22
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3738

**Closed by cartermp** 2020-04-23 20:22 UTC
