### ISSUE TITLE
Parameter-completion shows weird doc-comment stuff

### ISSUE THREAD

**Issue by ljw1004** [OmniSharp/omnisharp-vscode#408] opened 2016-06-07 15:46 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version:1.2.0
C# Extension version: ?? Not sure how to find this. I installed the public omnisharp today, using the suggested instructions.

## Steps to reproduce

1. Start a `dotnet new` project, restore it, then open it in VS Code.
2. Put `///` above `Main(param string[] arg)`
3. In the body of Main, start typing an invocation `Main(|`

## Expected  behavior

It should show me something useful in the parameter-completion popup.

## Actual behavior

Instead it shows me something weird about `<M:memberName>` that I don't understand.

![doc-comment-member](https://cloud.githubusercontent.com/assets/3316258/15864501/3fcfa2f8-2c8c-11e6-9bbf-a6937871f05f.png)

**Comment by DustinCampbell** [comment] 2016-06-07 20:35
This is a dupe of #97.

**Comment by DustinCampbell** [comment] 2016-06-08 16:31
Actually, even better, I just noticed that this has already been fixed. The original issue, #30, has been fixed. You should update your C# extension with the latest, 1.1.5.

**Closed by DustinCampbell** 2016-06-08 16:31 UTC
Labels: Resolved-Duplicate
