### ISSUE TITLE
Projects have trouble loading and intellisense showing errors when used with Unity

### ISSUE THREAD

**Issue by andymads** [OmniSharp/omnisharp-vscode#3744] opened 2020-04-24 10:13 UTC
## Issue Description ##

I'm often having issues when using OmniSharp with Unity. 

I get this message when opening the project in VS Code.
"Some projects have trouble loading. Please review the output for more details."

Output log with hundreds of warnings attached.
[output.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4528115/output.txt)

Also Intellisense is showing lots of CS0246 errors even though there's nothing wrong with the C# code. The namespace is present but grayed out and flagged as unnecessary.

![Screenshot 2020-04-24 at 11 05 58](https://user-images.githubusercontent.com/15214465/80201164-9c230080-861b-11ea-8f36-32130bfdae5c.png)

I have tried deleting the projects and solution and letting Unity recreate but it does not fix it.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.44.2
**C# Extension**: 1.21.17

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.6.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.9|
|csharp|ms-dotnettools|1.21.17|
|playfab-explorer|Playfab|0.1.8|
|unity-debug|Unity|2.7.5|
|vscode-azurefunctions|ms-azuretools|0.22.0|;

</details>

**Comment by JoeRobich** [comment] 2020-04-24 17:14
Hi @andymads, I am sorry you are running into this Unity bug. I am not sure which version of the Visual Studio Code Editor package your Unity project is configured with, but this is a known issue with version 1.1.4. See this thread where they suggest downgrading to version 1.1.3 - https://forum.unity.com/threads/visual-studio-code-editor-1-1-4-error-the-referenced-project-does-not-exist.806628/. I am closing this issue as the error is caused by a bad Unity package.

**Closed by JoeRobich** 2020-04-24 17:14 UTC
Labels: Resolved-External, Triaged, Unity
