### ISSUE TITLE
1.25.2 no longer honors the formatting settings in ~/.omnisharp/omnisharp.json

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#5457] opened 2022-11-11 07:35 UTC
## Issue Description ##
Since 1.25.2 upgraded to a new version of OmniSharp, it no longer honors the formatting settings in ~/.omnisharp/omnisharp.json. 
I can confirm that 1.25.0 does not have this issue. 

## Steps to Reproduce ##
In ~/.omnisharp/omnisharp.json, I have the following settings: 
```json
{
	"FormattingOptions": {
		"SpaceAfterControlFlowStatementKeyword": false
	},
	"RoslynExtensionsOptions": {
		"LocationPaths": [
			"/Users/Yuki/Roslyn Analyzers/"
		]
	}
}
```

In VS Code, open a C# project, write the following and do a format :
```csharp
if(true)
{
}
```
## Expected Behavior ##
With the configuration, the text should not change

## Actual Behavior ##
A space is inserted after `if` despite the config. 

### OmniSharp log ###
<details>
Starting OmniSharp server at 11/11/2022, 1:24:50 AM
    Target: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/Polytone-NextGenClient.sln

OmniSharp server started with Mono 6.12.0 (/Library/Frameworks/Mono.framework/Versions/Current/).
    Path: /Users/Yuki/.vscode/extensions/ms-dotnettools.csharp-1.25.2-darwin-arm64/.omnisharp/1.39.2/omnisharp/OmniSharp.exe
    PID: 15260

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 13.0.1 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: Mono 16.10.1 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.10.1 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/Yuki/PlasticSCM/Polytone-NextGenClient'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Polytone-NextGenClient.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Runtime.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModelsV2.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Geometry.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Foundation.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/com.stella3d.sharedarray.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Legacy.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Math.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.UserExperience.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/SQLite.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.EditorTests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/Yuki/PlasticSCM/Polytone-NextGenClient'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/Yuki/PlasticSCM/Polytone-NextGenClient' on host 15225.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-firstpass.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Runtime.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Runtime.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Runtime.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/ACTk.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModelsV2.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModelsV2.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModelsV2.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Geometry.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Geometry.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Geometry.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Foundation.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Foundation.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Foundation.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/com.stella3d.sharedarray.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/com.stella3d.sharedarray.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/com.stella3d.sharedarray.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.Server.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.Server.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4DataModels.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Legacy.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Legacy.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Legacy.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Math.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Math.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4Math.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.UserExperience.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.UserExperience.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.UserExperience.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.Configuration.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/SQLite.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/SQLite.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/SQLite.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.EditorTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.EditorTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/Yuki/PlasticSCM/Polytone-NextGenClient/K4.GameFoundation.EditorTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-firstpass
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ACTk.Runtime
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ACTk.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4DataModelsV2
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4Geometry
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4.GameFoundation
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4.Foundation
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4DataModels
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: com.stella3d.sharedarray
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4DataModels.Server
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4.Legacy
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4.Configuration
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4Math
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4.UserExperience
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4.Configuration.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SQLite
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: K4.GameFoundation.EditorTests
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 489.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
</details>

### C# log ###
Empty

## Environment information ##

**VSCode version**: 1.72.0
**C# Extension**: 1.25.2

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.403 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-cpp-syntax|jeff-hykin|1.16.3|
|cpptools|ms-vscode|1.12.4|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.2|
|doxdocgen|cschlosser|1.4.0|
|errorlens|usernamehw|3.6.0|
|mono-debug|ms-vscode|0.16.3|
|shaderlabvscode|amlovey|1.2.4|
|subtitles-editor|pepri|1.1.7|
|unity-debug|deitry|3.0.11|
|vscode-antlr4|mike-lischke|2.3.1|
|vscode-clang|mitaki28|0.2.4|
|vscode-icons|vscode-icons-team|12.0.1|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|;

</details>

**Comment by filipw** [comment] 2022-11-11 08:54
Thanks for reporting. This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5446.
See https://github.com/OmniSharp/omnisharp-vscode/issues/5446#issuecomment-1308655891 for explanation

**Closed by filipw** 2022-11-11 08:54 UTC
