### ISSUE TITLE
Omnisharp intellisense not working, timeout

### ISSUE THREAD

**Issue by PrinsRR** [OmniSharp/omnisharp-vscode#1977] opened 2018-01-25 07:16 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version:
version 1.19

C# Extension version:
1.13.0
## Steps to reproduce
Install visual studio code
Install c# plugin
Create any c# project
Try anything to do with the intellisense.
## Expected  behavior
when accessing properties of a class with:
```C#
public class test{
public string mystring {get;set;}
}
public string getString(){
test testobj = new test();
return testobj.mystring;
}
```
I expect it to suggest the part "mystring" after putting the . after testobj.
## Actual behavior
Doesn't react on the '.' at all. If i use ctrl+space it gets a timeout from omnisharp.

**Comment by DustinCampbell** [comment] 2018-01-25 16:19
Thanks for reporting this issue. I'm unable to reproduce the problem you described. Could you provide your OmniSharp Log from VS Code?

**Comment by cartermp** [comment] 2020-09-22 23:31
Closing out as this doesn't reproduce and there was no additional info given.

**Closed by cartermp** 2020-09-22 23:31 UTC
Labels: Needs More Info
