### ISSUE TITLE
Generate assets for build and debug not working

### ISSUE THREAD

**Issue by wvandeneede** [OmniSharp/omnisharp-vscode#3439] opened 2019-12-03 22:04 UTC
## Issue Description ##
dotnet core 3.1/mac when choosing "Generate assets for build and debug" from the command pallet the placeholder file is generated with a new sln and mvc project.

## Steps to Reproduce ##

dotnet new sln
dotnet new mvc -o <subfolder>
dotnet sln <.sln> add <subfolder>/<.csproj>

> View - Command Pallet - .NET: Generate Assets for Build and Debug

## Expected Behavior ##
Correct launch.json and tasks.json files are generated.

## Actual Behavior ##
Error message:
Could not locate .NET Core project. Assets were not generated. 
Source: c# (Extension)

### OmniSharp log ###
<details>No Output</details>

### C# log ###
<details>No Output</details>

## Environment information ##

**VSCode version**: 1.40.2
**C# Extension**: 1.21.8

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|composer-support-client|HyperledgerComposer|0.19.12|
|csharp|ms-vscode|1.21.8|
|markdown-preview-enhanced|shd101wyy|0.5.0|
|material-icon-theme|PKief|3.9.2|
|pdf|tomoki1207|0.5.1|
|vetur|octref|0.22.6|
|vscode-firefox-debug|firefox-devtools|2.5.3|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|;

</details>

**Comment by andy-yx-chen** [comment] 2019-12-04 06:26
Getting an C# compiler error on macos

Feature 'asynchronous using' is not available in C# 7.3. Please use language version 8.0 or greater.

**Comment by JoeRobich** [comment] 2019-12-04 19:09
@andy-yx-chen Could you create a separate issue for this and provide all the logging information? Thanks!

**Comment by ghidalgo3** [comment] 2019-12-11 16:25
I can also repro this without a solution:

`dotnet new console`
`code .`

VS Code Version: 1.40.2
C# for VS Code version: 1.21.8

**Comment by achandlerwhite** [comment] 2020-01-26 00:13
I am seeing this as well.

**Comment by achandlerwhite** [comment] 2020-01-28 19:08
I also recently installed (but am not using) Visual Studio for Mac. Could that be conflicting somehow?

**Comment by gregg-miskelly** [comment] 2020-01-28 20:23
Possibly - VS for Mac might have brought a new mono, and maybe OmniSharp is having trouble with it. If you post your OmniSharp log, someone might be able to help. Make sure to open a source file to get OmniSharp to initialize. You might also have better luck with a new issue. This issue has nothing to troubleshoot in it, and most likely folks are running into the problem for different reasons anyway.

**Comment by achandlerwhite** [comment] 2020-01-29 02:30
Turns I had the option to only load a project if a file was open because my solution is complicated. Thanks for pointing me in the right direction!

**Comment by JoeRobich** [comment] 2020-03-31 01:39
@wvandeneede Does this still reproduce with the latest release? The razor team added additional support for some scenarios.

Thanks to this open ticket I also found where we were not handling .NET 5 launch.json yet and will open a PR to fix.

**Comment by cartermp** [comment] 2020-09-23 00:32
Closing out as no additional info was added.

**Closed by cartermp** 2020-09-23 00:32 UTC
Labels: Needs More Info, Triaged
