### ISSUE TITLE
launch.json and tasks.json not added when moving from project.json to .csproj

### ISSUE THREAD

**Issue by ivanmartinvalle** [OmniSharp/omnisharp-vscode#982] opened 2016-11-23 04:09 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview4-004110)

Product Information:
 Version:            1.0.0-preview4-004110
 Commit SHA-1 hash:  740a7fe3fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview4-004110
```
VS Code version: 1.6.1
C# Extension version: 1.5.3

## Steps to reproduce
1. Download the latest dotnet cli tools (preview 4)
1. mkdir foobar
1. cd foobar
1. dotnet new
1. code .

## Expected  behavior
I expect that Visual Studio Code would prompt me to add missing assets (launch.json and tasks.json).

## Actual behavior
Visual Studio Code does not prompt me to add missing assets. I'm guessing this is because whatever was adding those assets was keying off the presence of project.json, which no longer exists in the new project model.

Modifying sdk.version in global.json and changing the versions back and forth between the old and new models seems to confirm this behavior.

**Comment by DustinCampbell** [comment] 2016-11-23 04:13
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/767.

**Closed by DustinCampbell** 2016-11-23 04:13 UTC
Labels: Resolved-Duplicate
