### ISSUE TITLE
Extension Performance issue

### ISSUE THREAD

**Issue by kevin-patel** [OmniSharp/omnisharp-vscode#3650] opened 2020-03-11 04:58 UTC
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 590,
		"activateCallTime": 23,
		"activateResolvedTime": 3411,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "onLanguage:csharp"
		}
	},
	"runtimeErrors": []
}
```

**Comment by cartermp** [comment] 2020-03-12 00:59
Closing as a duplicate of #3645

**Closed by cartermp** 2020-03-12 00:59 UTC
Labels: Resolved-Duplicate, Triaged
