### ISSUE TITLE
Intelllisense errors in a vscode dotnet core 2.1 / C# project (with git diff view)

### ISSUE THREAD

**Issue by llint** [OmniSharp/omnisharp-vscode#2538] opened 2018-09-18 10:49 UTC
[Intellisense.zip](https://github.com/OmniSharp/omnisharp-vscode/files/2392732/Intellisense.zip)
#### `dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

#### VS Code version:

Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

#### C# Extension version:

1.16.1

## Steps to reproduce
0. unzip the attached sample project, notice that the project contains a partial class called `Test`, and it spans two files: `Test.cs`, and `Test2.cs` 
1. put the project under Git control (do a `git init` at the project root dir), so one can have git diff view inside vscode (the "Source Control" icon on the leftmost side of vscode)
2. make some modification to the prototype of some method, like changing the parameter name from `input` to `inputxx` in the attached file `Test2.cs` of the method `internal string foo(string input)` (use "Rename Symbol" from the right click context menu to make sure the references are also changed - no compiler errors!), save the change in vscode
3. in the vscode git tab, click the file that now has the changes, so the vscode would show the git diff view of the file
4. hover the mouse on the changed variable, and see some Intellisense tips showing up, and hover your mouse anywhere around the project (like clicking open another file, and hovering the mouse pointer on top of random symbols)
5. now close the git diff view file tab - *IMPORTANT* the git diff view file tab needs to be CLOSED in order for the Intellisense errors to be showing up!
6. under the "Problems" output window in vscode, you *should* now see that Intellisense is complaining about various random syntax errors, e.g. `s` is not defined in `Test`, or something similar
7. build and run the project, it still works as expected.

## Expected  behavior
The Intellisense should not display random syntax errors after opening and closing the modified file diff view, while the source code is proved to be valid with normal build and run.

## Actual behavior
The Intellisense displays random syntax errors, even though there are no syntax errors!

## Summary
This issue seems to be related to git diff view, causing Intellisense to become messed up.

**Comment by zvinless** [comment] 2018-09-18 16:58
I'm seeing this too, or at least something very similar. Couldn't figure out how to repro until you mentioned git diff view! All I have to do is open the diff view on a script and close it; after that, I get red squigglies wherever that script's class is referenced (`The type or namespace name could not be found...`), even without any partial classes. I have to reload VSCode to fix it.

**Comment by llint** [comment] 2018-09-19 02:02
> I'm seeing this too with a Unity project, or at least something very similar. Couldn't figure out how to repro until you mentioned git diff view! All I have to do is open the diff view on a script and close it; after that, I get red squigglies wherever that script's class is referenced (`The type or namespace name could not be found...`), even without any partial classes. I have to reload VSCode to fix it.

@zvinless you are right, partial class is not required to reproduce this issue. I'm able to merge the partial class `Test` (also removing `partial` keyword), and Git diff view alone would solidly reproduce the issue.

**Comment by Marchyello** [comment] 2018-09-19 08:54
Same issue on Ubuntu 16.04.
It seems that any diff can trigger the issue (no need for partial class or anything specific). 
It's also (at least for me) not necessary to close the diff view to trigger the issue. I can reliably reproduce it just by switching between different files in Source Control. I could've sworn that at times the issue could even be triggered just by opening diff view and waiting a bit, but right now I can't seem to be able to reproduce it that way.

**Comment by akshita31** [comment] 2018-09-20 03:04
@llint I am definitely able to reproduce the error. I seems that when the file is opened in git view, omnisharp process deleted the file from the workspace, hence the intellisense seems messed up. Thanks for filing, we are investigating.

**Comment by akshita31** [comment] 2018-09-20 23:59
@rchande I investigated the issue here and here is what I found:

1. Whenever we open the git view, the extension identifies the document as a virtual document,and asks omnisharp to add it to the workspace. Since, omnisharp already knows about this document so it doesn't do anything here.
2. Now when we navigate away from diff view, the close virtual document is triggered and it sends a request to omnisharp to delete the document: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/virtualDocumentTracker.ts#L83.
3. Now since omnisharp has removed a document from the workspace that should not have been removed, the intellisense breaks and we get unexpected errors.

cc @NTaylorMullen Since this is related to the virtual document change, do you have any ideas how we can fix this?

**Comment by NTaylorMullen** [comment] 2018-09-21 00:12
@akshita31 files should probably be represented on the server via their URI not their path if this is an issue. That way different URI schemes wont conflict when adding/removing documents.

Another solution would be to only listen to virtual documents under a specific non-file scheme. It'd be something you'd have to document but would allow people who are interested in having virtual C# documents have them but also not have virtual C# documents conflict with already-existing extensions.

**Comment by rchande** [comment] 2018-09-21 20:58
@akshita31 @NTaylorMullen Maybe the solution is to add some kind of ref-counting to documents? By default, a document discovered through msbuild would have one reference. Opening the same path in git increments it, and closing the git copy of the file would decrement the count to 1, not 0. 

cc @DustinCampbell

**Comment by talyh** [comment] 2018-09-25 18:02
I've never had this issue until I recently started working on a new project. Maybe it's something that changed on omnisharp, but, more than that, this project uses a `~/.omnisharp/omnisharp.json`, which I haven't been doing before.
By cleaning up the json (ie. it still exists in the folder, but it's empty), the problem seems to go away (though far from a permanent solution).

**Closed** 2018-10-02 17:17 UTC
Labels: Bug

**Comment by rchande** [comment] 2018-10-02 18:08
@llint We have a release that we believe should fix this. Would you mind trying the beta vsix from [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta3) and letting us know if that resolves the issue?

**Comment by zvinless** [comment] 2018-10-03 18:06
@rchande I installed the newest beta and it fixed it for me! 👍

**Comment by llint** [comment] 2018-10-04 03:17
I installed the beta release following the link provide, and I can confirm that the issue has been fixed. Looking forward to the official release soon. Thanks for the quick action.

**Comment by rchande** [comment] 2018-10-04 16:08
@llint @zvinless Glad it works for you--thanks for taking the time to let us know!
