### ISSUE TITLE
Debugger: [Remote] Steps by statement instead of by line in VSCode

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1303] opened 2017-03-09 11:10 UTC
## Environment data
`dotnet --info` output:
**Server machine:**
      OS: OpenSUSE13.2
      .NET Core SDK:1.0.1
      VsDbg: https://aka.ms/getvsdbgsh
**Client machine:**
     OS: Ubuntu 16.04
     VSCode: 1.10.2 
     C# extension: v1.8.0-beta2

## Steps to reproduce
1. Open attached folder with VSCode on Client and Server Machine.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/830607/hwapp.zip)
2. Update the ".NET Core Remote Attach" configuration on launch.json file on Client Machine.
3. Dotnet run hwapp process on server machine with Terminal.
4. Remote attached the server process on client machine in VSCode
5. Set a breakpoint at the line which contains text " fun();  "
6. F11 -> F11 -> F11

## Expected  behavior
The cursor still stay at the line which contains test " for(int i=0; i<5; i++)"

## Actual behavior
The cursor hit line of 11.

## Investigation
At same scenario, the cursor hit line of 11 on local debugging , could you help me confirm this issue?

**Comment by gregg-miskelly** [comment] 2017-03-09 17:53
@GraceDong I am fairly certain this is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/1271. I will resolve it for now, but please verify once we send out the next release.

**Closed** 2017-03-09 17:53 UTC
Labels: Debugger, Resolved-Duplicate
