### ISSUE TITLE
 Extension causes high cpu load 

### ISSUE THREAD

**Issue by nopogo** [OmniSharp/omnisharp-vscode#3668] opened 2020-03-15 12:01 UTC
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4334149/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

**Comment by Thaina** [comment] 2020-03-17 05:57
Me too

[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4341669/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

**Comment by FrankHermes** [comment] 2020-03-17 09:16
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4342523/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

Same here, I can only work with Unity and VS Code using `1.21.12`

**Comment by zendu** [comment] 2020-03-17 18:32
Seems to be duplicate of #3645

**Comment by JoeRobich** [comment] 2020-03-17 20:31
Unfortunately these javascript logs are not actionable. If we could get a perf view trace, we might have information we can work from. Here are instructions for gathering a trace - https://github.com/dotnet/roslyn/blob/master/docs/wiki/Recording-performance-traces-with-PerfView.md

**Closed by JoeRobich** 2020-03-17 20:31 UTC
Labels: Resolved-Not Reproducible, Triaged

**Comment by Thaina** [comment] 2020-03-18 02:05
@JoeRobich Why close then?

**Comment by filipw** [comment] 2020-03-19 05:10
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.
