### ISSUE TITLE
Errors/Warnings failing again

### ISSUE THREAD

**Issue by Novack-** [OmniSharp/omnisharp-vscode#889] opened 2016-11-08 16:37 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

VS Code version: 1.7.1

C# Extension version: 1.5.0beta4

## Steps to reproduce
Install VSCode 1.7.1

## Expected  behavior
See issue #812 for details. 

## Actual behavior
After installing 1.7.1 the issue described in #812 is back again. Tried uninstalling and reinstalling 1.5.0beta4 without result.

As a side note, context and background, at the moment, Im forced to use VSPro.

**Comment by HawkenKing** [comment] 2016-11-15 16:48
same here, when I move the cursor, the red underline squiggles disappear.

**Comment by Novack-** [comment] 2016-11-15 16:57
@HawkenKing please use the :+1: on the main post here, issues gets sorted using that criteria... ¬¬

Not that this is a small thingie, basically VS Code becomes obsolete for Unity developers. Im coming back to Visual Studio and ScriptInspector3. Is a pitty because I really like Code, but the C# support is unstable to say the least, debugging is clumsy and intellisense far too limited. I'll try again in a few years :)

**Comment by DustinCampbell** [comment] 2016-11-16 19:55
@HawkenKing, @Novack- it looks like this is actually a bug in VS Code. I investigate #883 and found that the issue is not caused by the C# extension. It's likely an easy fix though. The details are in #883. I've filed https://github.com/Microsoft/vscode/issues/15585 to track getting this fixed in VS Code.

**Comment by DustinCampbell** [comment] 2016-11-17 16:02
It looks like a solid fix has been checked into VS Code. We should start seeing this working properly in VS Code Insiders builds soon.

**Closed by DustinCampbell** 2016-11-17 16:02 UTC
Labels: Bug, Resolved-External

**Comment by Novack-** [comment] 2016-11-17 17:38
Thank you.

**Comment by Novack-** [comment] 2016-11-23 19:34
@DustinCampbell happening again on latest stable setup: Code 1.7.2, omnisharp 1.5.3

**Comment by DustinCampbell** [comment] 2016-11-23 20:58
I don't believe the fix is in VS Code 1.7.2, which is a recovery build with a very specific fix. It should be in VS Code Insider builds. cc @jrieken to confirm.

**Comment by Novack-** [comment] 2016-11-23 21:47
@DustinCampbell Sorry man. Got carried by the anxiety.

**Comment by DustinCampbell** [comment] 2016-11-23 22:15
No problem. :smile:

**Comment by jrieken** [comment] 2016-11-24 08:38
re https://github.com/OmniSharp/omnisharp-vscode/issues/889#issuecomment-262628438 correct. This is insiders already today and will be in 1.8 which arrives mid december
