### ISSUE TITLE
dyld: Library not loaded. Reason: image not found

### ISSUE THREAD

**Issue by jersson** [OmniSharp/omnisharp-vscode#3555] opened 2020-02-06 04:01 UTC
## Environment data
**VSCode version**: 1.41.1
**C# Extension**: 1.21.10

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-vscode|1.21.10|
|ginfuru-vscode-jekyll-syntax|ginfuru|0.1.0|
|LiveServer|ritwickdey|5.6.1|
|mssql|ms-mssql|1.8.0|
|python|ms-python|2020.1.58038|
|r|Ikuyadeu|1.2.2|
|vetur|octref|0.23.0|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-jekyll-snippets|ginfuru|0.9.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.4|;

</details>

## Steps to reproduce
Open Visual Studio Code with dotnet web api project 

## Expected  behavior
Regular use of Code with dotnet projects

## Actual behavior
Terminal output:

Starting OmniSharp server at 2/5/2020, 10:55:08 PM
    Target: /Users/jersson/src/microservices-templates/02-netcore/00-template

OmniSharp server started.
    Path: /Users/jersson/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run
    PID: 44257

dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
  Referenced from: /Users/jersson/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/bin/mono
  Reason: image not found
/Users/jersson/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run: line 28: 44262 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by TingluoHuang** [comment] 2020-02-06 04:28
+1

**Comment by filipw** [comment] 2020-02-06 04:49
this is resolved in 1.21.11 in prerelease https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.11

**Comment by filipw** [comment] 2020-02-06 07:08
closing as duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1693 and https://github.com/OmniSharp/omnisharp-vscode/issues/3545

**Closed by filipw** 2020-02-06 07:08 UTC
Labels: Resolved-Duplicate
