### ISSUE TITLE
Debugger: Take more time to hit breakpoint in loop

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1265] opened 2017-02-27 09:35 UTC
## Environment data
dotnet --info output:
OS: Zorin 12 x64
VS Code version: 1.9.1
C# Extension version: 1.8.0-beta1
dotnet cli: 1.0.0-preview2-1-003177

## Steps to reproduce
1. Open attached folder with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/802942/hwapp.zip)
2. Select '.NET Core Launch.
3. F5 to start debugging 
4. When the program running, set a breakpoint at line of 11 in Program.cs

## Expected  behavior
The breakpoint should be hit as soon as possible.

## Actual behavior
When the breakpoint is hit, the value of elapsed is more than 2 minute.

## Investigation
When I configuration “engineLogging” value is true in launch.json ,  hit breakpoint spend 27 second.

**Comment by gregg-miskelly** [comment] 2017-02-27 17:15
@GraceDong are you using a single core VM? If so, does this still feel slow if you use a multi-core VM?

**Comment by GraceDong** [comment] 2017-02-28 01:03
@gregg-miskelly Yes, it still slow when I use a multi-core VM.

**Comment by WardenGnaw** [comment] 2017-03-03 00:30
@GraceDong Can you share the output from ```cat /etc/os-release``` on your dev box?

**Comment by GraceDong** [comment] 2017-03-03 10:06
@gregg-miskelly @WardenGnaw  This issue not reproduce on \\scratch2\scratch\janraj\vsdbg3\csharp-1.8.0-beta1.vsix. Attached here to os-release, hope to help you analyze.
[os-release.txt](https://github.com/OmniSharp/omnisharp-vscode/files/816432/os-release.txt)

**Comment by WardenGnaw** [comment] 2017-03-06 20:43
Tested this on Zorin OS 12 and 12.1. Also could not reproduce with \\scratch2\scratch\janraj\vsdbg3\csharp-1.8.0-beta1.vsix. Closing issue. Thanks for the help @GraceDong!

**Closed by WardenGnaw** 2017-03-06 20:43 UTC
Labels: Debugger, Debugger-Poachable
