### ISSUE TITLE
Incorrect Code Suggestions

### ISSUE THREAD

**Issue by cobbertine** [OmniSharp/omnisharp-vscode#5103] opened 2022-03-10 07:28 UTC
## Issue Description ##
This extension has recently begun to offer incorrect code suggestions. The "await" keyword is being suggested when I am creating a new for loop with the standard "i" variable. 

## Steps to Reproduce ##
Refer to the code example below:

```cs
public class Main
{
    public void test()
    {
        for(int i = 0; i // <<< At this point here, VSCode will display a popup with "await" as the suggested option. If you continue typing, it will add this in AND modify the method signature, adding the async keyword.
    }
}
```

![vscode-suggestion-forloop](https://user-images.githubusercontent.com/66068533/157609200-4660fec2-ff92-4ea0-a00c-fbba37355be3.png)

## Expected Behavior ##
The local variable "i" should be the top suggestion, causing the "i" to be added in the for loop as expected.

## Actual Behavior ##
The local variable "i" is the second suggestion from the top, causing the "await" keyword suggestion to be used, which adds the "async" keyword to the method signature as well as adding the "await" keyword in the for loop.

### OmniSharp log ###
<details>
Starting OmniSharp server at 10/03/2022, 5:56:32 pm
    Target: c:\\Users\\cobbertine\\Desktop\\deletein1sec

OmniSharp server started.
    Path: c:\\Users\\cobbertine\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.1\\.omnisharp\\1.38.1\\OmniSharp.exe
    PID: 27908

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.1.0 - "c:\\Users\\cobbertine\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.1\\.omnisharp\\1.38.1\\.msbuild\\Current\\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\\Users\\cobbertine\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.1\\.omnisharp\\1.38.1\\.msbuild\\Current\\Bin\\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.1.0 - "c:\\Users\\cobbertine\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.1\\.omnisharp\\1.38.1\\.msbuild\\Current\\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\\Users\\cobbertine\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.1\\.omnisharp\\1.38.1\\.msbuild\\Current\\Bin\\Roslyn
            MSBuildExtensionsPath = c:\\Users\\cobbertine\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.1\\.omnisharp\\1.38.1\\.msbuild
            MSBuildToolsPath = c:\\Users\\cobbertine\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.1\\.omnisharp\\1.38.1\\.msbuild\\Current\\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\\Users\\cobbertine\\Desktop\\deletein1sec'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\\Users\\cobbertine\\Desktop\\deletein1sec'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\\Users\\cobbertine\\Desktop\\deletein1sec'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\\Users\\cobbertine\\Desktop\\deletein1sec' on host 4716.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No document found. File: c:\\Users\\cobbertine\\Desktop\\deletein1sec\\Main.cs.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\\Users\\cobbertine\\Desktop\\deletein1sec\\Main.cs added to workspace
Received response for /findusages but could not find request.
Received response for /findusages but could not find request.
Received response for /v2/getcodeactions but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\\Users\\cobbertine\\Desktop\\deletein1sec\\Main.cs, Line: 2, Column: 22.

</details>

### C# log ###
<details>No Output</details>

## Environment information ##

**VSCode version**: 1.65.1
**C# Extension**: 1.24.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.416
 Commit:    8d3765c609

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.416\

Host (useful for support):
  Version: 5.0.14
  Commit:  d5b56c6327

.NET SDKs installed:
  3.1.120 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.24.1|
|remote-ssh|ms-vscode-remote|0.76.1|
|remote-ssh-edit|ms-vscode-remote|0.76.1|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|;

</details>

**Comment by heshuimu** [comment] 2022-03-13 07:28
Same here. It's the same behavior if I use a lambda with the argument being `i` or `a`, and if I type dot it will think that i accepted the selection and insert both async and await in the lambda expression. Very annoying. 

Actually, may I also suggest that language keywords should not even be in suggestion list at all? For every C# programmer we should already know all know what `static` or `void` is. Even if someone don't know what `stackalloc` or `async` is, they probably are not at the point that they have to know this keyword, and they are not gonna be learning this through Auto-Completion.

**Comment by JoeRobich** [comment] 2022-03-18 00:02
Closing as duplicate of #5096.

**Closed by JoeRobich** 2022-03-18 00:02 UTC
