### ISSUE TITLE
Selecting a solution file shows the source instead of loading all the projects

### ISSUE THREAD

**Issue by netbitshift** [OmniSharp/omnisharp-vscode#3526] opened 2020-01-24 16:19 UTC
**system info**
Version: 1.41.1 (system setup)
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

csharp extension version# 1.21.9

Choose File > Open file, choose a recently created solution file created with VS 2019. You get the source of the solution file instead of VS Code loading the projects within in it

The docs say otherwise - that the projects are supposed to be loaded
https://code.visualstudio.com/docs/languages/csharp
> Selecting a *.sln file opens a MSBuild-project. It will load the referenced *.csproj projects and sibling or descendant project.json files but no other project files that are referenced from the solution file.

**My currently installed extensions**
clintonrost.theme-firefox-devtools
codemooseus.vscode-devtools-for-chrome
firefox-devtools.vscode-firefox-debug
formulahendry.dotnet-test-explorer
jmrog.vscode-nuget-package-manager
ms-mssql.mssql
ms-vscode.csharp
ms-vscode.powershell
ms-vsts.team
msjsdiag.debugger-for-chrome
vincaslt.highlight-matching-tag

**Comment by JoeRobich** [comment] 2020-01-24 20:18
Hi @netbitshift,

The VS Code experience is a little different than that of VS. Instead of loading a project or solution file, you will open a folder which contains your code. The C# extension will then try and find the solution and project files that are in the folder or the folder's subfolders. It will then open one of those. If it opens the wrong project or solution file, you can click on the project selector at the bottom of the IDE to choose the correct one.

![image](https://user-images.githubusercontent.com/611219/73100842-46677c80-3ea3-11ea-843d-b3117dd90fe5.png)

**Comment by cartermp** [comment] 2020-03-19 20:59
Closing as by design

**Closed by cartermp** 2020-03-19 20:59 UTC
Labels: Resolved-By Design, Triaged
