### ISSUE TITLE
VS Code extension: Debugger gets stuck in "Paused at ..." status

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#307] opened 2016-05-11 19:16 UTC
##### Description
Can get into a state where the Call Stack window shows "Paused on Step", "Paused at Exception" or similar though no threads appear to be stopped. That is, the application is responsive while the debugger is in this state.

This may relate somewhat to #208 since I see `ERROR: Unknown Error: 0x9233000b` in the Debug Console most of time this occurs.

##### Repro steps
1. `git clone https://github.com/aspnet/MusicStore.git`
 - Have seen similar issues elsewhere but this app reliably hits exceptions while loading the home page.
2. `cd MusicStore`
3. `./build.sh --quiet initialize`
4. `cd src/MusicStore`
5. `code .`
6. Set a breakpoint in the `HomeController.Index()` method.
7. F5
8. At breakpoint, step out (into MVC framework code)
9. F5

Expected: Paused on Step message should clear itself.
Actual: Web site responds but Paused on Step message remains.

Have also seen this occur after stepping through to the last line of the `HomeController.Index()` method. Suspect this is a more general issue than the repro indicates.

##### Environment
VS Code: `1.1.0`
VS Code extension: `v1.0.5-rc2`
.NET CLI: `1.0.0-preview1-002700`
Platform: Happens on Windows, Ubuntu 14.04 LTS, Mint 17.2, and probably elsewhere

**Comment by dougbu** [comment] 2016-05-11 19:18
For example ![paused](https://cloud.githubusercontent.com/assets/6431421/15193374/7a62ceba-1772-11e6-98ac-34c689ae1663.png)

**Comment by gregg-miskelly** [comment] 2016-05-11 19:24
Can you follow https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging to gather a log and attach it to the bug?

**Comment by dougbu** [comment] 2016-05-13 23:03
[cs-debug.txt](https://github.com/OmniSharp/omnisharp-vscode/files/264206/cs-debug.txt)

**Comment by gregg-miskelly** [comment] 2016-05-13 23:08
Looks like this is a dupe of https://github.com/Microsoft/vscode/issues/6304, There will be a new VS Code Monday morning with the fix.

**Closed** 2016-05-13 23:09 UTC
Labels: Bug, Debugger, Debugger-Poachable
