### ISSUE TITLE
Clicking code lens: "run test" or "debug test" fails.

### ISSUE THREAD

**Issue by cja-careon** [OmniSharp/omnisharp-vscode#1319] opened 2017-03-13 15:06 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

VS Code version:
1.10.2

C# Extension version:
1.7.0

## Steps to reproduce
In the source of an XUnit test click on code lens: "run test" or "debug test"

## Expected  behavior
Test should run.

## Actual behavior
Shows error message: "Failed to run test because null."
Omnisharp Log shows:
```
[fail]: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
        An unhandled exception has occurred: Value cannot be null.
Parameter name: path1
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at OmniSharp.DotNetTest.Helpers.ProjectPathResolver.GetProjectPathFromFile(String filepath) in C:\projects\omnisharp-roslyn\src\OmniSharp.DotNetTest\Helpers\ProjectPathResolver.cs:line 11
   at OmniSharp.DotNetTest.Services.RunTestServices.GetResponse(String filepath, String methodName, String testFrameworkName) in C:\projects\omnisharp-roslyn\src\OmniSharp.DotNetTest\Services\RunTestService.cs:line 32
   at OmniSharp.DotNetTest.Services.RunTestServices.Handle(RunDotNetTestRequest request) in C:\projects\omnisharp-roslyn\src\OmniSharp.DotNetTest\Services\RunTestService.cs:line 27
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\Middleware\EndpointMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
[info]: OmniSharp.Middleware.LoggingMiddleware
        /v2/runtest: 500 12ms
```

**Comment by DustinCampbell** [comment] 2017-03-13 15:30
Hi! This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1100. The feature simply isn't implemented for .csproj-based .NET Core projects yet. We're working on it right now.

**Closed by DustinCampbell** 2017-03-13 15:30 UTC
Labels: Resolved-Duplicate
