### ISSUE TITLE
".NETFramework,Version=v5.0.100" not found when Visual Studio 2019 is < 16.8

### ISSUE THREAD

**Issue by tomschrot** [OmniSharp/omnisharp-vscode#4200] opened 2020-11-10 23:13 UTC
dotnet --version

5.0.100

dotnet new console -o Test5

->
`
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
`
**(change TargetFramework to netcoreapp3.1 does not crash omnisharp!? )**
->

Starting OmniSharp server at 10.11.2020, 23:57:21
    Target: c:\Users\Tom\Desktop\DOTNET\work\test5

OmniSharp server started.
    Path: c:\Users\Tom\.vscode\extensions\ms-dotnettools.csharp-1.23.5\.omnisharp\1.37.3\OmniSharp.exe
    PID: 3092

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.7.30621.155 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\Tom\.vscode\extensions\ms-dotnettools.csharp-1.23.5\.omnisharp\1.37.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.7.30621.155 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Tom\Desktop\DOTNET\work\test5'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Tom\Desktop\DOTNET\work\test5'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Tom\Desktop\DOTNET\work\test5\test5.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Tom\Desktop\DOTNET\work\test5'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Tom\Desktop\DOTNET\work\test5\test5.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Tom\Desktop\DOTNET\work\test5' on host 12268.
[fail]: OmniSharp.MSBuild.ProjectLoader
        Die Verweisassemblys für ".NETFramework,Version=v5.0.100" wurden nicht gefunden. Installieren Sie zum Beheben dieses Problems das Developer Pack (SDK/Paket zur Festlegung von Zielversionen) für diese Frameworkversion, oder richten Sie Ihre Anwendung neu aus. Sie können .NET Framework Developer Packs unter https://aka.ms/msbuild/developerpacks herunterladen.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Tom\Desktop\DOTNET\work\test5\test5.csproj'.
c:\Users\Tom\Desktop\DOTNET\work\test5\test5.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: Die Verweisassemblys für ".NETFramework,Version=v5.0.100" wurden nicht gefunden. Installieren Sie zum Beheben dieses Problems das Developer Pack (SDK/Paket zur Festlegung von Zielversionen) für diese Frameworkversion, oder richten Sie Ihre Anwendung neu aus. Sie können .NET Framework Developer Packs unter https://aka.ms/msbuild/developerpacks herunterladen.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\Tom\Desktop\DOTNET\work\test5\test5.csproj

**Comment by JustinGrote** [comment] 2020-11-10 23:56
FWIW my omnisharp works fine with 5.0, I install it via install-dotnet.ps1 -Channel "release/5.0.1xx"

**Comment by JoeRobich** [comment] 2020-11-10 23:58
@tomschrot Sorry you are running into issues. See this note one using .NET 5 - https://github.com/OmniSharp/omnisharp-vscode#note-about-using-net-5-sdks. It seems like the issue is that you have VS 16.7 installed, but .NET 5 requries the MSBuild from VS 16.8.

**Comment by Banyc** [comment] 2020-11-11 04:24
@JoeRobich Why Omnisharp is depending on MSBuild?

**Comment by tomschrot** [comment] 2020-11-11 09:16
@JoeRobich 

I dont think that is the problem

C:\Users\Tom>dotnet build
Microsoft (R)-Build-Engine, Version 16.8.0+126527ff1 für .NET
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

**Comment by filipw** [comment] 2020-11-11 09:23
@tomschrot the MSBuild verrsion reported by the dotnet CLI doesn't matter.
according to your log Omnisharp is picking up MSBuild form Visual Studio 16.7 which is not suitable for .N ET 5.0 RTM

```
Registered MSBuild instance: Visual Studio Community 2019 16.7.30621.155 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
```

Omnisharp will always prefer to use Visual Studio MSBuild if it's found on the user's machine over its own. YOu need to updated Visual Studio to a version (16.8) that supports .NET 5.0 RTM or uninstall it 🙂

**Comment by tomschrot** [comment] 2020-11-11 09:32
@filipw
like magic, the VS installer just claimed to update to 16.8 ....
I will report!

**Comment by filipw** [comment] 2020-11-11 09:42
VS2019 16.8 was released yesterday. Previously you'd need to have VS 2019 Preview installed (or, like I said, no VS at all)

**Comment by tomschrot** [comment] 2020-11-11 10:08
YES! 
Updated VS to 16.8
omnisharp works with target net5.0!

Oh boy - long struggle.

Thanks everybody for the efforts.

The questions remains: does omnisharp need such dependency?

**Comment by filipw** [comment] 2020-11-11 11:15
OmniSharp ships with minimal MSBuild which is not suitable for any other development than .NET Core.
VS (or Mono on unix) MSBuild is more complete - mainly cause it can work desktop .NET development, Unity and so on.

That's why OmniSharp prefers VS MSbuild  when found. This is also mentioned here https://github.com/OmniSharp/omnisharp-vscode#note-about-using-net-5-sdks

Note that this only causes trouble when there are breaking MSBuild changes - which is unfortunately the special case here (.NET 5  has a hard dependency on MSBuild 16.8), in most other cases it has no significance if your VS is updated to the latest version, since older MSBuild works well too.

I will close this issue since this behavior was as design - thanks.

**Closed by filipw** 2020-11-11 11:15 UTC
