### ISSUE TITLE
VSCode cannot start OmniSharp.exe on Windows 10 32 bit.

### ISSUE THREAD

**Issue by JunTaoLuo** [OmniSharp/omnisharp-vscode#457] opened 2016-06-21 17:41 UTC
## Environment data
`dotnet --info` output: 1.0.0-preview2-003118
VS Code version: 1.2.1
C# Extension version: 1.1.6

## Steps to reproduce
Open any .NETCore project

## Expected  behavior
OmniSharp launches correctly and the c# extension gives intellisense, xunit test support ...

## Actual behavior
From the OmniSharp Log it seems like the OmniSharp executable was not launched correctly so the c# extension is not available:
```
[INFO] Started OmniSharp from 'C:\Users\johluo\.vscode\extensions\ms-vscode.csharp-1.1.6\.omnisharp\OmniSharp.exe' with process id 724...
This version of C:\Users\johluo\.vscode\extensions\ms-vscode.csharp-1.1.6\.omnisharp\OmniSharp.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
[ERROR] Error: Failed to start OmniSharp
```

Is OmniSharp supported for 32 bit operating systems?

cc @troydai

**Comment by troydai** [comment] 2016-06-21 18:04
@DustinCampbell @david-driscoll

**Comment by chuckries** [comment] 2016-06-21 20:13
Duplicate of #338

**Closed** 2016-06-21 20:13 UTC
Labels: OmniSharp-Install, Resolved-Duplicate
