### ISSUE TITLE
Add "run tests" and "debug tests" code lens actions to test classes

### ISSUE THREAD

**Issue by bittercoder** [OmniSharp/omnisharp-vscode#1622] opened 2017-07-03 21:09 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

VS Code version: 1.13.1

C# Extension version: 1.11.0

## Production Suggest

It would be great if the dotnet testing code lens could include "run tests" and "debug tests" actions on the class if it contains 1 or more test methods, this workflow is really useful when TDD'ing.

**Comment by DustinCampbell** [comment] 2017-07-04 22:52
Hi! This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/420.

**Closed by DustinCampbell** 2017-07-04 22:52 UTC
Labels: Resolved-Duplicate
