### ISSUE TITLE
Extension is reporting problems with files in node_modules

### ISSUE THREAD

**Issue by ceottaki** [OmniSharp/omnisharp-vscode#2057] opened 2018-02-20 16:32 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

VS Code version: 1.20.1
C# Extension version: 1.14.0

## Steps to reproduce
Open a .NET Core project folder that contains a node_modules folder that includes cs files such as `selenium-webdriver`.

## Expected  behavior
The extension should ignore problems in the node_modules folder. It may be related to issue  #1990.

## Actual behavior
The extension reports, in the problems tab, problems with CS files contained in the node_modules folder.

**Comment by rchande** [comment] 2018-02-20 20:40
@akshita31 Can you take a look?

**Comment by DustinCampbell** [comment] 2018-02-27 14:18
FWIW, this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1990. The legacy OmniSharp project.json project system needs to be updated to not search in node_modules. This should be a straightforward change in omnisharp-roslyn. I'll close this as a dupe and assign #1990 to @akshita31.

**Closed by DustinCampbell** 2018-02-27 14:18 UTC
