### ISSUE TITLE
cannot open VS 2010 solution

### ISSUE THREAD

**Issue by gideondsouza** [OmniSharp/omnisharp-vscode#1213] opened 2017-02-09 10:48 UTC
For the life of me I cannot load a VS2010 solution with two C# Projects a Console and a Class Lib. I copied these to my fedora 24 machine 

## Environment data
`dotnet --info` output:
 OS Name:     fedora
 OS Version:  24
 OS Platform: Linux
 RID:         fedora.24-x64

VS Code version:
Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:21:13.228Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

C# Extension version: 1.6.2

## Steps to reproduce

1. Navigate with the Explorer to a folder that has target solution file.
2. After a few seconds there is a list on the top center of all projects and solutions.
3. Select the solution you want to open. 

## Expected  behavior
Solution should load (not sure how it's expected to load, haven't seen it load yet)

## Actual behavior
I get this in the OmniSharp log:
Starting OmniSharp server at 9/2/2017, 4:11:18 PM
    Target: /home/gideon/Coding/csharp/YAL/YAL.sln

OmniSharp server started wth Mono
    Path: /home/gideon/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/run
    PID: 4164

OmniSharp: -s /home/gideon/Coding/csharp/YAL/YAL.sln --hostPID 3860 --stdio DotNet:enablePackageRestore=false --encoding utf-8 formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/home/gideon/Coding/csharp/YAL' on host 3860."},"Seq":1,"Type":"event"}
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /home/gideon/Coding/csharp/YAL
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] MSBUILD_EXE_PATH environment variable set to /home/gideon/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/omnisharp/msbuild/MSBuild.dll
[INFORMATION:OmniSharp#MSBuild] MSBuildExtensionsPath environment variable set to /home/gideon/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/omnisharp/msbuild
[INFORMATION:OmniSharp#MSBuild] MSBuildSDKsPath environment variable set to /home/gideon/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/omnisharp/msbuild/Sdks
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/home/gideon/Coding/csharp/YAL/YAL.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using TargetFrameworkRootPath: /usr/lib/mono/xbuild-frameworks
[WARNING:OmniSharp#ProjectFileInfo] No assemblies were read in from the redist lists. A TargetFramework profile exclusion list could not be generated. 
[WARNING:OmniSharp#MSBuild] Failed to process project file '/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj'.
/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj(1,1)
System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \\server\share.
  at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation (System.String resourceName, System.Object[] args) [0x00019] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation (System.Boolean condition, System.String resourceName, System.Object arg0, System.Object arg1, System.Object arg2) [0x0000a] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Shared.FileUtilities+ItemSpecModifiers.GetItemSpecModifier (System.String currentDirectory, System.String itemSpec, System.String definingProjectEscaped, System.String modifier, System.String& fullPath) [0x004f2] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped (System.String currentDirectory, System.String evaluatedIncludeBeforeWildcardExpansionEscaped, System.String evaluatedIncludeEscaped, System.String definingProjectEscaped, System.String name, System.String& fullPath) [0x0002e] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetBuiltInMetadataEscaped (System.String name) [0x00012] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadataEscaped (System.String metadataName) [0x000ce] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadata (System.String metadataName) [0x00001] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at (wrapper remoting-invoke-with-check) Microsoft.Build.Execution.ProjectItemInstance+TaskItem:GetMetadata (string)
  at Microsoft.Build.Execution.ProjectItemInstance.GetMetadataValue (System.String name) [0x00001] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.GetFullPaths (System.Collections.Generic.ICollection`1[T] items) [0x0001b] in <e01e10ddee6e4ce381cb8602e4700e1c>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create (System.String projectFilePath, System.String solutionDirectory, Microsoft.Extensions.Logging.ILogger logger, OmniSharp.Options.MSBuildOptions options, System.Collections.Generic.ICollection`1[T] diagnostics, System.Boolean isUnityProject) [0x002c5] in <e01e10ddee6e4ce381cb8602e4700e1c>:0 
  at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProjectFileInfo (System.String projectFilePath, System.Boolean isUnityProject) [0x00024] in <e01e10ddee6e4ce381cb8602e4700e1c>:0 

/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj

[INFORMATION:OmniSharp#MSBuild] Loading project from '/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using TargetFrameworkRootPath: /usr/lib/mono/xbuild-frameworks
[WARNING:OmniSharp#ProjectFileInfo] No assemblies were read in from the redist lists. A TargetFramework profile exclusion list could not be generated. 
[WARNING:OmniSharp#MSBuild] Failed to process project file '/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj'.
/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj(1,1)
System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \\server\share.
  at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation (System.String resourceName, System.Object[] args) [0x00019] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation (System.Boolean condition, System.String resourceName, System.Object arg0, System.Object arg1, System.Object arg2) [0x0000a] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Shared.FileUtilities+ItemSpecModifiers.GetItemSpecModifier (System.String currentDirectory, System.String itemSpec, System.String definingProjectEscaped, System.String modifier, System.String& fullPath) [0x004f2] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped (System.String currentDirectory, System.String evaluatedIncludeBeforeWildcardExpansionEscaped, System.String evaluatedIncludeEscaped, System.String definingProjectEscaped, System.String name, System.String& fullPath) [0x0002e] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetBuiltInMetadataEscaped (System.String name) [0x00012] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadataEscaped (System.String metadataName) [0x000ce] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadata (System.String metadataName) [0x00001] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at (wrapper remoting-invoke-with-check) Microsoft.Build.Execution.ProjectItemInstance+TaskItem:GetMetadata (string)
  at Microsoft.Build.Execution.ProjectItemInstance.GetMetadataValue (System.String name) [0x00001] in <47da9606561546bfbe7ffd90f0d7b3c2>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.GetFullPaths (System.Collections.Generic.ICollection`1[T] items) [0x0001b] in <e01e10ddee6e4ce381cb8602e4700e1c>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create (System.String projectFilePath, System.String solutionDirectory, Microsoft.Extensions.Logging.ILogger logger, OmniSharp.Options.MSBuildOptions options, System.Collections.Generic.ICollection`1[T] diagnostics, System.Boolean isUnityProject) [0x002c5] in <e01e10ddee6e4ce381cb8602e4700e1c>:0 
  at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProjectFileInfo (System.String projectFilePath, System.Boolean isUnityProject) [0x00024] in <e01e10ddee6e4ce381cb8602e4700e1c>:0 

/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj

[INFORMATION:OmniSharp.Script.ScriptProjectSystem] Detecting CSX files in '/home/gideon/Coding/csharp/YAL'.
[INFORMATION:OmniSharp.Script.ScriptProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Configuration finished.

**Comment by DustinCampbell** [comment] 2017-02-09 14:04
Hi, could you provide the project? That will make it easier for us to repo.

**Comment by gideondsouza** [comment] 2017-02-11 17:31
ok oddly enough I downloaded code1.9.1 and I selected CSharp on the bottom right, suddenly it started downloading Mono Framework, Mono Runtime Assemblies and Omnisharp again. I believe they were installed so they just got auto updated.

Anyway so..I have :
VS Code Version 1.9.1 and C# Version 1.7.0

I tried again opening the sln file, it first opened the text of the file, the bottom right status bar said "Running" and then it failed again. This is the output log:

Starting OmniSharp server at 11/2/2017, 10:55:07 PM
    Target: /home/gideon/Coding/csharp/YAL/YAL.sln

OmniSharp server started wth Mono
    Path: /home/gideon/.vscode/extensions/ms-vscode.csharp-1.7.0/bin/run
    PID: 4771

OmniSharp: -s /home/gideon/Coding/csharp/YAL/YAL.sln --hostPID 3130 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/home/gideon/Coding/csharp/YAL' on host 3130."},"Seq":1,"Type":"event"}
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /home/gideon/Coding/csharp/YAL
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to /home/gideon/.vscode/extensions/ms-vscode.csharp-1.7.0/bin/omnisharp/msbuild/MSBuild.dll
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to /home/gideon/.vscode/extensions/ms-vscode.csharp-1.7.0/bin/omnisharp/msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to /home/gideon/.vscode/extensions/ms-vscode.csharp-1.7.0/bin/omnisharp/msbuild/Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/home/gideon/Coding/csharp/YAL/YAL.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj'.
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        No assemblies were read in from the redist lists. A TargetFramework profile exclusion list could not be generated. 
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file '/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj'.
/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj(1,1)
System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \\server\share.
  at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation (System.String resourceName, System.Object[] args) [0x00019] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation (System.Boolean condition, System.String resourceName, System.Object arg0, System.Object arg1, System.Object arg2) [0x0000a] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Shared.FileUtilities+ItemSpecModifiers.GetItemSpecModifier (System.String currentDirectory, System.String itemSpec, System.String definingProjectEscaped, System.String modifier, System.String& fullPath) [0x004f2] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped (System.String currentDirectory, System.String evaluatedIncludeBeforeWildcardExpansionEscaped, System.String evaluatedIncludeEscaped, System.String definingProjectEscaped, System.String name, System.String& fullPath) [0x0002e] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetBuiltInMetadataEscaped (System.String name) [0x00012] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadataEscaped (System.String metadataName) [0x000ce] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadata (System.String metadataName) [0x00001] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at (wrapper remoting-invoke-with-check) Microsoft.Build.Execution.ProjectItemInstance+TaskItem:GetMetadata (string)
  at Microsoft.Build.Execution.ProjectItemInstance.GetMetadataValue (System.String name) [0x00001] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.GetFullPaths (System.Collections.Generic.ICollection`1[T] items) [0x0001b] in <aca7f87b64bc414f95aff1158193a80c>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create (System.String projectFilePath, System.String solutionDirectory, Microsoft.Extensions.Logging.ILogger logger, OmniSharp.Options.MSBuildOptions options, System.Collections.Generic.ICollection`1[T] diagnostics, System.Boolean isUnityProject) [0x00309] in <aca7f87b64bc414f95aff1158193a80c>:0 
  at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProjectFileInfo (System.String projectFilePath, System.Boolean isUnityProject) [0x0001f] in <aca7f87b64bc414f95aff1158193a80c>:0 

/home/gideon/Coding/csharp/YAL/YAL/YAL.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj'.
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        No assemblies were read in from the redist lists. A TargetFramework profile exclusion list could not be generated. 
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file '/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj'.
/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj(1,1)
System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \\server\share.
  at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation (System.String resourceName, System.Object[] args) [0x00019] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation (System.Boolean condition, System.String resourceName, System.Object arg0, System.Object arg1, System.Object arg2) [0x0000a] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Shared.FileUtilities+ItemSpecModifiers.GetItemSpecModifier (System.String currentDirectory, System.String itemSpec, System.String definingProjectEscaped, System.String modifier, System.String& fullPath) [0x004f2] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped (System.String currentDirectory, System.String evaluatedIncludeBeforeWildcardExpansionEscaped, System.String evaluatedIncludeEscaped, System.String definingProjectEscaped, System.String name, System.String& fullPath) [0x0002e] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetBuiltInMetadataEscaped (System.String name) [0x00012] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadataEscaped (System.String metadataName) [0x000ce] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at Microsoft.Build.Execution.ProjectItemInstance+TaskItem.GetMetadata (System.String metadataName) [0x00001] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at (wrapper remoting-invoke-with-check) Microsoft.Build.Execution.ProjectItemInstance+TaskItem:GetMetadata (string)
  at Microsoft.Build.Execution.ProjectItemInstance.GetMetadataValue (System.String name) [0x00001] in <6a1392588f4a45bdbe07807130f9b3d0>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.GetFullPaths (System.Collections.Generic.ICollection`1[T] items) [0x0001b] in <aca7f87b64bc414f95aff1158193a80c>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create (System.String projectFilePath, System.String solutionDirectory, Microsoft.Extensions.Logging.ILogger logger, OmniSharp.Options.MSBuildOptions options, System.Collections.Generic.ICollection`1[T] diagnostics, System.Boolean isUnityProject) [0x00309] in <aca7f87b64bc414f95aff1158193a80c>:0 
  at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProjectFileInfo (System.String projectFilePath, System.Boolean isUnityProject) [0x0001f] in <aca7f87b64bc414f95aff1158193a80c>:0 

/home/gideon/Coding/csharp/YAL/YACL/YACL.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/gideon/Coding/csharp/YAL'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.

I've attached my solution with projects zipped here. YAL (Yet Another Language) Just throwaway code for a parser.

[YAL.zip](https://github.com/OmniSharp/omnisharp-vscode/files/768760/YAL.zip)

**Comment by DustinCampbell** [comment] 2017-02-11 18:38
Thanks for the added detail. I'll take a look.

**Comment by gideondsouza** [comment] 2017-02-12 10:20
Thanks so much Dustin. I have to say I think the work you guys are doing is so amazing. 

I've been using C# since I was 16 and then a few years ago moved from windows to Linux,  convinced with the view I had against MS and it's role in FOSS.  VS Code is really a huge statement to from MS and I'm glad I have a great experience with C# on linux. (Or there's is hope ...)

**Comment by DustinCampbell** [comment] 2017-02-12 13:46
One other question, could you run `mono --version` at a terminal window and let me know what version you have installed?

**Comment by gideondsouza** [comment] 2017-02-12 14:07
so on my machine:

```
[gideon@gideon-fedora Coding]$ mono --version
Mono JIT compiler version 4.2.4 (tarball Thu Jun 23 18:49:17 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.
com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
 
```

**Comment by DustinCampbell** [comment] 2017-02-12 14:11
OK. The reason I ask is because it doesn't repro on OSX for me with the latest Mono. I'm installing Fedora 24 into Parallels right now to try and get a repro. But it might be worth updating Mono to the latest and seeing if that addresses the problem.

**Comment by DustinCampbell** [comment] 2017-02-12 14:26
OK. I've got Fedora 24 installed now and can see the error. It looks like the Mono package for Fedora 24 hasn't been updated for 8 months. 😦

**Comment by gideondsouza** [comment] 2017-02-12 15:06
Yep. It's still at 4.2.4 and the latest is 4.2.6 right? Doesn't it make sense to try and install 4.2.6 from source? What version does the C# extension and OmniSharp require?

**Comment by DustinCampbell** [comment] 2017-02-12 15:18
To be clear, the C# extension doesn't *require* Mono (it carries it's own with it). The issue is that it must use whatever's on the machine when processing .NET Framework projects. Essentially, it needs to find the right MSBuild targets to run. However, in this case, it appears that there was a bug in the Mono package for Fedora 24, which is pretty out-of-date.

I grabbed a more recent version from https://copr.fedorainfracloud.org/coprs/tpokorra/mono/, which fixes the issue. I did a bit more digging and it *looks* (though I'm not 100% certain) that the bug you're encountering was fixed in Mono several months ago: https://github.com/mono/mono/commit/c005ca7358dcff367762a5159bba115eec94b6d3.

I'm still digging a bit. I'm going to try Fedora 25 and see if the fix is already there.

**Comment by DustinCampbell** [comment] 2017-02-12 16:23
I installed Fedora 25 and found that the Mono is fixed there. It doesn't look there's anything we can do in C# for Visual Studio Code, but there are a couple of options that will address the problem.

1. Install a more recent version of Mono on Fedora 24. You can get the latest and greatest using https://copr.fedorainfracloud.org/coprs/tpokorra/mono/.
2. Update to Fedora 25. mono-devel-4.4.2 is what you get with Fedora 25.
3. Abandon all hope and update to Fedora Rawhide! :smile: Although, Mono should work since it targets mono-devel-4.6.2.

Good luck! Let me know if there's anything else I can help with.

**Closed** 2017-02-12 16:24 UTC
Labels: Bug, Resolved-External

**Comment by gideondsouza** [comment] 2017-02-13 00:47
Thanks so much @DustinCampbell  I appreciate it. I've just delayed updating to Fedora 25. Guess now I have enough reason.
