### ISSUE TITLE
[Feature] Auto-attach debugger on process restart

### ISSUE THREAD

**Issue by rrmistry** [OmniSharp/omnisharp-vscode#5690] opened 2023-05-23 14:29 UTC
## Is your feature request related to a problem? Please describe.
We use the `dotnet watch run` pattern a lot for debugging. We also have a remote process running that is launched via SSH.

Currently, we rely on the `attach` method for debugging by attaching VS Code to the actively running `dotnet` built binary.

However, when the source code changes, the source is rebuilt and the dotnet session terminates. This causes the debug session to also break.

## Describe the solution you would like
Similar to [`Node.Js Feature: Restarting debug sessions automatically when source is edited`](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited) it would be great if the C#/OmniSharp debugger could also re-attach on termination.

## Applicable Scenarios
Remote debugging sessions where the process runs via SSH or [`dev containers`](https://containers.dev/).

## Describe alternatives you've considered
The only alternative right now is to always try to debug and attach

**Comment by gregg-miskelly** [comment] 2023-05-23 16:51
I think this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4822

**Closed by gregg-miskelly** 2023-05-23 16:51 UTC
