### ISSUE TITLE
Formatting Removes Region Indentation, Unable To Minimize Regions

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#1556] opened 2017-06-08 10:11 UTC
_From @excalith on June 7, 2017 11:39_

- VSCode Version: 1.12.2 (Have been around for a long time)
- OS Version: Windows 8.1 / Windows 10

Steps to Reproduce:
While encapsulating a code block with "#region" and "#endregion" using c#, if you decide to format it with "Alt+Shift+F", it removes indentation and minimizing regions won't work anymore.

_Copied from original issue: Microsoft/vscode#28180_

**Comment by aeschli** [comment] 2017-06-08 10:11
_From @Jan-Ka on June 7, 2017 18:44_

- VSCode Version: 1.12.2
- OS Version: Ubuntu 17.04

Doesn't work in TypeScript either.

**Comment by DustinCampbell** [comment] 2017-06-08 13:34
Hi! This is a duplicate of a couple of issues: #1475 and #617.

**Formatting**: C# for Visual Studio Code relies on Roslyn to handle formatting. Unfortunately, Roslyn does not yet provide options for controlling the indentation of preprocessor directives like `#region` and `#endregion`, but there is already a request for it: https://github.com/dotnet/roslyn/issues/12305. When that's implemented, we'll be able to expose the option from C# for VS Code.

**Folding**: I'd love to fix the folding behavior for `#region` and `#endregion`. At some point, I expect that we'll have a VS Code API that allows extensions to customize folding behavior. That would allow us to add folding for `#region` and `#endregion` -- regardless of indentation. This is tracked with https://github.com/Microsoft/vscode/issues/3422.

**Closed by DustinCampbell** 2017-06-08 13:34 UTC
Labels: Resolved-Duplicate
