### ISSUE TITLE
[FEAT] Snippet data fill base on context.

### ISSUE THREAD

**Issue by eByte23** [OmniSharp/omnisharp-vscode#796] opened 2016-10-01 03:15 UTC
When using Snippet, namespace  or class

I would like it to be able to provide autofill as default data as the folder location namespace like visual studio.
e.g.
```
- src
    - Project1
        - project.json
        - Controllers
            - AdminContoller.cs
    - Project2
        - project.json
        - SubFoler
            - SubSubFolder
                - MyHandler.cs
```

So when I create MyHandler.cs and the use namespace snippet should auto file 
```
namespace Project2.SubFoler.SubSubFolder
{

}
```
When using class snippet it should do a similar action creating a new file MyHandler.cs
using class snippet should auto file the file name 
```
class MyHandler 
{
    
}
```
Now I'm not sure exactly how this would be implemented whether this would be on new file creation of *.cs 
or whether you would expose varibles to snippets e.g. $defaultNamespace or $defaultClass
or could inject dynamic snippets from the plugin that has these things setup.

Thanks!

**Comment by DustinCampbell** [comment] 2016-10-03 15:56
I totally agree. Unfortunately, we don't have a great way to dynamically insert additional text into snippets today. We have a request on VS Code to better support this feature: https://github.com/Microsoft/vscode/issues/10561.

Resolving this as a dupe of #643.

**Closed by DustinCampbell** 2016-10-03 15:56 UTC
Labels: Feature Request, Resolved-Duplicate
