### ISSUE TITLE
error not highlighting properly.

### ISSUE THREAD

**Issue by harlyd** [OmniSharp/omnisharp-vscode#857] opened 2016-10-31 17:52 UTC
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: ms-vscode.csharp-1.4.1

## Steps to reproduce

```public int Id { get; set; } = "abc";```

## Expected  behavior

"abc" should be underlined red and remain that way until the error is fixed.

## Actual behavior

"abc" gets underlined in red for a few seconds then it disappears.

**Comment by Novack-** [comment] 2016-10-31 20:05
This one has been fixed in 1.5.0 beta4.

**Comment by MetaMythril** [comment] 2016-10-31 23:13
I can confirm this is happening on OS X as well with my Unity3D project.

**Comment by DustinCampbell** [comment] 2016-11-02 10:46
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/812.

@harlyd, @MetaMythril: Do you still see this issue if you install the latest [1.5.0-beta4](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta4) release of the C# extension?

To install a beta release in VS Code:

1. Download the VSIX package for the [release](https://github.com/OmniSharp/omnisharp-vscode/releases).
2. In Visual Studio Code, select `View->Extensions` from the menu to display the Extensions pane.
3. In the extensions pane, click the `[...]` in the top right corner and select `Install from VSIX...`
4. Locate the VSIX you just downloaded and click the `Open` button
5. Restart Visual Studio Code when prompted.

**Closed** 2016-11-02 10:47 UTC
Labels: Resolved-Duplicate
