### ISSUE TITLE
Using statements not showing up for ctrl-.

### ISSUE THREAD

**Issue by danroth27** [OmniSharp/omnisharp-vscode#1785] opened 2017-10-09 01:06 UTC
I'm still seeing issues with using statements not showing up in the lightbulb menu for new .NET Core projects

Steps to reproduce:
1. Install .NET Core 2.0 SDK
2. `dotnet new console`
3. `dotnet add package Microsoft.AspNetCore.All`
4. In `Program.Main` type `WebHost` and try to resolve the using statement for `WebHost`.

Expected result
- Lightbulb to add `using Microsoft.AspNetCore`

Actual result
- No helpful lightbulb to add the using statement
- Waiting doesn't help

Workaround:
- Closing and reopening the folder causes the using statements to start to show up

**Comment by DustinCampbell** [comment] 2017-10-09 18:14
Could you clarify your repro steps for me? 

* What OS are you running?
* At what point did you open your project in VS Code? Between `#2` and `#3` or between `#3` and `#4`?
* Did you type the commands at a command project or using VS Code's integrated terminal?

**Comment by danroth27** [comment] 2017-10-09 19:49
OS: Windows10

I opened the project in VS Code after step 3

I typed all commands at the command prompt.

**Comment by DustinCampbell** [comment] 2017-10-09 21:51
When I performed the repro steps, I get a slightly different experience.

1. After opening the project in VS Code, I get a message stating that there are unresolved dependencies from 'test.csproj'. Do you see this as well?

    ![image](https://user-images.githubusercontent.com/116161/31359608-8f5415b2-acff-11e7-9793-96c2f4c9caa9.png)

    I went ahead and clicked restore.

2. I typed "WebHost" in Main, and I _did_ get a light bulb, but it did not have a suggestion to add a using statement. Are you seeing the same thing? From your repro steps, it seemed like you weren't seeing a light bulb at all.
    
    ![image](https://user-images.githubusercontent.com/116161/31359817-75181dc8-ad00-11e7-958e-2b20cb9485dd.png)

3. After restarting VS Code, I see the add using statement lightbulb as you described.

Is this the same experience that you're seeing?

If so, I believe there are two things happening here:

1. `dotnet add package` does not do a package restore (by design), and you should perform one after adding a package in order for MSBuild (via OmniSharp) to resolve references to defined in the package.
2. There's a bug where OmniSharp doesn't update references with the project.assets.json file changes after a `dotnet restore`. This is https://github.com/OmniSharp/omnisharp-vscode/issues/1583.

If I'm correct, I think this might be a dupe of `#2` above.

**Comment by DustinCampbell** [comment] 2017-10-09 21:57
Also: https://github.com/OmniSharp/omnisharp-vscode/issues/1661

**Comment by danroth27** [comment] 2017-10-09 21:59
Yup, your experience accurately describes what I am seeing. Sorry for the lack of clarity on my part!

**Comment by DustinCampbell** [comment] 2017-10-09 22:31
No problem. Thanks for taking the time to report the issue.

**Comment by DustinCampbell** [comment] 2017-11-13 19:29
This issue has been fixed in the 1.14 milestone. We just released our [first beta of 1.14](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.14.0-beta1) if you're interested in giving it a spin. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to a beta release of C# for VS Code.

**Closed by DustinCampbell** 2017-11-13 19:29 UTC
Labels: Bug, OmniSharp, Resolved-Fixed

**Comment by Thaina** [comment] 2018-01-05 11:26
Still got this issue in beta2. vscode 1.19.1

![image](https://user-images.githubusercontent.com/1042507/34607360-c209545a-f245-11e7-8800-06e1135db0bd.png)

![image](https://user-images.githubusercontent.com/1042507/34607398-fadc0732-f245-11e7-9ed3-ef79e511ba91.png)
