### ISSUE TITLE
vscode install C# Extension error

### ISSUE THREAD

**Issue by JunLi0053** [OmniSharp/omnisharp-vscode#3312] opened 2019-10-03 15:00 UTC
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version:
1.38.1

C# Extension version:
1.21.3

## Steps to reproduce
open project show message
The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.
AND
Some projects have trouble loading. Please review the output for more details.

**Comment by filipw** [comment] 2019-10-03 20:10
This is duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3290, please update the extension to 1.21.4 which was released today.

**Closed by filipw** 2019-10-03 20:10 UTC

**Comment by JunLi0053** [comment] 2019-10-06 00:20
uddate the extension to 1.21.4，but have same question

**Comment by JunLi0053** [comment] 2019-10-06 00:22
> This is duplicate of #3290, please update the extension to 1.21.4 which was released today.

update the extension to 1.21.4，but have same question

**Comment by gpalazuelosg** [comment] 2019-11-12 06:53
hi,
Same situation here. I just installed extension version 1.21.7 and getting same error.

On VSCode, in a terminal, I'm able to execute this:

```
$ dotnet --version
3.0.100
```

But VSCode is not able to find .Net Core 3.0 SDK

My info:
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by SeattleSlough** [comment] 2019-12-05 19:02
I have the same set up and issue as gpalazuelosg.  Is there any visibility into this issue and when it might be rectified?

**Comment by Sm1le291** [comment] 2020-01-28 15:06
It's still valid for .Net Core SDK 3.1.1 and VS Code 1.41.1 on openSuse Linux

**Comment by Sm1le291** [comment] 2020-01-28 15:06
> I have the same set up and issue as gpalazuelosg. Is there any visibility into this issue and when it might be rectified?
> 
> UPDATE: I set omnisharp.path to "latest" and robooted vscode. that seemed to work.

Does not help me on openSuse

**Comment by JoeRobich** [comment] 2020-01-28 18:24
Hi @Sm1le291, Please try the instructions on this page - https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors
