### ISSUE TITLE
Breakpoints disappear after debug starts, can be hit, but not highlighted

### ISSUE THREAD

**Issue by renang** [OmniSharp/omnisharp-vscode#4079] opened 2020-09-21 17:19 UTC
## Issue Description ##
Breakpoints not sticking in editor or gutter after debug starts. Breakpoints are hit, but line is not highlighted in editor, and variables are not loaded. I can see variables loaded on sidebar, but not on editor on hover. I can add breakpoints after debug starts, but they don't show on gutter, though it shows as registered on sidebar. Please advise on what information is needed to identify the problem. It used to work fine.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.49.1
**C# Extension**: 1.23.2

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.2|
|csharp-to-typescript|adrianwilczynski|1.12.1|
|csharpextensions|jchannon|1.3.1|
|gitlens|eamodio|10.2.2|
|rest-client|humao|0.24.2|
|sftp|liximomo|1.12.9|
|todo-tree|Gruntfuggly|0.0.178|
|vscode-nuget-gallery|patcx|0.0.22|
|vscode-nuget-package-manager|jmrog|1.1.6|;

</details>

**Comment by jmarolf** [comment] 2020-09-22 23:29
duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3920

**Closed by jmarolf** 2020-09-22 23:29 UTC
