### ISSUE TITLE
Intellisense is not working inside the nested-intilializer block

### ISSUE THREAD

**Issue by duongphuhiep** [OmniSharp/omnisharp-vscode#1135] opened 2017-01-20 18:46 UTC
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

VS Code version: 1.8.1 Commit ee428b0
C# Extension version: 1.6.2 

## Steps to reproduce
```csharp
    public class Order {
        public Customer Customer { get; set; }
    }

    public class Customer {
        public string Name { get; set; }
        public string Age { get; set; }
    }

    public class App 
    {
        static void Main()
        {
            var o = new Order { Customer = new Customer {
               Name = "John"  // intellisense NOT working inside this block, it is not suggest the Name or Age
            }};
        }
    }
```

## Expected  behavior

Intellisense should suggest Name, Age

## Actual behavior

Intellisense didn't suggest anything

**Comment by DustinCampbell** [comment] 2017-01-20 22:52
Hi, this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/656.

**Closed** 2017-01-21 04:56 UTC
Labels: Resolved-Duplicate
