### ISSUE TITLE
.NET C# on visual code macos

### ISSUE THREAD

**Issue by vatsalyaagrawal** [OmniSharp/omnisharp-vscode#3743] opened 2020-04-23 18:16 UTC
After running for the first time in the folder the 'dotnet new console'
the template gets created successfully and so does the restore.

 
Running the 'dotnet run' command outputs "Hello World!",

After clicking on the Program.cs file and opening it for the first time I get 2 messages:

1. Add Required assets to build and debug -  I add. 
2. There are unresolved dependencies. Please execute the restore command to continue. Source: C# (Extension)
When I click on restore I still get these 26 problems. How do I solve this problem?

<img width="1680" alt="130552-screen-shot-2020-04-22-at-221906 (1)" src="https://user-images.githubusercontent.com/7817401/80134503-b42f4d00-8553-11ea-8604-5ad7346eb4e2.png">

 
Thanks in advance!

Copied over from: https://developercommunity.visualstudio.com/content/problem/1002666/net-c-on-visual-code-macos.html

**Comment by cartermp** [comment] 2020-04-23 20:17
This one doesn't reproduce for me on my mac. Tagging as needs more info to see if we can get some diagnostic data.

**Comment by selfup** [comment] 2020-04-24 21:29
I ran into this as well. Do you have `mono` installed? I needed `mono` for a buildstep in monogame but Omnisharp looks for mono and points to it if it sees a global mono version. Check your settings for omnisharp `cmd + ,` if this is the case (unless you need omnisharp to point to mono instead of dotnet)

**Comment by JoeRobich** [comment] 2020-04-24 22:09
@selfup The Omnisharp language server that powers the C# extension runs on Mono so that it can support full framework projects as well as .net core projects. So this is expected and normal. What can sometime be a problem is installations of Mono or .NET Core SDK that do not use the official installers.

To better diagnose problems with project loading, we need the full output of the Omnisharp Log from the VS Code Output pane. If you are running into trouble, I would be happy to take a look.

**Comment by selfup** [comment] 2020-04-24 22:34
Interesting that makes sense. I installed mono via brew so I will undo that and use the official installer and see if that fixes it!

**Comment by selfup** [comment] 2020-04-24 22:48
@JoeRobich 

That seems to have worked for me. Set omnisharp mono to `auto` after installing mono from the official mono website and added `mono` to my `PATH`

`export PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin/:${PATH}`

Hopefully this can help others that ran into this issue with `mono` via brew.

I hope it's this simple for @vatsalyaagrawal (assuming it is a mono issue as well..)

**Comment by cartermp** [comment] 2020-09-23 00:49
Yes, this appears to be a mono issue. Since there weren't any more diagnostic logs shared, I'll close this out.

**Closed by cartermp** 2020-09-23 00:49 UTC
Labels: Needs More Info, Triaged
