### ISSUE TITLE
Intellisense not working of c# in for unity.Firstly it showed that .net is not installed in my pc but even after installing it,intellisense is still not working

### ISSUE THREAD

**Issue by blackshadow369** [OmniSharp/omnisharp-vscode#3731] opened 2020-04-19 11:49 UTC
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Actual behavior
Here is the output of omisharp log. 

Starting OmniSharp server at 18/04/2020, 18:00:40
    Target: c:\Users\lucky\Desktop\Unity projects\New Unity Project\New Unity Project.sln

OmniSharp server started.
    Path: C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\OmniSharp.exe
    PID: 12860

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild
            MSBuildToolsPath = C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\lucky\Desktop\Unity projects\New Unity Project'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\lucky\Desktop\Unity projects\New Unity Project\New Unity Project.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\lucky\Desktop\Unity projects\New Unity Project\Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\lucky\Desktop\Unity projects\New Unity Project'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\lucky\Desktop\Unity projects\New Unity Project\Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\lucky\Desktop\Unity projects\New Unity Project' on host 8312.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Unity.Timeline.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Unity.VSCode.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Unity.TextMeshPro.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'UnityEngine.UI.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Unity.Timeline.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Unity.CollabProxy.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Unity.Rider.Editor.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Unity.TextMeshPro.csproj' does not exist.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'UnityEditor.UI.csproj' does not exist.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\lucky\Desktop\Unity projects\New Unity Project\Assembly-CSharp.csproj'.
c:\Users\lucky\Desktop\Unity projects\New Unity Project\Assembly-CSharp.csproj
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'Unity.Timeline.Editor.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'Unity.VSCode.Editor.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'Unity.TextMeshPro.Editor.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'UnityEngine.UI.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'Unity.Timeline.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'Unity.CollabProxy.Editor.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'Unity.Rider.Editor.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'Unity.TextMeshPro.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1850,5): Error: The referenced project 'UnityEditor.UI.csproj' does not exist.
C:\Users\lucky\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\lucky\Desktop\Unity projects\New Unity Project\Assembly-CSharp.csproj
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\lucky\Desktop\Unity projects\New Unity Project\Assets\NewBehaviourScript.cs added to workspace

**Comment by andersonschug** [comment] 2020-04-20 19:05
Hi @blackshadow369!
I was with a problem almost equals yours, I solved it changing the **TargetFrameworkVersion**

Go to the file **Assembly-CSharp.csproj**
Change "TargetFrameworkVersion" to the **latest .NET Framework Dev (Targeting Pack) version** (remember to **download the latest version with you don't have it** haha), in my case **4.7.1 became 4.8**, for some reason when Unity created the project it cames with that version.

Hopes it helps you and sorry for any english grammar issues, I still learning english haha.

**Comment by SCHUGRWS** [comment] 2020-04-20 19:06
Hi @blackshadow369!
I was with a problem almost equals yours, I solved it changing the **TargetFrameworkVersion**

Go to the file **Assembly-CSharp.csproj**
Change "TargetFrameworkVersion" to the **latest .NET Framework Dev (Targeting Pack) version** (remember to **download the latest version with you don't have it** haha), in my case **4.7.1 became 4.8**, for some reason when Unity created the project it cames with that version.

Hopes it helps you and sorry for any english grammar issues, I still learning english haha.

**Comment by SirIntruder** [comment] 2020-04-21 17:45
@SCHUGRWS is correct, through Unity may decide to change .csproj file later, and there can be multiple .csproj files that would need such babysitting (Plugins folder, Editor folder, packages etc.). 

Ideally you should install targeting pack for 4.7.1. Best way to do this is: `Visual Studio Installer -> <select your latest VS installation> -> Modify -> Individual Components`

![VS](https://user-images.githubusercontent.com/5102661/79894745-31e54280-8406-11ea-9803-89bf6927b8fc.png)

You can try to install targetting pack manually, but I've had problems with that, from my experience installing them with "big" Visual Studio is the only sure way to make everything work.

**Comment by JoeRobich** [comment] 2020-04-21 17:51
Since installing Visual Studio may be too much. You can get the targeting packs and a full MSBuild by installing the "Build Tools for Visual Studio" from https://visualstudio.microsoft.com/downloads/

![image](https://user-images.githubusercontent.com/611219/79897014-f6268a80-83bd-11ea-9550-8ac1f2d79a74.png)

**Comment by cartermp** [comment] 2020-04-23 20:29
Going to close this out as by design. The issue is stemming from not having .NET Framework targeting packs installed, which is necessary to target .NET Framework projects.

**Closed by cartermp** 2020-04-23 20:29 UTC
Labels: Resolved-By Design, Triaged
