### ISSUE TITLE
v1.8 breaks debugging of stand-alone executables on Windows if 'programName' is missing '.exe'

### ISSUE THREAD

**Issue by iSazonov** [OmniSharp/omnisharp-vscode#1335] opened 2017-03-20 13:05 UTC
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.10.2
C# Extension version: 1.8.0

## Steps to reproduce

After update on VS Code version: 1.10.2 and C# Extension version: 1.8.0 debugging no longer working on Windows (below config ".NET Core Launch"). After revert to C# Extension version: 1.7.0 debugging work well again.

## Expected  behavior

VS Code launch debugger.

## Actual behavior

Vs Code show error: "The system cannot find the file specified" on launch debugger step.

Console output:
```
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"logging":{"engineLogging":false,"consoleLogging":true,"trace":true,"traceResponse":true},"name":".NET Core Launch","type":"coreclr","request":"launch","justMyCode":false,"stopAtEntry":true,"program":"c:\\Users\\sie\\Documents\\GitHub\\iSazonov\\PowerShell/debug/powershell","preLaunchTask":"build","externalConsole":true,"cwd":"c:\\Users\\sie\\Documents\\GitHub\\iSazonov\\PowerShell"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (E) {"seq":4,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/LaunchFailed","data":{"VS.Diagnostics.Debugger.vsdbg.ErrorCode":1002,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.Version":"15.1.10310.6 commit:a43f72424a3fabcd92ca8ad10ef6fc26c80c59ec"}}}
<- (R) {"seq":5,"type":"response","request_seq":2,"success":false,"command":"launch","message":"The system cannot find the file specified."}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":4}
<- (E) {"seq":6,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.Version":"15.1.10310.6 commit:a43f72424a3fabcd92ca8ad10ef6fc26c80c59ec"}}}
<- (R) {"seq":7,"type":"response","request_seq":4,"success":true,"command":"disconnect"}
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "logging" : {
                "engineLogging" : true,
                "trace": true,
                "traceResponse" : true
            }
            "name": ".NET Core Launch",
            "type": "coreclr",
            "request": "launch",
            "justMyCode": false,
            "stopAtEntry": true,
            "program": "${workspaceRoot}/debug/powershell",
            "preLaunchTask": "build",
            "externalConsole": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "justMyCode": false,
            "processName": "powershell"
        }
    ]
}
```

**Comment by gregg-miskelly** [comment] 2017-03-20 16:32
@iSazonov I think I see the problem. I am assuming `powershell` is `powershell.exe`. Is that correct? If so, can you try adding the `.exe` suffix to powershell and see if it works?

**Comment by iSazonov** [comment] 2017-03-20 16:45
@gregg-miskelly Thanks! I tested this without success. `ProcMon` trace show that Vs Code is trying to search `powershell` and `powershell.exe` too.

**Comment by gregg-miskelly** [comment] 2017-03-20 16:50
@iSazonov is your project something that I can clone? Does the file `${workspaceRoot}/debug/powershell.exe` exist? I can tell you with pretty strong certainty that the issue is that the C# extension is getting ERROR_FILE_NOT_FOUND when we test that path.

**Comment by iSazonov** [comment] 2017-03-20 17:11
@gregg-miskelly  It is https://github.com/PowerShell/PowerShell/  Related Issue https://github.com/PowerShell/PowerShell/issues/3356
Yes, the file exists.

**Comment by gregg-miskelly** [comment] 2017-03-21 00:28
@iSazonov I think you must have run into the VSCode bug where if you make a launch.json change and immediately hit F5 it may not take effect, because when I added the `.exe` suffix it worked fine for me. Anyway, we will fix the `.exe` issue for the next release.

**Comment by iSazonov** [comment] 2017-03-21 03:27
@gregg-miskelly Many thanks!

- I change  the launch.json (add ".exe")
- Restart VS Code
- After F5 the debugger start and attach well.

So I see two Issue:
1. vsdbg-ui.exe make two search `powershell` - first is success, second is fail (it is from `ProcMon` trace) This worked with clrdbg in previous version.
2. VS Code don't apply changes in launch.json "on the fly"

**Comment by gregg-miskelly** [comment] 2017-03-21 03:34
@iSazonov Your 'launch.json change didn't apply' bug may be https://github.com/Microsoft/vscode/issues/22535. At least I haven't noticed the issue anymore after upgrading to an insiders build with the fix.

**Comment by iSazonov** [comment] 2017-03-21 04:12
@gregg-miskelly Clear. Thanks. Waiting 1.11

Should I still do something on the question about vsdbg-ui.exe ?

**Comment by gregg-miskelly** [comment] 2017-03-21 04:53
That is what this bug tracks.

**Comment by gregg-miskelly** [comment] 2017-03-21 16:41
This will be fixed in 1.9.

**Closed by gregg-miskelly** 2017-03-21 16:41 UTC
Labels: Debugger

**Comment by iSazonov** [comment] 2017-03-21 17:23
@gregg-miskelly  Many thanks!

**Comment by gregg-miskelly** [comment] 2017-03-28 18:40
I have posted a new release of the C# extension that includes the fix. 

To try it -- use the use the [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) instructions to install [v1.9.0-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.9.0-beta2).

**Comment by iSazonov** [comment] 2017-03-29 10:56
Confirm - in the beta the debugger is attached well. Thanks!
