### ISSUE TITLE
Cannot open c# source file from build error message

### ISSUE THREAD

**Issue by horney0824** [OmniSharp/omnisharp-vscode#2051] opened 2018-02-18 09:21 UTC
## Environment data
`dotnet --info` output: 2.1.4
VS Code version: 1.20.1
C# Extension version: 1.14.0
OS Environment: Windows 10

## Steps to reproduce
dotnet new console MyApp
Open MyApp folder in vscode using .NET Core task
Add some syntax error in Program.cs
Run build task
Click build error message in PROBLEMS panel.

## Expected  behavior
Jump to correct file and line number.

## Actual behavior
It shows "Unable to open 'Program.cs': File not found (file:///Program.cs)."
Meanwhile click intellisense error message can jump to correct file and line number.

![1](https://user-images.githubusercontent.com/7011500/36350236-f3f279b8-14cf-11e8-86ef-22316919a8f9.png)

## Comment
I tried to force .net tools to output English text, but in vain.

**Comment by rchande** [comment] 2018-02-20 21:59
@akshita31 Can you take a look?

**Comment by akshita31** [comment] 2018-02-20 22:33
Thanks @horney0824 ! This is a duplicate of #1197.

**Closed by akshita31** 2018-02-20 22:33 UTC

**Comment by horney0824** [comment] 2018-02-21 08:47
@akshita31 do you have schedule on fix this issue?
