### ISSUE TITLE
Types not highlighted in variable and field declarations

### ISSUE THREAD

**Issue by ivanz** [OmniSharp/omnisharp-vscode#687] opened 2016-08-18 19:45 UTC
Copy from: https://github.com/atom/language-csharp/issues/48

I'm using the VSCode Version 0.10.6 (0.10.6).
Default dark theme.

Here's a sample code:
```
class MyClass
{

}

class Program
{
    static void Main()
    {        
        //string is highlighted
        string s = "MyClass";

        //MyClass is not highlighted
        MyClass myClass = new MyClass();
    }
}
```

Here's an image:
![image](https://cloud.githubusercontent.com/assets/79742/17788232/86ab18d4-6584-11e6-88d2-98f9229563a8.png)

Here's a video demonstration:
https://www.youtube.com/watch?v=VpRPJc42FZQ

**Comment by johanneskopf** [comment] 2016-08-18 19:59
That's a duplicate of issue #674 .

**Comment by johanneskopf** [comment] 2016-08-18 20:02
That's a duplicate of issue #674

**Comment by ivanz** [comment] 2016-08-18 20:13
I thought 674 was about semantic highlighting where as I am thinking about simple regex rule that matches field and variable declarations and highlights the "type" bit - we already do this for properties and methods.

**Comment by johanneskopf** [comment] 2016-08-18 20:28
Oh, then maybe they have misunderstood my posting?
You mean it's possible to highlight the first Vector3 in
"Vector3 x = new Vector3(0f, 0f, 0f);"
but it's difficult to hightlight Debug in
"Debug.Log("test");"
Is this correct?

**Comment by DustinCampbell** [comment] 2016-08-19 15:37
Yes, that's right. Syntactically, there's no difference between "Debug" being a class or property, so we can't color it as a type. It's also impossible to highlight Vector3 differently if it's a class vs. a struct, which is something we do in VS.

**Closed** 2016-08-26 17:33 UTC
Labels: Bug, Syntax Highlighting
