### ISSUE TITLE
Failed to run test because null with nested test classes. 

### ISSUE THREAD

**Issue by shaunluttin** [OmniSharp/omnisharp-vscode#1151] opened 2017-01-26 03:49 UTC
## Environment data
`dotnet --info` output: 1.0.0-preview2-003133
VS Code version: 1.9.0-insider
C# Extension version: 1.6.2

## Steps to reproduce

For us the problem was nested classes. OmniSharp cannot handle this, when we click `run test`.

```
    public class SomeClass
    {
        public class SomeMethod
        {
            // Trying to run this test causes
            // "Failed to run test because null"
            [Fact]
            public void SomeTest()
            {
    
            }
        }
    }
```

## Expected  behavior

The test runs and the output says "Test Passed".

## Actual behavior

> Failed to run test because null

![capture](https://cloud.githubusercontent.com/assets/2066637/22319402/45c5c61c-e337-11e6-834c-71328aeb7bc6.PNG)

**Comment by gregg-miskelly** [comment] 2017-01-26 03:52
Thanks. This looks like a dupe of #1100

**Comment by shaunluttin** [comment] 2017-01-26 17:26
@gregg-miskelly It is not necessarily a dupe, because there are multiple reasons why Omnisharp might give that error. See also: http://stackoverflow.com/q/40858172/1108891

**Comment by gregg-miskelly** [comment] 2017-01-26 17:27
Okay, I will reopen for now then.

**Comment by DustinCampbell** [comment] 2017-01-26 22:58
Yeah, this has a different error. However, the "dupe" is from several months ago, so it might just be that behavior has changed since then. I suspect we started hitting null with this change: https://github.com/OmniSharp/omnisharp-roslyn/pull/683

FWIW, this will require a fix in omnisharp-roslyn. Looking at the code in https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.DotNetTest/Helpers/TestFeaturesDiscover.cs, I can see how it might fail to locate tests in nested classes. I'll take a look at this shortly.

**Comment by DustinCampbell** [comment] 2017-01-26 22:58
shortly == tomorrow. :smile:

**Comment by DustinCampbell** [comment] 2017-01-27 14:42
Note: There's also #743

**Comment by DustinCampbell** [comment] 2017-01-27 15:18
Looks like the problem is that there's some hacky code in omnisharp-roslyn that searches specifically for the presence of 'project.json'. https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.DotNetTest/Helpers/ProjectPathResolver.cs#L11

**Comment by DustinCampbell** [comment] 2017-01-27 23:20
OK. I see why the problem is specific to tests in nested classes. The offending line of code is here: https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.DotNetTest/Helpers/TestFeaturesDiscover.cs#L41.

Essentially, the code expects Roslyn's `ISymbol.ToDisplayName()` to return a name that can be used with 'dotnet test'. However, that method returns strings for _display_. Between a class and a nested class, it uses a '.' separator. However, 'dotnet test' expects a metadata name when the class and nested class are separated by a '+'. I had to write code that produced a metadata name once before -- for Code Model in VS (https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Impl/CodeModel/MetadataNameHelpers.cs). Looks like I might have to do that again. :smile:

**Comment by DustinCampbell** [comment] 2017-01-28 00:03
OK. I've got a fix for this in omnisharp-roslyn.

**Closed** 2017-01-30 23:16 UTC
Labels: Bug, Resolved-Fixed
