### ISSUE TITLE
Autocompletion replaces the current word after hitting space or other characters

### ISSUE THREAD

**Issue by math2001** [OmniSharp/omnisharp-vscode#1936] opened 2017-12-22 03:59 UTC
## Environment data

```
$ dotnet --info
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

VS Code version: `1.19.1`

C# Extension version: Unity 2017.2's version

## Steps to reproduce

```c#
using System;

class App {
    
    void Main() {
        Console.WriteLine("Hello world!");
        // start writing cons and hit space
    }

}
```

## Expected  behavior

Do not auto complete unless I hit tab

## Actual behavior

It actually auto completes when I hit space or dot.

This is really annoying, especially because sometimes it cannot be right when writing code "upside down" (some guy made a post about it and called it [wishful coding](https://assertnotmagic.com/2017/12/13/wishful-coding/)).

Sometimes, when I type a word quickly and press dot, it actually replaces the current word with the *previous* top completion, not the one corresponding to all the letters I typed.

So, I just would like to know if there is a way to disable this behavior.

Thanks anyway for this extension, it makes learning a new language so much easier! :+1:

**Comment by DustinCampbell** [comment] 2018-01-03 20:31
Thanks for the feedback. This design is very intentional as the completion list is intended to be a typing enhancement. In fact, we find that many users really appreciate it because they can type in all lowercase characters and the completion list will "case correct" the identifiers as the user types. This is precisely the same behavior that we have in C# in Visual Studio as well.

One completion list feature that Visual Studio has but C# for VS Code does not have is "suggestion mode". This is a mode where that can be activated to cause the completion list to ONLY complete on TAB, and no other characters. I think we'd be willing to add that feature to C# for VS Code, but the default behavior would still be what you described, as that's how it's designed. Does that make sense?

**Comment by DustinCampbell** [comment] 2018-01-03 20:31
cc @rchande

**Comment by YF1999** [comment] 2019-12-11 19:19
Seems that the suggestion mode is still not added?

To get the temporary suggestion mode, every time this extension updated I needed to change the completion list in the _extension.js_.

**Comment by cartermp** [comment] 2020-03-11 00:08
Since this is by design I'll close it out. We'll want to match the VS experience (which happens today) as best we can for now, especially as we work to centralize components in the VS Online service that can have multiple different clients.

**Closed by cartermp** 2020-03-11 00:08 UTC
Labels: Editor-IntelliSense, Resolved-By Design

**Comment by lilith** [comment] 2023-06-21 21:55
It would be phenomenal if it didn't replace "var" with "VariantType" on spacebar.
