### ISSUE TITLE
Automatic Formatting is using 4 spaces instead of what I set it to use

### ISSUE THREAD

**Issue by chrmarti** [OmniSharp/omnisharp-vscode#1015] opened 2016-12-05 15:09 UTC
_From @Lazzu on December 2, 2016 14:10_

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.2|
|Theme-azure|gerane|0.0.2|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|omnisharp|ms-vscode|0.3.3|
|better-merge|pprice|0.3.0|
|vscode-icons|robertohuertasm|4.0.4|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|gitblame|waderyan|1.3.0|
|unity-snippets|YclepticStudios|0.1.2|

---

Steps to Reproduce:

1. Set indentation formatting to be 2 spaces, no tabs. My config below:

"editor.tabSize": 2,
"editor.insertSpaces": true,
"editor.formatOnType": false,
"editor.formatOnSave": true

2. Automatic formatting is still using 4 spaces

_Copied from original issue: Microsoft/vscode#16386_

**Comment by chrmarti** [comment] 2016-12-05 15:09
_From @mrmlnc on December 2, 2016 14:12_

Language?

**Comment by chrmarti** [comment] 2016-12-05 15:09
_From @Lazzu on December 2, 2016 14:12_

C#

**Comment by chrmarti** [comment] 2016-12-05 15:09
_From @mrmlnc on December 2, 2016 14:14_

Is a random problem? 

I ask because we have similar problem with JS/TS (#15316).

**Comment by chrmarti** [comment] 2016-12-05 15:09
_From @Lazzu on December 2, 2016 14:16_

I haven't noticed it being random.

**Comment by chrmarti** [comment] 2016-12-05 15:09
@waderyan @jrieken Could this be a more general issue than just with JS/TS? (#15316)

**Comment by chrmarti** [comment] 2016-12-05 15:09
_From @jrieken on December 5, 2016 9:51_

re https://github.com/Microsoft/vscode/issues/16386#issuecomment-264553165 - I don't think so

**Comment by DustinCampbell** [comment] 2016-12-05 15:39
This is essentially a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/93. For now, you can specify formatting settings [using an omnisharp.json file](https://github.com/OmniSharp/omnisharp-roslyn/issues/366).

**Closed by DustinCampbell** 2016-12-05 15:39 UTC
Labels: Resolved-Duplicate
