### ISSUE TITLE
the c# extension for visual studio code (powered by omnisharp) is not compatible on linux armv7

### ISSUE THREAD

**Issue by schovan** [OmniSharp/omnisharp-vscode#4205] opened 2020-11-13 09:24 UTC
hi, when I install visual studio code and C# extension on Raspberry Pi 400 and open .net core 3.1 console project, I get an error

`the c# extension for visual studio code  (powered by omnisharp) is not compatible on linux armv7`

and I cannot build it and run it (and intellisense doesn't wok). Do you know what might be the problem? 

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /usr/share/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
1.51.1

C# Extension version:
1.23.5

## OmniSharp log
Empty

**Comment by gregg-miskelly** [comment] 2020-11-13 17:03
This extension doesn't currently support ARM.

**Comment by gregg-miskelly** [comment] 2020-11-13 17:04
Dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/2771

**Closed by gregg-miskelly** 2020-11-13 17:04 UTC
