### ISSUE TITLE
Popup error messages containing duplicate entries

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#2026] opened 2018-02-09 03:30 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```
VS Code version: `1.20.0`
C# Extension version: `1.13.1`

## Steps to reproduce
1. Create any application
2. In a `.cs` file, make sure there are some unnecessary `using` directives
3. hover the mouse on one of those `using` directives. For example, in the below snapshot, `using System.Linq;`

## Expected  behavior
In the popup error message, it shows only one entry of `Unnecessary using directive.`

## Actual behavior
It shows double `Unnecessary using directive.` In the snapshot the file has 2 `using` directives, as a result the **new** VS Code version `1.20.0` shows there are **4** errors for this file in **green,** in the **EXPLORER** rather than **2.**
![image](https://user-images.githubusercontent.com/19678455/36009691-42b89570-0db2-11e8-8da7-541f9e4fa9c3.png)

**Comment by cateyes99** [comment] 2018-02-09 08:59
This is for any messages (errors, warnings, & info) which appear in the **PROBLEM** window. Each of them has a duplicate one:
![image](https://user-images.githubusercontent.com/19678455/36019287-a3184e66-0de3-11e8-8db6-46f7a4d1d21b.png)
![image](https://user-images.githubusercontent.com/19678455/36019340-d6d30264-0de3-11e8-8dd9-99ea9a581537.png)

**Comment by DustinCampbell** [comment] 2018-02-09 18:21
Thanks for reporting this issue. It is a duplicate https://github.com/OmniSharp/omnisharp-vscode/issues/1830.

**Comment by egee-irl** [comment] 2018-02-13 13:58
It may be a duplicate, but #1830 is ``closed`` and I can also confirm I am seeing this in VSCode 1.20.0 on Arch Linux, extension number 1.13.1.

**Comment by DustinCampbell** [comment] 2018-02-13 16:48
#1830 was _just_ fixed, which is why it's closed. This is definitely a duplicate of that.

**Closed by DustinCampbell** 2018-02-13 16:48 UTC
Labels: Resolved-Duplicate
