### ISSUE TITLE
Debugger: Attach should stop debugging if stop app that launched with command window.

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#2480] opened 2018-08-31 07:14 UTC
## Environment data
`dotnet --info` output:
VS Code version: 1.26.1
C# Extension version: v1.16-beta4
SDK: 2.1.401

## Steps to reproduce
1. Open attachment project with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/2339083/hwapp.zip)
2. Launch the project in Command Prompt using the command "dotnet run"
3. Set a bp at line of 16( a++; ) in Program.cs.
4. Select the debug type ''.Net core Attach'
5. Press F5 to start debugging
6. Select process ID on UI
7. Stop the process that launch in Steps #2.
8. Continue debugging in vscode.

## Expected  behavior
Stop debugging successfully.

## Actual behavior
1. Still can debugging, cursor disappeared and the button still can display in top of vscode as attachment pic.
![image](https://user-images.githubusercontent.com/20184768/44898023-49068680-ad30-11e8-9d11-27e0ec6ebffc.png)

2. Still debugging correctly in second attach after stop app that had launched process.

**Comment by gregg-miskelly** [comment] 2018-08-31 16:51
This isn't a regression from 1.15, so I don't think I want to fix this for 1.16 at this point. But certainly seems like something that should be fixed.

**Comment by gregg-miskelly** [comment] 2018-08-31 17:55
This looks like a CoreCLR bug. I opened https://github.com/dotnet/coreclr/issues/19791 to track it.

**Closed by gregg-miskelly** 2018-08-31 17:55 UTC
Labels: Bug, Debugger, Resolved-External
