### ISSUE TITLE
The .NET CLI tools cannot be located

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#627] opened 2016-07-27 07:17 UTC
_From @Tobyee on July 27, 2016 5:56_

- VSCode Version: 1.3.1
- OS Version: Win7-x64
- dotnet Version: 1.0.0-beta-001598

Steps to Reproduce:

1. cmd: mkdir demo & cd demo
2. cmd: dotnet new
3. cmd: dotnet restore
4. cmd: code .

Error:

![image](https://cloud.githubusercontent.com/assets/1400574/17165279/e21fc9d8-5401-11e6-8b2c-8bd0b94d4628.png)

I'am sure that  .NET Core SDK for Windows was installed and `dotnet` command can be execute in `cmd`.

See alse:

https://github.com/dotnet/cli/issues/3858

_Copied from original issue: Microsoft/vscode#9831_

**Comment by gregg-miskelly** [comment] 2016-07-27 16:35
@Tobyee do you have the latest version of the C# extension (check in the extensions panel)? Assuming so, what do you get from:

1. Start->Run, cmd.exe
2. `where dotnet.exe`
3. `dotnet --info`

**Comment by Tobyee** [comment] 2016-07-28 07:04
@gregg-miskelly 
Thanks for you tips. I found the reason.
It's because I have a old version cli tools installed that influence on the new one.

The old version install is:
![old](https://cloud.githubusercontent.com/assets/1400574/17203865/7377bbde-54d4-11e6-8c13-0be94d1e0daf.png)
The new version install is:
![new](https://cloud.githubusercontent.com/assets/1400574/17203872/83aed2ee-54d4-11e6-8f29-bb9f8e331574.png)

I uninstall the old one then it fixed.

**Comment by gregg-miskelly** [comment] 2016-07-28 15:50
@Tobyee glad you solved your issue. I will close this issue then.

**Closed by gregg-miskelly** 2016-07-28 15:50 UTC
Labels: Debugger, Debugger-Install

**Comment by Luckz** [comment] 2018-01-23 03:23
Should this not warrant a warning added to the error message, that antique SDK versions can be the cause?

**Comment by gregg-miskelly** [comment] 2018-01-23 03:34
@Luckz if you are running into a problem related to this and would like some help, or have a concrete suggestion, please open a new issue.

**Comment by EliasCK** [comment] 2018-02-01 01:30
What do Linux users do?

**Comment by gregg-miskelly** [comment] 2018-02-01 01:45
@EliasCK if you are running into a problem related to this and would like some help, or have a concrete suggestion, please open a new issue so we can help understand what is going on on your machine.
