### ISSUE TITLE
VSCode-Vim and C# interfere with each other

### ISSUE THREAD

**Issue by rhys-vdw** [OmniSharp/omnisharp-vscode#3660] opened 2020-03-13 10:11 UTC
I'm wondering if this is because of the publisher change. Currently omnisharp-vscode and vscode-vim have a bad interaction where the entire editor locks up after #3645. I am unable to use VSCode with these to crucial extensions installed. Any guidance on how to opt out of this new version of omnisharp-vscode would be appreciated!

## Steps to reproduce

Try to "install another version" from cog in extensions pane. Then choose 1.21.12

![image](https://user-images.githubusercontent.com/822105/76611625-1fc8d800-651b-11ea-9780-ecca7c2ede34.png)

## Expected  behavior

Version installs.

## Actual behavior

Fails to download

![image](https://user-images.githubusercontent.com/822105/76611706-3a9b4c80-651b-11ea-8b1d-f6500265eeca.png)

**Comment by kristoff3r** [comment] 2020-03-13 11:05
I had exactly the same issue (both the editor locking up due to vscode-vim and not being able to downgrade). 

I managed to downgrade by uninstalling and installing manually from `https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.12` and running
`code --install-extension csharp-1.21.12.vsix`

**Comment by rhys-vdw** [comment] 2020-03-13 13:24
@kristoff3r amazing. Did you create an issue on vscode-vim? I haven't yet because I was hoping to get more info.

**Comment by kristoff3r** [comment] 2020-03-13 13:42
> @kristoff3r amazing. Did you create an issue on vscode-vim? I haven't yet because I was hoping to get more info.

No, because I don't know where the problem is exactly. There might not even be a problem in vscode-vim, it could just be that since all the extensions lock up and vscode-vim has control over the input then nothing happens.

**Comment by rhys-vdw** [comment] 2020-03-13 13:45
@kristoff3r you can still move the cursor around with the mouse. I was chatting to a gent in the vscode-vim Slack who suggested it might be bad error recovery from that extension. But yeah, similarly not sure what to report.

**Comment by AustinSmith13** [comment] 2020-03-15 00:28
I'm having the same issue with vs-code and vim.

**Comment by JoeRobich** [comment] 2020-03-16 18:45
Using latest VS Code, C#, and VSCode Vim, I am not seeing the editor lock up. I recommend updating all extensions and giving it another try.

**Comment by rib** [comment] 2020-03-16 20:30
I just checked for updates (didn't see any though) and tried re-enabling the C# plugin and this still seems to be an issue for me. As far as I can tell I have the latest versions:

VS Code = 1.43.0
C# = 1.21.14
Vim = v1.13.0

**Comment by JoeRobich** [comment] 2020-03-16 20:41
I guess we will need more details in order to reproduce this issue. What extensions and what project types are you working with?

**Comment by rib** [comment] 2020-03-16 21:44
<details><summary>This is my extensions.json from using the settings sync plugin in case that's helpful:</summary>

```json
[
  {
    "metadata": {
      "id": "d3836729-9cc1-42c1-b2af-d50071f57d29",
      "publisherId": "formulahendry.auto-close-tag",
      "publisherDisplayName": "formulahendry"
    },
    "name": "auto-close-tag",
    "publisher": "formulahendry",
    "version": "0.5.6"
  },
  {
    "metadata": {
      "id": "6e440e71-8ed9-4f25-bb78-4b13096b8a03",
      "publisherId": "formulahendry.auto-rename-tag",
      "publisherDisplayName": "formulahendry"
    },
    "name": "auto-rename-tag",
    "publisher": "formulahendry",
    "version": "0.1.1"
  },
  {
    "metadata": {
      "id": "f4f0748b-9f86-461e-84f9-73bf2e1f91c2",
      "publisherId": "rogalmic.bash-debug",
      "publisherDisplayName": "rogalmic"
    },
    "name": "bash-debug",
    "publisher": "rogalmic",
    "version": "0.3.7"
  },
  {
    "metadata": {
      "id": "b828ba23-db59-4911-abcf-db9d8c460163",
      "publisherId": "SharpNinja.cc65",
      "publisherDisplayName": "SharpNinja"
    },
    "name": "cc65",
    "publisher": "SharpNinja",
    "version": "0.0.2"
  },
  {
    "metadata": {
      "id": "de611071-4d05-4903-821c-6878df63d4af",
      "publisherId": "austin.code-gnu-global",
      "publisherDisplayName": "austin"
    },
    "name": "code-gnu-global",
    "publisher": "austin",
    "version": "0.2.2"
  },
  {
    "metadata": {
      "id": "e337c67b-55c2-4fef-8949-eb260e7fb7fd",
      "publisherId": "Shan.code-settings-sync",
      "publisherDisplayName": "Shan"
    },
    "name": "code-settings-sync",
    "publisher": "Shan",
    "version": "3.4.3"
  },
  {
    "metadata": {
      "id": "f6dbd813-b0a0-42c1-90ea-10dde9d925a7",
      "publisherId": "streetsidesoftware.code-spell-checker",
      "publisherDisplayName": "streetsidesoftware"
    },
    "name": "code-spell-checker",
    "publisher": "streetsidesoftware",
    "version": "1.8.0"
  },
  {
    "metadata": {
      "id": "690b692e-e8a9-493f-b802-8089d50ac1b2",
      "publisherId": "ms-vscode.cpptools",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "cpptools",
    "publisher": "ms-vscode",
    "version": "0.26.3"
  },
  {
    "metadata": {
      "id": "dff6b801-247e-40e9-82e8-8c9b1d19d1b8",
      "publisherId": "christian-kohler.npm-intellisense",
      "publisherDisplayName": "christian-kohler"
    },
    "name": "npm-intellisense",
    "publisher": "christian-kohler",
    "version": "1.3.0"
  },
  {
    "metadata": {
      "id": "40d39ce9-c381-47a0-80c8-a6661f731eab",
      "publisherId": "ms-vscode.powershell",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "powershell",
    "publisher": "ms-vscode",
    "version": "2020.3.0"
  },
  {
    "metadata": {
      "id": "f1f59ae4-9318-4f3c-a9b5-81b2eaa5f8a5",
      "publisherId": "ms-python.python",
      "publisherDisplayName": "ms-python"
    },
    "name": "python",
    "publisher": "ms-python",
    "version": "2020.2.64397"
  },
  {
    "metadata": {
      "id": "607fd052-be03-4363-b657-2bd62b83d28a",
      "publisherId": "ms-vscode-remote.remote-ssh",
      "publisherDisplayName": "ms-vscode-remote"
    },
    "name": "remote-ssh",
    "publisher": "ms-vscode-remote",
    "version": "0.50.0"
  },
  {
    "metadata": {
      "id": "bfeaf631-bcff-4908-93ed-fda4ef9a0c5c",
      "publisherId": "ms-vscode-remote.remote-ssh-edit",
      "publisherDisplayName": "ms-vscode-remote"
    },
    "name": "remote-ssh-edit",
    "publisher": "ms-vscode-remote",
    "version": "0.50.0"
  },
  {
    "metadata": {
      "id": "f0c5397b-d357-4197-99f0-cb4202f22818",
      "publisherId": "ms-vscode-remote.remote-wsl",
      "publisherDisplayName": "ms-vscode-remote"
    },
    "name": "remote-wsl",
    "publisher": "ms-vscode-remote",
    "version": "0.42.3"
  },
  {
    "metadata": {
      "id": "570e6089-b871-41df-9cf4-a723cb34ef01",
      "publisherId": "rust-lang.rust",
      "publisherDisplayName": "rust-lang"
    },
    "name": "rust",
    "publisher": "rust-lang",
    "version": "0.7.0"
  },
  {
    "metadata": {
      "id": "376bc29a-6eab-440e-a6c5-a6f4972e2ace",
      "publisherId": "ThreadHeap.serverless-ide-vscode",
      "publisherDisplayName": "ThreadHeap"
    },
    "name": "serverless-ide-vscode",
    "publisher": "ThreadHeap",
    "version": "0.5.16"
  },
  {
    "metadata": {
      "id": "a9b49b3a-f9a8-4f81-be73-530a48ed60b4",
      "publisherId": "zbecknell.t4-support",
      "publisherDisplayName": "zbecknell"
    },
    "name": "t4-support",
    "publisher": "zbecknell",
    "version": "0.4.3"
  },
  {
    "metadata": {
      "id": "9001c3f8-94bf-484d-92fc-07f2fd03ff5e",
      "publisherId": "ms-vscode.Theme-MarkdownKit",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "Theme-MarkdownKit",
    "publisher": "ms-vscode",
    "version": "0.1.4"
  },
  {
    "metadata": {
      "id": "d96e79c6-8b25-4be3-8545-0e0ecefcae03",
      "publisherId": "vscodevim.vim",
      "publisherDisplayName": "vscodevim"
    },
    "name": "vim",
    "publisher": "vscodevim",
    "version": "1.13.0"
  },
  {
    "metadata": {
      "id": "583b2b34-2c1e-4634-8c0b-0b82e283ea3a",
      "publisherId": "dbaeumer.vscode-eslint",
      "publisherDisplayName": "dbaeumer"
    },
    "name": "vscode-eslint",
    "publisher": "dbaeumer",
    "version": "2.1.1"
  },
  {
    "metadata": {
      "id": "8699dfcb-4beb-4760-b976-c46dcdd87df2",
      "publisherId": "KnisterPeter.vscode-github",
      "publisherDisplayName": "KnisterPeter"
    },
    "name": "vscode-github",
    "publisher": "KnisterPeter",
    "version": "0.30.3"
  },
  {
    "metadata": {
      "id": "5c7c798e-0755-438f-8bd9-edf98af999e9",
      "publisherId": "soltys.vscode-il",
      "publisherDisplayName": "soltys"
    },
    "name": "vscode-il",
    "publisher": "soltys",
    "version": "0.0.1"
  },
  {
    "metadata": {
      "id": "daf8b44d-8aae-4da2-80c5-1f770219f643",
      "publisherId": "DavidAnson.vscode-markdownlint",
      "publisherDisplayName": "DavidAnson"
    },
    "name": "vscode-markdownlint",
    "publisher": "DavidAnson",
    "version": "0.34.0"
  },
  {
    "metadata": {
      "id": "ae9e3eb0-3357-4cc0-90ee-598d2d384757",
      "publisherId": "eg2.vscode-npm-script",
      "publisherDisplayName": "eg2"
    },
    "name": "vscode-npm-script",
    "publisher": "eg2",
    "version": "0.3.11"
  },
  {
    "metadata": {
      "id": "1d3d1fb2-0d8f-47ed-bfce-990b8ddfc9d8",
      "publisherId": "zxh404.vscode-proto3",
      "publisherDisplayName": "zxh404"
    },
    "name": "vscode-proto3",
    "publisher": "zxh404",
    "version": "0.4.2"
  },
  {
    "metadata": {
      "id": "0cb81da2-1880-4755-9995-0ae9cc728e20",
      "publisherId": "DotJoshJohnson.xml",
      "publisherDisplayName": "DotJoshJohnson"
    },
    "name": "xml",
    "publisher": "DotJoshJohnson",
    "version": "2.5.0"
  }
]
```

</details>

For me I'm seeing the issue while editing C# code that's part of a Unity project. In case it helps reproduce this, I did recently publish a minimal Unity project [here ](https://github.com/rib/grpc-unity-deadlock-reproduction) for reproducing a bug in a different project.

**Comment by JoeRobich** [comment] 2020-03-16 21:54
@rib May or may not be related but, I emailed SharpNinja about cc65 when we changed publisher id. They responded that the extension was no longer supported and that it should be removed from the marketplace. Perhaps you could remove the cc65 extension and install the C# extension directly.

**Comment by rib** [comment] 2020-03-16 22:21
Ah, okey, I didn't realise there might be some conflict there, so I've removed that for now- thanks.

Re-testing without that, I do have the same issue though.

I have been installing the C# extension directly (unless I misunderstand you) it's just that I've had to disable the C# extension due to this bug so it wasn't in the above extensions.json. Interestingly when I enable the C# extension it also blocks me from being able to sync my settings (in addition to the vim input issues) so I can't easily show an updated extensions.json with the c# extension included.

**Comment by rib** [comment] 2020-03-16 22:27
<details><summary>Here's an updated extensions.json with the cc65 extension removed:</summary>

```json
[
  {
    "metadata": {
      "id": "d3836729-9cc1-42c1-b2af-d50071f57d29",
      "publisherId": "formulahendry.auto-close-tag",
      "publisherDisplayName": "formulahendry"
    },
    "name": "auto-close-tag",
    "publisher": "formulahendry",
    "version": "0.5.6"
  },
  {
    "metadata": {
      "id": "6e440e71-8ed9-4f25-bb78-4b13096b8a03",
      "publisherId": "formulahendry.auto-rename-tag",
      "publisherDisplayName": "formulahendry"
    },
    "name": "auto-rename-tag",
    "publisher": "formulahendry",
    "version": "0.1.1"
  },
  {
    "metadata": {
      "id": "f4f0748b-9f86-461e-84f9-73bf2e1f91c2",
      "publisherId": "rogalmic.bash-debug",
      "publisherDisplayName": "rogalmic"
    },
    "name": "bash-debug",
    "publisher": "rogalmic",
    "version": "0.3.7"
  },
  {
    "metadata": {
      "id": "b828ba23-db59-4911-abcf-db9d8c460163",
      "publisherId": "SharpNinja.cc65",
      "publisherDisplayName": "SharpNinja"
    },
    "name": "cc65",
    "publisher": "SharpNinja",
    "version": "0.0.2"
  },
  {
    "metadata": {
      "id": "de611071-4d05-4903-821c-6878df63d4af",
      "publisherId": "austin.code-gnu-global",
      "publisherDisplayName": "austin"
    },
    "name": "code-gnu-global",
    "publisher": "austin",
    "version": "0.2.2"
  },
  {
    "metadata": {
      "id": "e337c67b-55c2-4fef-8949-eb260e7fb7fd",
      "publisherId": "Shan.code-settings-sync",
      "publisherDisplayName": "Shan"
    },
    "name": "code-settings-sync",
    "publisher": "Shan",
    "version": "3.4.3"
  },
  {
    "metadata": {
      "id": "f6dbd813-b0a0-42c1-90ea-10dde9d925a7",
      "publisherId": "streetsidesoftware.code-spell-checker",
      "publisherDisplayName": "streetsidesoftware"
    },
    "name": "code-spell-checker",
    "publisher": "streetsidesoftware",
    "version": "1.8.0"
  },
  {
    "metadata": {
      "id": "690b692e-e8a9-493f-b802-8089d50ac1b2",
      "publisherId": "ms-vscode.cpptools",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "cpptools",
    "publisher": "ms-vscode",
    "version": "0.26.3"
  },
  {
    "metadata": {
      "id": "dff6b801-247e-40e9-82e8-8c9b1d19d1b8",
      "publisherId": "christian-kohler.npm-intellisense",
      "publisherDisplayName": "christian-kohler"
    },
    "name": "npm-intellisense",
    "publisher": "christian-kohler",
    "version": "1.3.0"
  },
  {
    "metadata": {
      "id": "40d39ce9-c381-47a0-80c8-a6661f731eab",
      "publisherId": "ms-vscode.powershell",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "powershell",
    "publisher": "ms-vscode",
    "version": "2020.3.0"
  },
  {
    "metadata": {
      "id": "f1f59ae4-9318-4f3c-a9b5-81b2eaa5f8a5",
      "publisherId": "ms-python.python",
      "publisherDisplayName": "ms-python"
    },
    "name": "python",
    "publisher": "ms-python",
    "version": "2020.2.64397"
  },
  {
    "metadata": {
      "id": "607fd052-be03-4363-b657-2bd62b83d28a",
      "publisherId": "ms-vscode-remote.remote-ssh",
      "publisherDisplayName": "ms-vscode-remote"
    },
    "name": "remote-ssh",
    "publisher": "ms-vscode-remote",
    "version": "0.50.0"
  },
  {
    "metadata": {
      "id": "bfeaf631-bcff-4908-93ed-fda4ef9a0c5c",
      "publisherId": "ms-vscode-remote.remote-ssh-edit",
      "publisherDisplayName": "ms-vscode-remote"
    },
    "name": "remote-ssh-edit",
    "publisher": "ms-vscode-remote",
    "version": "0.50.0"
  },
  {
    "metadata": {
      "id": "f0c5397b-d357-4197-99f0-cb4202f22818",
      "publisherId": "ms-vscode-remote.remote-wsl",
      "publisherDisplayName": "ms-vscode-remote"
    },
    "name": "remote-wsl",
    "publisher": "ms-vscode-remote",
    "version": "0.42.3"
  },
  {
    "metadata": {
      "id": "570e6089-b871-41df-9cf4-a723cb34ef01",
      "publisherId": "rust-lang.rust",
      "publisherDisplayName": "rust-lang"
    },
    "name": "rust",
    "publisher": "rust-lang",
    "version": "0.7.0"
  },
  {
    "metadata": {
      "id": "376bc29a-6eab-440e-a6c5-a6f4972e2ace",
      "publisherId": "ThreadHeap.serverless-ide-vscode",
      "publisherDisplayName": "ThreadHeap"
    },
    "name": "serverless-ide-vscode",
    "publisher": "ThreadHeap",
    "version": "0.5.16"
  },
  {
    "metadata": {
      "id": "a9b49b3a-f9a8-4f81-be73-530a48ed60b4",
      "publisherId": "zbecknell.t4-support",
      "publisherDisplayName": "zbecknell"
    },
    "name": "t4-support",
    "publisher": "zbecknell",
    "version": "0.4.3"
  },
  {
    "metadata": {
      "id": "9001c3f8-94bf-484d-92fc-07f2fd03ff5e",
      "publisherId": "ms-vscode.Theme-MarkdownKit",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "Theme-MarkdownKit",
    "publisher": "ms-vscode",
    "version": "0.1.4"
  },
  {
    "metadata": {
      "id": "d96e79c6-8b25-4be3-8545-0e0ecefcae03",
      "publisherId": "vscodevim.vim",
      "publisherDisplayName": "vscodevim"
    },
    "name": "vim",
    "publisher": "vscodevim",
    "version": "1.13.0"
  },
  {
    "metadata": {
      "id": "583b2b34-2c1e-4634-8c0b-0b82e283ea3a",
      "publisherId": "dbaeumer.vscode-eslint",
      "publisherDisplayName": "dbaeumer"
    },
    "name": "vscode-eslint",
    "publisher": "dbaeumer",
    "version": "2.1.1"
  },
  {
    "metadata": {
      "id": "8699dfcb-4beb-4760-b976-c46dcdd87df2",
      "publisherId": "KnisterPeter.vscode-github",
      "publisherDisplayName": "KnisterPeter"
    },
    "name": "vscode-github",
    "publisher": "KnisterPeter",
    "version": "0.30.3"
  },
  {
    "metadata": {
      "id": "5c7c798e-0755-438f-8bd9-edf98af999e9",
      "publisherId": "soltys.vscode-il",
      "publisherDisplayName": "soltys"
    },
    "name": "vscode-il",
    "publisher": "soltys",
    "version": "0.0.1"
  },
  {
    "metadata": {
      "id": "daf8b44d-8aae-4da2-80c5-1f770219f643",
      "publisherId": "DavidAnson.vscode-markdownlint",
      "publisherDisplayName": "DavidAnson"
    },
    "name": "vscode-markdownlint",
    "publisher": "DavidAnson",
    "version": "0.34.0"
  },
  {
    "metadata": {
      "id": "ae9e3eb0-3357-4cc0-90ee-598d2d384757",
      "publisherId": "eg2.vscode-npm-script",
      "publisherDisplayName": "eg2"
    },
    "name": "vscode-npm-script",
    "publisher": "eg2",
    "version": "0.3.11"
  },
  {
    "metadata": {
      "id": "1d3d1fb2-0d8f-47ed-bfce-990b8ddfc9d8",
      "publisherId": "zxh404.vscode-proto3",
      "publisherDisplayName": "zxh404"
    },
    "name": "vscode-proto3",
    "publisher": "zxh404",
    "version": "0.4.2"
  },
  {
    "metadata": {
      "id": "0cb81da2-1880-4755-9995-0ae9cc728e20",
      "publisherId": "DotJoshJohnson.xml",
      "publisherDisplayName": "DotJoshJohnson"
    },
    "name": "xml",
    "publisher": "DotJoshJohnson",
    "version": "2.5.0"
  }
]
```

</details>

**Comment by JoeRobich** [comment] 2020-03-16 22:53
@rib Thanks for the quick response. Can we isolate whether C# has problems on its own by disabling all other extensions? If things work ok then enable Debugger for Unity followed by vscode-vim if things are still good?

**Comment by rib** [comment] 2020-03-16 23:51
right, If I disable everything except C# that doesn't seem to be working either actually, so I suppose the c# extension is hogging something, starving other extensions from doing work, such as vim input handling or also the sync extension.

I do notice that when I enable the C# extension my fans start getting noisy and vscode is taking quite a lot of cpu :)

**Comment by rib** [comment] 2020-03-16 23:56
oooh, leaving it long enough that the fan noise stopped, it seems it actually finished whatever it was doing under the hood and now with vim enabled input is actually working.

So I suppose something slow that should be asynchronous is running synchronously and blocking things somehow?

**Comment by rib** [comment] 2020-03-16 23:58
I guess that probably now also means I'll no longer be able to reproduce the issue :)

**Comment by rhys-vdw** [comment] 2020-03-17 10:17
> I guess that probably now also means I'll no longer be able to reproduce the issue

You're suggesting that I leave VSCode overnight with the cursor frozen it will be permanently good to go after omnisharp is done doing some one-time setup?

**Comment by rib** [comment] 2020-03-18 12:25
Just to clarify, actually the issue doesn't magically resolve itself by just waiting a while. Whatever the extension does that blocks/starves other extensions does get repeated at other times and so vim input etc still gets disrupted.

**Comment by JoeRobich** [comment] 2020-03-19 01:33
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by JoeRobich** [comment] 2020-03-19 01:33
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by JoeRobich** [comment] 2020-03-19 01:33
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by JoeRobich** [comment] 2020-03-19 01:33
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by clynamen** [comment] 2020-03-19 07:15
@JoeRobich  I had the same problem. [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) seems to fix it.

**Comment by JoeRobich** [comment] 2020-03-20 16:56
@rhys-vdw Thanks for the report. Closing this now that 1.21.15 has been published.

**Closed by JoeRobich** 2020-03-20 16:56 UTC
Labels: Performance, Resolved-Fixed, Triaged
