### ISSUE TITLE
Cannot use extension on Pi-Top 

### ISSUE THREAD

**Issue by colombod** [OmniSharp/omnisharp-vscode#3642] opened 2020-03-08 17:34 UTC
## Issue Description ##
Running vscode connected to a remote pi-top (raspberry pi)
## Steps to Reproduce ##
Connect to a rasperry pi using ssh
Install omnisharp on the remote
open solution or project

### OmniSharp log ###
Starting OmniSharp server at 3/8/2020, 16:57:38
    Target: /home/pi/repos/pi-top/pi-top/pi-top.sln

[ERROR] Error: spawn /home/pi/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.21.13/.omnisharp/1.34.13/run ENOENT

### C# log ###
[WARNING]: Processor architecture 'armv7l' is not currently supported by the .NET Core debugger. Debugging will not be available.

## Environment information ##

**VSCode version**: 1.43.0-insider
**C# Extension**: 1.21.13

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/pi/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/home/pi/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/home/pi/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/home/pi/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.13|;

</details>

**Comment by WardenGnaw** [comment] 2020-03-10 20:09
Are you trying to develop on the Raspberry Pi or are you looking into debugging your program on the Raspberry Pi?

The debugger does not allow you to debug locally on the Raspberry Pi, but if you have another machine to host VS Code, you can [remote debug to the Raspberry Pi](https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm).

**Comment by colombod** [comment] 2020-03-10 20:37
I was trying to develop on the raspberry pi using the vs-remote over ssh

**Comment by gregg-miskelly** [comment] 2020-05-05 05:00
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2771

**Closed by gregg-miskelly** 2020-05-05 05:00 UTC
Labels: Needs More Info, Triaged
