### ISSUE TITLE
Support <ProjectReference /> aliases

### ISSUE THREAD

**Issue by Meowtimer** [OmniSharp/omnisharp-vscode#3309] opened 2019-10-02 23:06 UTC
## Issue Description ##
ProjectReference > Aliases  from csproj files not evaluated.
I believe reading aliases has been implemented for Reference  but not ProjectReference (https://github.com/OmniSharp/omnisharp-roslyn/pull/1409)

## Steps to Reproduce ##
Load a csproj including ProjectReferences with Aliases.

## Expected Behavior ##
omnisharp understands the aliases.

## Actual Behavior ##
omnisharp does not understand the aliases.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.3

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.0.0-preview1-002702 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-003131 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-003148 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.503 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.1.700 [/usr/local/share/dotnet/sdk]
  2.1.701 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002702 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|10.5.0|
|cobalt2-Theme|kamranmackey|0.0.3|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.3|
|debugger-for-chrome|msjsdiag|4.12.0|
|docomment|k--kato|0.1.8|
|dot|Stephanvs|0.0.1|
|er-syntax-highlighting|mikkel-ol|0.4.0|
|fairyfloss|nopjmp|0.0.5|
|fairyfloss|sailorhg|0.0.1|
|FilterText|yhirose|0.0.15|
|fish-vscode|skyapps|0.2.1|
|gitblame|waderyan|3.0.1|
|gitflow|vector-of-bool|1.2.1|
|gitlens|eamodio|10.0.1|
|graphviz-preview|EFanZh|1.3.3|
|hg|mrcrowl|1.3.0|
|jumptocolumn|salman-hasrat|1.1.0|
|language-haskell|justusadam|2.6.0|
|LogFileHighlighter|emilast|2.6.0|
|Material-theme|zhuangtongfa|2.27.2|
|mediawiki|jakeboone02|2.1.0|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.0.1|
|mono-debug|ms-vscode|0.15.8|
|mssql|ms-mssql|1.6.0|
|night-owl|sdras|1.1.3|
|noctis|liviuschera|10.11.0|
|pb-syntax|florianbaer|0.2.1|
|plsql|casian|0.0.5|
|powershell|ms-vscode|2019.9.0|
|prettier-vscode|esbenp|2.3.0|
|ruby|rebornix|0.25.3|
|rust|rust-lang|0.6.3|
|Theme-1337|ms-vscode|0.1.4|
|Theme-8-Colour-Dark|gerane|0.0.2|
|Theme-Cake|DanielPintilei|1.0.4|
|Theme-Eden|gerane|0.0.2|
|theme-hackershaze|Nuuf|2.0.1|
|Theme-MaterialKit|ms-vscode|0.1.4|
|Theme-Rebecca|gerane|0.0.2|
|Theme-Rebecca-mint|gerane|0.0.2|
|vscode-docker|ms-azuretools|0.8.1|
|vscode-mermaid-preview|vstirbu|1.2.0|
|vscode-styled-components|jpoissonnier|0.0.26|
|vscode-svgviewer|cssho|2.0.0|
|vscode-terminal-here|Tyriar|0.2.4|
|vscode-theme-onedark|akamud|2.1.0|
|vscode-xml|redhat|0.9.0|
|vsliveshare|ms-vsliveshare|1.0.905|
|vue-theme|mariorodeghiero|1.1.2|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by filipw** [comment] 2019-10-15 10:37
This used to work but looks like a regression...

**Comment by mholo65** [comment] 2020-01-22 11:26
Got bit by this also today. Will try to provide a fix for this in Omnisharp-Roslyn soonish.

**Comment by filipw** [comment] 2020-02-14 15:06
thanks - fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/1701

**Closed by filipw** 2020-02-14 15:06 UTC
Labels: Bug
