### ISSUE TITLE
MacOS omnisharp proccess errored (not happening on windows).

### ISSUE THREAD

**Issue by Jonatthu** [OmniSharp/omnisharp-vscode#2530] opened 2018-09-15 22:19 UTC
vscode 1.27
omnisharp 1.16.1

```
Starting OmniSharp server at 9/15/2018, 3:16:17 PM
    Target: /Users/jonatthu/Documents/Jonatthu/Playground/Playground.sln

OmniSharp server started with Mono 5.10.1.
    Path: /Users/jonatthu/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/OmniSharp.exe
    PID: 63529

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.13.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/jonatthu/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/jonatthu/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/jonatthu/Documents/Jonatthu/Playground'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/jonatthu/Documents/Jonatthu/Playground/Playground.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jonatthu/Documents/Jonatthu/Playground/GraphqlTest/GraphqlTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jonatthu/Documents/Jonatthu/Playground/FileObserver/FileObserver.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jonatthu/Documents/Jonatthu/Playground/EFTest/EFTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jonatthu/Documents/Jonatthu/Playground/Selectors/Selectors.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jonatthu/Documents/Jonatthu/Playground/RedisTestApi/RedisTestApi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jonatthu/Documents/Jonatthu/Playground/GraphqlApi/GraphqlApi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jonatthu/Documents/Jonatthu/Playground/RequestResponseExtensions/RequestResponseExtensions.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/jonatthu/Documents/Jonatthu/Playground'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/jonatthu/Documents/Jonatthu/Playground' on host 63439.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jonatthu/Documents/Jonatthu/Playground/GraphqlTest/GraphqlTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jonatthu/Documents/Jonatthu/Playground/GraphqlTest/GraphqlTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jonatthu/Documents/Jonatthu/Playground/GraphqlTest/GraphqlTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jonatthu/Documents/Jonatthu/Playground/FileObserver/FileObserver.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jonatthu/Documents/Jonatthu/Playground/FileObserver/FileObserver.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jonatthu/Documents/Jonatthu/Playground/FileObserver/FileObserver.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jonatthu/Documents/Jonatthu/Playground/EFTest/EFTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jonatthu/Documents/Jonatthu/Playground/EFTest/EFTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jonatthu/Documents/Jonatthu/Playground/EFTest/EFTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jonatthu/Documents/Jonatthu/Playground/Selectors/Selectors.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jonatthu/Documents/Jonatthu/Playground/Selectors/Selectors.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jonatthu/Documents/Jonatthu/Playground/Selectors/Selectors.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jonatthu/Documents/Jonatthu/Playground/RedisTestApi/RedisTestApi.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jonatthu/Documents/Jonatthu/Playground/RedisTestApi/RedisTestApi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jonatthu/Documents/Jonatthu/Playground/RedisTestApi/RedisTestApi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jonatthu/Documents/Jonatthu/Playground/GraphqlApi/GraphqlApi.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jonatthu/Documents/Jonatthu/Playground/GraphqlApi/GraphqlApi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jonatthu/Documents/Jonatthu/Playground/GraphqlApi/GraphqlApi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jonatthu/Documents/Jonatthu/Playground/RequestResponseExtensions/RequestResponseExtensions.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jonatthu/Documents/Jonatthu/Playground/RequestResponseExtensions/RequestResponseExtensions.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jonatthu/Documents/Jonatthu/Playground/RequestResponseExtensions/RequestResponseExtensions.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: GraphqlTest
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FileObserver
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: EFTest
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Selectors
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: RedisTestApi
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: GraphqlApi
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: RequestResponseExtensions
```

![image](https://user-images.githubusercontent.com/3742176/45590985-98d17a00-b8fa-11e8-8e09-d1ec5b50cf6b.png)

**Comment by estebanrao** [comment] 2018-09-17 15:42
I'm having the same issue
vscode: 1.27.2
omnisharp: 1.16.1

Similar output but for a different project

**Comment by akshita31** [comment] 2018-09-17 18:07
@Jonatthu @estebanrao Does the intellisense work for you ? I think this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2521.

**Comment by estebanrao** [comment] 2018-09-17 18:19
Yes it does, and yes, it is a duplicate of #2521 
This was the first result that appeared from a google search 🤭

**Closed as completed** 2018-09-17 19:24 UTC
Labels: Resolved-Duplicate

**Comment by akshita31** [comment] 2018-09-20 18:27
The beta with the fix for the red OmniSharp flame is out: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta1. Please give it a try.

**Comment by akshita31** [comment] 2018-09-20 22:27
The new beta is out: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta2. It can be installed by following the instructions here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases.

This aims at fixing the "Red OmniSharp flame" error when omnisharp is running on Mono,

**Comment by Jonatthu** [comment] 2018-09-21 16:56
@akshita31 Nice! I will wait until 1.17 goes out!

**Comment by gregg-miskelly** [comment] 2018-09-22 00:40
@jtsom your issue with debugging doesn't sound related to this issue. Can you open a new issue so we can talk more about what you are seeing?
