### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by nopogo** [OmniSharp/omnisharp-vscode#3651] opened 2020-03-11 08:29 UTC
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.43.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 21,
		"activateCallTime": 5,
		"activateResolvedTime": 145,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "onLanguage:csharp"
		}
	},
	"runtimeErrors": []
}
```

**Comment by cartermp** [comment] 2020-03-12 01:00
Closing as a duplicate of #3645

**Closed by cartermp** 2020-03-12 01:00 UTC
Labels: Resolved-Duplicate, Triaged
