### ISSUE TITLE
With .Net 5 Preview 2, failed to run .net 5 console project with reference to .Net 5.0 ClassLib

### ISSUE THREAD

**Issue by yuki233** [OmniSharp/omnisharp-vscode#3688] opened 2020-03-23 14:29 UTC
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.2.20169.1
 Commit:    0d8d4288ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.2.20169.1/

Host (useful for support):
  Version: 5.0.0-preview.2.20160.6
  Commit:  d12f79a4d1

.NET Core SDKs installed:
  5.0.100-preview.2.20169.1 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.2.20167.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
 
VS Code version:
vscode 1.43.1
C# Extension version:
C# extension 1.21.15

## Steps to reproduce
1.Via CLI, create a new .NET 5.0 console project with reference to a new .NET 5.0 class library project 
2. Open and run this project

## Expected  behavior
Project works normally

## Actual behavior
Project run failed with below error
Starting OmniSharp server at 3/23/2020, 5:46:58 PM
    Target: /Users/e2euser/s4/a

 

OmniSharp server started.
    Path: /Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/run
    PID: 1089

 

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.2 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/e2euser/s4/a'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/e2euser/s4/a'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/e2euser/s4/a/a.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/e2euser/s4/a'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/e2euser/s4/a' on host 903.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/e2euser/s4/a/a.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        Project '../b/b.csproj' targets 'net5.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v5.0'.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/e2euser/s4/a/a.csproj'.
/Users/e2euser/s4/a/a.csproj
/Users/e2euser/.vscode/extensions/ms-dotnettools.csharp-1.21.15/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1675,5): Error: Project '../b/b.csproj' targets 'net5.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v5.0'.

 

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/e2euser/s4/a/a.csproj

**Comment by filipw** [comment] 2020-03-23 16:02
this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3653

**Closed by filipw** 2020-03-23 16:02 UTC
