### ISSUE TITLE
Bug : Latest update of omnisharp 1.17.0 - preview Razor (cshtml) language service crashes visual studio code

### ISSUE THREAD

**Issue by saurabhnachankar** [OmniSharp/omnisharp-vscode#2641] opened 2018-11-01 12:51 UTC
Issue Type: <b>Bug</b>

While writing or editing razor page (cshtml) it crashes due to omnisharp's preview razor (cshtml) language service which is introduced in 1.17.0 !

**As it was crashing soo there is an option in vs code setting to disable it :**
To disable the preview Razor tooling set the "razor.disabled" setting to true.

I hope this gets fixed. Happy coding!

Extension version: 1.17.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2105 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by akshita31** [comment] 2018-11-01 14:42
cc @NTaylorMullen

**Comment by akshita31** [comment] 2018-11-01 14:43
@saurabhnachankar I haven't experienced the crash yet on my Windows machine. Could you post the output of "dotnet --info"

**Comment by NTaylorMullen** [comment] 2018-11-01 17:09
Oh wow, ya I haven't ran into this either. @saurabhnachankar can you reproduce this consistently?

**Comment by saurabhnachankar** [comment] 2018-11-02 06:30
Every time I change some code it stops responding, as i hereby attaching the screenshot of it. @akshita31 @NTaylorMullen 
![Uploading IMG-20181101-WA0001.jpeg…](The window has crashed)

**Comment by saurabhnachankar** [comment] 2018-11-02 06:31
Every time I change some code it stops responding, as i hereby attaching the screenshot of it. @akshita31 @NTaylorMullen 

![img-20181101-wa0001](https://user-images.githubusercontent.com/18824032/47897253-f9128000-de96-11e8-9521-d58fdc7ee1bc.jpeg)

**Comment by saurabhnachankar** [comment] 2018-11-02 06:35
@NTaylorMullen, yeah consistently this is crashing and I am unable to work due to this update!

Finally after hours of research i had to disable the Razor tooling !

**Comment by NTaylorMullen** [comment] 2018-11-02 17:22
> @NTaylorMullen, yeah consistently this is crashing and I am unable to work due to this update!

Does it also crash for you with a default project? Aka `dotnet new razor`?

**Comment by remcoros** [comment] 2018-11-04 09:15
After updating to latest omnisharp, I have the **exact** same issue.

```
PS C:\Users\Remco> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.0.0-preview2-006497 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.0-preview1-007372 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008530 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-25816-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

When I created an empty razor project (dotnet new razor), and open that, it didn't crash and started to download the latest omnisharp/debugger server, and the razor language service.

When I openen my original project again (regular .net standard project, no mvc, no razor), it didn't crash anymore.

**Comment by NTaylorMullen** [comment] 2018-11-05 18:30
> After updating to latest omnisharp, I have the **exact** same issue.
> When I created an empty razor project (dotnet new razor), and open that, it didn't crash and started to download the latest omnisharp/debugger and the razor language service.
> 
> When I opened my original project again (regular .net standard project, no mvc, no razor), it didn't crash anymore.

Wait, @remcoros so it does crash for you or does not?

**Comment by remcoros** [comment] 2018-11-05 19:09
> > After updating to latest omnisharp, I have the **exact** same issue.
> > When I created an empty razor project (dotnet new razor), and open that, it didn't crash and started to download the latest omnisharp/debugger and the razor language service.
> > When I opened my original project again (regular .net standard project, no mvc, no razor), it didn't crash anymore.
> 
> Wait, @remcoros so it does crash for you or does not?

not, since I opened that new razor project.

**Comment by NTaylorMullen** [comment] 2018-11-05 19:10
> ot (on any project), since I opened that razor project.

Ahh, interesting, good to know.

**Comment by NTaylorMullen** [comment] 2018-11-08 18:16
Found the root cause of this issue [here](https://github.com/Microsoft/vscode/issues/62802). Stay tuned for a fix from vscode 😄

**Comment by NTaylorMullen** [comment] 2018-11-27 20:57
@rchande or @akshita31 feel free to close this. It's been fixed.

**Closed** 2018-11-27 21:11 UTC
