### ISSUE TITLE
Intellisense issue for C# attributes on classes 

### ISSUE THREAD

**Issue by pcgeek86** [OmniSharp/omnisharp-vscode#1316] opened 2017-03-12 17:39 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

VS Code version: 1.10.2
C# Extension version: 1.7.0

## Steps to reproduce

Add an attribute to a class.

## Expected  behavior

Intellisense / tab-completion should not append the text "Attribute" to the attribute definition.

## Actual behavior

Tab-completion adds the "Attribute" text to an attribute on a class. The short-hand method is preferred, and I believe is the default in Visual Studio on Windows. I might be wrong about this.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by DustinCampbell** [comment] 2017-03-13 14:41
Hi Trevor -- this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/393

**Closed** 2017-03-13 14:41 UTC
Labels: Resolved-Duplicate
