### ISSUE TITLE
No intellisense within curly braces trying to assign properties

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#573] opened 2016-07-15 08:48 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
VS Code version: 1.3.1
C# Extension version: 1.2.2

## Steps to reproduce
Instantiate a constructor, open curly braces and hit Ctrl+Space to invoke intellisense

## Expected  behavior
To see list of available properties for that object

## Actual behavior
See list of all objects not relevant to the object

<img width="777" alt="screen shot 2016-07-15 at 09 44 40" src="https://cloud.githubusercontent.com/assets/105126/16868729/26df2540-4a71-11e6-84f1-2186338d77fc.png">

**Comment by DustinCampbell** [comment] 2016-07-16 09:52
This is a dupe of #260, which is dependent on https://github.com/OmniSharp/omnisharp-roslyn/issues/78.

**Closed by DustinCampbell** 2016-07-16 09:52 UTC
Labels: Bug, Resolved-Duplicate

**Comment by jchannon** [comment] 2016-07-16 09:55
Any ETA?

**Comment by DustinCampbell** [comment] 2016-07-16 09:58
It's a bit further down the road. I have to wrap up the work I'm currently doing to better enable Unity development. Then I'll be able to take a look at a number of lingering bugs like this one.

**Comment by filipw** [comment] 2017-01-27 08:23
@DustinCampbell would it make sense to polyfill the existing omnisharp-roslyn autocomplete service quickly to fix this ASAP (similarly to how keywords are added now), without having to wait for introducing the bigger work needed with creating a new completion endpoint for Completion API?

from the top of my head:

```csharp
if (item.Properties.ContainsKey("Provider") && 
item.Properties["Provider"] == "Microsoft.CodeAnalysis.CSharp.Completion.Providers.ObjectInitializerCompletionProvider")
{
    var response = new AutoCompleteResponse()
    {
        CompletionText = item.DisplayText,
        DisplayText = item.DisplayText,
        Snippet = item.DisplayText,
        Kind = item.Tags.FirstOrDefault() ?? "Property"
    };

    completions.Add(response);
}
```

That could improve the VS Code experience a lot in a hurry.
