### ISSUE TITLE
Mono error showing in OminSharp Log and causing a forced focus

### ISSUE THREAD

**Issue by Wolftousen** [OmniSharp/omnisharp-vscode#3712] opened 2020-04-09 04:37 UTC
## Steps to Reproduce ##
I cannot provide you with access to our repos, private organization and all...

## Expected Behavior ##
OmniSharp Log shouldn't ever be stealing focus, especially for things that don't actually matter.

## Actual Behavior ##
When the following entry appears in OmniSharp Log, the panel steals focus from everything else:

mono[12984] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

### OmniSharp log ###
Given i'm loading 80+ repos into my workspaces this log is tremendously large.  Also the log contains info that i can't share.

This is the log entry in question though: mono[12984] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

### C# log ###
C# log is empty, this happens when OmniSharp is loading or when you restart it

## Environment information ##

**VSCode version**: 1.44.0
**C# Extension**: 1.21.16

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.8.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.16|
|dotnet-test-explorer|formulahendry|0.7.1|
|gitlens|eamodio|10.2.1|
|mssql|ms-mssql|1.9.0|
|poor-mans-t-sql-formatter-vscode|TaoKlerks|1.6.10|
|prettier-vscode|esbenp|4.1.1|
|remote-containers|ms-vscode-remote|0.106.0|
|remote-ssh|ms-vscode-remote|0.51.0|
|remote-ssh-edit|ms-vscode-remote|0.51.0|
|remote-wsl|ms-vscode-remote|0.42.4|
|vscode-docker|ms-azuretools|1.0.0|
|vscode-pull-request-github|GitHub|0.15.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscode-trello-viewer|Ho-Wan|0.6.0|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by cartermp** [comment] 2020-04-09 20:11
Closing as duplicate of #3708

**Comment by cartermp** [comment] 2020-04-09 20:11
Closing as duplicate of #3708

**Closed by cartermp** 2020-04-09 20:11 UTC
Labels: Resolved-Duplicate, Triaged
