### ISSUE TITLE
ms-dotnettools.csharp-1.23.17

### ISSUE THREAD

**Issue by faeizazizi** [OmniSharp/omnisharp-vscode#4943] opened 2021-12-10 04:06 UTC
Issue Type: <b>Bug</b>

When I tried to switch between projects file:

[error] Error: Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators.
Its package.json#enabledApiProposals-property declares:  but NOT quickPickSeparators.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp

Extension version: 1.23.17
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.75GB (50.46GB free)|
|Process Argv|--crash-reporter-id f4120432-0ac5-4510-8f46-3752362169d7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by PsychoNineSix** [comment] 2021-12-10 06:44
I was told in a previous issue that this is fixed in a prerelease:

https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2

**Comment by aureliosaraiva** [comment] 2021-12-16 00:45
I have the same problem. I'm using Mac. I downloaded the beta version mentioned, but it still has the same problem.

**Comment by kellan-cartledge** [comment] 2021-12-21 02:12
Same issue. 
Extension version: 1.23.17
VS Code version: 1.63.2
OS version: macOS 11.6.1
Restricted Mode: No

**Comment by dethmourne** [comment] 2021-12-21 21:54
Same issue as well.

**Comment by alan994** [comment] 2021-12-22 13:20
Same issue 👍 
I just installed `v1.24.0-beta1` and got an error 
![image](https://user-images.githubusercontent.com/8849512/147098870-098ba162-aa24-48c4-9001-7a2f62d56c81.png)

Any help around this?

**Comment by explorest** [comment] 2021-12-23 01:28
Same issue happening on my Linux machine.
Extension version: 1.23.17
VS Code version: 1.63.2
OS version: Ubuntu 20.04
Restricted Mode: No

**Comment by ALENTL** [comment] 2022-01-01 10:48
Same issue happening on my Linux distro
Extension version: 1.23.17
VS Code Version: 1.63.2
OS Version: Pop Os! 21.10
Restricted Mode: No
.Net SDK: 6.0

**Comment by gregg-miskelly** [comment] 2022-01-01 14:39
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4970

**Closed by gregg-miskelly** 2022-01-01 14:39 UTC

**Comment by 1thorsheikh0** [comment] 2023-01-05 07:25
how much size it will take (mbs)
