### ISSUE TITLE
Errors are reported multiple times

### ISSUE THREAD

**Issue by aaubry** [OmniSharp/omnisharp-vscode#1881] opened 2017-11-20 11:16 UTC
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.18.1
C# Extension version: 1.13.1

## Steps to reproduce

1. Create a new console application `dotnet new console`
2. Add a syntax error, e.g. remove a semicolon.
3. Build the project (Ctrl+Shift+B)

## Expected  behavior

A single entry in the "Problems" tab.

## Actual behavior

Omnisharp reports the error at least twice (sometimes more), and the error from the build is also reported.

![Screenshot](https://cld.pt/dl/download/463e3f2c-8ee0-487f-b917-ca9c8eda01c3/Visual%20Studio%20Code.png)

**Comment by DustinCampbell** [comment] 2017-11-20 14:30
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1830.

**Closed** 2017-11-20 14:30 UTC
Labels: Resolved-Duplicate

**Comment by aaubry** [comment] 2017-11-20 15:32
This is not completely a duplicate of #1830, because that issue does not mention the duplication between the Omnisharp errors and the build errors.

**Comment by DustinCampbell** [comment] 2017-11-20 15:36
I think that's related to https://github.com/OmniSharp/omnisharp-vscode/issues/1198.
