### ISSUE TITLE
Intellisense loads incredibly slow in large projects

### ISSUE THREAD

**Issue by nrj** [OmniSharp/omnisharp-vscode#230] opened 2016-04-21 15:16 UTC
I am working on a rather large Unity project and whenever I use my hotkey in Visual Studio Code to trigger Intellisense, I am stuck having to wait at least 5 seconds before I see the popup with code suggestions. No matter what I'm attempting to get suggestions on, this is the result:

![screen-shot-2016-04-21-at-10 44 28](https://cloud.githubusercontent.com/assets/149472/14713995/a20816bc-07e3-11e6-8000-554ddcfda64a.png)

I have the following in my user settings:
    
    "editor.suggestOnTriggerCharacters": false,
    "editor.quickSuggestions": false,

And in my hotkeys:

    "key": "cmd+space", "command": "editor.action.triggerSuggest", "when": "editorTextFocus"

VSCode 1.0.0 
C# for Visual Studio Code (powered by OmniSharp) 0.3.7

There was the same issue on the vscode project itself, which is now closed as fixed. You can see it here: https://github.com/Microsoft/vscode/issues/1923

**Comment by okuligowski** [comment] 2016-04-28 08:14
Same issue here. Driving me crazy, as there is no reasonable alternative on OSX (I hate MonoDevelop :P).

**Comment by reapazor** [comment] 2016-06-02 18:31
Just a quick relief, as this also happens for me at times in big projects.

An interim solution I've implemented is branching off chunks of code and compiling out DLLs of code that is not changed often.  

Not the best solution, but helps ...

**Comment by kreso22** [comment] 2016-06-08 04:57
I think this is linked #269

**Comment by DustinCampbell** [comment] 2016-08-27 10:41
Hey everyone -- I'm curious to know if the [latest beta](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.4.0-beta8) works better for any of you. We've addressed some significant performance issues in large project.

**Comment by reapazor** [comment] 2016-08-28 00:10
I'll give it a whirl this week :)

**Comment by atsokolov** [comment] 2016-09-01 13:47
Hi! Just tried the latest beta with our enormous unity project - works great for me, thanks!

**Comment by DustinCampbell** [comment] 2016-09-01 14:53
Great to hear! In that case, this is almost certainly a duplicate of #269. We've done a lot of work to improve handling of larger solutions. There is still much to do, but it should work much better -- especially for solutions with >1000 files. We'll track further work on on this in #269.

**Closed by DustinCampbell** 2016-09-01 14:53 UTC
Labels: Bug, Performance, Unity
