### ISSUE TITLE
Unable to open projects on Arch Linux

### ISSUE THREAD

**Issue by nikoslyk2093** [OmniSharp/omnisharp-vscode#3354] opened 2019-10-16 21:52 UTC
I followed the instructions here : 
https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-.NET-Core-Debugger-on-Arch-Linux

but i still cant make the debugger to work.

this is the output from vscode : 

> Starting OmniSharp server at 10/17/2019, 12:48:45 AM
>     Target: /home/nikos/Desktop/test/TestWebApp
> 
> OmniSharp server started with Mono 6.0.0.
>     Path: /home/nikos/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.20/omnisharp/OmniSharp.exe
>     PID: 115440
> 
> [info]: OmniSharp.Stdio.Host
>         Starting OmniSharp on arch 0.0 (x64)
> [info]: OmniSharp.Services.DotNetCliService
>         DotNetPath set to dotnet
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Located 1 MSBuild instance(s)
>             1: StandAlone 16.3 - "/home/nikos/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.20/omnisharp/.msbuild/Current/Bin"
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         MSBUILD_EXE_PATH environment variable set to '/home/nikos/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.20/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Registered MSBuild instance: StandAlone 16.3 - "/home/nikos/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.20/omnisharp/.msbuild/Current/Bin"
>             CscToolExe = csc.exe
>             TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
>             MSBuildToolsPath = /home/nikos/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.20/omnisharp/.msbuild/Current/Bin
>             CscToolPath = /home/nikos/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.20/omnisharp/.msbuild/Current/Bin/Roslyn
>             BypassFrameworkInstallChecks = true
>             MSBuildExtensionsPath = /usr/lib/mono/xbuild
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Detecting Cake files in '/home/nikos/Desktop/test/TestWebApp'.
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Could not find any Cake files
> [info]: OmniSharp.MSBuild.ProjectSystem
>         No solution files found in '/home/nikos/Desktop/test/TestWebApp'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Queue project update for '/home/nikos/Desktop/test/TestWebApp/TestWebApp.csproj'
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Detecting CSX files in '/home/nikos/Desktop/test/TestWebApp'.
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Could not find any CSX files
> [info]: OmniSharp.WorkspaceInitializer
>         Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
> [info]: OmniSharp.WorkspaceInitializer
>         Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
> [info]: OmniSharp.WorkspaceInitializer
>         Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
> [info]: OmniSharp.WorkspaceInitializer
>         Configuration finished.
> [info]: OmniSharp.Stdio.Host
>         Omnisharp server running using Stdio at location '/home/nikos/Desktop/test/TestWebApp' on host 115100.
> [info]: OmniSharp.MSBuild.ProjectManager
>         Loading project: /home/nikos/Desktop/test/TestWebApp/TestWebApp.csproj
>   It was not possible to find any installed .NET Core SDKs
>   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
>       https://aka.ms/dotnet-download
> [warn]: OmniSharp.MSBuild.ProjectManager
>         Failed to load project file '/home/nikos/Desktop/test/TestWebApp/TestWebApp.csproj'.
> /home/nikos/Desktop/test/TestWebApp/TestWebApp.csproj(1,1)
> Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  /home/nikos/Desktop/test/TestWebApp/TestWebApp.csproj
>   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject (System.String errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, System.Object[] args) [0x00040] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1] (System.Boolean condition, System.String errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, T1 arg0) [0x00003] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1] (Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, T1 arg0) [0x00000] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].ExpandAndLoadImportsFromUnescapedImportExpressionConditioned (System.String directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement, System.Collections.Generic.List`1[Microsoft.Build.Construction.ProjectRootElement]& projects, Microsoft.Build.BackEnd.SdkResolution.SdkResult& sdkResult, System.Boolean throwOnFileNotExistsError) [0x00254] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].ExpandAndLoadImports (System.String directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement, Microsoft.Build.BackEnd.SdkResolution.SdkResult& sdkResult) [0x00027] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].EvaluateImportElement (System.String directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement) [0x0000d] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].PerformDepthFirstPass (Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport) [0x000e6] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].Evaluate (Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Framework.BuildEventContext buildEventContext) [0x0011c] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].Evaluate (Microsoft.Build.Evaluation.IEvaluatorData`4[P,I,M,D] data, Microsoft.Build.Construction.ProjectRootElement root, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, System.Int32 maxNodeCount, Microsoft.Build.Collections.PropertyDictionary`1[T] environmentProperties, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Evaluation.IItemFactory`2[S,T] itemFactory, Microsoft.Build.Evaluation.IToolsetProvider toolsetProvider, Microsoft.Build.Evaluation.ProjectRootElementCache projectRootElementCache, Microsoft.Build.Framework.BuildEventContext buildEventContext, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, System.Int32 submissionId, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext, System.Boolean interactive) [0x0002f] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project.Reevaluate (Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x0005e] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary (Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x00035] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary (Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x00000] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary (Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x00007] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project.Initialize (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, System.String subToolsetVersion, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x00126] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, System.String subToolsetVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x00093] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, System.String subToolsetVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings) [0x00000] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings) [0x00000] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection) [0x00000] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject (System.String fileName, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion) [0x000f7] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject (System.String fileName, System.String toolsVersion) [0x00000] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
>   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore (System.String filePath) [0x0003f] in <c933cc4e87d7492788a994e6b5a03bec>:0 
>   at OmniSharp.MSBuild.ProjectLoader.BuildProject (System.String filePath) [0x0000d] in <c933cc4e87d7492788a994e6b5a03bec>:0 
>   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load (System.String filePath, OmniSharp.MSBuild.ProjectIdInfo projectIdInfo, OmniSharp.MSBuild.ProjectLoader loader) [0x00015] in <c933cc4e87d7492788a994e6b5a03bec>:0 
>   at OmniSharp.MSBuild.ProjectManager+<>c__DisplayClass29_0.<LoadProject>b__0 () [0x00000] in <c933cc4e87d7492788a994e6b5a03bec>:0 
>   at (wrapper delegate-invoke) System.Func`1[System.ValueTuple`3[OmniSharp.MSBuild.ProjectFile.ProjectFileInfo,System.Collections.Immutable.ImmutableArray`1[OmniSharp.MSBuild.Logging.MSBuildDiagnostic],OmniSharp.MSBuild.Notification.ProjectLoadedEventArgs]].invoke_TResult()
>   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject (System.String projectFilePath, System.Func`1[TResult] loader) [0x0001b] in <c933cc4e87d7492788a994e6b5a03bec>:0 
> 
> [fail]: OmniSharp.MSBuild.ProjectManager
>         Attempted to update project that is not loaded: /home/nikos/Desktop/test/TestWebApp/TestWebApp.csproj

**Comment by WardenGnaw** [comment] 2019-10-17 17:45
The logs you provided are for the language service. Do you have a `tasks.json` and `launch.json` for building and debugging?

Could you share the logs you get by adding logging to your `launch.json`?

You can do this by adding the following to your `launch.json`:
```
"logging": {
   "engineLogging": true
}
```

**Comment by SuddenGunter** [comment] 2019-10-22 15:28
@nikoslyk2093 @WardenGnaw same here
But from my point of view, it's not a debugger issue, VS Code C# extension wasn't able to find SDKs just when I've opened my project.

**Comment by SuddenGunter** [comment] 2019-10-23 10:40
@nikoslyk2093 try this
https://github.com/OmniSharp/omnisharp-vscode/issues/3316#issuecomment-538807803
- resolved issue for me
also see this https://github.com/OmniSharp/omnisharp-roslyn/issues/1610

**Comment by gregg-miskelly** [comment] 2019-10-28 19:45
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3316

**Closed by gregg-miskelly** 2019-10-28 19:45 UTC
