### ISSUE TITLE
Omnisharp does not actually install

### ISSUE THREAD

**Issue by StornZ** [OmniSharp/omnisharp-vscode#3399] opened 2019-11-08 03:51 UTC
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
Install C# extension powered by omnisharp from within VS Code

## Expected  behavior
Extension downloads, installs, and is placed in the .omnisharp folder at the %UserProfile% path

## Actual behavior
Nothing actually installs and therefore the path cannot be found.

**Comment by filipw** [comment] 2019-11-08 05:32
that folder is empty by design. can you please describe what problem do you actually have?

**Comment by filipw** [comment] 2019-11-22 14:17
Closing this as by design.
The location of the extension is under VS Code extension folder 

Windows %USERPROFILE%\.vscode\extensions.
Mac $HOME/.vscode/extensions.
Linux $HOME/.vscode/extensions.

**Closed by filipw** 2019-11-22 14:17 UTC
Labels: Needs More Info, Resolved-By Design

**Comment by StornZ** [comment] 2019-11-22 16:12
So what you're saying is when I download the extension the folder should be empty and vscode should not be finding the omnisharp path by default? It used to work where I just downloaded and installed the extension and it worked. Something obviously broke.

**Comment by filipw** [comment] 2019-11-22 16:52
The issue you opened was about `%UserProfile%/.omnisharp` path, which by default is empty and is in no way related to OmniSharp being/not being there. It is not where the extension installs anything. That folder is created at OmniSharp startup as a placeholder for global configuration files and preserved across extension/OmniSharp updates.

However, if after the extension installs (which happens into the 3 locations I posted), it cannot find OmniSharp path, then it's a different issue. 
Actually, the extension doesn't ship with OmniSharp. When you install the extension it only installs the client part, and then it downloads OmniSharp server and the C# debugger from the Internet separately. It could be that on your machine this download fails (you have to be online, so installing an extension on an offline machine will not succeed as it won't be able to pull OmniSharp server).

Please post the C# extension log and/or the OmniSharp log (it could also be that OmniSharp was downloaded, but cannot start for some other reason) - we could then troubleshoot it.

Hope this helps.
