### ISSUE TITLE
Intelisense autocomplete turns off while typing

### ISSUE THREAD

**Issue by hristijankiko** [OmniSharp/omnisharp-vscode#3280] opened 2019-09-16 06:37 UTC
## Issue Description ##
Intellisense autocomplete stops working as soon as I type the first character.
For example:
Intellisense works
![image](https://user-images.githubusercontent.com/8568277/64938082-03b3e900-d8a0-11e9-8a26-78047bff54ec.png)
Intellisense does not work
![image](https://user-images.githubusercontent.com/8568277/64938106-162e2280-d8a0-11e9-8e3e-a49b603295dd.png)

If i complete it, then it works again
![image](https://user-images.githubusercontent.com/8568277/64938137-33fb8780-d8a0-11e9-9c15-32d8babe49a5.png)

Is there a setting which controls this or is it related to something else?

## Steps to Reproduce ##
Start typing after the initial autocomplete suggestions are displayed.

## Expected Behavior ##
Intellisense should continue working as I type
## Actual Behavior ##
Intellisense turns off after I type the first character.
### OmniSharp log ###
Working as expected, no errors

### C# log ###
No logs

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|1.4.3|
|better-comments|aaron-bond|2.0.5|
|codebucket|pstreule|0.2.0|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.2|
|debugger-for-chrome|msjsdiag|4.11.7|
|discord-vscode|icrawl|3.8.2|
|docomment|k--kato|0.1.8|
|dotenv|mikestead|1.0.1|
|dotnet-test-explorer|formulahendry|0.7.1|
|gitconfig|sidneys1|2.0.1|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.9.3|
|java|redhat|0.48.0|
|LogFileHighlighter|emilast|2.5.0|
|material-icon-theme|PKief|3.9.0|
|Material-theme|zhuangtongfa|2.27.1|
|msbuild-project-tools|tintoy|0.2.55|
|mssql|ms-mssql|1.6.0|
|powershell|ms-vscode|2019.5.0|
|python|ms-python|2019.9.34911|
|remote-wsl|ms-vscode-remote|0.39.5|
|theme-cobalt2|wesbos|2.1.6|
|vscode-coverage-gutters|ryanluker|2.4.0|
|vscode-docker|ms-azuretools|0.8.1|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-java-debug|vscjava|0.21.0|
|vscode-java-dependency|vscjava|0.5.1|
|vscode-java-pack|vscjava|0.8.0|
|vscode-java-test|vscjava|0.19.0|
|vscode-jest|Orta|3.0.2|
|vscode-jira|KnisterPeter|0.6.0|
|vscode-npm-script|eg2|0.3.9|
|vscode-solution-explorer|fernandoescolar|0.3.5|
|vscode-styled-components|jpoissonnier|0.0.26|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-yaml|redhat|0.5.3|
|vscodeintellicode|VisualStudioExptTeam|1.1.9|
|vsliveshare|ms-vsliveshare|1.0.809|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by cartermp** [comment] 2020-04-28 23:39
@hristijankiko Does this still reproduce for you with the latest VSCode? If so, is there any log you can attach? It sounds like some kind of IntelliSense crash going on here, but we can't reproduce it with a new ASP.NET Core app.

**Comment by cartermp** [comment] 2020-09-23 00:52
Closing out as no additional info was added.

**Closed by cartermp** 2020-09-23 00:52 UTC
Labels: Needs More Info, Triaged
