### ISSUE TITLE
[WARNING]: The current Linux distribution 'ubuntu' version '17.04' is not currently supported by the .NET Core debugger. Debugging will not be available.

### ISSUE THREAD

**Issue by jcasimiro** [OmniSharp/omnisharp-vscode#1381] opened 2017-04-12 15:28 UTC
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         ubuntu.17.04-x64

VS Code version:
Version 1.11.1
Commit d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
Date 2017-04-06T13:55:56.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

C# Extension version:
c# 1.9.0 - beta2

## Steps to reproduce
Just create a new project using the command "dotnet new", then open the vscode and try to debug the project.

## Expected  behavior
Debug the program.

## Actual behavior
The .NET Core Debugger is still being downloaded. See the C# Output Window for more information.

**Comment by jcasimiro** [comment] 2017-04-12 16:01
https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/platform.ts

(...)
private static getExactRuntimeId(distributionName: string, distributionVersion: string): string {
        switch (distributionName) {
            case 'ubuntu':
                if (distributionVersion === "14.04") {
                    // This also works for Linux Mint
                    return LinuxRuntimeId.ubuntu_14_04;
                }
                else if (distributionVersion === "16.04") {
                    return LinuxRuntimeId.ubuntu_16_04;
                }
                else if (distributionVersion === "16.10") {
                    return LinuxRuntimeId.ubuntu_16_10;
                }
                break;
(...)

Is it safe to make another else if to my current version, returning LinuxRuntimeId.ubuntu_16_10??

Thanks,
José Amílcar Casimiro

**Comment by gregg-miskelly** [comment] 2017-04-12 16:08
@jcasimiro that depends on if Ubuntu 17 is backwards compatible enough with 16.10 that .NET Core 16.10 will actually work. Have you tried running a basic 'hello world' app using the 16.10 .NET Core by chance?

**Comment by jcasimiro** [comment] 2017-04-12 16:11
Hello,

Yes the application runs fine, only the debugger is not working.
I new to this project, but i read somewhere that i could define by configuration what version of linux i want to use, is this correct?

Thanks

**Comment by gregg-miskelly** [comment] 2017-04-12 16:21
@jcasimiro The next version of the C# extension will support that, but our current version doesn't yet. Let me send you a private version with the new support for specifying the runtime id and you can give that a try.

**Comment by jcasimiro** [comment] 2017-04-12 16:25
Thanks, you're the man. ;)

**Comment by gregg-miskelly** [comment] 2017-04-12 16:40
There is a private attached to this comment. Please:

1. Download [csharp-1.9.0-beta2-private.zip](https://github.com/OmniSharp/omnisharp-vscode/files/917252/csharp-1.9.0-beta2-private.zip)
2. Rename the extension from '.zip' to '.vsix'
3. Follow instructions on https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases for installing it.
4. Let me know how well things work for you

Hope this helps.

**Comment by jcasimiro** [comment] 2017-04-12 19:20
Gregg it worked!!! Thank you man. 

This was the output after installation:
---------------------------------------------------------------------------------------
Updating C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=17.04

Downloading package 'Mono Runtime (Linux / x64)' (1545 KB) .................... Done!
Downloading package 'Mono Framework Assemblies' (5829 KB) .................... Done!
Downloading package 'OmniSharp (Mono 4.6)' (21959 KB) .................... Done!

Installing package 'Mono Runtime (Linux / x64)'
Installing package 'Mono Framework Assemblies'
Installing package 'OmniSharp (Mono 4.6)'

Finished
[WARNING]: The current Linux distribution 'ubuntu' version '17.04' is not currently supported by the .NET Core debugger. Debugging will not be available.
If 'ubuntu' is binary compatible with a Linux distribution officially supported by .NET Core, you may be able to resolve this by setting 'csharp.fallbackDebuggerLinuxRuntimeId' in 'File->Preferences->Settings' and restarting VS Code.

**Obviously I changed the setting.**
Thank you!! Solved!!

**Comment by gregg-miskelly** [comment] 2017-04-12 22:46
@jcasimiro Excellent! Thanks for trying. I will close this for now then.

**Closed by gregg-miskelly** 2017-04-12 22:46 UTC
Labels: Debugger, Debugger-Install

**Comment by alikzao** [comment] 2017-04-29 16:15
I was not helped by this recipe unfortunately.
![Screenshot](http://joxi.ru/v29XlGvu3XwvNm.jpg)

**Comment by gregg-miskelly** [comment] 2017-05-01 22:02
@alikzao the problem is that `true` is not a valid value for fallbackDebuggerLinuxRuntimeId. If you are on Ubuntu17, you likely want `ubuntu.16.10-x64`.

**Comment by SuddenGunter** [comment] 2017-06-30 18:02
@gregg-miskelly Thank you, it works. 
And it's not required to install a beta version of OmniSharp because the latest one (v1.11) works fine.
You just need to add `"csharp.fallbackDebuggerLinuxRuntimeId": "ubuntu.16.10-x64"` and everything will be ok.

**Comment by neverbackdow** [comment] 2017-07-30 12:13
@gregg-miskelly its not working pleaze provide me exact steps what to do to debug code in ubuntu 17.04 .net core c#

**Comment by gregg-miskelly** [comment] 2017-07-31 15:06
I am on vacation this week, but at this point I would recommend following instructions from the wiki on installing the most recent beta, as that has official support and is just about to go out on the release channel.
