### ISSUE TITLE
Possibly a color coding issue due to preprocessor directives

### ISSUE THREAD

**Issue by gsscoder** [OmniSharp/omnisharp-vscode#3521] opened 2020-01-22 07:36 UTC
Wrong color coding for me:
First image: `IEnumeble<Tuple...` (line 78).
![image](https://user-images.githubusercontent.com/611219/72921845-e0db8a80-3d00-11ea-9aa2-fae7413ad07c.png)

Second Image: colors of all preprocessor directives.
![image](https://user-images.githubusercontent.com/611219/72921862-e76a0200-3d00-11ea-9d3e-40cb1f7b663b.png)

Hope this can help you make OmniSharp even better!

Best Regards,
Giacomo

**Comment by JoeRobich** [comment] 2020-01-22 18:23
@gsscoder Thanks for opening an issue! I updated the description with the images from your link.

**Comment by gsscoder** [comment] 2020-01-24 18:07
@JoeRobich, happy to help! :)

**Comment by XeonG** [comment] 2020-02-26 12:15
One major reason I still use Visual Studio instead of VSCode is because of this issue ...and it has been reported multiple times.

**Comment by gsscoder** [comment] 2020-02-29 06:01
@XeonG, I'm sure the team will fix it. :)

**Comment by XeonG** [comment] 2020-03-05 11:00
lol right, MS still can't even manage to implement the basics of scroll wheel cycling tabs let alone support a multiline tabbar... https://github.com/microsoft/vscode/issues/13902

despite other developers writing the code for it to, they can't even be bothered to implement it in the main codebase..

**Comment by JoeRobich** [comment] 2020-03-05 18:47
@XeonG As with everything, there is a cost to fixing bugs and making enhancements and we have to spend our resources wisely. This particular issue is a limitation of the textmate theme and will be resolved once we upgrade to providing semantic classification. The benefit of focusing on semantic classification as opposed to textmate is that it is a complete solution for the classification issues we have.

**Comment by XeonG** [comment] 2020-03-10 15:24
> @XeonG As with everything, there is a cost to fixing bugs and making enhancements and we have to spend our resources wisely. This particular issue is a limitation of the textmate theme and will be resolved once we upgrade to providing semantic classification. The benefit of focusing on semantic classification as opposed to textmate is that it is a complete solution for the classification issues we have.

There are fixes and implementation to support both mousewheel tab cycling on the tabbar and also support for multiline tabbar functionality... how long could it possibly take to implement that with some customization options... seriously frankly I'm not even sure how it has taken this long... requests for those features have been around since vscode near came out..  user have become accustomed to such features in other software for 2 decades now.. its not new, though according to some of your staff behind stalling such things https://github.com/microsoft/vscode/issues/13902  its like some hard to add new thing.

**Comment by cartermp** [comment] 2020-03-17 21:00
Closing this as by design for now, since the only way to really support this is with semantic colorization, which LSP does not currently support. However, the good news is that semantic colorization will be coming to LSP (date unknown, but it won't be forever), and once that does, Roslyn has what it needs to provide the level of colorization needed here. So I'll close this out on that basis.

**Closed by cartermp** 2020-03-17 21:00 UTC
Labels: Resolved-By Design, Triaged
