### ISSUE TITLE
The "ProtoCompile" task failed unexpectedly

### ISSUE THREAD

**Issue by xolott** [OmniSharp/omnisharp-vscode#3258] opened 2019-09-03 20:02 UTC
## Issue Description ##

I can't use omnisharp in vscode with grpc projects from the .Net Core 3.0 Preview

## Steps to Reproduce ##
Execute: 

dotnet new grpc -n TestApp -o src/

cd src/

code .

## Expected Behavior ##

Normal behavior

## Actual Behavior ##

Exception: The "ProtoCompile" task failed unexpectedly.

### OmniSharp log ###
<details>

Starting OmniSharp server at 9/3/2019, 3:40:05 PM
    Target: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer

OmniSharp server started.
    Path: /home/jose/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/run
    PID: 26921

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.0 - "/home/jose/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/jose/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "/home/jose/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /home/jose/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/jose/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/jose/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/clients/csharp/grpc_client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/audit_logger/gen_csharp/audit_logger.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/facenet/gen_csharp/facenet.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/health_check/gen_csharp/health_check.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/midas/gen_csharp/midas.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/tessocr/gen_csharp/tessocr.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/src/FaissBalancer.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/clients/csharp/grpc_client.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer' on host 26740.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/clients/csharp/grpc_client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/clients/csharp/grpc_client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/audit_logger/gen_csharp/audit_logger.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/audit_logger/gen_csharp/audit_logger.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/audit_logger/gen_csharp/audit_logger.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/facenet/gen_csharp/facenet.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/facenet/gen_csharp/facenet.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/facenet/gen_csharp/facenet.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/health_check/gen_csharp/health_check.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/health_check/gen_csharp/health_check.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/health_check/gen_csharp/health_check.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/midas/gen_csharp/midas.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/midas/gen_csharp/midas.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/midas/gen_csharp/midas.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/tessocr/gen_csharp/tessocr.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/tessocr/gen_csharp/tessocr.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/lib/namku_grpc/services/tessocr/gen_csharp/tessocr.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/src/FaissBalancer.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "ProtoCompile" task failed unexpectedly.
System.MissingMethodException: Method not found: void Microsoft.Build.Utilities.ToolTask.set_UseCommandProcessor(bool)
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <4e0a1f1d78cf4c1ebd6f9a3dbcebf3bb>:0 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x00212] in <4e0a1f1d78cf4c1ebd6f9a3dbcebf3bb>:0 
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/src/FaissBalancer.csproj'.
/media/Datos/Symmetrik/DesarrolloSymmetrik/Dev/Microservice/faiss-balancer/src/FaissBalancer.csproj
/home/jose/.nuget/packages/grpc.tools/1.22.0-pre1/build/_protobuf/Google.Protobuf.Tools.targets(264,5): Error: The "ProtoCompile" task failed unexpectedly.
System.MissingMethodException: Method not found: void Microsoft.Build.Utilities.ToolTask.set_UseCommandProcessor(bool)
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <4e0a1f1d78cf4c1ebd6f9a3dbcebf3bb>:0 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x00212] in <4e0a1f1d78cf4c1ebd6f9a3dbcebf3bb>:0 
</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.37.1
**C# Extension**: 1.21.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/jose/dotnet/sdk/3.0.100-preview8-013656/

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  3.0.100-preview8-013656 [/home/jose/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/home/jose/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/home/jose/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.1|
|dotenv|mikestead|1.0.1|
|dotnet-test-explorer|formulahendry|0.7.1|
|gitconfig|sidneys1|2.0.1|
|gitflow|vector-of-bool|1.2.1|
|JavaScriptSnippets|xabikos|1.7.2|
|jinjahtml|samuelcolvin|0.10.5|
|markdown-all-in-one|yzhang|2.4.2|
|markdown-preview-enhanced|shd101wyy|0.4.3|
|material-icon-theme|PKief|3.9.0|
|night-owl|sdras|1.1.3|
|npm-intellisense|christian-kohler|1.3.0|
|pgformatter|bradymholt|1.7.0|
|prettier-vscode|esbenp|2.2.2|
|python|ms-python|2019.8.30787|
|rainbow-csv|mechatroner|1.3.1|
|swdc-vscode|softwaredotcom|1.1.26|
|vetur|octref|0.22.2|
|vscode-ant-design-vue-helper|ant-design-vue|1.0.6|
|vscode-coverage-gutters|ryanluker|2.4.0|
|vscode-django|batisteo|0.19.0|
|vscode-docker|ms-azuretools|0.7.0|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-jumpy|wmaurer|0.3.1|
|vscode-proto3|zxh404|0.3.0|
|vscode-status-bar-format-toggle|tombonnike|1.5.0|
|vue-vscode-extensionpack|sdras|0.2.0|
|vue-vscode-snippets|sdras|1.8.0|
|wordpress-snippet|tungvn|1.1.5|;

</details>

**Comment by akshita31** [comment] 2019-09-05 21:29
@nguerrera Do you have an idea what the `ProtoCompile` task is and why it might be failing here ?

**Comment by nguerrera** [comment] 2019-09-05 21:34
I don't know what it is yet, but it seems to be due to binding it to an older version of msbuild than what has this defined:

```
System.MissingMethodException: Method not found: void Microsoft.Build.Utilities.ToolTask.set_UseCommandProcessor(bool)
```

**Comment by nguerrera** [comment] 2019-09-05 21:35
Hmm, that property is pretty ancient.

**Comment by nguerrera** [comment] 2019-09-05 21:53
The task comes from here: https://github.com/grpc/grpc/blob/b7d69ad42533b88c70868dd61ed543c2c8a055da/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L16

**Comment by nguerrera** [comment] 2019-09-05 21:55
So, the net45 copy of Protobuf.MSBuild.dll references Microsoft.Build.Utilities.v4.0, and it appears that wherever that is coming from doesn't have `void Microsoft.Build.Utilities.ToolTask.set_UseCommandProcessor(bool)`

**Comment by nguerrera** [comment] 2019-09-05 22:06
Looks like `Microsoft.Build.Utilities.v4.0` comes from mono, and not from msbuild:

"C:\Users\nicholg\Downloads\omnisharp-osx\lib\mono\gac\Microsoft.Build.Utilities.v4.0\4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Utilities.v4.0.dll"

**Comment by nguerrera** [comment] 2019-09-05 22:07
https://github.com/mono/mono/blob/master/mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolTask.cs

**Comment by akshita31** [comment] 2019-09-05 22:11
@nguerrera Does that mean it used to exist in previous versions and is no more present, hence updating the mono version would not be helpful ?

**Comment by nguerrera** [comment] 2019-09-05 22:14
@akshita31 It may be the case the mono implementation of this dll never had this property. I don't know. But ideally, nothing would use this old .v4.0 assembly in mono and instead use the .Core version that comes with a recent msbuild.

**Comment by nguerrera** [comment] 2019-09-05 22:15
@juntaoluo my recommendation would be to use a MSBuild 15.0+ package reference for both net45 and non-net45 here:  https://github.com/grpc/grpc/blob/b7d69ad42533b88c70868dd61ed543c2c8a055da/src/csharp/Grpc.Tools/Grpc.Tools.csproj#L86-L91

**Comment by nguerrera** [comment] 2019-09-05 22:15
cc @Pilchie

**Comment by nguerrera** [comment] 2019-09-05 22:15
cc @rainersigwald

**Comment by akshita31** [comment] 2019-09-05 22:17
@nguerrera Thanks for the detailed analysis 💯

**Comment by rainersigwald** [comment] 2019-09-05 22:23
Strong agree on @nguerrera's analysis. Including @radical for Mono MSBuild.

**Comment by Pilchie** [comment] 2019-09-06 02:48
Also including @jamesnk too

**Comment by radical** [comment] 2019-09-06 05:00
Mono adds facade assemblies for `Microsoft.Build.{Tasks,Utilities}.v{4,12}.0`, which just typeforward to the newer assemblies. But Omnisharp doesn't seem to be copying them over - https://github.com/OmniSharp/omnisharp-roslyn/blob/master/mono-packaging/copy-msbuild.sh#L53-L58 . When I copy the assemblies over manually, the error goes away.

PR for a fix: https://github.com/OmniSharp/omnisharp-roslyn/pull/1595

**Comment by filipw** [comment] 2019-09-06 06:46
this wss discussed here https://github.com/grpc/grpc/pull/19589 but never merged

the fix from @radical looks good to me 👍

**Comment by akshita31** [comment] 2019-09-09 18:14
The issue will be fixed in the next release of the extension. Thanks @radical  for the prompt response 🥇

**Comment by qiudesong** [comment] 2019-09-23 03:44
I have the same problem.

VSCode version: 1.38.1
C# Extension: 1.21.3

**Comment by xolott** [comment] 2019-09-26 21:12
Happy to see a PR merged, but, what is the expected release date? Do you work with regular or irregular releases?

**Comment by yucaowang** [comment] 2019-10-16 02:16
Same issue found on MacOS, Any ETA of the release including the fix? Or any workaround could make my project goes on?
Thanks.

**Comment by ahmelsayed** [comment] 2019-10-22 20:37
@akshita31 the issue is still there with the 1.21.5 release which as far as I can tell has [OmniSharp 1.34.5](https://github.com/OmniSharp/omnisharp-vscode/commit/928897bc69ef5eb2745a7c55ba3e1184783b008f) which should have @radical changes, but I still get the same error

```
/home/ahmed/.nuget/packages/grpc.tools/2.23.0/build/_protobuf/Google.Protobuf.Tools.targets(264,5): Error: The "ProtoCompile" task failed unexpectedly.
System.MissingMethodException: Method not found: void Microsoft.Build.Utilities.ToolTask.set_UseCommandProcessor(bool)
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in <b695b16788dd418cbe8b4d98f7a92ff3>:0 
```

**Repro:** 

```bash
$ dotnet new grpc -o GrpcGreeter
$ cd GrpcGreeter
$ code .
```

```bash
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by nagytech** [comment] 2019-10-24 02:59
I've added some more analysis here: https://github.com/OmniSharp/omnisharp-roslyn/issues/1481#issuecomment-545717131

At the moment, the work around is to set `"omnisharp.useGlobalMono": "never",`.  

Looking at the other options for `omnisharp.useGlobalMono` I can see that `"auto"` applies a hard coded lower bound to the Mono version (currently 5.8.1).  I'm wondering if bumping that to `6.4.1` or allowing us to set it with a semver token would suffice until the next Mono comes around.

**Comment by filipw** [comment] 2019-10-28 09:13
this is a duplicate of https://github.com/OmniSharp/omnisharp-roslyn/issues/1481

**Comment by filipw** [comment] 2019-10-28 09:13
see https://github.com/OmniSharp/omnisharp-roslyn/issues/1481#issuecomment-546593870 for the "status update"

**Comment by vogon** [comment] 2019-11-27 21:22
just updated to vscode 1.40.2 + ms-vscode.csharp 1.21.8 on my laptop and checked in on this issue for the first time in a while, and the fix appears to have landed, but ymmv

**Closed** 2020-05-05 23:30 UTC
Labels: Resolved-Fixed, Triaged
