### ISSUE TITLE
Adding args to launch.json config causes debugger to fail to launch

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-vscode#426] opened 2016-06-11 21:13 UTC
User error? Either I don't understand what "args" is in launch.json or something isn't working as expected.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003041)

Product Information:
 Version:            1.0.0-preview2-003041
 Commit SHA-1 hash:  cc3d19463d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
VS Code version: 1.2.0
C# Extension version: 1.1.5

## Steps to reproduce
**launch.json**
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/worker/src/Worker/bin/Debug/netcoreapp1.0/Worker.dll",
            "args": [
                "--debug"
            ],
            "cwd": "${workspaceRoot}/worker/src/Worker/",
            "stopAtEntry": true,
            "externalConsole": false
        }
    ]
}
```

## Expected  behavior
Start the app with "--debug" passed in as an argument to `Program.Main(string[] args)`

## Actual behavior

```
No executable found matching command "dotnet-/Users/namc/dev/worker/src/Worker/bin/Debug/netcoreapp1.0/Worker.dll--debug"
The program '/Users/namc/dev/worker/src/Worker/bin/Debug/netcoreapp1.0/Worker.dll' has exited with code 0 (0x00000000).
```

**Comment by gregg-miskelly** [comment] 2016-06-12 05:54
This isn't user error - what you are doing I would expect to work.

**Comment by gregg-miskelly** [comment] 2016-06-14 16:58
The issue is that OpenDebugAD7 is concatting the arguments in correctly:

    LaunchOptions  ExeArguments='/Users/greggm/clinew/bin/Debug/netcoreapp1.0/clinew.dllfoo'

**Comment by gregg-miskelly** [comment] 2016-06-14 17:24
@caslan I think your fix is already in the package used in the master branch, but not in release. But I didn't confirm.

**Comment by gregg-miskelly** [comment] 2016-06-14 19:42
I confirmed that this is fixed by 9bc4d2f8871853f04f8190aa5951f524541dd9d1. The fix will ship with 1.1.6, which we expect to post very soon. Hopefully today.

**Closed by gregg-miskelly** 2016-06-14 19:42 UTC
Labels: Bug, Debugger

**Comment by gregg-miskelly** [comment] 2016-06-15 00:40
@natemcmaster this should now be fixed if you upgrade your version of the C# extension (F1, Extensions: Show Outdated Extensions, update C#)

**Comment by natemcmaster** [comment] 2016-06-15 16:06
Awesome. Looks good :)
