### ISSUE TITLE
Roslyn Clr Heap Allocation Analyzer

### ISSUE THREAD

**Issue by ssoher** [OmniSharp/omnisharp-vscode#3760] opened 2020-05-06 21:37 UTC
Are there any planned features that will analyze (preferably on command instead of in real time) and mark heap allocations like the below Visual Studio extension does?

https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer

**Comment by filipw** [comment] 2020-05-07 06:14
It's available as an analyzer and since OmniSharp supports analyzers, you can just install it into your project and use it

```
<PackageReference Include="ClrHeapAllocationAnalyzer" Version="3.0.0" />
```

<img width="1050" alt="Screen Shot 2020-05-07 at 08 13 28" src="https://user-images.githubusercontent.com/1710369/81260659-ba84f500-903a-11ea-85f8-3c76a2d8e6f4.png">

**Comment by ssoher** [comment] 2020-05-07 11:31
@filipw great to hear that. excuse my ignorance but how do I install it in my project?

**Comment by cartermp** [comment] 2020-05-12 23:39
Resolving as by design. Since this is an analyzer, once you can include it as a dependency on your project then it should work.

**Closed by cartermp** 2020-05-12 23:39 UTC
Labels: Resolved-By Design, Triaged
