### ISSUE TITLE
I can't use auto-complete

### ISSUE THREAD

**Issue by NucleonRabbit** [OmniSharp/omnisharp-vscode#4545] opened 2021-05-09 19:39 UTC
## Environment data
`dotnet --info` output:

Version:   5.0.202
 Commit:    db7cc87d51

运行时环境:
 OS Name:     fedora
 OS Version:  34
 OS Platform: Linux
 RID:         fedora.34-x64
 Base Path:   /usr/lib64/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

VS Code version:
C# Extension version:
v1.23.11
## OmniSharp log
Starting OmniSharp server at 2021/5/10上午3:11:54
    Target: /home/nucleon14/Project/SSMGWebsite/SSMGWebsite.sln

Razor dev mode active. Suppressing built-in OmniSharp Razor support.

OmniSharp server started.
    Path: /home/nucleon14/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.9-beta.62/run
    PID: 20745

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 34.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.10.0 - "/home/nucleon14/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.9-beta.62/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/nucleon14/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.9-beta.62/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.10.0 - "/home/nucleon14/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.9-beta.62/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/nucleon14/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.9-beta.62/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/nucleon14/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.9-beta.62/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/nucleon14/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.9-beta.62/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/nucleon14/Project/SSMGWebsite'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/nucleon14/Project/SSMGWebsite/SSMGWebsite.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/nucleon14/Project/SSMGWebsite/SSMGWebsite/SSMGWebsite.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/nucleon14/Project/SSMGWebsite'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/nucleon14/Project/SSMGWebsite' on host 15599.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/nucleon14/Project/SSMGWebsite/SSMGWebsite/SSMGWebsite.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "Microsoft.AspNetCore.Razor.Tasks.DiscoverDefaultScopedCssItems" task could not be loaded from the assembly /usr/lib64/dotnet/sdk/5.0.202/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/../../tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll. Invalid Image Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/nucleon14/Project/SSMGWebsite/SSMGWebsite/SSMGWebsite.csproj'.
/home/nucleon14/Project/SSMGWebsite/SSMGWebsite/SSMGWebsite.csproj
/usr/lib64/dotnet/sdk/5.0.202/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.ScopedCss.targets(118,3): Error: The "Microsoft.AspNetCore.Razor.Tasks.DiscoverDefaultScopedCssItems" task could not be loaded from the assembly /usr/lib64/dotnet/sdk/5.0.202/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/../../tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll. Invalid Image Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/nucleon14/Project/SSMGWebsite/SSMGWebsite/SSMGWebsite.csproj

## Steps to reproduce
Open an ASP.NET CORE project, Errors gets thrown from Vscode

## Expected  behavior
![Screenshot_20210510_033154](https://user-images.githubusercontent.com/59787326/117584588-5b235e80-b140-11eb-9272-fba1dacc9da4.png)
![Screenshot_20210510_033450](https://user-images.githubusercontent.com/59787326/117584647-bbb29b80-b140-11eb-8f4e-e03f3c28fa38.png)
can use auto-complete

## Actual behavior
can't use auto-complete

**Comment by jcmordan** [comment] 2021-05-17 23:15
Same issue:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     fedora
 OS Version:  34
 OS Platform: Linux
 RID:         fedora.34-x64
 Base Path:   /usr/lib64/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by JoeRobich** [comment] 2021-06-19 01:10
The issue here is that the source build version of the SDK is installed. There is a known issue that they do not include the Full Framework assemblies in the source build release of the SDK (see https://github.com/dotnet/source-build/issues/2006).

There are different packages you can install. For Arch users there is the `dotnet-sdk-bin` package. For Fedora or CentOS users, you can try this suggestion https://github.com/OmniSharp/omnisharp-vscode/issues/4360#issuecomment-779086868

**Comment by JoeRobich** [comment] 2021-06-19 01:11
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4360

**Closed by JoeRobich** 2021-06-19 01:11 UTC
Labels: Resolved-Duplicate
