### ISSUE TITLE
Omnisharp fails on OSX

### ISSUE THREAD

**Issue by kzaher** [OmniSharp/omnisharp-vscode#5445] opened 2022-11-09 08:55 UTC
## Issue Description ##
Omnisharp fails with

OmniSharp requires a complete install of Mono (including MSBuild) to provide language services when `omnisharp.useModernNet` is disabled in Settings. Please install the latest Mono and restart.

`omnisharp.useModernNet` is disabled in settings already.

## Steps to Reproduce ##
Just open project

## Expected Behavior ##
Omnisharp should work

## Actual Behavior ##
Omnisharp fails with 

OmniSharp requires a complete install of Mono (including MSBuild) to provide language services when `omnisharp.useModernNet` is disabled in Settings. Please install the latest Mono and restart.

### OmniSharp log ###
OmniSharp failed to start because of missing requirements.
OmniSharp failed to start because of missing requirements.
OmniSharp failed to start because of missing requirements.
OmniSharp failed to start because of missing requirements.

### C# log ###
empty

## Environment information ##

**VSCode version**: 1.73.0
**C# Extension**: 1.25.1

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.401/

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: arm64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-cpp-syntax|jeff-hykin|1.16.3|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.1|
|csharpier-vscode|csharpier|1.3.5|
|debugger-for-chrome|msjsdiag|4.13.0|
|isort|ms-python|2022.4.0|
|jupyter|ms-toolsai|2022.9.1202862440|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.12|
|python|ms-python|2022.18.1|
|remote-containers|ms-vscode-remote|0.262.3|
|remote-ssh|ms-vscode-remote|0.90.1|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|remote-wsl|ms-vscode-remote|0.72.0|
|textproto-grammer|thejustinwalsh|0.0.8|
|vetur|octref|0.36.1|
|vim|vscodevim|1.24.3|
|vscode-bazel|BazelBuild|0.6.0|
|vscode-docker|ms-azuretools|1.22.2|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-proto3|zxh404|0.5.5|
|vscode-pylance|ms-python|2022.11.10|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|
|vscode-solution-explorer|fernandoescolar|0.7.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.4|;

</details>

**Comment by kzaher** [comment] 2022-11-09 09:02
Confirmed this is a regression in 1.25.1, 1.25.0 works fine.

**Comment by filipw** [comment] 2022-11-09 09:03
This is a duplicate of #5443

**Comment by rohitvishwakarma1819** [comment] 2022-11-09 18:43
> Confirmed this is a regression in 1.25.1, 1.25.0 works fine.

@kzaher how to downgrade to 1.25.0 ?

**Comment by kzaher** [comment] 2022-11-09 19:26
Google itOn 9 Nov 2022, at 19:43, Rohit Vishwakarma ***@***.***> wrote:﻿

Confirmed this is a regression in 1.25.1, 1.25.0 works fine.

@kzaher how to downgrade to 1.25.0 ?

**Comment by j1mmie** [comment] 2022-11-09 19:31
Downgraded to 1.25.0

I've never had to downgrade a VSCode extension, so for anyone else who doesn't know:

![image](https://user-images.githubusercontent.com/4650220/200923643-ec6c5560-0043-4b25-b00b-bdabcf1adc1a.png)

And select 1.25.0

**Comment by dibarbet** [comment] 2022-11-09 21:29
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5443 .  Should be resolved in the next release (hopefully today).  Until then, the linked issue has workarounds.

**Closed by dibarbet** 2022-11-09 21:29 UTC
Labels: Resolved-Duplicate, Triaged

**Comment by StephenMcConnel** [comment] 2022-11-09 23:34
The same problem occurs in Linux Ubuntu 20.04

**Comment by josercc** [comment] 2023-05-09 08:02
macOS still exists in v1.25.7 version

**Comment by Jesseekoh** [comment] 2023-06-14 14:05
I downgraded to 1.25.2 and it seems to most recent one that works
