### ISSUE TITLE
[Feature Request] Inlay Hints

### ISSUE THREAD

**Issue by knom** [OmniSharp/omnisharp-vscode#4782] opened 2021-09-22 08:39 UTC
Given Inlay Hints are supported in VSCode for JS / TS..
https://www.youtube.com/watch?v=wFsiSJcpv60

Any way to bring this to C#?

**Comment by JoeRobich** [comment] 2021-09-22 17:43
Roslyn provides an InlineHintsService which OmniSharp can access through the [OmniSharpInlineHintsService](https://github.com/dotnet/roslyn/blob/main/src/Tools/ExternalAccess/OmniSharp/InlineHints/OmniSharpInlineHintsService.cs) class. The OmniSharp-Roslyn repo would need to be updated with a new InlineHints endpoint that is powered by the hint service. We could then consume the endpoint in OmniSharp-VSCode and [add inline hints](https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/inlayHints.ts) in a similar manner as the typescript extension.

**Comment by 333fred** [comment] 2021-09-23 23:49
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2823. The reason I haven't done this yet is that the vscode API is still in preview.

**Closed by 333fred** 2021-09-23 23:49 UTC
Labels: Question, Triaged
