### ISSUE TITLE
Debugger: Is it expected pop up an error dialog after double clicking F5?

### ISSUE THREAD

**Issue by Serena01** [OmniSharp/omnisharp-vscode#495] opened 2016-06-29 10:06 UTC
![error](https://cloud.githubusercontent.com/assets/20184641/16448380/c1f643ec-3e23-11e6-8883-c39aa7e28ca9.PNG)
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
 C# Extension version:1.1.7

## Steps to reproduce
1.Download and launch the sample project from https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip 
 2.Select ".NET Core Launch Web" and configure the location of musicstore.dll for "program which contains the space at the end as following: "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/musicstore.dll ",
3.Doulble click "F5"

## Expected  behavior
VS code should start debugging successfully.

## Actual behavior
There is a error with "Build erros have been detected during preLauchTask 'build'".

![error](https://cloud.githubusercontent.com/assets/20184641/16448392/cf390a80-3e23-11e6-9b0b-cac7a92db210.PNG)

**Comment by caslan** [comment] 2016-06-30 00:08
This should be a VS Code issue, but I can't remember if there was anything tracking this. @chuckries, can you look at this further?

**Comment by chuckries** [comment] 2016-06-30 22:42
@caslan The issue here is the default launch.json template configures the preLaunchTask to 'build' and in this case @Serena01 does not have a tasks.json. The launch.json here is the default template, NOT the asset created by omnsiharp, so there is not an autogen'd tasks.json. I know in the past we have talked about removing 'build' from the default preLaunchTask section, but had decided to leave it in. 

People will hit this if they do not let omnisharp create the build/launch assets for them. If you are new to VS Code, this seems very cryptic as you are likely unfamiliar with build tasks, and the error message does not exactly point you in the right direction. We cannot change the error message in this case as it is coming from VS Code not us.

We can either resolve this as by design, won't fix, or we can remove build from the default preLaunchTask. Thoughts?

**Comment by gregg-miskelly** [comment] 2016-07-01 17:44
@chuckries @Serena01 do you have a tasks.json file?

If you have no tasks.json, you are supposed to get this, which is what happens when I try:

![no-task-runner-configured](https://cloud.githubusercontent.com/assets/11078489/16529488/11b8591a-3f78-11e6-9470-87b8330fc552.JPG)

If you aren't seeing this, you are running into a VS Code bug.

The 'build errors detected' message is supposed to show up only if you have a 'build' task and it produced errors. Note that at earlier we were seeing problems with VS Code occasionally thinking that the 'build' task produced errors even when it didn't.

**Comment by caslan** [comment] 2016-08-10 19:58
Closing this issue as it has been stale for a while. @Serena01 please reopen if you are still seeing this issue.

**Closed by caslan** 2016-08-10 19:58 UTC
Labels: Debugger
