### ISSUE TITLE
ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#362] opened 2016-05-21 10:15 UTC
_From @ealsur on May 20, 2016 20:11_

- VSCode Version:1.1.1
- OS Version: Windows 10

Using C# Extension 1.0.11 and ASPNET Core RC2 (dotnet cli installed) using net461, I am unable to get Omnisharp to work.

Whenever I open a folder with a project with that version of ASPNET Core I get this error on the Omnisharp Log:

`[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] myproject/.NETFramework,Version=v4.6.1[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

_Copied from original issue: Microsoft/vscode#6592_

**Comment by itn3000** [comment] 2016-05-23 03:43
It was occured in my environment(win8.1x64+vscode1.1.1+omnisharp-vscode1.0.8).
I found the some node_modules/** directory created by npm is too deep and exceed MAX_PATH(260).
It's avoidable by adding the `node_modules/**/*.*` entry in "exclude" setting in project.json

**Comment by jtillman** [comment] 2016-05-23 04:55
I've had this issue since the release of the RC2 update. I also found it was due to the node_modules folder being so far deep. Adding it to the exclude of project.json worked for me as well.

**Comment by ealsur** [comment] 2016-05-24 02:08
I can confirm that adding an *exclude* attribute to **project.json** fixes the issue.

![image](https://cloud.githubusercontent.com/assets/1633401/15490027/1736e970-213b-11e6-9ef2-bc4b5954b183.png)

The problem is that, according to the [official annoucement](https://github.com/aspnet/Announcements/issues/175), the *exclude*  attribute is now deprecated on RC2 (it should be inside the *buildOptions > compile* tree), maybe it's something that is still left to migrate on Omnisharp's logic.

**Comment by DustinCampbell** [comment] 2016-05-24 18:43
This looks like the same issue as https://github.com/OmniSharp/omnisharp-vscode/issues/279. So long as you're using the latest released version of the C# extension, it *should* be using the latest schema for project.json.

cc @troydai

**Comment by ealsur** [comment] 2016-05-24 19:14
@DustinCampbell I'm using C# extension version 1.0.11, unless there's a new one that is not [published on the Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp). I'm attaching a screen capture of a project load without the "exclude" setting that shows the error on the Omnisharp log and what happens when you add the setting.
![animation](https://cloud.githubusercontent.com/assets/1633401/15516716/76517fe4-21ca-11e6-8c27-34076d1fd552.gif)

**Comment by ngraef** [comment] 2016-06-15 00:39
Excluding `node_modules` doesn't quite fix it for me -- it removes all but one of the errors. Even `"exclude": "**"` produces the one error. Is there a more detailed log where I can see what path it doesn't like? I checked the project directory in PowerShell with `cmd /c dir /a /s /b | ?{ $_.FullNameLength -gt 247 }` and the only results/errors were the node modules, so I'm stumped.

- Windows 10.0.10586 x64
- VS Code 1.2.1
- C# Extension 1.1.5
- .NET Core 1.0.0-rc2-002416

**Comment by DustinCampbell** [comment] 2016-07-21 00:26
This should be much better with the [1.3.0 release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0). In that release, we'll be using the CoreCLR-based OmniSharp for .NET Core projects, which supports long file names. The problem is that the .NET Desktop version of OmniSharp (which we currently use on Windows) can crash with MAX_PATH issues.

**Comment by DustinCampbell** [comment] 2016-09-22 12:45
I'm going to go ahead and close this issue. Let me know if you see this problem anymore.

**Closed by DustinCampbell** 2016-09-22 12:45 UTC
Labels: Bug
