### ISSUE TITLE
Debugger: Attach doesn't work correctly with app in a tight loop on mac

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1030] opened 2016-12-12 06:14 UTC
## Environment data
`dotnet --info` output:
VS Code version: 1.7.2
C# Extension version: v.1.6.0-beat3
.NET Core version: 1.0.0-preview2 -1 - 003177
OS: Mac10.11

## Steps to reproduce
1. Open VSCode
2. Install C# Extension v.1.6.0-beta3
3. Delete all files in C:\Users<alias>.vscode\extensions\ms-vscode.csharp-.debugger except “install.complete”
4. Unzip the contents of the matching zip file into the C:\Users<alias>.vscode\extensions\ms-vscode.csharp-.debugger
5. Download hwapp folder in attachments directly and open with VSCode
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/645206/hwapp.zip)

6. Launch the project in Command Prompt using the command "dotnet run"
7. Select the debug type “.Net core Attach”
![screen shot 2016-12-12 at 1 46 34 pm](https://cloud.githubusercontent.com/assets/20922638/21089529/c4605014-c073-11e6-9e51-072f61023ef2.png) 
8. Set a BP at line of 13
9. Press F5 to start debugging
10. Select process ID on UI
![screen shot 2016-12-12 at 1 47 15 pm](https://cloud.githubusercontent.com/assets/20922638/21089549/ed109776-c073-11e6-99b7-47feb380304f.png)

## Expected  behavior
This bp should be hit

## Actual behavior
The bp can't be hit

**Comment by gregg-miskelly** [comment] 2016-12-12 15:34
This may be the same issue that the CoreCLR generally has with breaking into programs with tight loops. Though there is enough in the loop that I would have thought it would work...

**Comment by gregg-miskelly** [comment] 2020-01-22 20:37
This is tracked with #3520

**Comment by cartermp** [comment] 2020-03-11 00:13
closing as duplicate of #3520

**Closed by cartermp** 2020-03-11 00:13 UTC
Labels: Debugger, Debugger-Poachable, Resolved-Duplicate
