### ISSUE TITLE
Lack of support for Linux ARM32 (Raspberry Pi)

### ISSUE THREAD

**Issue by SuperJMN** [OmniSharp/omnisharp-vscode#3181] opened 2019-07-17 11:52 UTC
* No IntelliSense
* No quick actions
* No debugger
* Lack of integration (F5, Control + F5...)

I'm using VS Code ("Code-OSS") by headmelted and it just acts like a plain simple text editor. The only feature that works is syntax coloring.

Please, provide more support to this platform. The combo Raspbian + VS Code is 100% winner.

**Comment by gregg-miskelly** [comment] 2021-02-18 19:44
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2771

**Closed by gregg-miskelly** 2021-02-18 19:44 UTC
Labels: Feature Request
