### ISSUE TITLE
vscode not recognizing .csproj file

### ISSUE THREAD

**Issue by AAndharia** [OmniSharp/omnisharp-vscode#1250] opened 2017-02-17 10:15 UTC
- VSCode Version: 1.9.1
- OS Version: win

Steps to Reproduce:

1. have installed web api start project using this command 
yo aspnet webapi MyFirstASPNetCoreWebAPI

I've followed these links to create web api project template
https://docs.microsoft.com/en-us/aspnet/core/client-side/yeoman?#building-projects-with-yeoman
https://github.com/OmniSharp/generator-aspnet

2. open the project in vscode

3. It shows there are unresolved dependancies from .csproj. Please execute the restore command to continue. clicking restore shows this error in "Output"

error: Invalid input 'd:\Projects\vs-code-web\WebAPI1\WebAPI1.csproj'. The file type was not recognized.
Done: 1.

**Comment by DustinCampbell** [comment] 2017-02-17 15:04
Hi! What version of C# for VS Code do you have installed?

**Comment by AAndharia** [comment] 2017-02-17 17:35
I have not installed any c# version specifically, i just installed omnisharp plugin.

**Comment by DustinCampbell** [comment] 2017-02-17 18:25
I'm not sure what you mean by the "omnisharp plugin". The extension produced by this repo is "C# for Visual Studio Code". You should have this installed:

![image](https://cloud.githubusercontent.com/assets/116161/23077909/4a6d0dda-f4fb-11e6-9a52-b8a4b420a98f.png)

In addition, could run `dotnet --info` at a command prompt and copy-and-paste the output here.

**Comment by KarimGeiger** [comment] 2017-02-24 16:00
Hi,

I did the same and got the same error message, although I'm using Linux.

Running the --info command provided:
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     elementary
 OS Version:  0.4
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

**Comment by DustinCampbell** [comment] 2017-02-24 16:15
Note that the .NET Core SDK that you have installed only supports older project.json-based projects.

**Comment by DustinCampbell** [comment] 2017-02-27 18:16
@AAndharia: Without more information here, I'm unable to help. Could you take a moment to reply to my most recent response to you?

**Comment by AAndharia** [comment] 2017-02-28 12:51
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

**Comment by vonbloom** [comment] 2017-02-28 18:17
Hi,

I'm stuck with a similar issue.

I have a unity project, generated using [Unity VSCode plugin](https://github.com/dotBunny/VSCode).

My .NET core specs are:

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

When I open the project, omnisharp complains that can't process .csproj file:

```
...
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file '/path/to/project/Assembly-CSharp.csproj'.
...
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file '/path/to/project/Assembly-CSharp-Editor-firstpass.csproj'.
...
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/path/to/project'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.
```

**Comment by DustinCampbell** [comment] 2017-03-01 01:31
@vonbloom: That's likely a different issue since it's a Unity project. Could you file a separate issue?

**Comment by DustinCampbell** [comment] 2017-03-01 01:33
@AAndharia: The problem you're experiencing is by design. The problem is that you have an older .NET Core SDK which only supports project.json .NET Core projects. However, it sounds like the 'yo aspnet' templates have been updated to create the csproj-based .NET Core projects. So, `dotnet restore` is failing because it doesn't understand your project file. I recommend installing a newer version of the .NET Core SDK from [here](https://github.com/dotnet/cli/releases) which should work with csproj-based .NET Code projects.

**Comment by DustinCampbell** [comment] 2017-03-01 01:35
@KarimGeiger: I suspect my comment above describes the problem you're experiencing as well.

**Comment by KarimGeiger** [comment] 2017-03-01 05:52
Yes, thank you very much. I think you can close this issue (at least from my point of view).

**Comment by DustinCampbell** [comment] 2017-03-01 14:42
OK. I'm going to go ahead and close this issue.

@AAndharia, please let me know if this doesn't solve the issue you're experiencing.
@vonbloom, please file a separate issue. As you're targeting a Unity project, there's almost certainly a different underlying problem.

Thanks all!

**Closed by DustinCampbell** 2017-03-01 14:42 UTC
Labels: Needs More Info

**Comment by FourOnes** [comment] 2017-03-06 08:52
@DustinCampbell I had as same as question, now resolved, thanks.

**Comment by iluqmansharif** [comment] 2017-11-30 09:28
I'm having this issue on Visual Studio Code while running a Unity project.

> Failed to load project file 'f:\Unity Projects\Pehli Paheli\Assembly-CSharp.csproj'.
> f:\Unity Projects\Pehli Paheli\Assembly-CSharp.csproj
> 
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Detecting CSX files in 'f:\Unity Projects\Pehli Paheli'.
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Could not find any CSX files

**Comment by iluqmansharif** [comment] 2017-11-30 10:24
@DustinCampbell Any help?

**Comment by DustinCampbell** [comment] 2017-12-01 16:54
@iluqmansharif : I recommend filing a separate issue rather than reporting a new problem on an issue that's been closed for nine months. Given the amount of time, the problem you're seeing is almost certainly different.
