### ISSUE TITLE
Can we install both legacy and latest version of omnisharp-vscode?

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-vscode#410] opened 2016-06-08 04:32 UTC
I'm using unity on OSX and need to use legacy omnisharp-vscode

I know that I need to uninstall the latest version before install the legacy version

But what would happen if we install the latest version after that? Is it just disable the legacy version again?

ps. Also are there any roadmap about fixing this problem?

**Comment by DustinCampbell** [comment] 2016-06-08 13:34
Unfortunately, I don't believe you can do this. I expect that both extensions running on .cs files will cause significant problems.

Getting .csproj projects working again on OSX is our highest priority right now. We've just merged a change in the OmniSharp server that should get us much closer [here](https://github.com/OmniSharp/omnisharp-roslyn/pull/581). I hope to have a new version of the C# extension available soon using a version of OmniSharp with this change. Would you be willing to try it out?

**Comment by Thaina** [comment] 2016-06-09 03:17
@DustinCampbell So... what I need to do? Just install latest version of omnisharp roslyn and vscode plugin will be work just that?

**Comment by DustinCampbell** [comment] 2016-06-09 13:55
Not yet. I'll ping back on this post when we've got a build for you to try.

**Comment by elvirb** [comment] 2016-06-09 16:32
@DustinCampbell, I'm willing to test it as well if possible.

**Comment by DustinCampbell** [comment] 2016-06-24 18:37
@Thaina, @elvirb: I've added a new release [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.1.7) that adds support for MSBuild projects (i.e. .csproj) on OS X and Linux. This should bring back Unity support. I've tried it with the Unity sample project and a handful of other Unity projects. Could you try it on your projects and see if it works? Be sure to uninstall the Legacy C# Support extension before you install the new v1.1.7 release.

**Comment by elvirb** [comment] 2016-06-24 18:43
@DustinCampbell : Tried it out but it doesn't seem to work. The logs show this error:

```
[ERROR:OmniSharp.Startup] The project system 'MSBuildProjectSystem' threw exception during initialization.
The type initializer for 'Crypto' threw an exception.
   at Interop.Crypto.EvpMd5()
   at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
   at System.Security.Cryptography.MD5.Implementation..ctor()
   at OmniSharp.MSBuild.MSBuildProjectSystem.UnityTypeGuid(String projectName) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 187
   at OmniSharp.MSBuild.MSBuildProjectSystem.Initalize(IConfiguration configuration) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 68
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.Host/Startup.cs:line 183
```

**Comment by DustinCampbell** [comment] 2016-06-24 18:45
@elvirb: Try this first from the Terminal window:

brew install openssl
brew link --force openssl

**Comment by elvirb** [comment] 2016-06-24 19:11
@DustinCampbell : That fixed it!

**Comment by DustinCampbell** [comment] 2016-06-24 19:14
Awesome! IntelliSense and Find All References are working for you again with the latest C# Extension?

**Comment by mdouglass** [comment] 2016-06-24 19:47
After the same link of openssl it's starting up for me.  However, I'm getting a lot of warnings/errors generated for my Unity project that seem to be caused by it not recognizing Unity's particular version of .NET. 

In the OmniSharp logs, I see:
```
[WARNING:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

In terms of errors/warnings, here are a sampling (all of these compile fine in Unity and were not giving warnings/errors with the Legacy extension):
```
using System.Linq;
The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?) [Assembly-CSharp-Editor]
```

```
System.Diagnostics.Process.Start("https://jenkins.example.com");
The type or namespace name 'Process' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?) [Assembly-CSharp-Editor]
```

```
return EditorBuildSettings.scenes.Where(s => s.enabled).Select(s => s.path).ToArray();
'EditorBuildSettingsScene[]' does not contain a definition for 'Where' and no extension method 'Where' accepting a first argument of type 'EditorBuildSettingsScene[]' could be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp-Editor]
```

**Comment by DustinCampbell** [comment] 2016-06-24 19:53
Great -- thanks @mdouglass. I'll take a look at this.

**Comment by elvirb** [comment] 2016-06-24 23:35
@DustinCampbell , somewhat working.

After leaving VSCode open for a while, I will start getting this error:

```
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 7ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
```

Also, I get this while loading a project now:

```
[WARNING:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

**Comment by DustinCampbell** [comment] 2016-06-25 00:04
Thanks for trying it out. It's progress, but we've still got some work to do. For now, continue using the Legacy C# Support extension, and I'll continue working on this.

**Comment by DustinCampbell** [comment] 2016-07-18 22:29
Take Two! I've just released [v.1.3.0-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta1) which brings support for two OmniSharp servers: a .NET Core one for project.json projects, and a Mono/Desktop version for .csproj/.sln projects. Please try this out and let me know if it fixes Unity development for you.

**Comment by mdouglass** [comment] 2016-07-19 16:53
On OS X, it's installing, files open with correct warnings/errors and I get reference counts on class members very quickly.  But almost as soon as I start to type in a new file, Code goes non-responsive and I see the Electron Helper process eating about 100% cpu and a mono-sgen32 process eating another 3-400% cpu.  This is on a medium-size Unity project (about 1k .cs files). Is there a way I can help get you profiling information (or other useful info) to debug this? Unfortunately, it's a commercial project so I can't share it.

**Comment by DustinCampbell** [comment] 2016-07-19 16:56
Well, that's a start at least. :smile:

Are you comfortable posting the OmniSharp Log?

**Comment by mdouglass** [comment] 2016-07-19 17:40
Interesting, took longer to get the long pauses this time it wasn't immediately on edit.  But finally saw a couple good 15s ones and grabbed the log. Doesn't seem to be much interesting in it, but hopefully it'll help.

[OmniSharp.txt](https://github.com/OmniSharp/omnisharp-vscode/files/372064/OmniSharp.txt)

**Comment by mdouglass** [comment] 2016-07-19 17:43
The pauses seem to be more frequent if I have the errors/warnings pane open.  Which I've also now noticed is showing a lot of duplicates of the same warnings.
<img width="354" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5410142/16960278/988014d2-4d9d-11e6-9d4e-175bf9682d8f.png">

**Comment by DustinCampbell** [comment] 2016-07-19 17:47
Thanks @mdouglass, I've got another report of that issue and I'll be looking at it shortly. The _good_ news (I think) is that the 1.3.0-beta1 has restored Unity support for you, correct? I'll touch base again here once I've got this bug addressed.

**Comment by mdouglass** [comment] 2016-07-19 18:48
Yep, other than the random pauses and the duplicated warnings everything seems to be working great.  Much better having working unity support :)

**Comment by DustinCampbell** [comment] 2016-07-20 17:46
@mdouglass: I've put up a new release, [v1.3.0-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta2), which should address the duplicate warnings. Could you give it a spin?

**Comment by mdouglass** [comment] 2016-07-20 20:14
The duplicate warnings are indeed gone, thanks! Also, really helpful that the 'unnecessary usings' has been moved down to info level from warning (not sure when that happened, but I just noticed it).

**Comment by DustinCampbell** [comment] 2016-07-20 20:22
That happened in this release too. Glad to hear it working for you!

**Comment by DustinCampbell** [comment] 2016-07-21 00:07
We'll be pushing this release to the marketplace soon.

**Closed by DustinCampbell** 2016-07-21 00:07 UTC
Labels: Question, Resolved-Fixed, Unity
