### ISSUE TITLE
Search and Go To Definition with multi folder workspace dont work

### ISSUE THREAD

**Issue by prime31** [OmniSharp/omnisharp-vscode#2853] opened 2019-02-14 04:04 UTC
Issue Type: <b>Bug</b>

This is a bit tricky to describe, but I'll do my best. I do not know if this is a bug or a feature request either.

I am working with a C# project that references a few other C# projects. The folder structure is like this, where MainProj references both SomeProj and AnotherProj:

[SomeProj]
[AnotherProj]
[MainProj]

This creates two different scenarios for use with two different results:
1. Open the MainProj folder directly
- Go to Definition WORKS as expected here in C# files
- Cmd + P and search for a file in one of the referenced projects does NOT work
- code complete DOES work

2. Open a workspace with each project folder in the workspace fil
- Go to Definition does NOT work anymore in C# files
- Cmd + P and search for a file in one of the referenced folders DOES work
- code complete does NOT work

So, Go to Definition, code completions and file search act consistently in the two different scenarios. The expected result would be for Go to Definition and file search to work in both scenarios.

Extension version: 1.17.1
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rchande** [comment] 2019-02-19 16:14
I think this is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/1889

**Closed by rchande** 2019-02-19 16:14 UTC
