### ISSUE TITLE
Error processing 'variables' request. Unknown Error: 0x8000211d

### ISSUE THREAD

**Issue by rspaulino** [OmniSharp/omnisharp-vscode#3926] opened 2020-07-23 20:58 UTC
## Issue Description ##
When I set a breakpoint and try to watch the value of a variable I get the following message
`Error processing 'variables' request. Unknown Error: 0x8000211d`

## Steps to Reproduce ##
`dotnet new web --no-https -n api `
`dotnet new sln `
`dotnet sln add api `

``` c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton(new JsonSerializerOptions()
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            PropertyNameCaseInsensitive = true,
        });
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env, JsonSerializerOptions serializerOptions)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseRouting();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapGet("/", async context =>
            {
                await context.Response.WriteAsync("Hello World!");
            });

            endpoints.MapPost("deposit", async context =>
            {
                var transaction = await context.Request.ReadFromJsonAsync<Transaction>();
                await context.Response.WriteAsync($"Hello World! {transaction.Id} {transaction.Amount} {transaction.Comment}");
            });
        });
    }
}
```

`dotnet run --project api  `

Set Breakpoint to see the value of **transaction**

`curl -X POST http://localhost:5000/deposit -H "Content-Type: application/json" -d '{"Id":102,"Amount":200,"Comment":"rent"}'`

## Expected Behavior ##
Expected to see an object with this values: '{"Id":102,"Amount":200,"Comment":"rent"}'`
## Actual Behavior ##
The variable show this value: `Error processing 'variables' request. Unknown Error: 0x8000211d`

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.47.2
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.10.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20366.6
 Commit:    0684df3a5b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.7.20366.6/

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1

.NET SDKs installed:
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]
  3.1.302 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.7.20366.6 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.11|
|csharp|ms-dotnettools|1.22.1|
|file-downloader|mindaro-dev|1.0.0|
|github-vscode-theme|GitHub|1.1.3|
|gitlens|eamodio|10.2.2|
|mindaro|mindaro|0.1.120200723|
|mssql|ms-mssql|1.9.0|
|python|ms-python|2020.7.94776|
|remote-containers|ms-vscode-remote|0.128.0|
|sonarlint-vscode|SonarSource|1.16.0|
|vscode-dapr|ms-azuretools|0.2.1|
|vscode-docker|ms-azuretools|1.4.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.2.1|
|vscode-postgresql|ms-ossdata|0.3.0|
|vscode-sanddance|msrvida|3.0.0|
|vscode-solution-explorer|fernandoescolar|0.3.10|
|vscode-sqlite|alexcvzz|0.8.2|
|vscode-yaml|redhat|0.9.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.9|
|vsliveshare|ms-vsliveshare|1.0.2478|
|vsliveshare-audio|ms-vsliveshare|0.1.85|;

</details>

**Comment by jmarolf** [comment] 2020-09-01 23:38
@gregg-miskelly do you have any insights in to what could be happening here?

**Comment by gregg-miskelly** [comment] 2020-09-02 00:33
@rspaulino Are you still seeing this problem? What version of .NET Core is your app running on?

**Comment by rspaulino** [comment] 2020-09-02 01:01
@gregg-miskelly I just tested again and still happening.

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.8.20417.9/

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9
```
<img width="1680" alt="Screen Shot 2020-09-01 at 8 58 15 PM" src="https://user-images.githubusercontent.com/378671/91920143-2c421800-ec96-11ea-80e7-175e978a9f4a.png">

Here is the project hope this can help:
[ntmp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/5159458/ntmp.zip)

**Comment by gregg-miskelly** [comment] 2020-09-02 18:17
Thanks. I can reproduce the problem. I will take a look at what is going on.

**Comment by gregg-miskelly** [comment] 2020-09-02 18:24
This is a bug with our handling of `decimal` types. The issue is already fixed internally, but we haven't pushed it to the extension yet. We were about to insert a new build that has the fix.

**Comment by rspaulino** [comment] 2020-09-02 18:41
@gregg-miskelly great!, thanks.

**Comment by WennderSantos** [comment] 2020-09-11 13:22
I am facing the same error. I tried to remove decimal properties just to test what @gregg-miskelly said about the problem and worked.

**Comment by mikes-gh** [comment] 2020-10-06 11:58
@gregg-miskelly is there any timeline on the next build with this fix please

**Comment by mikes-gh** [comment] 2020-10-06 12:15
@gregg-miskelly I used 1.23.3beta 3 and still had this issue

**Comment by gregg-miskelly** [comment] 2020-10-06 16:03
Hopefully today, https://github.com/OmniSharp/omnisharp-vscode/pull/4091 will fix this.

**Comment by gregg-miskelly** [comment] 2020-10-06 23:39
Fixed by https://github.com/OmniSharp/omnisharp-vscode/pull/4091

**Closed by gregg-miskelly** 2020-10-06 23:39 UTC
Labels: Debugger, Resolved-Fixed

**Comment by eestein** [comment] 2020-11-10 14:55
The same error happens on VS for mac, are you guys related to that one as well? Thanks.

**Comment by gregg-miskelly** [comment] 2020-11-10 17:20
@eestein Thanks. We will work with the VS for Mac team to get the fix deployed there too.

**Comment by darkguy2008** [comment] 2020-11-18 09:11
Same happening on VSCode for Windows. App is in .NET 5, how do I get the exception for you guys?

**Comment by mikes-gh** [comment] 2020-11-18 13:56
@darkguy2008 are you losing the latest vscode and omnisharp.  This particular issue was fixed for me on windows and mac.

**Comment by gregg-miskelly** [comment] 2020-11-18 16:58
@darkguy2008 If you are still seeing this using the current C# extension (1.23.6) please open a new issue and include a [debugger log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging). Information about the types of all the variables you have in the current frame would also be useful.
