### ISSUE TITLE
Debugger: Breakpoints cannot be set when the target app is in a tight loop

### ISSUE THREAD

**Issue by v-zhanme** [OmniSharp/omnisharp-vscode#901] opened 2016-11-09 11:02 UTC
## Environment data
`dotnet --info` output:
 VS Code version: 1.7.1
 C# Extension version: v.1.5.0-beta7
 .NET Core version: 1.0.0-SDK Preview4
C# Extension version:

## Steps to reproduce
Launch the project in Command Prompt(cmd window) using the Command 'dotnet run'.
2.Open the attachment project with VSCode.
[myapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/580567/myapp.zip)

3.change the debugger status is .NET Core Launch(console)
4.Press F5 to start debugging
5.set a BP at line 17

## Expected  behavior
The cursor will hit line 17

## Actual behavior
Can not hit BP at line 17
![screen shot 2016-11-09 at 6 56 56 pm](https://cloud.githubusercontent.com/assets/20921752/20136315/0bd6f7f6-a6af-11e6-8f94-c1261fc69845.png)

**Comment by gregg-miskelly** [comment] 2016-11-09 15:15
@v-zhanme Your code has an infinite loop, so line 17 will never execute. Is there something I am missing?

**Comment by v-zhanme** [comment] 2016-11-10 01:15
I'm sorry for typo, The BP should be on line 9

**Comment by v-zhanme** [comment] 2016-11-10 01:18
Hi,

I'm so sorry for typo, The BP should be on line 9.

Thanks,
Dianne

**Comment by gregg-miskelly** [comment] 2016-11-10 01:20
@v-zhanme Thanks. What OS were you on?

**Comment by v-zhanme** [comment] 2016-11-10 01:23
Hi,

This issue repro on Mac and Fedora. And not repro on windows OS.

Thanks,
Dianne

**Comment by v-zhanme** [comment] 2016-11-10 02:55
This issue repro on Mac and Fedora. And not repro on windows OS.
I send e-mail to you about this question at last an hour.

**Comment by gregg-miskelly** [comment] 2016-11-11 22:15
This issue only repos if the app is in a tight loop. @Mikem8361 would it make sense to have a bug in the CoreCLR repo about breaking into apps on Unix when the app is in a tight loop? Or is that just a really hard problem and I should resolve this as 'by design'.

**Comment by mikem8361** [comment] 2016-11-11 23:32
It is similar to https://github.com/dotnet/coreclr/issues/4623 which is about aborting funcevals that are caught in a tight loop.  The reason and the solution for both problems would be the same.  This is a fairly large work item.

**Comment by gregg-miskelly** [comment] 2016-11-12 01:01
Resolving this as external.

**Closed by gregg-miskelly** 2016-11-12 01:01 UTC
Labels: Debugger, Resolved-External
