### ISSUE TITLE
Debugging doesn't work, error: Error processing launch options at field: program.

### ISSUE THREAD

**Issue by vchirikov** [OmniSharp/omnisharp-vscode#3901] opened 2020-07-10 11:38 UTC
## Issue Description ##

Tests debugging doesn't work.

## Steps to Reproduce ##
Repro repository:
https://github.com/vchirikov/omnisharp_vscode_repro

Click on `Debug test` codelens link on `UnitTest1.Test1`

## Expected Behavior ##
Debugging works

## Actual Behavior ##
I got 
![image](https://user-images.githubusercontent.com/40987940/87150142-34935d80-c2ba-11ea-8ef0-1a3227bba36c.png)

Debugging doesn't work

### OmniSharp log ###
<details>Starting OmniSharp server at 10.07.2020, 14:28:26
    Target: c:\code\vchirikov\omnisharp-vscode-repro

OmniSharp server started.
    Path: c:\Users\verysimplenick\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\OmniSharp.exe
    PID: 4000

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.7.30218.91 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "c:\Users\verysimplenick\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.7.30218.91 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\code\vchirikov\omnisharp-vscode-repro'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\code\vchirikov\omnisharp-vscode-repro'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\code\vchirikov\omnisharp-vscode-repro\omnisharp-vscode-repro.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\code\vchirikov\omnisharp-vscode-repro'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\code\vchirikov\omnisharp-vscode-repro\omnisharp-vscode-repro.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\code\vchirikov\omnisharp-vscode-repro' on host 19368.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\code\vchirikov\omnisharp-vscode-repro\omnisharp-vscode-repro.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\code\vchirikov\omnisharp-vscode-repro\omnisharp-vscode-repro.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: omnisharp-vscode-repro
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 4.
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"TestSession.Connected","Payload":null}
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"ProtocolVersion","Payload":1}
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session started.
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session ended.</details>

### C# log ###
<details>-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"logging":{"engineLogging":false},"type":"coreclr","name":".NET Test Launch","request":"launch","debuggerEventsPipeName":"\\\\.\\pipe\\Microsoft.VSCode.CSharpExt.TestDebugEvents-19368","program":null,"args":null,"cwd":"C:\\code\\vchirikov\\omnisharp-vscode-repro","internalConsoleOptions":"openOnSessionStart","__sessionId":"29b9572b-dc2b-4f38-88a6-3b05cf5b4de0"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/CommandFailed","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.19041","VS.Diagnostics.Debugger.vsdbg.Command":"Launch","VS.Diagnostics.Debugger.vsdbg.ErrorCode":1006,"VS.Diagnostics.Debugger.vsdbg.AdditionalData":"program","VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}
<- (R) {"seq":4,"type":"response","request_seq":2,"success":false,"command":"launch","message":"Error processing launch options at field: program"}</details>

## Environment information ##

**VSCode version**: 1.46.1
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-fork.vchirikov [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aspnet-helper|schneiderpat|0.6.4|
|auto-close-tag|formulahendry|0.5.8|
|auto-rename-tag|formulahendry|0.1.4|
|blazor-snippet-pack|adrianwilczynski|2.6.1|
|blazorsnippets|ScottSauber|1.3.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|classynaming|reflectiondm|1.2.0|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.9.0|
|code-spell-checker-russian|streetsidesoftware|0.2.4|
|csharp|ms-dotnettools|1.22.1|
|csharp-grammar-extended|dannymcgee|1.1.1|
|csharp2ts|rafaelsalguero|0.0.24|
|csharpextensions|jchannon|1.3.1|
|csharpfixformat|Leopotam|0.0.84|
|dark-plus-syntax|dunstontc|0.0.167|
|debugger-for-edge|msjsdiag|1.0.15|
|docker-explorer|formulahendry|0.1.7|
|docomment|k--kato|0.1.13|
|dotnet-test-explorer|formulahendry|0.7.3|
|EditorConfig|EditorConfig|0.15.1|
|embrace|mycelo|1.0.0|
|excel-to-markdown-table|csholmq|1.2.2|
|git-project-manager|felipecaputo|1.7.1|
|githistory|donjayamanne|0.6.5|
|gitlens|eamodio|10.2.2|
|hexeditor|ms-vscode|1.1.0|
|html-css-class-completion|Zignd|1.19.0|
|ilspy-vscode|icsharpcode|0.8.0|
|js-debug-nightly|ms-vscode|2020.7.917|
|linecount|yycalm|0.1.7|
|macros|geddski|1.2.1|
|markdown-all-in-one|yzhang|3.1.0|
|markdown-mermaid|bierner|1.5.1|
|markdown-table-prettify|darkriszty|2.5.0|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.0.3|
|msbuild-project-tools|tintoy|0.3.8|
|namespace|adrianwilczynski|1.1.2|
|nuget-reverse-package-search|jesschadwick|0.1.68|
|path-intellisense|christian-kohler|2.2.1|
|powershell-preview|ms-vscode|2020.6.1|
|prettier-vscode|esbenp|5.1.3|
|quicktype|quicktype|12.0.46|
|rainbow-csv|mechatroner|1.7.0|
|razor-plus|austincummings|0.1.4|
|remote-wsl|ms-vscode-remote|0.44.4|
|supersharp|craigthomas|0.1.4|
|vscode-commitizen|KnisterPeter|0.9.2|
|vscode-custom-css|be5invis|3.0.10|
|vscode-docker|ms-azuretools|1.3.1|
|vscode-drawio|hediet|0.7.2|
|vscode-extensions-pack-builder|mrluje|0.1.4|
|vscode-markdownlint|DavidAnson|0.36.1|
|vscode-mscgen|mscgenjs|1.2.0|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-paste-image|mushan|1.0.4|
|vscode-pull-request-github|GitHub|0.17.0|
|vscode-scss|mrmlnc|0.9.0|
|vscode-text-tables|RomanPeshkov|0.1.5|
|vscode-wsl-workspacefolder|lfurzewaddock|1.1.2|
|xml|DotJoshJohnson|2.5.0|
|yandex-translate|airstep|1.0.7|;

</details>

**Comment by vchirikov** [comment] 2020-07-10 12:17
Seems like copy of the issue https://github.com/OmniSharp/omnisharp-vscode/issues/3459

**Comment by cartermp** [comment] 2020-07-14 23:43
Yep, duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3459 - looks like it's related to the custom output path

**Closed by cartermp** 2020-07-14 23:43 UTC
Labels: Resolved-Duplicate, Triaged
