### ISSUE TITLE
Semantic highlighting overrides constant.character.escape

### ISSUE THREAD

**Issue by ssoher** [OmniSharp/omnisharp-vscode#3956] opened 2020-08-08 15:04 UTC
When semantic highlighting is enabled the scope `constant.character.escape` is overriden by the scope `string`. How can one change the color of the escape characters when semantic highlighting is enabled in C#? I've also tried `semanticTokenColors` with `stringEscapeCharacter` but no luck.

![Screenshot_3](https://user-images.githubusercontent.com/4283979/89713593-5e1ad400-d9a1-11ea-98b5-944955a93e82.jpg)

**Comment by cartermp** [comment] 2020-08-11 23:39
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3864

**Closed by cartermp** 2020-08-11 23:39 UTC
Labels: Resolved-Duplicate, Triaged
