### ISSUE TITLE
Whitespace until next non-whitespace token ignored after paramref in xmldoc

### ISSUE THREAD

**Issue by Phrohdoh** [OmniSharp/omnisharp-vscode#954] opened 2016-11-16 03:23 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview4-004081)

Product Information:
 Version:            1.0.0-preview4-004081
 Commit SHA-1 hash:  6d57ca7e14

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version: 1.7.1
C# Extension version: 1.5.2

## Steps to reproduce

```csharp
        /// <exception cref="ClientException">Thrown if <paramref name="absolutePath"/> is null, empty, or whitespace-only.</exception>
        public string PushSync(string absolutePath, object content)
        {
            ...
        }
```

Hover over `PushSync` to reveal tooltip.

## Expected output

`ClientException Thrown if absolutePath is null, empty, or whitespace-only.`

## Actual output

`ClientException Thrown if absolutePathis null, empty, or whitespace-only.`

---

Notice the missing space between `absolutePath` and `is`.

## Other

I tried with both `<paramref name="absolutePath"></paramref>` and `<paramref name="absolutePath"/>`.

**Comment by DustinCampbell** [comment] 2016-11-16 03:26
Nice bug -- thanks!

**Comment by DustinCampbell** [comment] 2016-11-16 20:28
Actually, this is a duplicate of #672. The good news is that we just took a fix to OmniSharp that will fix it: https://github.com/OmniSharp/omnisharp-roslyn/pull/670

**Closed by DustinCampbell** 2016-11-16 20:28 UTC
Labels: Bug, Resolved-Duplicate
