### ISSUE TITLE
View type information for types not in the source

### ISSUE THREAD

**Issue by ivanz** [OmniSharp/omnisharp-vscode#648] opened 2016-08-09 15:28 UTC
It would be great if we can see where types are defined where the type is not part of the source code. Right now if I can't "go to definition" or "peek definition" - I have no idea where is this type defined. 

It would be amazing if we could get the same behaviour as in Visual Studio IDE where it displays a "[from metadata]" tab with the assembly name, namespace and list of members in C# code, but even just knowing which assembly and namespace the type comes from would be a start.

![image](https://cloud.githubusercontent.com/assets/79742/17522032/73395876-5e4d-11e6-85a4-d361aaea6549.png)

Edit:

I noticed one case where extra information is displayed and that's for field/property declaration's type:

![image](https://cloud.githubusercontent.com/assets/79742/17522496/2a3dd9ce-5e4f-11e6-94ef-8f9aeb6ff351.png)

**Comment by DustinCampbell** [comment] 2016-08-15 19:26
Thanks for the request @ivanz. Adding the "Metadata as Source" that VS has for symbols not defined in source is definitely something we want to do for VS Code. Dupe of #165.

**Closed by DustinCampbell** 2016-08-15 19:26 UTC
Labels: Feature Request, Resolved-Duplicate
