### ISSUE TITLE
Release seen as Severe threat by Windows Defender

### ISSUE THREAD

**Issue by MicahZoltu** [OmniSharp/omnisharp-vscode#1502] opened 2017-05-20 22:35 UTC
## Steps to reproduce
1. Install Windows 10 Pro.
2. Update to latest.
3. Make sure Windows Defender is fully up to date.
4. Download `csharp-1.10.0-beta4.vsix` from the Releases tab of GitHub.

## Expected  behavior
Not to get a Trojan.

## Actual behavior
Received a Trojan according to Windows Defender: https://www.microsoft.com/security/portal/threat/encyclopedia/Entry.aspx?Name=Trojan:Win32/Spursint.F!cl

**Comment by gregg-miskelly** [comment] 2017-05-21 00:07
Interesting. I removed the .vsix, I am not sure if our CI bot will recreate it, though obviously depending on what the problem is, this could come back anyway.

**Comment by MicahZoltu** [comment] 2017-05-21 00:09
I received the same problem with the previous version (forgot to update the issue after I tried it).

**Comment by MicahZoltu** [comment] 2017-05-21 00:10
I just tried all of the releases back to `csharp-1.9.0.vsix` and Windows defender gives the same error for all of them.

**Comment by MicahZoltu** [comment] 2017-05-21 00:12
The windows defender interface in Windows 10 sucks as it has data that scrolls off the right side of the screen but no scrollbar, no option to copy the text, and no ability to resize the window.  None the less, it does appear to indicate that the problem is with a file _inside_ the vsix.  All I can get from the path to the problematic file is `extension/gulpfi...` though.  :/

**Comment by MicahZoltu** [comment] 2017-05-21 00:23
If you are able to reproduce it, you can file a report with Microsoft [here](https://www.microsoft.com/en-us/security/portal/developer/ContactUS.aspx) to try and get it whitelisted.

**Comment by gregg-miskelly** [comment] 2017-05-21 01:16
Interesting, Windows Defender didn't report an issue for me with beta3, only beta4. I am not sure how to get our CI system from creating a new release. @DustinCampbell do you have any idea if that is possible?

**Comment by DustinCampbell** [comment] 2017-05-21 13:51
Is the warning on our gulpfile? Could we just not include that with the VSIX? I don't think we use it for anything.

**Comment by DustinCampbell** [comment] 2017-05-21 13:55
I kicked the CI to rebuild. New 1.10-beta4 is there.

**Comment by gregg-miskelly** [comment] 2017-05-21 16:16
Took me a little while, but I managed to bypass Windows Defender and actually get the .vsix downloaded and extracted to do do a full scan. It does look like the gulpfile is the only thing it is complaining about, and Windows defender is definitely wrong about the gulpfile. I reported the issue to Windows defender. I don't have time to test this now, but I can submit a PR on Monday to stop packaging it in the .vsix.

**Comment by natemcmaster** [comment] 2017-05-22 21:42
I'm still getting this error trying to download 1.10.0-beta5

![image](https://cloud.githubusercontent.com/assets/2696087/26329599/d7fba242-3efc-11e7-9215-24e6ea181449.png)

**Comment by gregg-miskelly** [comment] 2017-05-22 21:44
Yup, now that I have it up I see that too :(

**Comment by DustinCampbell** [comment] 2017-05-22 21:46
Any idea what's flagging it?

**Comment by natemcmaster** [comment] 2017-05-22 21:46
I'm trying to get more details on which files are in there, but the UI truncates the filename

![image](https://cloud.githubusercontent.com/assets/2696087/26329716/67faa0c8-3efd-11e7-8bd2-d2ebc5978b28.png)

**Comment by bernardbr** [comment] 2017-05-22 21:46
It's only with WD... I've tried with Kaspersky and Avast and both work without error.

**Comment by DustinCampbell** [comment] 2017-05-22 21:50
Unfortunately, the files listed there are simply the javascript files that make up the extension.

**Comment by bernardbr** [comment] 2017-05-22 21:53
Maybe Windows Defender developers check javascript files that handle files and folders to avoid WCry's infection.
I hope this is a misguided intuition of mine.

**Comment by DustinCampbell** [comment] 2017-05-22 21:57
Out of curiosity, is this happening with other VSIX extensions? I'm not a position to try right now, but do other VSIX releases suffer the same problem? (e.g. https://github.com/DonJayamanne/pythonVSCode/releases).

**Comment by gregg-miskelly** [comment] 2017-05-22 21:59
I removed the Beta5 release since it didn't help. I did send feedback to Defender so hopefully they will eventually resolved this. Otherwise I am not sure what to do.

**Comment by bernardbr** [comment] 2017-05-22 22:04
@DustinCampbell I'll check if WD does the false alert on that VSIX too. But I'll need some time.

**Comment by bernardbr** [comment] 2017-05-23 14:38
@DustinCampbell I tried with [pythonVSCode](https://github.com/DonJayamanne/pythonVSCode/releases) and Windows Defender didn't identify virus on the package...

**Comment by gregg-miskelly** [comment] 2017-05-24 20:56
@natemcmaster @MicahZoltu do you still see this problem if you update to today's Windows Defender definition? I used to repro this, but the problem has gone away, at least for me.

**Comment by natemcmaster** [comment] 2017-05-24 21:02
@gregg-miskelly  appears to be resolved, at least for https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.10.0-beta4/csharp-1.10.0-beta4.vsix

**Comment by DustinCampbell** [comment] 2017-05-24 21:03
Maybe Patch Tuesday fixed it?

**Comment by MicahZoltu** [comment] 2017-05-24 22:23
I was able to download `csharp-1.10.0-beta4.vsix` with no Windows Defender complaints.

**Comment by DustinCampbell** [comment] 2017-05-24 22:28
Are you able to download any of the other releases you mentioned without Defender complaining as well? This is seeming more and more like a Defender issue that got fixed.

**Comment by MicahZoltu** [comment] 2017-05-25 00:52
All .10 releases and the latest .9 release downloaded from the GitHub releases page without Windows Defender issues.

**Comment by DustinCampbell** [comment] 2017-05-25 01:50
Thanks for confirming @MicahZoltu. It sounds like we're exonerated. :smile:

**Comment by DustinCampbell** [comment] 2017-05-25 13:44
OK. I"m going to go ahead and close this. I suspect that a recent Defender definitions both caused and fixed this issue. Please let us know right away if you see this problem again.

**Closed by DustinCampbell** 2017-05-25 13:44 UTC
Labels: Resolved-External
