### ISSUE TITLE
revert to 1.19.0 from 1.19.1 cannot find netstandard 2.0

### ISSUE THREAD

**Issue by bruce31** [OmniSharp/omnisharp-vscode#3070] opened 2019-05-16 09:48 UTC
Issue Type: <b>Bug</b>

Win Server 2012 R2
Attempted upgrade to 1.19.1 - this required install of Framework 4.7.2
Cannot change .Net Framework version on server so needed to revert to 1.19.0

Why is .NET Framework 4.7.2 required? .Net Core 2.1 is installed on this machine. Also this is a user install of VS Code how can a machine-wide change be a requirement?
```
Starting OmniSharp server at 5/16/2019, 9:33:31 AM
    Target: e:\Devs\bruce317\eval\trunk\Retirement\UnitTestCode\Retirement.Utility.Extensions.UnitTest

OmniSharp server started.
    Path: C:\Users\bruce317\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\OmniSharp.exe
    PID: 32724

System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.HostHelpers.Start(Func`1 action) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\HostHelpers.cs:line 29

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

```

Extension version: 1.19.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (64 x 2295)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|256.00GB (123.49GB free)|
|Process Argv|..\DeveloperTools\GlobalTools|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by filipw** [comment] 2019-05-16 09:54
1.19.0 requires .NET 4.7.2, however it didn't manifest itself properly with a popup message, only with a silent `System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` error.

The last release that used .NET 4.6.1 was 1.18.0

Unfortunately this is by design - MSBuild 16, which is needed in OmniSharp as part of .NET Core 3.0 support, requires .NET 4.7.2 to run therefore OmniSharp was updated to it.

**Comment by filipw** [comment] 2019-05-17 08:16
Closing as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2992 - thanks

**Closed by filipw** 2019-05-17 08:16 UTC
Labels: Resolved-By Design
