### ISSUE TITLE
Code analysis result fails to navigate to the file on mouse click

### ISSUE THREAD

**Issue by jdvor** [OmniSharp/omnisharp-vscode#2102] opened 2018-03-11 10:52 UTC
## Environment data
dotnet --info
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**VS Code version:**
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**C# Extension version:**
ms-vscode.csharp 1.14.0

**Other extensions:**
adamvoss.yaml
bungcip.better-toml
cake-build.cake-vscode
dbankier.vscode-instant-markdown
donjayamanne.githistory
DotJoshJohnson.xml
EditorConfig.EditorConfig
eridem.vscode-nupkg
formulahendry.code-runner
formulahendry.dotnet-test-explorer
jchannon.csharpextensions
jmrog.vscode-nuget-package-manager
k--kato.docomment
Leopotam.csharpfixformat
lukehoban.Go
ms-vscode.csharp
ms-vscode.PowerShell
PeterJausovec.vscode-docker
robertohuertasm.vscode-icons
tintoy.msbuild-project-tools
zxh404.vscode-proto3

## Steps to reproduce
- Clone sample project `git clone https://github.com/jdvor/vscode-code-analysis-issue.git issue`
- Open VSCode `cd issue && code .`
- Run build task `Ctrl+Shift+B`
- Open tab Problems `Ctrl+Shift+M`
- Click any issue found for NastyClass.cs

## Expected  behavior
C# code analysis produces a list of warnings about the code that are displayed in Problems tab and are groupped by file name.
When the issue is mouse-clicked the corresponding file should open at the line reported.

## Actual behavior
Error message is displayed _"Unable to open 'NastyClass.cs': File not found (file:///NastyClass.cs)"._
Hint: the error message contains path (file:///) that is relative and wrong by having just a filename and missing part of directory structure. It probably should be file:///src/Lib2/NastyClass.cs or absolute path.

**Comment by DustinCampbell** [comment] 2018-03-12 18:06
This looks like a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1197.

**Closed** 2018-03-12 18:06 UTC
Labels: Resolved-Duplicate
