### ISSUE TITLE
formatter broken on last vscode update 1.43

### ISSUE THREAD

**Issue by jr549** [OmniSharp/omnisharp-vscode#3680] opened 2020-03-18 21:07 UTC
shift + alt + f

broken

## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by JoeRobich** [comment] 2020-03-19 19:37
@jr549 Can you provide the full OmniSharp log from the Output tab as well as what file type you were formatting?

**Comment by jr549** [comment] 2020-03-19 21:23
Well it seems that after reinstalling the latest version, 1.43.1 and
setting the desired extension, simonsiefke.prettier-vscode as default it is
now working again. I used the right click context menu to set default value
tied to the shift -alt - f shortcut key sequence. It took me several hours
to get this to work again. I assume there is a configuration file for this
setting but do not know where?

**Comment by cartermp** [comment] 2020-09-22 23:49
Configuration is likely in the VSCode settings. I'll close this out since it appears to be working for you (I also confirmed that formatting works for me on the latest plugin, too).

**Closed by cartermp** 2020-09-22 23:49 UTC
Labels: Needs More Info, Triaged
