### ISSUE TITLE
Restart button no longer working (.dll's locked with "process cannot access the file" errors)

### ISSUE THREAD

**Issue by winzig** [OmniSharp/omnisharp-vscode#2596] opened 2018-10-10 15:35 UTC
In the last couple weeks I've started experiencing a problem with VS Code (Insiders) where the Restart button does not successfully restart the debugging process. Instead, I get this error over and over in the TERMINAL tab of vscode:

/usr/local/share/dotnet/sdk/2.1.105/Microsoft.Common.CurrentVersion.targets(4118,5): warning MSB3026: Could not copy "obj/Debug/netcoreapp2.0/Web.dll" to "bin/Debug/netcoreapp2.0/Web.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/Users/tom/Documents/Repositories/code/Web/bin/Debug/netcoreapp2.0/Web.dll' because it is being used by another process. [/Users/tom/Documents/Repositories/code/Web/Web.csproj]

## Environment data
`dotnet --info` output:

Toms-MacBook-Pro:diag.net tom$ dotnet --info
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

VSCode Version: Version 1.29.0-insider (1.29.0-insider)
OS Version: macOS High Sierra 10.13.6 (17G65)
C# Extension version: 1.16.2

## Steps to reproduce

 1. Hit the "Play" button to start debugging a .NET Core web project
 2. After a while, hit the Restart button to restart debugging
 3. See the above error over and over in the terminal tab
 4. Give up and hit the stop button, followed by the start button.

## Expected  behavior

Restart should restart debugging

## Actual behavior

It doesn't.

**Comment by gregg-miskelly** [comment] 2018-10-11 15:52
This is a duplicate of https://github.com/Microsoft/vscode/issues/60593

**Closed by gregg-miskelly** 2018-10-11 15:52 UTC
