### ISSUE TITLE
When inside comment blocks (/* */), pressing the Period key on the keyboard should not trigger Content Assist dialog box.

### ISSUE THREAD

**Issue by tommai78101** [OmniSharp/omnisharp-vscode#2441] opened 2018-07-29 02:43 UTC
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.202)

Product Information:
 Version:            2.1.202
 Commit SHA-1 hash:  281caedada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.202\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.9
  Build    : 1632fa1589b0eee3277a8841ce1770e554ece037

VS Code version: 1.25.1
C# Extension version: 1.15.2
OS Version: Windows 10 Professional

## Issue: 

When inside comment blocks (/* */), pressing the Period key on the keyboard should not trigger Code Assist dialog box. 

It is annoying when you invoke the Content Assist dialog box, but it is even worse when you press the Spacebar in places where it should have been whitespaces. Like 

1. aaa
2. bbb
3. ccc

And then you accidentally invoke the Content Assist on the first "period", and the first entry is accidentally applied when the "Spacebar" key is pressed down.

## Steps to Reproduce:

1. In a blank C# file, start with a comment block. (/\* \*/).
2. Type out an ordered list (List that starts with 1, 2, 3, ...).
3. The moment you type a period in the ordered list, you are invoking the Content Assist dialog box.
4. All I'm doing is pressing only Spacebar and Period keys inside the comment block. The Content Assist shouldn't be invoked inside the comment blocks at all.

![gif](https://user-images.githubusercontent.com/6444116/43362261-0b5f8598-92b4-11e8-8c38-7d40911d4855.gif)

## Expected  behavior

Content Assist shouldn't be appearing inside comment blocks, nor invoked.

## Actual behavior

Content Assist is being invoked while inside comment blocks.

**Comment by rchande** [comment] 2018-07-30 17:55
@akshita31 I think you were looking into this at some point?

**Comment by akshita31** [comment] 2018-07-30 18:03
Yes, this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1424

**Comment by tommai78101** [comment] 2018-07-30 20:35
Yep, thanks for that issue @akshita31 .

**Closed** 2018-07-31 17:15 UTC
Labels: Resolved-Duplicate
