### ISSUE TITLE
C# highlight function displays wrong colors when using string interpolation

### ISSUE THREAD

**Issue by lennylxx** [OmniSharp/omnisharp-vscode#450] opened 2016-06-17 08:10 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.2.1
C# Extension version: 1.1.6

## Steps to reproduce
1. Open VSCode and create a C# source file: test.cs
2. Paste below content and save
```
using System;

namespace ConsoleApplication1
{
    class Program
    {
        public static string World = string.Empty;
        public static string Test = DuplicateString($"{nameof(World)}");

        static void Main()
        {
            Console.WriteLine("Hello " + Test);
        }

        public static string DuplicateString(string s)
        {
            return s;
        }
    }
}
```

## Expected  behavior
C# highlight function works perfect.

## Actual behavior
![test](https://cloud.githubusercontent.com/assets/5811576/16144502/f704764e-34a5-11e6-9976-b295d8fcdbae.png)

**Comment by DustinCampbell** [comment] 2016-06-23 17:46
This is a duplicate of #249. We'll use that issue to track this bug.

**Closed by DustinCampbell** 2016-06-23 17:46 UTC
Labels: Bug, Resolved-Duplicate
