### ISSUE TITLE
Option for putting curly brackets on "new line" after method declaration for C#

### ISSUE THREAD

**Issue by natemakesgames** [OmniSharp/omnisharp-vscode#3367] opened 2019-10-23 08:09 UTC
I would appreciate an option for putting curly brackets on "new line" after method declaration. It would be nice if this option was right there in the preferences window.

**Comment by cartermp** [comment] 2020-04-16 20:23
Resolving as a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1591

**Closed by cartermp** 2020-04-16 20:23 UTC
Labels: Resolved-Duplicate, Triaged
