### ISSUE TITLE
while Restart-Debugging there is build error after new update. kindly fix it

### ISSUE THREAD

**Issue by saurabhnachankar** [OmniSharp/omnisharp-vscode#2599] opened 2018-10-11 05:02 UTC
- Extension Name: csharp
- Extension Version: 1.16.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by gregg-miskelly** [comment] 2018-10-11 15:51
This is a duplicate of https://github.com/Microsoft/vscode/issues/60593

**Closed by gregg-miskelly** 2018-10-11 15:51 UTC
