### ISSUE TITLE
Only loads after file is modified

### ISSUE THREAD

**Issue by sguillia** [OmniSharp/omnisharp-vscode#3893] opened 2020-07-04 18:26 UTC
## Issue Description ##
The symbols in the outline only appear when an edit is made to the open document

## Steps to Reproduce ##

1. Open a .cs file
2. Observe as there are no symbols in the outline (no symbols found)
3. Add or delete a character from the .cs file
4. Observe as the symbols appear in the outline

## Expected Behavior ##

The symbols are loaded immediatly when a C-sharp text editor becomes active.

## Actual Behavior ##

The symbols are loaded immediatly when `onDidChangeTextDocument` even is triggered.

## Logs ##

n/a

## Environment information ##

**VSCode version**: 1.47.0-insider
**C# Extension**: 1.21.18

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.10.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.0.0 [/usr/share/dotnet/sdk]
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.18|
|vscodeintellicode|VisualStudioExptTeam|1.2.9|;

</details>

**Comment by SensehacK** [comment] 2020-07-07 15:51
Reproducible on my workstation as well.

Tried changing the folder structure and also opening the root folder with .csproj files. Still this issue persists, I'm using Unity 2019.3.12f1 build and vscode as my external IDE editor of choice.

Running these commands didn't help as well.
> restart omnisharp
> omnisharp select project
> omnisharp analyze the project

All these commands doesn't generate the intellisense for C# projects and command/control + click to jump to the variable declaration or find by references.

**Comment by JoeRobich** [comment] 2020-07-14 04:23
@sguillia Sorry things aren't working as expected. I was unable to reproduce the behavior you are seeing. Can you tell me more about the workflow you use to reproduce this? 

- Did you open a folder in VS Code that contains your source along side a .csproj or .sln file, then select a file from the explorer pane? Or are you opening a single .cs file on its own?
- Do you have a repo where this reproduces reliably?

**Comment by cartermp** [comment] 2020-09-23 01:04
Closing as no additional info was added.

**Closed by cartermp** 2020-09-23 01:04 UTC
Labels: Needs More Info, Triaged

**Comment by SensehacK** [comment] 2020-09-24 14:44
I had got this working with this dependency last time, but sometimes it does download Developer pack for C# support in the console.

Though installing Microsoft Developer Pack tools SDK for .NET resolved this issue temporarily.
https://www.microsoft.com/en-us/download/details.aspx?id=56119
