### ISSUE TITLE
Omnisharp refuses to start when VS Code is started from Unity

### ISSUE THREAD

**Issue by rhacer63** [OmniSharp/omnisharp-vscode#1377] opened 2017-04-11 20:11 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.11.1
C# Extension version:1.8.0

## Steps to reproduce
Open Project in Unity
Assets->Open C# Project

![installing omnisharp](https://cloud.githubusercontent.com/assets/27306556/24928585/eb36761c-1ed0-11e7-91d4-d91c0fa87bfa.PNG)
![post installation](https://cloud.githubusercontent.com/assets/27306556/24928587/eb3a98a0-1ed0-11e7-8fe7-c8bf09fa3e23.PNG)
![restarting omnisharp](https://cloud.githubusercontent.com/assets/27306556/24928588/eb3ed5e6-1ed0-11e7-974b-ce2255934d9b.PNG)
![no flame icon](https://cloud.githubusercontent.com/assets/27306556/24928586/eb36c37e-1ed0-11e7-8729-0ad3dab4b755.PNG)

Omnisharp will not start and no Intellisense.

## Expected  behavior

Omnisharp starts

## Actual behavior

Omnisharp will not start.

I can get it to start if I run "dotnet new" within my project directory. This creates a project.json file that appears to halfway work (It has no concept of any Unity classes, methods, functions). It also reports All my classes and methods as being ambiguously defined.

Interestingly, if I set VS2015 as my Unity editor, Intellisense works just fine.

**Comment by DustinCampbell** [comment] 2017-04-11 20:20
Don't create a project.json file. That causes nasty issues (like the classes and methods being ambiguously defined). This will not solve the problem in the way you might want it to.

Could you provide your OmniSharp log? Just load your Unity project in VS Code and then select View->Output from the VS Code menu. Choose "OmniSharp Log" from the drop-down at the top-right of the Output pane to display the log. Copy and paste it here.

**Comment by rhacer63** [comment] 2017-04-11 21:06
Dustin,

There is no output, I get absolutely NOTHING that gives me a hint as to what's going on (or not going on as the case may be) In fact there is not "OmniSharp Log" entry in the drop down.

**Comment by DustinCampbell** [comment] 2017-04-11 21:12
Do you have an OmniSharp status bar item on the far bottom right of the status bar? It should have a little "flame" OmniSharp logo.

![image](https://cloud.githubusercontent.com/assets/116161/24930976/585d9dc6-1ec0-11e7-9e05-2e8c003b9ff2.png)

Try clicking that status bar item. Clicking that should display a drop-down where you can pick your solution file:

![image](https://cloud.githubusercontent.com/assets/116161/24931102/d5787362-1ec0-11e7-8c83-e1759fb85a77.png)

**Comment by rhacer63** [comment] 2017-04-11 21:19
Dustin, the fourth image above (circled horribly in red) shows what my status bar looks like.

When I use the Command Palette->OmniSharp: Select Project I get this...
![image](https://cloud.githubusercontent.com/assets/27306556/24931271/9e616e46-1eda-11e7-97f5-f4b5ce80a338.png)

If it's helpful my project directory looks like this after select "Open C# Project"
![image](https://cloud.githubusercontent.com/assets/27306556/24931363/01a2f8c6-1edb-11e7-85c1-4250ab4cddf6.png)

**Comment by DustinCampbell** [comment] 2017-04-11 21:24
I'm a bit confused. Do you have any other extensions installed? Could you check %USERPROFILE%\.vscode\extensions and let me know what is there?

**Comment by rhacer63** [comment] 2017-04-11 21:32
You and me both!

Here's the Extensions Panel in VSCode (I actually did a complete uninstall/reinstall cycle over the weekend in the hopes that that would fix things)...

![image](https://cloud.githubusercontent.com/assets/27306556/24931719/4f918aec-1edc-11e7-825b-452a7bdd3223.png)

`PS C:\Users\rhace> cd .\.vscode\extensions\
PS C:\Users\rhace\.vscode\extensions> dir


    Directory: C:\Users\rhace\.vscode\extensions


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2017-04-08  11:33 AM                ms-vscode.csharp-1.8.1
d-----       2017-04-10   4:39 PM                ms-vscode.mono-debug-0.15.4
d-----       2017-04-08  11:12 AM                Tobiah.unity-tools-0.1.9
d-----       2017-04-08  11:11 AM                Unity.unity-debug-1.1.0
d-----       2017-04-07   8:09 AM                vscodevim.vim-0.6.15`

**Comment by DustinCampbell** [comment] 2017-04-11 21:39
One of the reasons I'm confused is because you described adding a project.json file and getting ambiguity errors in VS Code, which would require OmniSharp to load. However, other descriptions (such as no OmniSharp Log being available) would indicate that it's not being loaded.

**Comment by rhacer63** [comment] 2017-04-11 21:44
Oh, when the `dotnet new` command didn't work as expected I scrubbed all that

Code pre-`dotnet new`
![image](https://cloud.githubusercontent.com/assets/27306556/24932103/09d74346-1ede-11e7-867d-67e2285b93ff.png)

Code post-'dotnet new`
![image](https://cloud.githubusercontent.com/assets/27306556/24932192/60f6f04a-1ede-11e7-93e8-dadbf5b3d718.png)

I now also have a log file from OmniSharp...

```
Starting OmniSharp server at 4/11/2017, 5:42:27 PM
    Target: c:\Users\rhace\Documents\code\Catlike - Clock

OmniSharp server started
    Path: C:\Users\rhace\.vscode\extensions\ms-vscode.csharp-1.8.1\bin\omnisharp\OmniSharp.exe
    PID: 16552

OmniSharp: -s c:\Users\rhace\Documents\code\Catlike - Clock --hostPID 12728 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\Users\rhace\Documents\code\Catlike - Clock' on host 12728.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\rhace\Documents\code\Catlike - Clock
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update project c:\Users\rhace\Documents\code\Catlike - Clock
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Add project c:\Users\rhace\Documents\code\Catlike - Clock\project.json => 3eb49979-71c0-4724-b365-f9f4d9bd088c
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.DotNet.DotNetProjectSystem
          Processing [ProjectState] Catlike - Clock/.NETCoreApp,Version=v1.0
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 2 and removed 0 documents.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to C:\Users\rhace\.vscode\extensions\ms-vscode.csharp-1.8.1\bin\omnisharp\msbuild\MSBuild.exe
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to C:\Users\rhace\.vscode\extensions\ms-vscode.csharp-1.8.1\bin\omnisharp\msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to C:\Users\rhace\.vscode\extensions\ms-vscode.csharp-1.8.1\bin\omnisharp\msbuild\Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'c:\Users\rhace\Documents\code\Catlike - Clock\Catlike - Clock.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'c:\Users\rhace\Documents\code\Catlike - Clock\Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: c:\Users\rhace\Documents\code\Catlike - Clock\Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Assembly-CSharp
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\rhace\Documents\code\Catlike - Clock'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Watcher: c:\Users\rhace\Documents\code\Catlike - Clock\project.lock.json updated.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update project c:\Users\rhace\Documents\code\Catlike - Clock
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.DotNet.DotNetProjectSystem
          Processing [ProjectState] Catlike - Clock/.NETCoreApp,Version=v1.0
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 73 and removed 0 file references```

**Comment by DustinCampbell** [comment] 2017-04-11 21:50
And if you close VS Code, delete that project.json file and re-open the same folder in VS Code, you don't get a log at all?

**Comment by rhacer63** [comment] 2017-04-11 21:50
That is exactly correct!

**Comment by DustinCampbell** [comment] 2017-04-11 21:52
Do you have a C# file open in the editor?

**Comment by rhacer63** [comment] 2017-04-11 21:53
![image](https://cloud.githubusercontent.com/assets/27306556/24932470/b46fcee4-1edf-11e7-9607-d2a55ba5858c.png)

**Comment by rhacer63** [comment] 2017-04-11 21:53
I do.

**Comment by rhacer63** [comment] 2017-04-11 21:58
I"ve gotta go cook my wife and daughter dinner, but I'll be around later. I'd love to learn what boneheaded thing I'm doing that is preventing this from working!

Thanks for your help so far!

**Comment by DustinCampbell** [comment] 2017-04-11 21:59
Ok. I'm wondering if one of the other extensions on your machine is interfering with C# for VS Code. What happens if you uninstall everything but C# for VS Code and restart VS Code?

**Comment by DustinCampbell** [comment] 2017-04-11 22:33
I just tried all of the extensions you listed and wasn't able to reproduce the problem on my own project. Could you try the following?

1. Open VS Code.
2. Select File->Close Folder from the menu to close your project.
3. Select Help->Toggle Developer Tools
4. In the Developer Tools, select the "Console" tab.
5. Select File->Open Folder from the menu and open your project folder (the one containing the .sln file).

I'm assuming there's no OmniSharp Log. Does anything appear in the Developer Tools console?

**Comment by rhacer63** [comment] 2017-04-11 22:43
This is what I see there...

```extensionHost.ts:284 [Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\rhace\AppData\Local\GitHub'
    at Error (native)d.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98```

**Comment by rhacer63** [comment] 2017-04-12 16:28
Dustin,

Was that any help?

**Comment by DustinCampbell** [comment] 2017-04-17 22:31
Sorry for the delay here. It's clear that _some_ extension is failing here, though it's not clear which one or whether that failure is conflicting with C# or not.

I've heard some reports of a particular extension inside of VS Code failing and causing strange behavior in C# for VS Code. Could you try something for me? In VS Code, invoke the "SCM: Disable Preview SCM" command from the command palette. You can display the command palette with <kbd>Ctrl+Shift+P</kbd>.

**Comment by rhacer63** [comment] 2017-04-18 14:46
Dustin,

I've done that, and no change. 

I've closed unity, and wiped out the .sln file and the two Assembly-CSharp* files and started both again and no change.

I followed the steps above  with regard to the Developer Tools and there is now no output on Console tab.

I just did an uninstall/reinstall and the version of VSCode is now 1.11.2.

OmniSharp is still not starting.

**Comment by rhacer63** [comment] 2017-04-20 17:22
Dustin,

Just wanted you to know that I've attempted removing all extensions but C#, and I have the same results.

**Comment by tamirh** [comment] 2017-04-20 20:16
I was getting this same behavior, this is what fixed it for me:

Code -> Preferences -> Settings

I had the setting `"omnisharp.useMono": true` (the default is false). Removing that from my settings file let the omnisharp server start back up.

**Comment by Acidic9** [comment] 2017-04-21 13:29
Same issue here... It was working on another project but on this one I'm working on it omnisharp doesn't show.

**Comment by DustinCampbell** [comment] 2017-04-21 13:32
@acidic9: Are you sure it's the same issue? Are you on Windows? Do you not have an OmniSharp log?

**Comment by Acidic9** [comment] 2017-04-21 13:33
I am on windows, but I am not sure how to view the log

**Comment by DustinCampbell** [comment] 2017-04-21 13:34
Instructions are above: https://github.com/OmniSharp/omnisharp-vscode/issues/1377#issuecomment-293388254

**Comment by Acidic9** [comment] 2017-04-21 13:37
I don't have the OmniSharp log in my output window as seen here:
http://i.imgur.com/vd8CrIJ.png

**Comment by DustinCampbell** [comment] 2017-04-21 13:41
Thanks for verifying. That *does* sound like the same issue. Any chance you could share your project?

**Comment by Acidic9** [comment] 2017-04-21 13:41
Welp, after reopening VSCode a few times, my laptop's fan started spinning and suddenly the omnisharp icon in the bottom right appeared and it worked.

The issue was it was taking a very long time to load.

Thanks for the quick responses.

**Comment by DustinCampbell** [comment] 2017-04-21 13:42
Hmm... That's a little bizarre too. 😀

**Comment by Acidic9** [comment] 2017-04-21 13:46
Oh I think I found something that could help people having the same issue...

If your Unity project is very large, try changing the setting `omnisharp.projectLoadTimeout` to something greater than 60. It might just need a little extra time to load.

**Comment by DustinCampbell** [comment] 2017-04-21 13:53
Even if the project load timed out, there should've been an OmniSharp Log. That's what struck me as bizarre.

**Comment by Acidic9** [comment] 2017-04-21 13:56
Yeah it is pretty strange, I'm not sure what it could be then but it's working now so it's all good.

**Comment by rhacer63** [comment] 2017-04-21 16:15
After seeing these notes, I got rid of of my "`omnisharp.useMono": true`" entry in preferences and updated my timeout to 120, but still no luck.

**Comment by DustinCampbell** [comment] 2017-04-21 16:17
You had "omnisharp.useMono" set? That is super-unnecessary on Windows, since OmniSharp just runs on the desktop .NET Framework. Do you have other options set?

**Comment by rhacer63** [comment] 2017-04-21 16:20
Dustin, It was one of the things I was attempting to do to get it work and had failed to get rid of it.

Here're my preferences....
```
// Place your settings in this file to overwrite the default settings
{
    "files.exclude": {
        "**/*.js": true,
        "**/.vs": true,
        "**/.vscode": true,
        "**/*.csproj": true,
        "**/*.sln": true,
        "**/.collabignore": true,
        "**/Fonts": true,
        "**/Images": true,
        "**/Music": true,
        "**/*Textures": true,
        "**/VSCode": true,
        "**/*Themes": true,
        "**/Prefabs": true,
        "**/Materials": true
    },
    "window.zoomLevel": 0,
    "editor.codeLens": true,

    "workbench.experimental.colorCustomizations": true,

//    "omnisharp.useMono": true,
    "omnisharp.projectLoadTimeout": 120,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe"
}
```

**Comment by Acidic9** [comment] 2017-04-21 16:22
@rhacer63 The steps I followed was simply reopening and closing VSCode a few times. Also, I'm using a [plugin in Unity](https://github.com/dotBunny/VSCode/) to launch VSCode (by following [this tutorial](https://code.visualstudio.com/docs/other/unity)). This plugin automatically created a file in .vscode/launch.json which contains the following:
```json
{
	"version":"0.2.0",
	"configurations":[ 
		{
			"name":"Unity",
			"type":"mono",
			"request":"attach",
			"address":"localhost",
			"port":9596
		}
	]
}
```

This plugin isn't necessary to get OmniSharp to work, I'm just mentioning it because notice it adds `"type": "mono"`.

My only suggestion is relaunch VSCode and wait to see if it loads after a minute.

**Comment by rhacer63** [comment] 2017-04-21 16:30
@Acidic9 Thanks for the tips! I started off NOT using dotBunny's plugin, when things didn't work as expected I installed it, and then converted back to not using it when things continued to no work.

I did, however, just create that launch.json file in my project's .vscode directory as I didn't have one. Still no luck.

**Comment by Acidic9** [comment] 2017-04-21 16:32
@rhacer63 Sorry, to hear that. I think the launch.json has nothing to do with it honestly, it's the only suggestion I had. Does the project you're working in contain a huge number of files?

**Comment by DustinCampbell** [comment] 2017-04-21 16:37
Correct. @rhacer63 is experiencing a much more significant problem in that the C# extension does not even seem to be loaded.

**Comment by Acidic9** [comment] 2017-04-22 10:20
This problem is occurring again for me. Sometimes it wants to work and sometimes it doesn't.

**Comment by Acidic9** [comment] 2017-04-22 10:24
The issue is project-specific. I just switched to my previous project which I knew OmniSharp worked on fine and it works perfectly there... I switched back to this new project and it doesn't load.

**Comment by DustinCampbell** [comment] 2017-04-22 14:37
@Acidic9: If you could share that project, it'd definitely be easier to help out.

**Comment by Acidic9** [comment] 2017-04-23 05:43
Sorry for the late reply, it's 600+ mb and I don't have fantastic internet. This project 100% has the issue, I'm curious to see if you have the same issue with the specific project.

But here is the link: http://www.mediafire.com/file/ge3tvbkwgad83nm/OmniSharp_not_working_here_%28Unity_Project%29.zip

If it asks for a password, it's **OmniSharp321**

_I'll edit this comment to remove the password once I receive your reply._

**Comment by DustinCampbell** [comment] 2017-04-23 13:55
@Acidic9: I opened your project and found a couple of things;

1. It's so big because it includes your Builds folder
2. It doesn't actually include any csproj or sln files. Without those, OmniSharp has nothing to launch with.

**Comment by rhacer63** [comment] 2017-04-23 16:09
I got a new version of the C# extension. I closed my project folder and Unity, deleted the .vscode directory in my project, and the *.csproj and *.sln files. Restarted everything and I'm sad to report that there has been no improvement.

**Comment by DustinCampbell** [comment] 2017-04-23 16:53
If the csproj and sln files don't exist, OmniSharp won't be able to load. Is that what you've been doing this whole time? The project and solution files are essential for OmniShato make sense of your code.

**Comment by rhacer63** [comment] 2017-04-23 19:58
@DustinCampbell Unity creates them when using the "Open C# Project" I just wanted to make sure that there was nothing in any of those files that was preventing OmniSharp from starting.

**Comment by rhacer63** [comment] 2017-04-23 19:58
![image](https://cloud.githubusercontent.com/assets/27306556/25316947/c1bf0fee-283d-11e7-9b9b-5dc4b051885b.png)

**Comment by rhacer63** [comment] 2017-04-25 21:44
Dustin,

Is there anything I can do to help you? I'm on the East Coast, but at my desk all day so am willing to undertake any sort of debugging and inspection you might need.

**Comment by tamirh** [comment] 2017-04-25 22:37
@DustinCampbell - here is the simplest project that Unity will generate. It includes a single .cs file, a csproj, sln file, and all of the other supporting files it needs:

https://www.dropbox.com/s/h48163cfr5n6bg3/simple_unity_test_csharp.zip?dl=0

**Comment by rhacer63** [comment] 2017-04-26 12:15
@tamirh I've downloaded that project with the same results (I didn't expect anything different but wanted to close that loop).

**Comment by Acidic9** [comment] 2017-04-26 12:24
Hmm, I think I have an idea, as @DustinCampbell said, it needs those files to reference too.
Maybe Unity only creates those files once you open it in an editor that needs them such as Visual Studio 2015/2017

Maybe someone should open their project with Visual Studio 2015/2017 first, then try with Visual Studio Code?

(Can't do it right now sorry but it's just an idea I had)

**Comment by Acidic9** [comment] 2017-04-26 14:15
**SOLUTION:**
Open your project with MonoDevelop or Visual Studio 2015/2017 **first**, then reopen VSCode.

**PROBLEM:**
Unity doesn't create the .sln file in the root of your project unless you open it with an editor. I guess VSCode doesn't tell it to generate the .sln file for some reason.

----

This is not OmniSharp's issue. Sorry for this long discussion here haha, hopefully this helps anyone with the problem.

**Comment by DustinCampbell** [comment] 2017-04-26 14:18
VS Code doesn't do anything special for Unity projects. From VS Code's perspective, they are simply projects and solutions targeting .NET Framework or Mono.

There is a great "getting started" for Unity and VS Code at https://code.visualstudio.com/docs/other/unity. That document describes this process for getting setup.

**Comment by rhacer63** [comment] 2017-04-26 14:19
@Acidic9 Just tried it out (brand new installation of VS17 with the Unity Tools installed). Everything works great in VS17, but on changing back to VSC, things are back to my "normal".

**Comment by Acidic9** [comment] 2017-04-26 14:20
@rhacer63 Check the root of your project, did it create an .sln file with the same name as your project folder?

Also, did you restart VSCode?

Also, maybe try opening with Monodevelop first to see if it will create the file for you?

**Comment by rhacer63** [comment] 2017-04-26 14:36
@Acidic9 Yep, there's an sln file and two Assembly files. I can close Unity and VSC delete those files and Unity will recreate them, but unless I run `dotnet new` in that root directory, OmniSharp won't start, and running `dotnet new` creates several other problems.

**Comment by Acidic9** [comment] 2017-04-26 14:38
Hmm then I have no more ideas, I thought that was the solution. I'm not sure what else you can try, sorry.

**Comment by rhacer63** [comment] 2017-04-26 14:40
@Acidic9 I lived a long time without anything like Intellisense. At the moment, I'm just running VSCode and pretending I don't know that Intellisense should work (because aside from Vim, it quickly bubbled to the top of favorite editors).

**Comment by Acidic9** [comment] 2017-04-26 14:46
@rhacer63 Yeah of course, VSCode is the best out there (from testing many), there's a reason why I want to use VSCode over Visual Studio 2017 and Monodevelop etc.

Hopefully you can find a solution soon, just one more thing to check is make sure VSCode has opened the project folder rather than the single file and try using both these OmniSharp options to refresh OmniSharp entirely.

![Omnisharp options](http://image.prntscr.com/image/e01fd79832254244980f695ac4397cc3.png)

**Comment by rhacer63** [comment] 2017-04-26 14:51
@Acidic9 Starting with your second point, I've tried both options there `Select Project` provides an empty list.

Your first point, I'm unsure how to validate. My understanding is that the Assets->Open C# Project should do that, but from within VSC, I don't know how to ascertain that I've opened a folder rather than a single file. The sidebar certainly lists all my files and its root is my project root, but I'm not sure if that actually answers the question or not.

**Comment by Acidic9** [comment] 2017-04-26 14:55
@rhacer63 Yeah seeing as you see all the files from the root of your project, it means you have your project open. Sorry I have 0 more ideas. I managed to get it working for myself with what you said, just clicking Assets -> Open C# Project (with Monoedit as the default editor in preferences) which created the necessary sln file and now it's working just fine. In your case, I'm lost. Sorry.

**Comment by rhacer63** [comment] 2017-04-26 14:57
@Acidic9 I appreciate your taking the time!

**Comment by rhacer63** [comment] 2017-05-01 18:29
![image](https://cloud.githubusercontent.com/assets/27306556/25589256/f2710eac-2e79-11e7-8429-8c60ddce43af.png)

I needed to share that. 

My Surface Book screen started going south. I took it to the MS Store today, and they swapped out my old SB for a brand new one. Of course that meant I had to re-install everything from scratch, and when I did Omnisharp started working.

Here's what I think happened. When I first fired up VSC I was told that the CLI tools were missing. When OmniSharp installed, it said it couldn't run the dotnet command. This time, instead of asking to install the CLI tools I said "Ignore the warning." My bet is the presence of the CLI tools is what borked my original installation. I'm not going to try and prove that (at least not at the moment) but thought I would pass along my findings.

**Comment by rhacer63** [comment] 2017-05-01 23:44
Well that was a short-lived celebration. One reboot later and things are back to where they were before.

I do see an error message regarding the dotnet cli tools It's flagged as a C# error and not an OmniSharp error though. `Failed to spawn 'dotnet --info'`

**Comment by rhacer63** [comment] 2017-05-01 23:52
One more note, I wish I'd taken a picture. One time I received an error message at the top of the window saying "OmniSharp Server not running" or something along those lines. I've been trying to duplicate that message, but so far have failed.

**Comment by inmallinath** [comment] 2017-05-02 02:22
I had a similar issue with my VS Code editor. I was trying to run a web app on netcoreapp1.1 framework. When I used the Command Palette->OmniSharp: Select Project, I got "Select 1 of 0 projects". VS Code failed to start omnisharp and I could not find any omnisharp logs. All I did was to create a <projectName>.sln file [with no contents in it] in the root of my project. I closed out of the editor and when I relaunched my project in VS Code...voila... Omnisharp was running and now I have intellisense for my project!

**Comment by inmallinath** [comment] 2017-05-02 02:36
and of course, I renamed the .sln file to some dummy file extension soon after so that I could build my project....but omnisharp just needed its presence in the beginning. And btw, this was all done in a mac OS for building my asp.net core web application!

**Comment by rhacer63** [comment] 2017-05-03 12:44
@inmallinath Thanks for trying to help. I'll try anything! Sadly no luck! Your idea prompted me to try several variations of opening VSC and the project folder without Unity running, but I got the same environment each time.

@DustinCampbell the only thing that's different since the re-install is that I now get the `Failed to spawn 'dotnet --info'` message every time VSC starts. However, it seems that since it actually worked once, that error is likely spurious.

**Comment by DustinCampbell** [comment] 2017-05-03 16:17
@rhacer63: That is happening because of this:

> Here's what I think happened. When I first fired up VSC I was told that the CLI tools were missing. When OmniSharp installed, it said it couldn't run the dotnet command. This time, instead of asking to **install the CLI tools I said "Ignore the warning."** My bet is the presence of the CLI tools is what borked my original installation. I'm not going to try and prove that (at least not at the moment) but thought I would pass along my findings.

C# for VS Code does not install the the .NET CLI tools. On start up, the extension tries to run `dotnet --info` as part of trying to install the .NET Core debugger. If it can't find `dotnet` on your path, it displays a warning ([code](https://github.com/OmniSharp/omnisharp-vscode/blob/610c50de0592c538b4e2bec94d571c4116c0cf98/src/coreclr-debug/activate.ts#L96)). There is a `csharp.suppressDotnetInstallWarning` VS Code setting that you can use to suppress the warning.

**Comment by rhacer63** [comment] 2017-05-03 16:55
@DustinCampbell I have that configured. I just didn't know if that error may be pertinent in determining what may be going on.

Previously I DID have the .NET CLI tools installed.

**Comment by DustinCampbell** [comment] 2017-05-03 16:58
I don't *think* that error would cause an issue. Although, if it worked the first time but not subsequent times, I'm not sure. @gregg-miskelly, can you think of anything that might fail here? I'm wondering if the promises in the debugger around checking for the dotnet install might cause subsequent promises (such as launching OmniSharp) not to run.

**Comment by gregg-miskelly** [comment] 2017-05-03 17:56
@DustinCampbell I can't think of any great theory as to how that could happen. Looking at [main.ts](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/main.ts#L42). The OmniSharp activation actually gets kicked off first. So the only way something like that could happen would be if the debugger actually somehow entirely blocked the extension process from running.

@rhacer63 are still seeing the failed to spawn error? You can confirm/deny if this has anything to do with the debugger by opening up ~/.vscode/extensions/ms-vscode.csharp-1.9.0/out/src/main.js and commenting out the call to `coreclrdebug.activate`.

**Comment by DustinCampbell** [comment] 2017-05-03 18:01
Thanks @gregg-miskelly, I didn't look to closely. Just theorizing.

**Comment by rhacer63** [comment] 2017-05-03 18:22
@gregg-miskelly 

I have commented out the line that reads `coreclrdebug.activate(extension, context, reporter, logger, _channel);`

@DustinCampbell That got rid of the `dotnet --info` diagnostic, however, the server did not start.

**Comment by rhacer63** [comment] 2017-05-05 16:08
Just a note, I've upgraded to the May release of VSC. With no change in this behavior.

**Comment by DustinCampbell** [comment] 2017-05-05 16:21
@rhacer63: Are you able to launch OmniSharp from the command-line?

I'm not sure what version you have installed, but it should be located in`%UserProfile%\.vscode\extensions\ms-vscode.csharp-<version number goes here>\bin\omnisharp\OmniSharp.exe`

Try running that from the command line with the following arguments: `--stdio -s "<path to your solution file"`

**Comment by rhacer63** [comment] 2017-05-05 16:44
Absolutely. I just got a screen full of logging and it didn't exit, so I'm guessing it's running.

**Comment by DustinCampbell** [comment] 2017-05-05 16:46
Well that's some validation I guess. :smile: My suspicion is still that VS Code (for some unknown reason) isn't even launching the C# extension at all.

**Comment by rhacer63** [comment] 2017-05-05 16:50
I think this is some path related issue, though I don't know how to track that down. It sure feels like it!

**Comment by DustinCampbell** [comment] 2017-05-05 16:51
It does feel that way. Is there anything interesting about the path that you're opening in VS Code? I.e. does it have spaces are anything else that might be interesting?

**Comment by rhacer63** [comment] 2017-05-05 16:54
Yeah, my home directory is "Timothy Grant" (though it wasn't on the prior machine). Also all my code directories have spaces in them `.\Documents\code\Timothys - Game` etc. One moment while I test the theory...

**Comment by rhacer63** [comment] 2017-05-05 17:03
So creating .\Documents\code\Bar as my project didn't solve the problem, but that still doesn't resolve the issue of the User home directory.

So I created a new project on my D: Drive `D:\Foo\FooBar` I was hopeful for a brief moment as it took a bit to open, but that hope was in vain.

**Comment by jackytse** [comment] 2017-05-11 06:02
I got same error.

**Comment by rhacer63** [comment] 2017-05-30 20:02
@DustinCampbell Just downloaded the most recent extension and still have a failure to launch.

**Comment by rhacer63** [comment] 2017-06-15 14:30
@DustinCampbell Just checking to see if any progress has been made here. If there's any other information I can provide that might help.

**Comment by rhacer63** [comment] 2017-06-23 18:08
@DustinCampbell Anything?

**Comment by DustinCampbell** [comment] 2017-06-26 16:13
Sorry @rhacer63. I've just gotten back from vacation.

Unfortunately, I haven't been able to reproduce this issue, so I don't have any news. 😞

**Comment by rhacer63** [comment] 2017-06-26 16:50
@DustinCampbell I hope you had an extraordinarily good vacation!

**Comment by rhacer63** [comment] 2017-06-26 17:21
Just in case it's useful, I can runOmniSharp from the command prompt

```PS C:\Users\Timothy Grant\Documents\code\Logistica> ..\..\..\.vscode\extensions\ms-vscode.csharp-1.10.0\bin\omnisharp\OmniSharp.exe
OmniSharp: 
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location 'C:\Users\Timothy Grant\Documents\code\Logistica' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in C:\Users\Timothy Grant\Documents\code\Logistica
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBuild will use local Visual Studio installation.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Detecting projects in 'C:\Users\Timothy Grant\Documents\code\Logistica\Logistica.sln'.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: C:\Users\Timothy Grant\Documents\code\Logistica\Assembly-CSharp-firstpass.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: C:\Users\Timothy Grant\Documents\code\Logistica\Assembly-CSharp.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: C:\Users\Timothy Grant\Documents\code\Logistica\Assembly-CSharp-Editor-firstpass.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: C:\Users\Timothy Grant\Documents\code\Logistica\Assembly-CSharp-Editor.csproj
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: Assembly-CSharp-firstpass
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: Assembly-CSharp
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: Assembly-CSharp-Editor-firstpass
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Update project: Assembly-CSharp-Editor
info: OmniSharp.Script.ScriptProjectSystem[0]
      Detecting CSX files in 'C:\Users\Timothy Grant\Documents\code\Logistica'.
info: OmniSharp.Script.ScriptProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
info: OmniSharp.Startup[0]
      Configuration finished.```



I've also tried updating my preferences to include the following (though it didn't work):

```"omnisharp.path": "C:\\Users\\Timothy Grant\\.vscode\\extentions\\ms-vscode.csharp-1.10.0\\bin\\omnisharp\\OmniSharp.exe"```

**Comment by codeRiftel** [comment] 2017-08-24 18:38
I had the same issue. Seems like it's caused by adding *.sln and *.csproj to your "files.exclude" setting.

**Comment by rhacer63** [comment] 2017-08-24 19:20
@codeRiftel How the heck did you figure that out? I just checked, and that did, indeed, resolve the issue. Entertainingly I've already shifted over to Rider, so no longer need the fix!

Seriously good detective work though.

**Comment by DustinCampbell** [comment] 2017-08-24 19:43
*head smack* I had not considered that. Thanks for finding that @codeRiftel!

**Comment by DustinCampbell** [comment] 2017-08-24 19:44
Since the issue has finally been solved (though I'm slightly sad that I wasn't able to figure it out :smile:), I'll go ahead and close this.

**Closed by DustinCampbell** 2017-08-24 19:44 UTC
Labels: Resolved-External

**Comment by litemesa** [comment] 2018-01-05 09:46
Got the same issue, @codeRiftel, use saved my day :D

**Comment by gregruth** [comment] 2018-02-04 02:50
Anyone else having this issue, you can have Unity 2017 generate the sln and csproj files by first setting your script editor to VSCode (Unity -> Preferences -> External Tools -> Script Editor). Then go to Assests -> Open C# Project. Once I did that and restarted VsCode it all seemed to work!

**Comment by zachstronaut** [comment] 2018-06-15 18:40
Unity 2017, Mac OS... solution for me was to upgrade Mono.

**Comment by cemerson** [comment] 2018-07-29 10:54
+1 thank you do @codeRiftel! This was driving me NUTS and that files.exclude thing seems to fix it!

**Comment by kruncher** [comment] 2018-09-03 12:52
+1 on the "files.exclude" thing. It seems strange to me that OmniSharp cannot see the solution/project files when they are excluded from the "Explorer" pane.

**Comment by HarshNarayanJha** [comment] 2020-07-31 05:03
Hey there, I found a solution
https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net471-developer-pack-offline-installer
Install this and it will work (infact the omnisharp log also says to install this)

**Comment by norbux** [comment] 2021-04-16 19:26
I struggled with this issue too and in my case, setting "omnisharp.waitForDebugger": false, fixed my problem

**Comment by TheRabbitSoup** [comment] 2022-05-13 21:49
> I struggled with this issue too and in my case, setting "omnisharp.waitForDebugger": false, fixed my problem

As of 5/13/2022, this was the solution for me.

**Comment by Malthe122** [comment] 2022-06-25 14:47
Still have this issue. Tried everything on here with no success

**Comment by Malthe122** [comment] 2022-06-25 14:55
> Still have this issue. Tried everything on here with no success

I found my omnisharp log file (not shown in output) using "Everything". In that log there was an error that i needed to install .Net 6. I did and now it works.

Its crazy that this issue looking exactly the same can have so many different causes

**Comment by wilg** [comment] 2022-07-08 03:43
I had to set `"omnisharp.useModernNet": false` to get OmniSharp to boot and show a request for an updated .NET version. I swear this worked before. The extension must have updated and broken something?

**Comment by JoeRobich** [comment] 2022-07-09 17:26
@wilg With useModernNet set to false, ensure that you have the requirements installed https://github.com/OmniSharp/omnisharp-vscode#requirements
