### ISSUE TITLE
Told to install c# extension when already installed

### ISSUE THREAD

**Issue by zachstronaut** [OmniSharp/omnisharp-vscode#3622] opened 2020-03-05 20:35 UTC
Issue Type: <b>Bug</b>

When I open a c# file I'm told to install the c# extension. If I click the Install button it opens "@id:ms-vscode.csharp" in the Extensions: Marketplace and says "No extensions found."

Also, I've already got the c# extension installed!

Issue occurred after installing latest Safari and Security update for Mac OSX 10.14.6.

I've tried uninstalled and reinstalling the extension. I've tried re-installing dot net cli/sdk and mono and then reinstalling the extension. Nothing has helped.

Extension version: 1.21.13
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 7, 5|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by atticdweller** [comment] 2020-03-05 20:44
Same issue here on Windows 10. Using issue persists on Unity 2019.2.21f1 and 2019.2.13 even after uninstalling and reinstalling both Unity and VS Code.

**Comment by zachstronaut** [comment] 2020-03-05 20:55
I believe this is the cause: https://github.com/OmniSharp/omnisharp-vscode/issues/3620

**Comment by zachstronaut** [comment] 2020-03-05 21:10
Roll back 1.21.12 people!

Uninstall c# extension

download csharp-1.21.12.vsix

run:
code --install-extension csharp-1.21.12.vsix

wow look at that intellisense works again after 90 minutes of frustration because the c# extension unique id was changed

**Comment by atticdweller** [comment] 2020-03-05 22:29
This worked for me!

Extra step I had to do to get it working was to delete the old generated .sln and .csproj files in the Unity project root folder. 

@zachstronaut thank you for your help!

**Comment by Vixxd** [comment] 2020-03-05 22:50
> Roll back 1.21.12 people!

Yep, confirming this works - IntelliSense is working. I chose a *really* bad afternoon to use Unity with VSCode for the first time.

**Comment by mareklinka** [comment] 2020-03-06 00:55
Related: the change of the extension ID broke some other VSC extensions as well, like [Roslynator](https://github.com/JosefPihrt/Roslynator) and [Auto-Using](https://github.com/natanfudge/Auto-Using) who depend on the old ID.

**Comment by AddisonYarborough** [comment] 2020-03-06 17:47
Can also confirm this works, thank you for the fix!

**Comment by JoeRobich** [comment] 2020-03-09 23:23
I've got an update. I've verified that the latest stable and insiders releases, which are available now, no longer suggest installing the C# extension from the old publisher. However, extensions with dependencies on the C# extension still need to be republished specifying the new publisher.

**Comment by cartermp** [comment] 2020-03-10 22:20
Thanks for reporting. The issue is due to the publisher rename, which has broken the unity extension. [There is a pull request merged on the unity extension](https://github.com/OmniSharp/omnisharp-vscode/issues/3646), and once the extension updates go through, it should be resolved. Closing as a duplicate of #3620

**Closed by cartermp** 2020-03-10 22:20 UTC
