### ISSUE TITLE
Expression Bodied Members w/ String Interpolation breaks Syntax highlighting

### ISSUE THREAD

**Issue by scionwest** [OmniSharp/omnisharp-vscode#347] opened 2016-05-19 02:25 UTC
This is similar to issue #249 however in this scenario, it stops performing any syntax highlighting for the rest of the source file. This is using 1.0.10

![screen shot 2016-05-18 at 7 23 03 pm](https://cloud.githubusercontent.com/assets/1865693/15380774/25dbdd20-1d2e-11e6-85d7-19ebf106af6c.png)

It looks like this is specific to the string interpolation, since Expression Bodied Members without string interpolation appear to work fine.

    // Works fine
    public IConnection[] GetConnections() => 
        this.playerConnections.Select(keyValuePair => keyValuePair.Value).ToArray();

while string interpolation breaks it

    // Breaks
    public override string ToString() => $"{this.game.Name} - Adapter: {this.Name}";

**Comment by DustinCampbell** [comment] 2016-06-23 17:45
This is a duplicate of #249. We'll use that issue to track this.

**Closed by DustinCampbell** 2016-06-23 17:45 UTC
Labels: Bug, Resolved-Duplicate
