### ISSUE TITLE
Not able to switch C# projects in remote WSL2 window

### ISSUE THREAD

**Issue by jmihalich** [OmniSharp/omnisharp-vscode#3845] opened 2020-06-12 04:52 UTC
## Issue Description ##
When trying to switch projects (OmniSharp: Select Project), i get an little error window at the bottom right that says:
your 131072x1 screen size is bogus. expect trouble

The Host OS is: Windows 10 Pro 2004 build 19041.329

Note that all other C# extension functionality is working fine.  I can code, build, debug fine.  The project switcher just seems to be busted.

## Steps to Reproduce ##
1) Open VSCode Remote WSL window, with a WSL2 Ubuntu 18.04 distro.
2) Create a workspace with 2 projects in it.
3) In the project picker area in the status bar, click it, and select the other project to switch to it (the one that's not currently active)
4) project is not switched and the error above is displayed.

## Expected Behavior ##
Omnisharp should switch to the new project. This worked fine in WSL 1.

## Actual Behavior ##
Project is not changed.

### OmniSharp log ###
Starting OmniSharp server at 6/11/2020, 9:35:49 PM
    Target: /mnt/c/src/um/uberretail/server/dotnetcore/dataapi

OmniSharp server started.
    Path: /home/jmihalich/.vscode-server/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.2/run
    PID: 1249

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/jmihalich/.vscode-server/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.2/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/jmihalich/.vscode-server/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.2/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/home/jmihalich/.vscode-server/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.2/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/jmihalich/.vscode-server/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.2/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/jmihalich/.vscode-server/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.2/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/jmihalich/.vscode-server/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.2/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi/dataapi.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uberretail/server/dotnetcore/dataapi/dataapi.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi' on host 119.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi/dataapi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi/dataapi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: dataapi
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/permissions-api-client/permissions-api-client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/permissions-api-client/permissions-api-client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/permissions-api-client/permissions-api-client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-logging-nlog/utils-extensions-logging-nlog.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-logging-nlog/utils-extensions-logging-nlog.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-logging-nlog/utils-extensions-logging-nlog.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/utils/utils.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/utils/utils.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/utils/utils.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/http-client/http-client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/http-client/http-client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/http-client/http-client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-restapi-aspnetcore/utils-extensions-restapi-aspnetcore.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-restapi-aspnetcore/utils-extensions-restapi-aspnetcore.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-restapi-aspnetcore/utils-extensions-restapi-aspnetcore.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-db-mysql/utils-extensions-db-mysql.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-db-mysql/utils-extensions-db-mysql.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-db-mysql/utils-extensions-db-mysql.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-configuration/utils-extensions-configuration.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-configuration/utils-extensions-configuration.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-configuration/utils-extensions-configuration.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uberretail/server/dotnetcore/dataapi-database/dataapi-database.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi-database/dataapi-database.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi-database/dataapi-database.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/geojson/geojson.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/geojson/geojson.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/geojson/geojson.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-json-newtonsoft/utils-extensions-json-newtonsoft.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-json-newtonsoft/utils-extensions-json-newtonsoft.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-json-newtonsoft/utils-extensions-json-newtonsoft.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/db-common/db-common.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/db-common/db-common.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/db-common/db-common.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /mnt/c/src/um/uber-common/dotnetcore/mysql-db/mysql-db.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mnt/c/src/um/uber-common/dotnetcore/mysql-db/mysql-db.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/c/src/um/uber-common/dotnetcore/mysql-db/mysql-db.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/permissions-api-client/permissions-api-client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/permissions-api-client/permissions-api-client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-logging-nlog/utils-extensions-logging-nlog.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-logging-nlog/utils-extensions-logging-nlog.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/utils/utils.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/utils/utils.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/http-client/http-client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/http-client/http-client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-restapi-aspnetcore/utils-extensions-restapi-aspnetcore.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-restapi-aspnetcore/utils-extensions-restapi-aspnetcore.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-db-mysql/utils-extensions-db-mysql.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-db-mysql/utils-extensions-db-mysql.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-configuration/utils-extensions-configuration.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-configuration/utils-extensions-configuration.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uberretail/server/dotnetcore/dataapi-database/dataapi-database.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uberretail/server/dotnetcore/dataapi-database/dataapi-database.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/geojson/geojson.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/geojson/geojson.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/utils-extensions-json-newtonsoft/utils-extensions-json-newtonsoft.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/utils-extensions-json-newtonsoft/utils-extensions-json-newtonsoft.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/db-common/db-common.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/db-common/db-common.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/c/src/um/uber-common/dotnetcore/mysql-db/mysql-db.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mnt/c/src/um/uber-common/dotnetcore/mysql-db/mysql-db.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: permissions-api-client
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: utils-extensions-logging-nlog
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: utils
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: http-client
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: utils-extensions-restapi-aspnetcore
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: utils-extensions-db-mysql
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: utils-extensions-configuration
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: dataapi-database
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: geojson
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: utils-extensions-json-newtonsoft
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: db-common
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: mysql-db
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 237.

### C# log ###
Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' (45044 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'

Downloading package '.NET Core Debugger (linux / x64)' (54671 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (linux / x64)'

Downloading package 'Razor Language Server (Linux / x64)' (52869 KB).................... Done!
Installing package 'Razor Language Server (Linux / x64)'

Finished

## Environment information ##

**VSCode version**: 1.46.0
**C# Extension**: 1.22.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.22.0|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.11|
|msbuild-project-tools|tintoy|0.3.6|;

</details>

**Comment by jmihalich** [comment] 2020-06-12 04:54
<img width="1919" alt="vscode-err" src="https://user-images.githubusercontent.com/15250728/84466350-0aed0500-ac2e-11ea-9157-15b5dc61dfe6.png">


Here's a screen shot of the error

**Comment by JoeRobich** [comment] 2020-06-12 18:42
@jmihalich  Thanks for this report. Closing as duplicate of #3580

**Closed by JoeRobich** 2020-06-12 18:42 UTC
Labels: Resolved-Duplicate, Triaged
