### ISSUE TITLE
Incorrect syntax highlight with string interpolation 

### ISSUE THREAD

**Issue by JefStat** [OmniSharp/omnisharp-vscode#442] opened 2016-06-15 16:59 UTC
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: Version 1.2.0 (1.2.0)
C# Extension version: 1.1.4

## Steps to reproduce
Use string interpolation with escaped double quotes

## Expected  behavior
Correct syntax highlighting. 

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/583018/16089332/96caffea-32f8-11e6-8526-f09e8e804f06.png)

**Comment by Abdullah2993** [comment] 2016-06-15 20:47
+1 for this one for

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version: `1.2.1`
C# Extension version: `1.1.6`

![Proof](http://i.imgur.com/5SAguZj.png)

**Comment by lennylxx** [comment] 2016-06-17 08:16
+1 for this https://github.com/OmniSharp/omnisharp-vscode/issues/450.

**Comment by DustinCampbell** [comment] 2016-06-23 17:46
This is a duplicate of #249. We'll use that issue to track this bug.

**Closed by DustinCampbell** 2016-06-23 17:46 UTC
Labels: Bug, Resolved-Duplicate
