### ISSUE TITLE
I am not getting any intellisense for C# or dotnet in Visual Studio Code

### ISSUE THREAD

**Issue by drhhusain** [OmniSharp/omnisharp-vscode#4591] opened 2021-06-02 16:59 UTC
.NET Core SDK (reflecting any global.json):
 Version:   3.1.409     
 Commit:    217439b5ae  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19042
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.409\

Host (useful for support):
  Version: 3.1.15
  Commit:  dc339bd0fb

.NET Core SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]      
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Code is running but...

![dotnet_ex](https://user-images.githubusercontent.com/54940714/120520770-d13e7c80-c3f1-11eb-8270-432b88c1d0b6.png)

Intellisense is not Working

![dotnet_ex2](https://user-images.githubusercontent.com/54940714/120520853-ec10f100-c3f1-11eb-8180-677e5798896b.png)

**Comment by gcmlpfaltaher** [comment] 2021-06-08 13:27
check if Windows Defender is flagging Omnisharp

**Comment by JoeRobich** [comment] 2021-06-08 16:00
@drhhusain Can you share the OmniSharp log from the Output pane?

**Comment by hemirunner426** [comment] 2021-06-14 14:58
I'm seeing the same behavior.  Here is the output from the extension host:

[2021-06-14 07:53:13.104] [exthost] [error] Activating extension ms-dotnettools.csharp failed due to an error:
[2021-06-14 07:53:13.104] [exthost] [error] Error: command 'dotnet-sdk.acquireStatus' not found
    at p._tryExecuteCommand (file:///C:/Users/hemir/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///C:/Users/hemir/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
[2021-06-14 07:53:13.104] [exthost] [error] Activating extension ms-dotnettools.dotnet-interactive-vscode failed due to an error:
[2021-06-14 07:53:13.104] [exthost] [error] Error: command 'dotnet-sdk.acquireStatus' not found
    at p._tryExecuteCommand (file:///C:/Users/hemir/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///C:/Users/hemir/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    
    I think it may be related to the dotnet client updates released this past cycle.  I've tried removing all the dotnet core related SDKs and installed the latest 5.0.301 SDK manually.  All works fine in Visual Studio.

**Comment by JoeRobich** [comment] 2021-06-15 17:42
Closing. This issue was caused by invoking an Extension method on the dotnet-pack. It was fixed in https://github.com/dotnet/vscode-dotnet-pack/pull/20 and should be in the latest release. Please comment back if you are having issues with the latest version of the dotnet-pack installed.

**Closed by JoeRobich** 2021-06-15 17:42 UTC
