### ISSUE TITLE
Missing assembly definition in Unity project

### ISSUE THREAD

**Issue by Sov3rain** [OmniSharp/omnisharp-vscode#4142] opened 2020-10-23 15:01 UTC
## Issue Description ##

Hi,

Omnisharp is telling me that a assembly definition is missing in my script but in fact, Unity has no problem compiling the project.
For those who are familiar with Unity projects, I get this error when I try to access other assemblies located in my /Plugins folder, and in some extent, in any /Editor folder in my project too.

The problem is I don't get any autocompletion, and it's really not convenient. I don't know what is causing this, and I really need some insights.

## Steps to Reproduce ##

Try to access any assembly located in /Plugins or /Editor folder.

## Actual Behavior ##

Omnisharp is throwing `The type or namespace name 'NativeGallery' could not be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp]`

## Screenshots ##

![image](https://user-images.githubusercontent.com/10755450/97019740-f95b2880-1550-11eb-9481-fc4ba7addb1b.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.4

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-using|Fudge|0.7.15|
|awesome-flutter-snippets|Nash|2.0.4|
|csharp|ms-dotnettools|1.23.4|
|dart-code|Dart-Code|3.15.1|
|flutter|Dart-Code|3.15.1|
|material-icon-theme|PKief|4.3.0|
|namespace|adrianwilczynski|1.1.2|
|unity-debug|Unity|2.7.5|
|unity-tools|Tobiah|1.2.12|
|vscode-surround|yatki|1.0.2|;

</details>

**Comment by ericdrobinson** [comment] 2020-10-23 16:57
This is probably a duplicate of #4113. Please try the workarounds outlined in [this comment](https://github.com/OmniSharp/omnisharp-vscode/issues/4113#issuecomment-714748347).

**Comment by Sov3rain** [comment] 2020-10-23 19:12
I can confirm that rolling back to Visual Studio Code Editor package version 1.1.3 (sticking to C# for VS Code version 1.23.4) fixed the issue ! Thanks for the hint.

**Comment by JoeRobich** [comment] 2020-10-23 21:43
@Sov3rain closing this as a duplicate. Thanks for opening a report.

**Closed by JoeRobich** 2020-10-23 21:43 UTC
Labels: Resolved-Duplicate
