### ISSUE TITLE
Could not load file or assembly 'Microsoft.Build'

### ISSUE THREAD

**Issue by imba-tjd** [OmniSharp/omnisharp-vscode#2815] opened 2019-01-26 09:29 UTC
## Environment data
<details>
<summary>`dotnet --info` output:</summary>

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    b9f2fa0ca8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
</details>

<details>
<summary>VS Code version:</summary>

```
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```
</details>

C# Extension version: **Perhaps any version other than newest(1.17.1)**, for example 1.17.0

## Steps to reproduce

This problem only happends when I use `Install Another Version` to install old versions. I tested several version, all of them have this issue. But back to the time when they were the newest version, I didn't encounter this issue.

I have tried https://github.com/OmniSharp/omnisharp-vscode/issues/2208#issuecomment-384735388 but it doesn't work.

It's also OK to just close. After all, the newest version works and I don't know whether this is my system's problem because it works fine in my win7 x86 VM.

## Output Log

<details>
<summary>Log</summary>

```
Starting OmniSharp server at 1/26/2019, 4:59:45 PM
    Target: c:\dotnet

OmniSharp server started.
    Path: C:\Users\xxx\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\OmniSharp.exe
    PID: 19264

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.0.28522.59 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\xxx\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.0.28522.59 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\dotnet'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\dotnet'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\dotnet\dotnet.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\dotnet'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\dotnet' on host 17296.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\dotnet\dotnet.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\dotnet\dotnet.csproj'.
c:\dotnet\dotnet.csproj(1,1)
System.IO.FileNotFoundException: Could not load file or assembly “Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a” or one of its dependencies. The system can not find the file specified.
File name:“Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\dotnet\dotnet.csproj
```
</details>

**Comment by akshita31** [comment] 2019-01-28 19:54
@imba-tjd Since it works on the newest version, I think we can close this for now. Please feel free to reopen if the issue reproduces with the current latest or the upcoming versions

**Closed by akshita31** 2019-01-28 19:54 UTC

**Comment by Cedz** [comment] 2019-07-12 01:10
Currently failing with exact same error message on the latest version of C# Estenstion and VSCode 

Starting OmniSharp server at 7/11/2019, 5:57:54 PM
    Target: c:\WorkSpace\src\repos\WikiFeedbackLinkInjector

Log
OmniSharp server started.
    Path: c:\Users\celabu\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\OmniSharp.exe
    PID: 45760

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Enterprise 2017 15.9.28307.770 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Bin"
            2: StandAlone 15.0 - "c:\Users\celabu\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2017 15.9.28307.770 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\WorkSpace\src\repos\WikiFeedbackLinkInjector'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\WorkSpace\src\repos\WikiFeedbackLinkInjector'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\WorkSpace\src\repos\WikiFeedbackLinkInjector\WikiFeedbackLinkInjector.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\WorkSpace\src\repos\WikiFeedbackLinkInjector'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\WorkSpace\src\repos\WikiFeedbackLinkInjector\WikiFeedbackLinkInjector.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\WorkSpace\src\repos\WikiFeedbackLinkInjector\WikiFeedbackLinkInjector.csproj'.
c:\WorkSpace\src\repos\WikiFeedbackLinkInjector\WikiFeedbackLinkInjector.csproj(1,1)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 304

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\WorkSpace\src\repos\WikiFeedbackLinkInjector\WikiFeedbackLinkInjector.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\WorkSpace\src\repos\WikiFeedbackLinkInjector' on host 30900.

**Comment by imba-tjd** [comment] 2019-07-12 01:13
@Cedz You'd better open a new issue
