### ISSUE TITLE
Debugger: "No Debug"(Ctrl+F5) is not supported by keyboard operation

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#704] opened 2016-08-24 09:22 UTC
## Environment data
VS Code version: 1.4.0
OS:Mac

C# Extension version:
csharp-1.4.0-beta6.vsix

## Steps to reproduce
1: Create a new project following under steps:
![screen shot 2016-08-24 at 4 49 25 pm](https://cloud.githubusercontent.com/assets/20184768/17924667/2d5d3bd0-6a1c-11e6-879e-f1f50bccab35.png)
2: Open this project with VSCode
3: Ctrl/Command+F5

## Expected  behavior
Support for launching a project with "No Debug"(Ctrl+F5).

## Actual behavior
1. "No Debug"(Command+F5) is not supported by keyboard operation.
2. Support for launching a project with "No Debug"(Ctrl+F5) in Command Palette:
![screen shot 2016-08-24 at 5 12 23 pm](https://cloud.githubusercontent.com/assets/20184768/17925153/58906424-6a1e-11e6-82a0-fc5fb0ced66b.png)
(Command+F5) should display same result by  keyboard operation.

**Comment by gregg-miskelly** [comment] 2016-08-24 16:06
@ClaireKang I am not quite sure what you are saying. First, are you running into #701, because I would have expected that bug to break all testing? If you are working around that, are you finding that it works correctly with Command-F5? If not, does it work correctly with F5? How about with 'Debug: Start Without Debugging' from the command palette?

**Comment by wesrupert** [comment] 2016-08-24 19:45
Using `⌘-F5` on my mac opens VoiceOver; is this what you were seeing @ClaireKang? If so, this looks like an issue with VS Code's shortcut choice, and is not something we can do anything about on our side. Selecting the "Debug: Start without Debugging" command from the command palette ran as expected for me.

**Comment by ClaireKang** [comment] 2016-08-25 01:02
I'm so sorry to not tell you what about Using ⌘-F5 on my mac. 
Using ⌘-F5 on my mac opens VoiceOver that are the same result with you. Selecting the "Debug: Start without Debugging" command from the command palette ran which is the expected result

**Comment by gregg-miskelly** [comment] 2016-08-25 01:24
@weinand @isidorn would the VS Code be interested in us porting this issue to VS Code (that the default shortcut for 'Debug: Start without Debugging' conflicts with VoiceOver on macOS). Or would you consider this 'By Design'?

**Comment by isidorn** [comment] 2016-08-25 05:42
This is by design, especially since I think there is no conflict if you use the F keys on the mac as standard keys (which is not the default).
The default is that for each F key you first have to hold the fn key. So by default start without debugging is cmd + fn + F5, while voice over is cmd + F5.

**Comment by weinand** [comment] 2016-08-25 08:20
@gregg-miskelly there is a global macOS setting that let's you flip the way how the F keys work. I would except that every developer has turned this on:

![2016-08-25_10-17-49](https://cloud.githubusercontent.com/assets/1898161/17961650/49133b0e-6aad-11e6-8936-14ee4ca87214.png)

**Comment by gregg-miskelly** [comment] 2016-08-25 15:10
@weinand @isidorn Thanks! I will close this then.

**Closed by gregg-miskelly** 2016-08-25 15:10 UTC
Labels: Blocked, Debugger
