### ISSUE TITLE
OmniSharp stops keyboard input after load

### ISSUE THREAD

**Issue by v2k** [OmniSharp/omnisharp-vscode#3675] opened 2020-03-17 16:10 UTC
I've been using this setup for years without issue, I'm not sure what has changed that's triggered this.  I've tried rolling back OmniSharp, but it won't install anything older than 1 month.

VSCode Version: 1.43.0
OS Version: Windows 10

Steps to Reproduce:

Install ms-dotnettools.csharp
Install vscodevim.vim (also same with neo vim)
Open VSCode and edit a file.
Note keyboard will work for a 20-30 seconds, then it will stop. Developer: Reload Window can get it working briefly, but it will stop again after 20-30 seconds.  It stops keyboard input when  OmniSharp is doing its refresh - ie when its log stops.

I've tried using older versions of Vim, uninstalling all plugins and VSCode and reinstalling.

I noticed that the reload window does trigger an OmniSharp refresh, so it must be related. I've tried various C# projects, and they all seem to behave in the same manner.

I'm using Unity C# projects.  In one case, I get errors like these:

`\.vscode\extensions\ms-dotnettools.csharp-1.21.13\.omnisharp\1.34.13\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): Error: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "DeckLinkAPI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.`

**Comment by JoeRobich** [comment] 2020-03-17 20:21
@v2k Can you share your OmniSharp log and VSCode VIM extension version? 

The issue about processor architecture is unrelated.

**Comment by JoeRobich** [comment] 2020-03-17 20:25
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3660

**Closed by JoeRobich** 2020-03-17 20:25 UTC
Labels: Resolved-Duplicate, Triaged
