### ISSUE TITLE
Syntax highlighting breaks when a comment containing a C# keyword is on the same line as a property definition

### ISSUE THREAD

**Issue by sbeca** [OmniSharp/omnisharp-vscode#2021] opened 2018-02-08 03:10 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version: `1.20.0`
C# Extension version: `1.13.1`

## Steps to reproduce
Write a comment containing a C# keyword (e.g. `class`, `struct`, `enum`) on the same line as a single line property definition.

## Expected  behavior
<img width="494" alt="bugreport2" src="https://user-images.githubusercontent.com/1635228/35953537-3f087e9c-0cd9-11e8-8ab9-152575a7e1a7.png">

## Actual behavior
<img width="413" alt="bugreport1" src="https://user-images.githubusercontent.com/1635228/35953533-3a2e6bc0-0cd9-11e8-953d-c735e0e73f0e.png">

**Comment by DustinCampbell** [comment] 2018-02-08 18:09
Thanks for reporting this issue for the C# TextMate grammar. This is a duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/75.

**Closed** 2018-02-08 18:09 UTC
Labels: Resolved-Duplicate
