### ISSUE TITLE
Intellisence netcore 5.0 doesnot work

### ISSUE THREAD

**Issue by umbruxo** [OmniSharp/omnisharp-vscode#4396] opened 2021-02-15 10:39 UTC
## Environment data
`dotnet --info` output:

Пакет SDK для .NET (отражающий любой global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

C# Extension version:
v1.23.9

## OmniSharp log
Received response for /v2/getcodeactions but could not find request.
[warn]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 573,
  "Command": "/completion",
  "Arguments": {
    "FileName": "c:\\Users\\shurupov\\Source\\repos\\WebAPITest\\WebAPITest\\Controllers\\ReportController.cs",
    "Line": 34,
    "Column": 13,
    "CompletionTrigger": 1
  }
}
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 573,
  "Command": "/completion",
  "Running": true,
  "Success": false,
  "Message": "\"System.InvalidCastException: Невозможно выполнить приведение [A]System.Threading.Tasks.Task`1[System.ValueTuple`2[Microsoft.CodeAnalysis.Completion.CompletionList,System.Boolean]] к [B]System.Threading.Tasks.Task`1[System.ValueTuple`2[Microsoft.CodeAnalysis.Completion.CompletionList,System.Boolean]]. Источником типа A является \\\"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\\\" в контексте \\\"LoadNeither\\\" в расположении \\\"C:\\\\WINDOWS\\\\Microsoft.Net\\\\assembly\\\\GAC_64\\\\mscorlib\\\\v4.0_4.0.0.0__b77a5c561934e089\\\\mscorlib.dll\\\". Источником типа B является \\\"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\\\" в контексте \\\"LoadNeither\\\" в расположении \\\"C:\\\\WINDOWS\\\\Microsoft.Net\\\\assembly\\\\GAC_64\\\\mscorlib\\\\v4.0_4.0.0.0__b77a5c561934e089\\\\mscorlib.dll\\\".\\r\\n   в OmniSharp.Roslyn.CSharp.Services.Intellisense.CompletionItemExtensions.GetCompletionsInternalAsync(CompletionService completionService, Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Intellisense\\\\CompletionItemExtensions.cs:строка 65\\r\\n   в OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService.<Handle>d__7.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Completion\\\\CompletionService.cs:строка 120\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:строка 230\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:строка 131\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:строка 215\"",
  "Body": null,
  "Seq": 2659,
  "Type": "response"
}
Received response for /quickinfo but could not find request.
[warn]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 624,
  "Command": "/completion",
  "Arguments": {
    "FileName": "c:\\Users\\shurupov\\Source\\repos\\WebAPITest\\WebAPITest\\Controllers\\ReportController.cs",
    "Line": 34,
    "Column": 10,
    "CompletionTrigger": 1
  }
}
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 624,
  "Command": "/completion",
  "Running": true,
  "Success": false,
  "Message": "\"System.InvalidCastException: Невозможно выполнить приведение [A]System.Threading.Tasks.Task`1[System.ValueTuple`2[Microsoft.CodeAnalysis.Completion.CompletionList,System.Boolean]] к [B]System.Threading.Tasks.Task`1[System.ValueTuple`2[Microsoft.CodeAnalysis.Completion.CompletionList,System.Boolean]]. Источником типа A является \\\"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\\\" в контексте \\\"LoadNeither\\\" в расположении \\\"C:\\\\WINDOWS\\\\Microsoft.Net\\\\assembly\\\\GAC_64\\\\mscorlib\\\\v4.0_4.0.0.0__b77a5c561934e089\\\\mscorlib.dll\\\". Источником типа B является \\\"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\\\" в контексте \\\"LoadNeither\\\" в расположении \\\"C:\\\\WINDOWS\\\\Microsoft.Net\\\\assembly\\\\GAC_64\\\\mscorlib\\\\v4.0_4.0.0.0__b77a5c561934e089\\\\mscorlib.dll\\\".\\r\\n   в OmniSharp.Roslyn.CSharp.Services.Intellisense.CompletionItemExtensions.GetCompletionsInternalAsync(CompletionService completionService, Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OptionSet options, CancellationToken cancellationToken) в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Intellisense\\\\CompletionItemExtensions.cs:строка 65\\r\\n   в OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService.<Handle>d__7.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Completion\\\\CompletionService.cs:строка 120\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:строка 230\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:строка 131\\r\\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\\r\\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   в OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() в D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:строка 215\"",
  "Body": null,
  "Seq": 8193,
  "Type": "response"
}

## Steps to reproduce
Every time when i try to use intelisense or just typing something in editor window omnisharp log throw the text above

## Expected  behavior
Intellisense showld work properly

## Actual behavior
Every time when i try to use intelisense or just typing something in editor window omnisharp log throw the text above
But when i build,run,debug project it works fine. I only cannot use intellisense while coding. As if I'm using a simle notepad

**Comment by umbruxo** [comment] 2021-02-15 11:34
Intellisense work fine in Omnisharp 1.21.17 but, there is no time to check in what version it is broken... Please check this out

**Comment by filipw** [comment] 2021-02-15 12:14
this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4090
Unfortunately we have not been able to reproduce this or find the root cause so far.

**Closed by filipw** 2021-02-15 12:14 UTC
