### ISSUE TITLE
"xx references" disappears if current file contains empty class body

### ISSUE THREAD

**Issue by myocytebd** [OmniSharp/omnisharp-vscode#5552] opened 2023-01-24 20:55 UTC
## Issue Description ##
(It is not a new issue of 1.25.4.)  
"xx references" before methods, fields etc. are not displayed in some files, but correctly displayed in other files in same project.  
No relevant messages are displayed in Outputs.  

## Steps to Reproduce ##
1. Open any project, and add a new file as below. "xx references" are displayed correctly.  
```
namespace ns {
    public class EmptyClassA {
        int field;
    }
    public class EmptyClassB : System.Object {
        int field;
    }
    public static class SA {
        public static int sField;
        public static void sMethod() {}
    }
}
```
2. Comment out, or delete any of the two ```int field;``` lines, and "xx references" will disappear.  
Outputs does not add any new message.  

## Expected Behavior ##
"xx references" before methods etc. are always displayed.

## Actual Behavior ##
"xx references" before methods, fields etc. are not displayed if the file contains empty class body.  

### OmniSharp log ###
<details>Starting OmniSharp server at 1/25/2023, 4:23:44 AM
    Target: /home/xxx/.wine64/drive_c/new/Marfusha/mod

OmniSharp server started with .NET 7.0.100-rc.2.22477.23
 (/home/xxx/.dotnet).
    Path: /home/xxx/.vscode/extensions/ms-dotnettools.csharp-1.25.4-linux-x64/.omnisharp/1.39.4-net6.0/OmniSharp.dll
    PID: 186085

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to /home/xxx/.dotnet/dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.4.0 - "/home/xxx/.dotnet/sdk/7.0.100-rc.2.22477.23/"
            2: .NET Core SDK 6.0.402 17.3.2 - "/home/xxx/.dotnet/sdk/6.0.402/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "/home/xxx/.dotnet/sdk/7.0.100-rc.2.22477.23/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/xxx/.wine64/drive_c/new/Marfusha/mod'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/xxx/.wine64/drive_c/new/Marfusha/mod'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/xxx/.wine64/drive_c/new/Marfusha/mod/mod.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/xxx/.wine64/drive_c/new/Marfusha/mod'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/xxx/.wine64/drive_c/new/Marfusha/mod' on host 185886.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/xxx/.wine64/drive_c/new/Marfusha/mod/mod.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/xxx/.wine64/drive_c/new/Marfusha/mod/mod.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/xxx/.wine64/drive_c/new/Marfusha/mod/mod.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: mod
</details>

### C# log ###
<details>Post the output from Output-->C# here  
(empty)</details>

## Environment information ##

**VSCode version**: 1.74.1
**C# Extension**: 1.25.4

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/xxx/.dotnet/sdk/7.0.100-rc.2.22477.23/

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: x64
  Commit:       550605cc93

.NET SDKs installed:
  6.0.402 [/home/xxx/.dotnet/sdk]
  7.0.100-rc.2.22477.23 [/home/xxx/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/home/xxx/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [/home/xxx/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/xxx/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.13.41|
|cpptools|ms-vscode|1.13.9|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.4|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|isort|ms-python|2022.8.0|
|java|redhat|1.14.0|
|jupyter|ms-toolsai|2022.11.1003412109|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.14|
|nugetpackagemanagergui|aliasadidev|2.0.6|
|powershell|ms-vscode|2023.1.0|
|python|ms-python|2022.20.2|
|ruby|rebornix|0.28.1|
|vscode-back-forward-button|grimmer|0.1.6|
|vscode-fileutils|sleistner|3.8.0|
|vscode-java-debug|vscjava|0.47.0|
|vscode-java-dependency|vscjava|0.21.1|
|vscode-java-pack|vscjava|0.25.7|
|vscode-java-test|vscjava|0.37.1|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-maven|vscjava|0.40.4|
|vscode-pylance|ms-python|2023.1.30|
|vscode-ruby|wingrunr21|0.28.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|;

</details>

**Comment by filipw** [comment] 2023-01-25 13:02
Thanks a lot for your report. This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5466 so I will close it.

**Closed by filipw** 2023-01-25 13:02 UTC
