### ISSUE TITLE
Razor formatting

### ISSUE THREAD

**Issue by Boheminsan** [OmniSharp/omnisharp-vscode#4030] opened 2020-09-01 17:42 UTC
(C# extension lead me to here)
I want to format razor (cshtml) files. 
Visual studio has a file association "Razor" file (.cshtml).
When i install C# extension, it adds one more filetype which associated with (.cshtml) file named "aspnetcorerazor". 
![Image of YIssue](https://i.imgur.com/nXYJRum.png)
I try change language mode to Razor and it doesnt change.
I forced to change when i close file and reopen it turns to aspnetcorerazor back. 
I couldnt remove or even changed aspnetcore filetype.
Emmet doesn't see aspnetcorerazor file as html and doesn's show suggestions.
Also C# is the default formatter of that file and doesnt support neither html nor c# side correctly in aspnetcorerazor file.
It really annoys. 
I am drowning in vscode settings.json.
Please fix this.

**Comment by ajaybhargavb** [comment] 2020-09-01 17:59
@Boheminsan, thanks for the report. We are already working on this. You can track it here, https://github.com/dotnet/aspnetcore/issues/14271.  Currently we only support pure C# formatting in `@code` blocks but we recently added support for HTML as well as part of https://github.com/dotnet/aspnetcore-tooling/pull/2445. This will be available in an upcoming release of the C# extension.

**Comment by jmarolf** [comment] 2020-09-01 23:20
closing as duplicate of https://github.com/dotnet/aspnetcore/issues/14271

**Closed by jmarolf** 2020-09-01 23:20 UTC
