### ISSUE TITLE
Generate Assets for Build and Debug generates assets for wrong project

### ISSUE THREAD

**Issue by dozer75** [OmniSharp/omnisharp-vscode#2740] opened 2018-12-11 10:24 UTC
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.29.1

C# Extension version: 1.17.1

## Steps to reproduce
Have a solution with an ASP.NET Core and a xUnit project in the following structure:
src\Web
test\UnitTest

Run the command Generate Assets for Build and Debug

## Expected  behavior
The assets should be generated for the ASP.NET Core project (or both), not only for the xUnit project (not sure if having it for the xUnit project gives any real value, see open issue #1392)

## Actual behavior
The assets is only generated for the xUnit project

**Comment by rchande** [comment] 2018-12-11 16:41
@akshita31 I think you'll need to fix this in Omnisharp.

**Comment by gregg-miskelly** [comment] 2019-01-05 02:10
This bug will be significantly improved by PR https://github.com/OmniSharp/omnisharp-vscode/pull/2780 -- with that PR, there is now a chooser for selecting which project to be the startup project. Its not a perfect fix in that the unit test project will still be listed as a choice even though that makes no sense. But still a big improvement.

We actually already had a bug tracking the fact that unit tests are considered launchable by OmniSharp: https://github.com/OmniSharp/omnisharp-vscode/issues/1392. So I am going to resolve this as a dupe of that.

@akshita31 I see that this issue is currently assigned to you. If you have the cycles to fix OmniSharp to return info on if a project is a unit test project, please assign #1392 to yourself.

**Closed by gregg-miskelly** 2019-01-05 02:10 UTC
Labels: Bug, Launch-And-Task-Json-Generation
