### ISSUE TITLE
"Execute the restore command to continue" messages in large projects cycle continuously 

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#928] opened 2016-11-14 09:44 UTC
_From @ryanbrandenburg on November 11, 2016 22:36_

- VSCode Version: 1.7.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Clone an AspNet Core repo with lots of projects (like aspnet/Mvc).
2. Open that folder in VS Code and wait for all the messages reading `There are unresolved dependencies from 'project'. Please execute the restore command to continue.` to appear.
3. From the command line run `dotnet restore`.
4. Observe the rapid scroll of the restore messages.

_Copied from original issue: Microsoft/vscode#15387_

**Comment by DustinCampbell** [comment] 2016-11-14 18:22
This is essentially a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/845.

In the latest release that _just_ shipped, we added a `csharp.suppressDotnetRestoreNotification` which you can set for your project. After installing the update, do the following:

1. Open your project in Visual Studio Code
2. Select Preferences -> User Settings
3. In settings.json add the following:

```JSON
    "csharp.suppressDotnetRestoreNotification": true
```

Now, close and reopen your project (or relaunch VS Code).

**Closed by DustinCampbell** 2016-11-14 18:22 UTC
Labels: Resolved-Duplicate

**Comment by anshupitlia** [comment] 2019-05-13 11:05
Does `"csharp.suppressDotnetRestoreNotification": true` only suppresses the notification or it does a dotnet restore and then suppress the notification?

**Comment by rchande** [comment] 2019-05-13 16:40
@anshupitlia It only suppresses the warning.
