### ISSUE TITLE
Not compatible with some Chinese characters

### ISSUE THREAD

**Issue by 717009629** [OmniSharp/omnisharp-vscode#281] opened 2016-05-06 06:34 UTC
![d 7e2b0 w uo j8 0t6 b7](https://cloud.githubusercontent.com/assets/16289643/15065907/f547e2ee-1396-11e6-949d-ecff7d6910a0.png)
`    public class Test
    {
        public void 测试()
        {
            return ;
        }       
        public void 未读()
        {
            return ;
        }
    }`

The method “测试” is ok, but  the method “未读”  has "unexpected character" flag.
the following characaters(in red box) have the same problem.
![s 1ixbkuz6hfhgc yd5 5](https://cloud.githubusercontent.com/assets/16289643/15066274/8dfbd27c-139a-11e6-9822-bdf609f3117d.png)

 E69CAA  未
 E69CAB  末
 E69CAC  本
 E69CAD  札
 E69CAF  术

**Comment by DustinCampbell** [comment] 2016-05-06 14:38
This looks like a dupe of issues #4 and #140.

**Closed by DustinCampbell** 2016-05-06 14:38 UTC
Labels: Resolved-Duplicate
