### ISSUE TITLE
High CPU consumption!

### ISSUE THREAD

**Issue by khteh** [OmniSharp/omnisharp-vscode#3130] opened 2019-06-21 05:21 UTC
Please paste the output from your clipboard
![Screenshot from 2019-06-21 13-20-39](https://user-images.githubusercontent.com/3871483/59899501-87884180-9427-11e9-9cc9-2a9f48f73188.png)

**Comment by rchande** [comment] 2019-07-29 22:47
Suspect this is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/2847

**Closed by rchande** 2019-07-29 22:47 UTC
