### ISSUE TITLE
OSX : Unable to attach to CoreCLR. 

### ISSUE THREAD

**Issue by ggregg** [OmniSharp/omnisharp-vscode#1348] opened 2017-03-28 09:59 UTC
## Environment data
`dotnet --info` output:
> .NET Command Line Tools (1.0.1)
>
>Product Information:
> Version:            1.0.1
> Commit SHA-1 hash:  005db40cd1
>
>Runtime Environment:
> OS Name:     Mac OS X
> OS Version:  10.12
> OS Platform: Darwin
> RID:         osx.10.12-x64
> Base Path:   /usr/local/share/dotnet/sdk/1.0.1

VS Code version: 1.10.2 (1.10.2)
C# Extension version: 1.8.0

## Notes
I installed last night the MacOS (10.12.4 (16E195)) and Xcode (8.3 (8E162)) updates and this morning the debugger no longer works. Thanks for help.

## Steps to reproduce
In terminal
>dotnet new console
>dotnet restore

Open Visual Studio Code
> Required assets to build and debug are missing from 'test'. Add them? Yes
> Launch : .NET Core Launch (console)
>>The program '[3439] test.dll' has exited with code -1 (0xffffffff).
>>
>>You may only use the Microsoft .NET Core Debugger (vsdbg) with...
>>**Unable to attach to CoreCLR.**

## Expected  behavior
Debugging :)

## Actual behavior
No-debugger :(

**Comment by AntoineVht** [comment] 2017-03-28 11:56
Same issue, I just updated to 10.12.. 
I hope this will be corrected quickly

**Comment by gregg-miskelly** [comment] 2017-03-28 14:34
This is a duplicate of #1220. I will fix the title of that bug to make it more clear.

**Closed by gregg-miskelly** 2017-03-28 14:34 UTC
