### ISSUE TITLE
Needed parameters not shown

### ISSUE THREAD

**Issue by johanneskopf** [OmniSharp/omnisharp-vscode#662] opened 2016-08-15 16:48 UTC
## Environment data
VS Code version:
C# Extension version: 1.3
OS Version: Windows 10, Build 14901

## Steps to reproduce
Open a Unity solution
Create a new script
Write somewhere "GameObject o = new GameObject(" and check out the shown parameters.

## Expected  behavior
Showing the needed parameters.

## Actual behavior
Doesn't show the parameter type + name, instead some info.
![parameters_not_showing](https://cloud.githubusercontent.com/assets/13490371/17671672/87eef88c-6318-11e6-8816-3c6cc09b8e2b.PNG)

**Comment by DustinCampbell** [comment] 2016-08-15 19:33
This is duplicate of #36.

**Closed by DustinCampbell** 2016-08-15 19:33 UTC
Labels: Bug, Resolved-Duplicate
