### ISSUE TITLE
Warning/errors being shown twice

### ISSUE THREAD

**Issue by vieira-andre** [OmniSharp/omnisharp-vscode#1965] opened 2018-01-20 00:57 UTC
## Environment data
`dotnet --info` output:

```
Product Information:
Version:            2.1.4
Commit SHA-1 hash:  5e8add2190

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.16299
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

Version  : 2.0.5
Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version:

> 1.19.2 (x64)

C# Extension version:

> 1.13.1

## Steps to reproduce

1. Create a Console Application project with `dotnet new console`
2. Declare [and optionally assign] a value to any variable. For instance, `int x = 1;`
3. Do not use it anywhere in the code.
4. Hover the mouse over it.

Obs.: sometimes you need to hover twice to get the fault behavior, or let the pointer over the variable for a bit.

## Expected  behavior

A warning stating:

> The variable 'x' is assigned but its value is never used [`namespace`]
> int x

## Actual behavior

The warning appears twice:

> The variable 'x' is assigned but its value is never used [`namespace`]
> The variable 'x' is assigned but its value is never used [`namespace`]
> int x

**Comment by vieira-andre** [comment] 2018-01-20 03:29
I changed the title because I noticed that this duplication behavior happens with any warnings/errors.

**Comment by imba-tjd** [comment] 2018-01-28 10:23
@DustinCampbell Fine. I think this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1830

**Comment by DustinCampbell** [comment] 2018-01-29 15:52
Thanks @imba-tjd. Agreed!

**Closed by DustinCampbell** 2018-01-29 15:52 UTC
Labels: Resolved-Duplicate
