### ISSUE TITLE
Clicking item in Problems Tab results in File Not Found on Pop!OS (Ubuntu 17.10)

### ISSUE THREAD

**Issue by Alumniminium** [OmniSharp/omnisharp-vscode#2073] opened 2018-02-27 09:37 UTC
## Environment data
`dotnet --info` output:

> 
> .NET Command Line Tools (2.1.4)
> 
> Product Information:
>  Version:            2.1.4
>  Commit SHA-1 hash:  5e8add2190
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  17.10
>  OS Platform: Linux
>  RID:         linux-x64
>  Base Path:   /usr/share/dotnet/sdk/2.1.4/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.5
>   Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
> 

VS Code version:

> Version 1.20.1
> Commit f88bbf9137d24d36d968ea6b2911786bfe103002
> Date 2018-02-13T15:31:21.019Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64
> 

C# Extension version: 1.14.0

## Steps to reproduce

Have any error in project -> Build -> Click entry in "Problems" tab

## Expected  behavior

Jump to file & line where this problem is located

## Actual behavior

"ERROR: Unable to open 'MsgText.cs': File not found (file:///Network/Packets/Conquer/MsgText.cs)."

Build Output:

> 
> Build FAILED.
> 
> Network/Packets/Conquer/MsgText.cs(439,36): error CS1003: Syntax error, ':' expected [/home/alumni/Desktop/yi-x/YiX.csproj]
>     0 Warning(s)
>     1 Error(s)
> 
Image: http://pix.toile-libre.org/upload/original/1519724739.png

**Comment by Alumniminium** [comment] 2018-02-27 09:38
Is there any workaround / Solution? It's really painful to work like that.

**Comment by DustinCampbell** [comment] 2018-02-27 13:40
This looks to me like a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1197. If that's correct, you should be able to workaround the issue by adding `<GenerateFullPaths>true</GenerateFullPaths>` to your project or including `/p:GenerateFullPaths=True` in the build task in your tasks.json file.

**Comment by Alumniminium** [comment] 2018-02-27 16:33
> {
>     "version": "2.0.0",
>     "tasks": [
>         {
>             "label": "build",
>             "command": "dotnet",
>             "type": "process",
>             "args": [
>                 "build",
>                 "${workspaceFolder}/YiX.csproj",
>                 "/property:GenerateFullPaths=true"
>             ],
>             "problemMatcher": "$msCompile"
>         }
>     ]
> }
tasks.json file updated with said switch, problem resolved. Thank you very much!

**Closed** 2018-02-28 14:06 UTC
Labels: Resolved-Duplicate
