### ISSUE TITLE
[cshtml] New lines are added unexpectedly when saving a *.cshtml file

### ISSUE THREAD

**Issue by HoTKreeZy** [OmniSharp/omnisharp-vscode#5327] opened 2022-08-01 09:34 UTC
## Is this a Bug or Feature request?:
Bug

## Steps to reproduce

⚠️ Only tested with a freshly created Razor Pages app ⚠️ 

1. Open a `*.cshtml` file in the Pages folder (e.g. Index.cshtml).
2. Save the file

## Description of the problem:

First, I thought it was an error from the VSCode Neovim extension, so I disabled it and found out it wasn't.

When saving a `*.cshtml` file, new lines are added even when the file has not been changed but still saving the file.

Expected behavior:

Do not add new lines

#### OmniSharp
------------------- Please fill in this section -------------------------
To find the OmniSharp log, open VS Code's "Output" pane, then in the dropdown choose "OmniSharp Log".

#### Razor
<details><summary>Expand</summary>
<p>

```
[Client - 11:03:51] -- Starting Issue Data Collection-- 
[Client - 11:03:57] Updating the C# document for Razor file 'd:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml' (12)
[Client - 11:03:57] Notifying document 'd:\develop\Kinshr\Kinshr.Server\Pages\Recipes\Index.cshtml' changed 'csharpChanged'
[Client - 11:03:57] Updating the HTML document for Razor file 'd:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml' (12)
[Client - 11:03:57] Notifying document 'd:\develop\Kinshr\Kinshr.Server\Pages\Recipes\Index.cshtml' changed 'htmlChanged'
[Client - 11:04:00] Updating the C# document for Razor file 'd:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml' (13)
[Client - 11:04:00] Notifying document 'd:\develop\Kinshr\Kinshr.Server\Pages\Recipes\Index.cshtml' changed 'csharpChanged'
[Client - 11:04:00] Updating the HTML document for Razor file 'd:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml' (13)
[Client - 11:04:00] Notifying document 'd:\develop\Kinshr\Kinshr.Server\Pages\Recipes\Index.cshtml' changed 'htmlChanged'
[Client - 11:04:01] Updating the C# document for Razor file 'd:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml' (14)
[Client - 11:04:01] Notifying document 'd:\develop\Kinshr\Kinshr.Server\Pages\Recipes\Index.cshtml' changed 'csharpChanged'
[Client - 11:04:01] Updating the HTML document for Razor file 'd:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml' (14)
[Client - 11:04:01] Notifying document 'd:\develop\Kinshr\Kinshr.Server\Pages\Recipes\Index.cshtml' changed 'htmlChanged'
[Client - 11:04:04] -- Stopping Issue Data Collection-- 
```

</p>
</details>

#### Razor document:
<details><summary>Expand</summary>
<p>

```Razor
@page
@model Kinshr.Server.Pages_Recipes.IndexModel

@{







    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Recipe[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipe[0].Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipe[0].ReleaseDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Recipe)



        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseDate)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>







        }
    </tbody>
</table>

```

</p>
</details>

#### Projected CSharp document:
<details><summary>Expand</summary>
<p>

```C#
////////////////////// Projected CSharp as seen by extension ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace Kinshr.Server.Pages.Recipes
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "d:/develop/Kinshr/Kinshr.Server/Pages/_ViewImports.cshtml"
using Kinshr.Server;

#line default
#line hidden
#nullable disable
    public class Pages_Recipes_Index : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((System.Action)(() => {
#nullable restore
#line 2 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
Kinshr.Server.Pages_Recipes.IndexModel __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 4 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
  







    ViewData["Title"] = "Index";

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "Create";
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#nullable restore
#line 24 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
           __o = Html.DisplayNameFor(model => model.Recipe[0].Title);

#line default
#line hidden
#nullable disable
#nullable restore
#line 27 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
           __o = Html.DisplayNameFor(model => model.Recipe[0].Content);

#line default
#line hidden
#nullable disable
#nullable restore
#line 30 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
           __o = Html.DisplayNameFor(model => model.Recipe[0].ReleaseDate);

#line default
#line hidden
#nullable disable
#nullable restore
#line 36 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
         foreach (var item in Model.Recipe)



        {
            

#line default
#line hidden
#nullable disable
#nullable restore
#line 43 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.Title);

#line default
#line hidden
#nullable disable
#nullable restore
#line 46 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.Content);

#line default
#line hidden
#nullable disable
#nullable restore
#line 49 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.ReleaseDate);

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "./Edit";
#nullable restore
#line 52 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                                                  __o = item.ID;

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = string.Empty;
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "./Details";
#nullable restore
#line 53 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                                                     __o = item.ID;

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = string.Empty;
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "./Delete";
#nullable restore
#line 54 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                                                    __o = item.ID;

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = string.Empty;
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#nullable restore
#line 56 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                 







        }

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Kinshr.Server.Pages_Recipes.IndexModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<Kinshr.Server.Pages_Recipes.IndexModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<Kinshr.Server.Pages_Recipes.IndexModel>)PageContext?.ViewData;
        public Kinshr.Server.Pages_Recipes.IndexModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591



////////////////////// Projected CSharp as seen by VSCode ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace Kinshr.Server.Pages.Recipes
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "d:/develop/Kinshr/Kinshr.Server/Pages/_ViewImports.cshtml"
using Kinshr.Server;

#line default
#line hidden
#nullable disable
    public class Pages_Recipes_Index : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((System.Action)(() => {
#nullable restore
#line 2 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
Kinshr.Server.Pages_Recipes.IndexModel __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 4 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
  







    ViewData["Title"] = "Index";

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "Create";
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#nullable restore
#line 24 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
           __o = Html.DisplayNameFor(model => model.Recipe[0].Title);

#line default
#line hidden
#nullable disable
#nullable restore
#line 27 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
           __o = Html.DisplayNameFor(model => model.Recipe[0].Content);

#line default
#line hidden
#nullable disable
#nullable restore
#line 30 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
           __o = Html.DisplayNameFor(model => model.Recipe[0].ReleaseDate);

#line default
#line hidden
#nullable disable
#nullable restore
#line 36 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
         foreach (var item in Model.Recipe)



        {
            

#line default
#line hidden
#nullable disable
#nullable restore
#line 43 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.Title);

#line default
#line hidden
#nullable disable
#nullable restore
#line 46 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.Content);

#line default
#line hidden
#nullable disable
#nullable restore
#line 49 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
               __o = Html.DisplayFor(modelItem => item.ReleaseDate);

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "./Edit";
#nullable restore
#line 52 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                                                  __o = item.ID;

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = string.Empty;
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "./Details";
#nullable restore
#line 53 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                                                     __o = item.ID;

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = string.Empty;
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = "./Delete";
#nullable restore
#line 54 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                                                    __o = item.ID;

#line default
#line hidden
#nullable disable
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = string.Empty;
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#nullable restore
#line 56 "d:/develop/Kinshr/Kinshr.Server/Pages/Recipes/Index.cshtml"
                 







        }

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Kinshr.Server.Pages_Recipes.IndexModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<Kinshr.Server.Pages_Recipes.IndexModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<Kinshr.Server.Pages_Recipes.IndexModel>)PageContext?.ViewData;
        public Kinshr.Server.Pages_Recipes.IndexModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591

// 14
```

</p>
</details>

#### Projected Html document:
<details><summary>Expand</summary>
<p>

```Html
////////////////////// Projected Html as seen by extension ///////////////////////
~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~







    ~~~~~~~~~~~~~~~~~ ~ ~~~~~~~~
~

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~
            </th>
            <th>
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~~~
            </th>
            <th>
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        ~~~~~~~~ ~~~~ ~~~~ ~~ ~~~~~~~~~~~~~



        ~
            <tr>
                <td>
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~
                </td>
                <td>
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~
                </td>
                <td>
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="~~~~~~~~">Edit</a> |
                    <a asp-page="./Details" asp-route-id="~~~~~~~~">Details</a> |
                    <a asp-page="./Delete" asp-route-id="~~~~~~~~">Delete</a>
                </td>
            </tr>







        ~
    </tbody>
</table>



////////////////////// Projected Html as seen by VSCode ///////////////////////
~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~







    ~~~~~~~~~~~~~~~~~ ~ ~~~~~~~~
~

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~
            </th>
            <th>
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~~~
            </th>
            <th>
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        ~~~~~~~~ ~~~~ ~~~~ ~~ ~~~~~~~~~~~~~



        ~
            <tr>
                <td>
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~
                </td>
                <td>
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~
                </td>
                <td>
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~ ~~~~~~~~~~~~~~~~~
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="~~~~~~~~">Edit</a> |
                    <a asp-page="./Details" asp-route-id="~~~~~~~~">Details</a> |
                    <a asp-page="./Delete" asp-route-id="~~~~~~~~">Delete</a>
                </td>
            </tr>







        ~
    </tbody>
</table>

// 14
```

</p>
</details>

See the screenshots took directly inside vscode with the [CodeSnap](https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap) extension.

<details><summary>Expand</summary>

File auto generated when creating the project with the dotnet cli so no problems here :

![code](https://user-images.githubusercontent.com/42871753/182116356-da9d61fc-ae4d-4e3b-89ca-4def7a7a340c.png)

New lines added when saving the file without any changes :

![code-saved](https://user-images.githubusercontent.com/42871753/182116381-933d77b9-7b47-4b10-ae24-95b191ce8526.png)

New lines keep to be added when saving the file : 

![code-saved2](https://user-images.githubusercontent.com/42871753/182116414-d0d64a28-6ac9-4e11-b1a9-70fc7add11de.png)

</details>

## Machine information

**VSCode version**: 1.69.2
**Razor.VSCode version**: 1.25.0
#### `dotnet --info`

<details><summary>Expand</summary>
<p>

```
SDK .NET (refl�tant tous les fichiers global.json)�:
 Version:   6.0.302
 Commit:    c857713418

Environnement d'ex�cution�:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

```

</p>
</details>

#### Extensions
<details><summary>Expand</summary>
<p>

|Extension|Author|Version|
|---|---|---|
|better-comments|aaron-bond|3.0.2|
|code-spell-checker|streetsidesoftware|2.3.4|
|code-spell-checker-french|streetsidesoftware|0.2.2|
|codesnap|adpyke|1.3.4|
|csharp|ms-dotnettools|1.25.0|
|data-workspace-vscode|ms-mssql|0.2.2|
|github-vscode-theme|GitHub|6.3.2|
|material-icon-theme|PKief|4.19.0|
|material-product-icons|PKief|1.3.0|
|mssql|ms-mssql|1.15.0|
|project-manager|alefragnani|12.6.1|
|sql-bindings-vscode|ms-mssql|0.2.1|
|sql-database-projects-vscode|ms-mssql|0.17.2|
|theme-dracula|dracula-theme|2.24.2|
|todo-tree|Gruntfuggly|0.0.215|
|vscode-docker|ms-azuretools|1.22.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.22|;

</p>
</details>

**Comment by JoeRobich** [comment] 2022-08-01 16:31
@ryanbrandenburg Razor formatting issue?

**Comment by ryanbrandenburg** [comment] 2022-08-02 17:43
@davidwengier is more likely to know about formatting issues. @davidwengier does this sound familiar?

**Comment by davidwengier** [comment] 2022-08-02 21:21
Not a known formatting issue, though there are some issues to do with LF line endings that might be related, but that is a complete guess. Also there seems to be no formatting in the OmniSharp log, but I'm not sure whether that would appear anyway.

I see you're on Windows @HoTKreeZy , but is your repo configured to use LF line endings?

**Comment by HoTKreeZy** [comment] 2022-08-02 21:45
So, I just reopened my project for the first time since I opened the issue to see if it was indeed using LF line endings and yes, it is.

I tried to change to CRLF line endings and it looks like the problem just went away.

**Comment by davidwengier** [comment] 2022-08-02 22:08
Thanks @HoTKreeZy, I think in that case this is a duplicate of https://github.com/dotnet/razor-tooling/issues/4349

**Comment by HoTKreeZy** [comment] 2022-08-02 22:13
@davidwengier okay, I just looked a the issue you linked and i hade the exactly same problem.

**Comment by davidwengier** [comment] 2022-08-02 22:26
Awesome, thanks for reporting!

**Comment by davidwengier** [comment] 2022-08-02 22:27
@JoeRobich You can close this :)

**Comment by JoeRobich** [comment] 2022-08-02 22:28
You can track this issue at https://github.com/dotnet/razor-tooling/issues/4349

Closing as external.

**Closed by JoeRobich** 2022-08-02 22:28 UTC
Labels: External-Issue
