### ISSUE TITLE
give intellisense for accessible object properties on object initialization

### ISSUE THREAD

**Issue by tugberkugurlu** [OmniSharp/omnisharp-vscode#260] opened 2016-04-29 16:21 UTC
Assuming that I have the below view and my cursor sits in the middle of two curly braces:

![image](https://cloud.githubusercontent.com/assets/328122/14922174/f0bd8dde-0dea-11e6-86fd-c1ddd08c1c76.png)

I don't get intellisense for accessible properties. This is possible in Visual Studio either by start typing or hitting `ALT` + `→`. This would be nice to have. I am willing to give this a go but might need some help to get my head around the structure of the project.

I am using VS Code C# extension 0.3.7 on VS Code 1.0.0:

```
Version 1.0.0
Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
Date 2016-04-13T14:21:33.326Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by jchannon** [comment] 2016-07-15 08:48
Seems similar to #573

**Comment by DustinCampbell** [comment] 2016-07-16 09:51
Yup -- #573 is a dupe of this one.

**Comment by jchannon** [comment] 2016-07-20 09:17
I also see the same behaviour when `override` is typed into the browser which I think is just a snippet, no intellisense is offered to give you a list of members to actually override. Not sure if that is a separate issue so let me know and I'll create one if it is

**Comment by DustinCampbell** [comment] 2016-07-20 14:15
This is known, but it's actually more tricky. The difficulty with override completion is that we need changes to the VS Code APIs to provide a bit more information and provide richer facilities when applying a completion item. Essentially, we need to know what typed character triggered the completion list, and we need the ability to be able to have a completion item insert multiple lines of text and allow us to move the caret afterwards. I've been chatting with the VS Code folks about this.

**Comment by jlost** [comment] 2016-10-22 01:58
+1, would like to see this.

**Comment by filipw** [comment] 2017-05-02 14:07
Related to https://github.com/OmniSharp/omnisharp-roslyn/pull/840

**Closed** 2017-05-04 17:09 UTC
Labels: Bug, Editor-IntelliSense, Resolved-Fixed
