### ISSUE TITLE
XUnit debug test case failing with - "Error processing launch options at field: program"

### ISSUE THREAD

**Issue by surenderssm** [OmniSharp/omnisharp-vscode#3965] opened 2020-08-11 13:36 UTC
## Issue Description ##

Debugging a XUnit Test case is failing with following error
Error processing launch options at field: program

[Open launch.json] [Cancel]
## Steps to Reproduce ##

1. Try to run a xunit test case

## Expected Behavior ##

1. Test should be debugged

## Actual Behavior ##

1. It fails with error "Error processing launch options at field: program"
Not sure what broke this, it was working as expected for all these days and this stopped today !
### OmniSharp log ###
<details>Post the output from Output-->-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"logging":{"engineLogging":false},"type":"coreclr","name":".NET Test Launch","request":"launch","debuggerEventsPipeName":"\\\\.\\pipe\\Microsoft.VSCode.CSharpExt.TestDebugEvents-29608","program":null,"args":null,"cwd":"D:\\garage\\chakra","internalConsoleOptions":"openOnSessionStart","__sessionId":"2d687374-1cd7-4f01-9f46-d2a7d789f723"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/CommandFailed","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.20180","VS.Diagnostics.Debugger.vsdbg.Command":"Launch","VS.Diagnostics.Debugger.vsdbg.ErrorCode":1006,"VS.Diagnostics.Debugger.vsdbg.AdditionalData":"program","VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}
<- (R) {"seq":4,"type":"response","request_seq":2,"success":false,"command":"launch","message":"Error processing launch options at field: program"}
![xunitFailure](https://user-images.githubusercontent.com/12485087/89903717-a33f4000-dc05-11ea-94ef-3908e0b86990.png)
</details>

### C# log ###
<details>Post the output from Output-->----- Debugging test method test.StringTests.TestIndexOf -----

Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  chakra -> d:\garage\chakra\src\bin\Debug\netcoreapp3.1\chakra.dll
  test -> d:\garage\chakra\test\bin\Debug\netcoreapp3.1\test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.71

[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (64-bit .NET Core 3.1.6)
[xUnit.net 00:00:00.43]   Discovering: test
[xUnit.net 00:00:00.49]   Discovered:  test
Debugging complete.</details>

## Environment information ##

**VSCode version**: 1.47.3
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400
 Commit:    035fb2aa2f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20180
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.11|
|azurecli|ms-vscode|0.5.0|
|azurerm-vscode-tools|msazurermtools|0.12.0|
|csharp|ms-dotnettools|1.22.1|
|go|golang|0.16.1|
|go-to-method|trixnz|0.2.0|
|mssql|ms-mssql|1.9.0|
|prettier-vscode|esbenp|5.1.3|
|python|ms-python|2020.7.96456|
|remote-wsl|ms-vscode-remote|0.44.4|
|vscode-aks-tools|ms-kubernetes-tools|0.0.6|
|vscode-azureappservice|ms-azuretools|0.18.0|
|vscode-azurestorage|ms-azuretools|0.9.0|
|vscode-dotnet-runtime|ms-dotnettools|0.1.2|
|vscode-drawio|hediet|0.7.2|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.2.1|
|vscode-yaml|redhat|0.9.1|;

</details>

**Comment by gregg-miskelly** [comment] 2020-08-11 15:46
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3459. I believe @JoeRobich has fixed this in the latest beta (see [instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)).

**Closed by gregg-miskelly** 2020-08-11 15:46 UTC
Labels: Test

**Comment by surenderssm** [comment] 2020-08-11 16:10
Thank you @gregg-miskelly for the quick update and @JoeRobich for the fix.
I confirm it worked for me with C# Extension**: 1.23.0 , instructions to download beta helped !
