### ISSUE TITLE
"for"-template not initially selected

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#659] opened 2016-08-15 09:06 UTC
_From @johanneskopf on August 12, 2016 22:5_

- VSCode Version: 1.5.0-insider
- OS Version: Windows 10, Build 14901

Steps to Reproduce:

1. Open a c# file
2.  Write "for"
3. You have to press (Down) and (Tab) to use the "for"-template, it's not possible to write "for" and press (Tab) to use that template on the go.
Selecting the template initially would speed up coding.

![opened_single_file_for](https://cloud.githubusercontent.com/assets/13490371/17638274/4da34c2c-60e9-11e6-8780-eaf33d22b8dc.png)

![opened_solution_for](https://cloud.githubusercontent.com/assets/13490371/17638275/5064cbf2-60e9-11e6-98d3-5c24bd8ffdf6.png)

_Copied from original issue: Microsoft/vscode#10488_

**Comment by ivanz** [comment] 2016-08-18 13:52
This is not a bug, because extensions don't have control over the order of items displayed. However as of VSCode 1.4 a setting has been added to change snippets to be always displayed first or not or keep old default behavior: `"editor.snippetSuggestions": "top"`
 
@DustinCampbell you can close this one :)

**Comment by johanneskopf** [comment] 2016-08-18 14:06
Thank you very much, that's making programming faster for me

**Closed** 2016-08-18 14:10 UTC
