### ISSUE TITLE
Insiders never finishes build task

### ISSUE THREAD

**Issue by jsacapdev** [OmniSharp/omnisharp-vscode#1665] opened 2017-07-26 09:36 UTC
## Environment data

PS C:\playground\DreamyDays> dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9VS Code version:

C# Extension version:
1.11.0

## Steps to reproduce
1. mkdir DreamyDays
2. dotnet new sln
3. mkdir src
4. cd src
5. dotnet new web -n Dreamy.Days.Api
6. cd ..
7. dotnet sln add ./src/Dreamy.Days.Api/Dreamy.Days.Api.csproj
8. Open in Vs Code Insiders
9. Add tasks.json:

{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "args": [
                "build", "DreamyDays.sln"
            ],
            "command": "dotnet",
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal":"always"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}

10. CTRL + SHIFT + B to build

## Expected  behavior

Executing task: dotnet build DreamyDays.sln <

Microsoft (R) Build Engine version 15.3.388.41745 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Dreamy.Days.Api -> C:\playground\DreamyDays\src\Dreamy.Days.Api\bin\Debug\netcoreapp2.0\Dreamy.Days.Api.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.87

Terminal will be reused by tasks, press any key to close it.

## Actual behavior

Executing task: dotnet build DreamyDays.sln <

Microsoft (R) Build Engine version 15.3.388.41745 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Dreamy.Days.Api -> C:\playground\DreamyDays\src\Dreamy.Days.Api\bin\Debug\netcoreapp2.0\Dreamy.Days.Api.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.91

*** Task runs indefinitely and never completes ***

## Additional Information:

The expected behavior does work on VS Code

**Comment by ncthbrt** [comment] 2017-07-26 12:13
Had the same problem with omnisharp and various other .NET F# tooling (Ionide and Forge)
Had to reinstall windows and rollback.

**Comment by DustinCampbell** [comment] 2017-07-26 14:07
This is almost certainly not caused by the C# for VS Code extension. It looks like this is a dupe of https://github.com/Microsoft/vscode/issues/31387.

**Closed** 2017-07-26 14:07 UTC
Labels: Resolved-External
