### ISSUE TITLE
Ubuntu 16.10 "Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by blendsdk** [OmniSharp/omnisharp-vscode#1009] opened 2016-12-02 00:20 UTC
I am unable to debug on a Ubuntu vm. I get the following  error:

- Debug adapter process has terminated unexpectedly
- ASP.NET Core 1.1 preview 2
- VSCode:
    Version 1.7.2 
    Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
    Date 2016-11-21T22:14:18.217Z
    Shell 1.3.8
    Renderer 52.0.2743.82
    Node 6.5.0

Any ideas?

**Comment by gregg-miskelly** [comment] 2016-12-02 00:24
@blendsdk this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/956. 

I've created a [v1.6-beta3](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta3) release of the C# extension that should address this. See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

**Closed by gregg-miskelly** 2016-12-02 00:24 UTC
Labels: Debugger, Resolved-Duplicate
