### ISSUE TITLE
The C# extension for Visual Studio Code (powered by OmniSharp) is incompatiable on linux aarch64

### ISSUE THREAD

**Issue by madmungrel** [OmniSharp/omnisharp-vscode#4316] opened 2020-12-22 20:42 UTC
Hi Just getting started with VS Code latest 1.5.2 on a Unbuntu20.4 OS on ARM64 RasberryPI and get this message when have C# for Visual Studio Code (powered by OmniSharp) ext-installed

Did have 1.5.1 VS code installed and same issue ?

Is this a no support for ARM ? only supports x86 ? Or am I missing a configuration, environment issue ?

**Comment by filipw** [comment] 2020-12-22 20:48
Linux ARM is currently not supported.

**Comment by gregg-miskelly** [comment] 2021-01-06 01:38
This is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/2771

**Closed by gregg-miskelly** 2021-01-06 01:38 UTC
Labels: Question

**Comment by gregg-miskelly** [comment] 2021-01-06 03:04
See https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm for instructions.

**Comment by lokinfey** [comment] 2021-01-09 09:39
@gregg-miskelly 

hi I think I missed something , I want to debug aarch64  program in my macOS , I follow your instruction :

 https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm

but it show me .........

![Screen Shot 2021-01-09 at 5 37 32 PM](https://user-images.githubusercontent.com/4607663/104088379-6ef9a980-52a1-11eb-8217-3c7ef3dbd807.png)

**Comment by gregg-miskelly** [comment] 2021-01-10 05:28
@lokinfey You asked about Linux. arm64 macOS is not yet supported.

**Comment by lokinfey** [comment] 2021-01-11 07:20
> @lokinfey You asked about Linux. arm64 macOS is not yet supported.

@gregg-miskelly  I want to know when I can using C# extension in local aarch64  dev env .  I build linux arm64 vm in my apple silicon mbp . I know C# for apple silicon not ready , but linux arm64 local debug can publish ......

**Comment by gregg-miskelly** [comment] 2021-01-11 18:35
@lokinfey Since your issue is fairly unrelated to this original issue, please open a new issue. Nothing on Apple Silicon is tested/supported yet. So I am not sure if we will really be able to help. But we can try.
