### ISSUE TITLE
Expressions within array indexer not classified properly

### ISSUE THREAD

**Issue by Actionintint** [OmniSharp/omnisharp-vscode#2089] opened 2018-03-05 03:43 UTC
## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version:
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15: 34: 36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

C# Extension version:1.14.0

## Steps to reproduce
Write the product to the subscript of the array
Format the code

## Expected  behavior
Variable is highlighted in light blue

## Actual behavior
![default](https://user-images.githubusercontent.com/20414138/36956401-87d0868c-2071-11e8-818b-67abd3160bf5.png)

**Comment by rchande** [comment] 2018-03-07 19:21
@DustinCampbell Are you interested in taking this one?

**Comment by DustinCampbell** [comment] 2018-03-09 22:06
This is a duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/99. Essentially, `a * b` is being highlighted as a pointer type (e.g. `a* b`.

**Closed** 2018-03-09 22:06 UTC
Labels: Bug, Resolved-Duplicate
