### ISSUE TITLE
Intermittent Intellisense preselecting class over locals with single character variable names

### ISSUE THREAD

**Issue by almightyju** [OmniSharp/omnisharp-vscode#2014] opened 2018-02-07 15:58 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.2.0-preview1-007947)

Product Information:
 Version:            2.2.0-preview1-007947
 Commit SHA-1 hash:  e8f7ddd01b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007947\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9
```
VS Code version:
```
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:36:34.867Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
C# Extension version: 1.13.1

## Steps to reproduce
Using the following class:
```c#
using System.Linq;
using Microsoft.AspNetCore.Mvc;

public static void Main(string args) {
    
}
```
type the following in the Main function:
```
 args.Select(v => v
```
The selected suggestion will be "ValidateAntiForgeryTokenAttribute"

## Expected  behavior
It should auto select the local "v", for other letters this works fine, I've had a few other examples but this is the easiest most reproducible I've found.

## Actual behavior
![Result](https://user-images.githubusercontent.com/7722347/35926252-9f9ba4ba-0c1f-11e8-99ac-87693260cf42.png)

**Comment by rchande** [comment] 2018-02-08 16:54
@almightyju Unfortunately, the C# extension can't control the matching. This would have to be fixed in VS Code. I think this is a dupe of https://github.com/Microsoft/vscode/issues/41977 . cc @jrieken

**Closed** 2018-02-08 16:57 UTC
Labels: Resolved-External

**Comment by almightyju** [comment] 2018-02-08 22:13
@rchande  Fair enough, I wasn't sure if VS handled the matching order, I'll keep an eye on the linked, thanks
