### ISSUE TITLE
Fully Support Visual Basic (VB)

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#25] opened 2016-01-30 16:20 UTC
_From @habakuk007 on January 29, 2016 13:23_

VB is compared to C# the advanced language - fully support it.

_Copied from original issue: Microsoft/vscode#2538_

**Comment by kolbma** [comment] 2016-06-15 14:49
I'd like to see Visual Basic .Net support in Visual Studio Code, too.
Of course including all the features it provides for C# development.
This would be awesome because there is no good working IDE for VB .Net next to Visual Studio, which is only running on Windows platform.
So this would be a major step to push VB .Net language usage, when you can use all supported platforms to develop with VB .Net.

**Comment by borgdylan** [comment] 2016-09-21 14:52
:+1: for Vb. I also recommend a language neutral way of handling the msbuild project file for any .net language since the XML structure would be identical.

**Comment by sunheat** [comment] 2017-01-11 04:02
Save developers who have to work with legacy code written in VB6 like myself. 

Voting for this one. +1

**Comment by Falthazar** [comment] 2017-06-10 04:20
I would like to see this as well! +1

**Comment by tthiery** [comment] 2017-08-15 09:36
It is a pity that VB is not supported. .NET Core supports it now, and considering the beginner-friendly and business-friendly nature of VB, it would be a great addition to omnisharp-roslyn and omnisharp-vscode.

**Comment by pemo11** [comment] 2017-10-18 08:04
What really missing is Debugger support especially since .NET Core 2.0 finally supports the VB language and offers a few templates.

**Comment by ahendry2688** [comment] 2018-06-26 23:38
+1, thumbs up, whatever is needed to get this implemented

**Comment by sharkguto** [comment] 2018-08-27 01:29
+1

**Comment by shodanx2** [comment] 2018-08-28 07:41
I was going to ask, is vb.net supported ?  But seeing this thread, I have to assume this extension only supports C# and not vb.net . I think that is going to prevent me from switching for full visual studio to visual studio code

**Comment by shodanx2** [comment] 2018-09-18 23:31
Sending them money is probably the most effective way of getting their
attention. Next would be introducing vscode to fellow VB coders and have
them post on this thread of their genuine desire to have the basic features
of intellisense and live debugging added to vscode

**Comment by loligans** [comment] 2018-09-19 16:51
Would it make a difference if donations were sent to the omnisharp team for VB.NET integration with VSCode? @david-driscoll @DustinCampbell

**Comment by oleg-shilo** [comment] 2018-09-20 09:31
You may want to try [CS-Script VS-Code extension](https://marketplace.visualstudio.com/items?itemName=oleg-shilo.cs-script). It supports VB.NET since Apr 2018:

![vscode_vb](https://user-images.githubusercontent.com/16729806/45809496-a8423000-bd0b-11e8-9879-7f918c8f71c7.gif)

**Comment by E4N** [comment] 2018-10-05 08:05
Upvoted, would love to use VB.NET on VSCode.

**Comment by CreatorVilius** [comment] 2019-04-22 12:26
> You may want to try [CS-Script VS-Code extension](https://marketplace.visualstudio.com/items?itemName=oleg-shilo.cs-script). It supports VB.NET since Apr 2018:
> 
> ![vscode_vb](https://user-images.githubusercontent.com/16729806/45809496-a8423000-bd0b-11e8-9879-7f918c8f71c7.gif)

Apparently, it doesn't work for me at least. CS-Script isn't that good at supporting VB.NET. Also, no syntax highlight fix...

**Comment by oleg-shilo** [comment] 2019-04-22 13:39
Could you please elaborate?

**Comment by Fleischhauer** [comment] 2019-11-15 11:18
No VB yet?? Do it!

**Comment by oleg-shilo** [comment] 2019-11-15 12:22
I am not sure I understand what you are trying to say. 

VB is supported by CS-Script plugin since Apr 2018. VSCode does Syntax highlight and CS-Script does intellisense, execution and debugging. The screenshot (two posts above) illustrates it. 

So "doesn't work for me" and "do it" without any details do not help the discussion.

**Comment by APerricone** [comment] 2020-02-26 11:01
CS-Script needs Mono, I don't use mono, but I would like to see the file structure on my VB files...

**Comment by APerricone** [comment] 2020-02-26 11:13
CS-Script does not have outline on VB files...

**Comment by jaxspades** [comment] 2020-03-10 16:18
@oleg-shilo Thanks for the extension. It's a great way to execute C# and VB like Python. Does it work with VS Projects too?

**Comment by oleg-shilo** [comment] 2020-03-13 11:27
If you mean Visual Studio then yes.

If you mean opening .csproj file in VSCode. Then NO :(
CS-Script follows Python approach. A single script file is a complete expression of all runtime dependencies: f.cs files, assemblies and packages. So .csproj does not have role in any scripting scenario.

**Comment by oleg-shilo** [comment] 2020-03-13 11:34
> 
> 
> CS-Script does not have outline on VB files

CS-Script does not implement outlining at all but only intellisense operations, execution and debugging integration. Outlining is the responsibility of IDE. You can use CodeMap extention. It supports 10 languages including C#. But for VB you will need to extend it:
https://marketplace.visualstudio.com/items?itemName=oleg-shilo.codemap

**Comment by cartermp** [comment] 2020-03-17 20:50
Closing this as by design. The C# plugin is for C# and there will be some future investments that may allow for a proper VB plugin to be built that uses the same core Roslyn-based infrastructure. But there aren't any plans to incorporate a full fidelity VB experience into the C# OmniSharp experience.

**Closed by cartermp** 2020-03-17 20:50 UTC
Labels: Feature Request, Resolved-By Design

**Comment by govert** [comment] 2020-07-29 13:42
@cartermp Could you please clarify a bit what the current status of Visual Basic is for OmniSharp (and/or VS Code):

* Does your comment and closing the issue mean that OmniSharp is strictly a C# language service, and that a Roslyn-based Visual Basic language service would have to be developed as a fork / from scratch and not as part of the OmniSharp project?
* If so, do you know of any such project that one could contribute to?
(It's a bit surprising, since the compilers, workspaces and other infrastructure of Visual Basic is shared in Roslyn.)

**Comment by Chiel92** [comment] 2021-01-30 22:23
@cartermp Could you please respond to the above questions and elaborate on this decision. There are a lot of people that have to work with legacy VB code.

**Comment by rogerbk** [comment] 2021-09-09 14:02
> > CS-Script does not have outline on VB files
> 
> CS-Script does not implement outlining at all but only intellisense operations, execution and debugging integration. Outlining is the responsibility of IDE. You can use CodeMap extension. It supports 10 languages including C#. But for VB you will need to extend it:
> https://marketplace.visualstudio.com/items?itemName=oleg-shilo.codemap



> Could you please elaborate?

Hey man, I did the setup visual studio code and not is working, could you please share some step by step?

**Comment by oleg-shilo** [comment] 2021-09-09 22:43
CodeMap does not have built-in support for VB so you will need to enable it by setting up a new VB custom mapper. It is actually quite simple. You have two choices. Either define a tiny TS class that analyses the specified document lines and "marks" your functions as outlining elements or simply define (in the VSCode settings file) a regular expression that detects VB functions. This is the simplest approach even though it is less flexible:

The guide is here: https://github.com/oleg-shilo/codemap.vscode/wiki/Adding-custom-mappers

For VB syntax you simply need to add this section in the VSCode settings.json: 

```json
 "codemap.vb": [
    {
      "pattern": "[Cc]lass .*",
      "clear": "",
      "suffix": "",
      "role": "class",
      "icon": "class"
    },
    {
      "pattern": "([Ff]unction|[Ss]ub) (.*?)[(|:{]",
      "clear": "[Ff]unction |[Ss]ub |\\(",
      "suffix": "()",
      "role": "function",
      "icon": "function"
    }
  ],
```
![image](https://user-images.githubusercontent.com/16729806/132771953-df8535b5-090e-4dd1-b24e-037a86550cec.png)

It is my very quick and dirty solution but you may further experiment with it.

But this is what it does:
![image](https://user-images.githubusercontent.com/16729806/132772027-dbd19c42-1795-444e-b531-c8a33493c0f1.png)

**Comment by oleg-shilo** [comment] 2021-09-10 00:32
In fact, I have just published the extension update so you can get your VB mapper if you just update the extension

**Comment by rogerbk** [comment] 2021-09-10 01:29
> In fact, I have just published the extension update so you can get your VB mapper if you just update the extension

Thank you. Is working now. Other question, sorry for many questions. I am setup notepad ++ to use visual basic .net
I cannot find the file css_config. Dont know how to run the command. It is indicatind that the file css_config does not exist

https://www.cs-script.net/cs-script/help-legacy/Config.html

**Comment by shodanx2** [comment] 2021-09-10 03:11
This is great new, could someone currently using VB recap this thread with a trial of the current state of things programming visual basic in visual studio code and with omnisharp ? 

Does debugging work, does intellisense work properly and in context ?
